### ISSUE TITLE
StackOverflowError related to implicits

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#6119] opened 2019-03-19 16:02 UTC
The following code is minimized from ScalaTest, which compiles fine in Scala 2.12.8, but causes a stackoverflow in Dotty:

```Scala
class Test {
  def to[Col[_]](factory: Factory[Int, Col[Int]]): Col[Int] = ???

  to(Vector)

  type Factory[-A, +C] = scala.collection.generic.CanBuildFrom[Nothing, A, C] // Ideally, this would be an opaque type

  implicit def fromCanBuildFromConversion[X, A, C](x: X)(
    implicit toCanBuildFrom: X => scala.collection.generic.CanBuildFrom[Nothing, A, C]): Factory[A, C] = ???

  implicit def genericCompanionToCBF[A, CC[X] <: scala.collection.GenTraversable[X]](
    fact: scala.collection.generic.GenericCompanion[CC]): scala.collection.generic.CanBuildFrom[Any, A, CC[A]] = ???
}
```

Note that in the above, if we comment out `fromCanBuildFromConversion`, it compiles both in Scala 2.12.8 and Dotty.

This seems to be the culprit of a compiler hang when working with a test in [Scalactic](https://github.com/scalatest/scalatest/blob/3.1.x/scalactic-test/src/test/scala/org/scalactic/ChainSpec.scala#L1233).

```Scala
Chain(1, 2, 3).to(Vector) shouldBe Vector(1, 2, 3)
```

**Comment by smarter** [comment] 2019-03-19 20:30
Duplicate of https://github.com/lampepfl/dotty/issues/6119 ?

**Closed** 2019-03-27 09:27 UTC
Labels: area:implicits, itype:bug, prio:blocker
