### ISSUE TITLE
Can't define JS facades with wildcards

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#12115] opened 2021-04-16 07:01 UTC
## Compiler version

3.0.0-RC1

## Minimized code

This is just a small part of the Scala JS facades for React. It's quite common for JS facades to be type aliases in addition to traits and classes.

```Scala
type ComponentClass [P <: js.Object, S <: js.Object] = js.Function1[P, React.Component[P, S]] with HasDisplayName
type ComponentClassP[P <: js.Object]                 = ComponentClass[P, _ <: js.Object]
type ComponentClassUntyped                           = ComponentClass[_ <: js.Object, _ <: js.Object]
```

## Output

```
[warn] -- [E043] Type Migration Warning: /home/golly/projects/public/scalajs-react/core/src/main/scala/japgolly/scalajs/react/raw/React.scala:85:55 
[warn] 85 |type ComponentClassP[P <: js.Object]                 = ComponentClass[P, _ <: js.Object]
[warn]    |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[warn]    |unreducible application of higher-kinded type [P <: scalajs.js.Object, S <: scalajs.js.Object] =>> 
[warn]    |  scalajs.js.Function1[P, japgolly.scalajs.react.raw.React.Component[P, S]]
[warn]    | & japgolly.scalajs.react.raw.HasDisplayName to wildcard arguments
[warn] -- [E043] Type Migration Warning: /home/golly/projects/public/scalajs-react/core/src/main/scala/japgolly/scalajs/react/raw/React.scala:86:55 
[warn] 86 |type ComponentClassUntyped                           = ComponentClass[_ <: js.Object, _ <: js.Object]
[warn]    |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[warn]    |unreducible application of higher-kinded type [P <: scalajs.js.Object, S <: scalajs.js.Object] =>> 
[warn]    |  scalajs.js.Function1[P, japgolly.scalajs.react.raw.React.Component[P, S]]
[warn]    | & japgolly.scalajs.react.raw.HasDisplayName to wildcard arguments
```

## Workaround

I have to manually expand all the type aliases.

```scala
type ComponentClass [P <: js.Object, S <: js.Object] =
  js.Function1[P, React.Component[P, S]] with HasDisplayName

type ComponentClassP[P <: js.Object] =
  js.Function1[P, React.Component[P, _ <: js.Object]] with HasDisplayName

type ComponentClassUntyped =
  js.Function1[_ <: js.Object, React.Component[_ <: js.Object, _ <: js.Object]] with HasDisplayName
```

which is very troublesome because clearly Scala 3 supports the intention of the code - it just doesn't expand wildcards through type aliases.

## Expectation

This has nothing to do with existential types which have been removed from Scala 3. This is about wildcards so I'm expecting this to compile without warnings. Type aliases and wildcards shouldn't be mutually-exclusive.

## Proposal 1

I expect that if I pass in a wildcard to a type-alias, and that type is only used once, then it should be a matter of simple substitution and no contention:

```scala
type F[A] = List[A]
type G = F[?] // via simple substitution, it should be the same as: type G = List[?]
```

If a type alias arg is used more than once, @odersky has previously said that the expansion requires existential types

```scala
type F[A] = (List[A], List[A])
type G = F[?] // should expand to (List[A], List[A]) {for some A=?}
```

but as far as I can tell, simple substitution would work fine here too because if `F` were manually expanded using wildcards, it behaves like this:

```scala
type G = (List[?], List[?])
( List[Int](), List[Unit]() ) : G // this passes despite the Lists being of different types
                                  // they both satisfy the same bounds specified by the wildcards.
                                  // (List[A], List[A]) {for some A=?}  ≡  (List[?], List[?])

```

The relationship between the two occurrences of `A` in `F` being the same doesn't hold for wildcards (which just moves the bounds). If type aliases were to use simple substitute and allow wildcards I think it would behave the same. I don't see how we lose anything.

## Proposal 2

If we can't have simple substitution, can we have another means of doing this valid thing? After all, it's quite common in JS facades. Maybe we could have `*` or something instead of `?` to allow us to use wildcards with type aliases? Meaning `type G=F[?]` would warn about existential types but `type G=F[*]` is a user very explicitly specifying a wildcard and expecting the simple substitution.

At the end of the day, manually expanding type aliases everywhere is frustrating but most importantly, carries the risk that manually-expanded aliases will go out of sync. I think we need *some* kind of solution in place even if it's not one of the above two suggestions. :slightly_smiling_face:

**Comment by japgolly** [comment] 2021-04-16 07:09
Btw, just to show how crazy this can get at scale, here's another snippet from React facades:

```scala
  type ComponentType[Props <: js.Object] =
    ComponentClass[Props, _ <: js.Object] |
    ForwardRefComponent[Props, _] |
    StatelessFunctionalComponent[Props]

  type ElementType = String | ComponentType[_ <: js.Object]
```

which now has to be expanded to:

```scala
  type ComponentType[Props <: js.Object] =
    (js.Function1[Props, React.Component[Props, _ <: js.Object]] with HasDisplayName) |
    ForwardRefComponent[Props, _] |
    StatelessFunctionalComponent[Props]

  type ElementType =
    String |
    (js.Function1[_ <: js.Object, React.Component[_ <: js.Object, _ <: js.Object]] with HasDisplayName) |
    ForwardRefComponent[_ <: js.Object, _] |
    StatelessFunctionalComponent[_ <: js.Object]
```

which is already starting to look like a maintenance nightmare and it's only the beginning. I'm sure I'll come across larger expansions before long.

**Comment by sjrd** [comment] 2021-04-16 07:22
This doesn't seem to have anything to do with facades of even Scala.js. It's very likely possible to write reproductions that don't depend on `js.*`.

**Comment by japgolly** [comment] 2021-04-16 07:36
@sjrd Yes I could provide minifications that don't rely on `scalajs.js`, but the ability to use type aliases and wildcards is often crucial to writing JS facades. I just wanted to provide more context to why this is important, show some of the real situations, and demonstrate why a simple syntax fix by a facade author often isn't feasible.

**Comment by smarter** [comment] 2021-04-16 07:44
> The relationship between the two occurrences of A in F being the same doesn't hold for wildcards (which just moves the bounds). If type aliases were to use simple substitute and allow wildcards I think it would behave the same. I don't see how we lose anything.

If a value has type `F[?]`, by definition that means it also has a more precise type `F[X]` for some unknown X, but if we allow wildcard substitutions in type aliases that isn't true anymore as you've noted with the pair of list example.

> If we can't have simple substitution, can we have another means of doing this valid thing?

There's at least two ways:
- If you really don't care about the two uses of the same type parameter being the same type, use two type parameters in your alias:
```scala
type ComponentClass0 [P1 <: js.Object, P2 <: js.Object, S <: js.Object] =
  js.Function1[P1, React.Component[P2, S]] with HasDisplayName
type ComponentClass[P <: js.Object, S <: js.Object] = ComponentClass0[P, P, S]
type ComponentClassUntyped = ComponentClass0[_, _, _]
```
- If you do care, wrap it in a class:
```scala
class ComponentClass[P <: js.Object, P <: js.Object] extends ... { ... }
type ComponentClassUntyped = ComponentClass0[_, _]
```

So I don't think there's any need for a new syntax introducing a whole new kind of type application here, and I'll be closing this since we don't consider this to be an issue.

**Closed by smarter** 2021-04-16 07:44 UTC
Labels: itype:bug

**Comment by japgolly** [comment] 2021-04-19 06:12
> If a value has type F[?], by definition that means it also has a more precise type F[X] for some unknown X, but if we allow wildcard substitutions in type aliases that isn't true anymore as you've noted with the pair of list example.

@smarter Some problems with that:

1) Let's say we agree on your above statement, ok now why can't we have wildcard substitutions in type aliases where there's no need to worry about agreement between substitutions (i.e. type appears once only)? `type F[A] = List[A]; type G = F[?]` should have no problems. It's literally the same as `type G = List[?]`. Is it cos of transitivity like `type P[A] = (A,A); type F[A] = P[A]; type G = F[?]`? The compiler should technically be able to work it out, right?

2) The workaround you suggested above still emits the same warning anyway. There's literally no workaround I'm aware of apart from manually expanding type aliases which is a recipe for disaster from a maintenance point of view.
    ```
    [warn] 12 |type ComponentClassUntyped = ComponentClass0[_, _, _]
    [warn]    |                             ^^^^^^^^^^^^^^^^^^^^^^^^
    [warn]    |unreducible application of higher-kinded type [P1 <: scalajs.js.Object, P2 <: scalajs.js.Object, S <: scalajs.js.Object] =>> 
    [warn]    |  scalajs.js.Function1[P1, japgolly.scalajs.react.raw.React.Component[P2, S]]
    [warn]    | & japgolly.scalajs.react.raw.HasDisplayName to wildcard arguments
    ```

3) Oh and sadly I can't wrap my facade in a class. It's a facade because it's the interface of an external JS type which you don't have control over in Scala. Once you've got those nasty facades in the type system, then you can start wrapping them to make more pleasant interfaces for Scala use, but you've got to start with those basic facades first.

**Comment by smarter** [comment] 2021-04-19 07:32
> type F[A] = List[A]; type G = F[?] should have no problems. 

Right, I just tried it and it does work: https://scastie.scala-lang.org/kh0lb3RLQkyAL1JzNdY0WA, so I don't know what issue you're facing.
