### ISSUE TITLE
Retrieving type arguments through Java reflection does not work

### ISSUE THREAD

**Issue by pjfanning** [lampepfl/dotty#10872] opened 2020-12-20 20:39 UTC
## Minimized code

https://github.com/pjfanning/scala3-sample-classes/blob/annotation-issue/src/test/scala/com/github/pjfanning/scala3/ClassWithMapsSpec.scala

https://github.com/pjfanning/scala3-sample-classes/blob/annotation-issue/src/main/scala/com/github/pjfanning/scala3/ClassWithMaps.scala

## Output

```scala
[info] - should support TypeReference *** FAILED ***
[info]   java.lang.IllegalArgumentException: Internal error: TypeReference constructed without actual type information
[info]   at com.fasterxml.jackson.core.type.TypeReference.<init>(TypeReference.java:35)
[info]   at com.github.pjfanning.scala3.ClassWithMapsSpec$$anon$1.<init>(ClassWithMapsSpec.scala:12)
```

## Expectation

This test case passes in Scala 2.13.

https://github.com/FasterXML/jackson-core/blob/2.12/src/main/java/com/fasterxml/jackson/core/type/TypeReference.java

This class tries to get the generic super class and this is the parameterized type in Scala 2.13 - eg `new TypeReference[ClassWithMaps[String]]{}` yields `ClassWithMaps[String]` but this does not work in Scala 3.0.0-M3.

**Comment by smarter** [comment] 2020-12-20 20:54
Duplicate of https://github.com/lampepfl/dotty/issues/6349

**Closed by smarter** 2020-12-20 20:54 UTC
Labels: compat:java, itype:bug
