### ISSUE TITLE
Syntax change for wildcards and type lambas

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#4223] opened 2018-03-31 10:50 UTC
Currently we have:

```scala
Set[_ <: X] // wildcards
type Reader[I, A] = Freer[[T] => Ask[I, T], A] // type lambdas
```

Looking outside a little we see that:
* In Cousin Java, wildcards are `?`
* Term-level lambdas allow `_` to be used in place of an lambda args

It would be nice to make this consistent at the type level like the following:

```scala
Set[? <: X] // wildcards
type Reader[I, A] = Freer[Ask[I, _], A] // type lambdas
```

**Comment by odersky** [comment] 2018-03-31 11:08
I agree, it would be great if we could do this. But how to get from here to there? We'd need to

 1. Introduce `?` syntax as an alternate for `_`. This breaks all programs that use kind-projector.
 2. Deprecate `_` as wildcard syntax, and add a rewrite rule that maps `_` to `?`.
 3. Disallow `_` as wildcard syntax.
 4. Re-introduce `_` as a placeholder of a type lambda. 

It seems each step requires a major release, and we cannot compress the schedule. Furthermore, it's difficult even to get started on that path because of the conflicts with kind projector. So I don't think we can take the first step with 2.13.

**Comment by japgolly** [comment] 2018-03-31 11:24
Ignoring kind-projector for now (mainly just 'cos my brain is nearly off and I need to sleep), could we not just do steps 2-4 in a single major release and provide a rewrite rule? I don't think it's unreasonable amount of change for a major release especially if the migration can be trivially automated.

And if not 2.13 (which I wasn't considering anyway TBH), it wouldn't be a problem to do in Dotty before 1.0 and its backwards-compatibility becomes set, would it?

**Comment by smarter** [comment] 2018-03-31 16:17
Duplicate of https://github.com/lampepfl/dotty/issues/2041

**Closed by smarter** 2018-03-31 16:17 UTC

**Comment by odersky** [comment] 2018-04-01 15:11
> gnoring kind-projector for now (mainly just 'cos my brain is nearly off and I need to sleep), could we not just do steps 2-4 in a single major release and provide a rewrite rule? I don't think it's unreasonable amount of change for a major release especially if the migration can be trivially automated.

The problem is cross-building. You can't support new and old versions with the same source then.
