### ISSUE TITLE
Cyclic reference for top-level definitions of recursive match types

### ISSUE THREAD

**Issue by flomebul** [lampepfl/dotty#6362] opened 2019-04-23 13:52 UTC
The following exemple no more accepted
```scala
  type LeafElem[X] = X match {
      case String => Char
      case Array[t] => LeafElem[t]
      case Iterable[t] => LeafElem[t]
      case AnyVal => X
    }
```
with the following error
```scala
-- Error: recursive.scala:11:7 -------------------------------------------------
11 |  type LeafElem[X] = X match {
   |       ^
   |illegal cyclic reference: match ... (caught cyclic reference) ... of      |type LeafElem refers back to the type itself
```

**Comment by DReigada** [comment] 2019-06-13 14:06
This seems to still be happening for top level definitions of recursive match types

**Comment by flomebul** [comment] 2019-06-14 16:22
For information, look like the code is accepted by dotr,but not by dotc.

**Comment by kubukoz** [comment] 2019-10-10 00:25
Indeed, it seems like the issue is top level definitions + recursive match types. I just wasted some time fighting it :P

**Comment by flomebul** [comment] 2020-02-27 16:05
Having a look to the regression "tests/pos/6362.scala", my feeling is that it does not cover the case. Is it possible to rewrite-it without the "object Test" encapsulation, so that the "match type" is really at top level?

**Comment by smarter** [comment] 2020-05-19 14:01
Fixed by #9001.

**Closed by smarter** 2020-05-19 14:01 UTC
