### ISSUE TITLE
transparent inline within transparent inline looses type refinement

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#14007] opened 2021-11-26 12:37 UTC
## Compiler version

v3.1.0

## Minimized code
https://scastie.scala-lang.org/iVSSZgQyQt6TAeTniSCFtQ
```Scala
trait Id[T]{type Out <: Int}
transparent inline def internal [T <: Int]: Id[T] = new Id[T]{type Out = T}

transparent inline def id: Int =
  val one = internal[1]
  ??? : one.Out

val i : 1 = id
```

## Output

```scala
Found:    Int
Required: (1 : Int)
```

## Expectation
No error.

**Comment by smarter** [comment] 2021-11-26 12:39
Duplicate of https://github.com/lampepfl/dotty/issues/8739

**Closed by smarter** 2021-11-26 12:39 UTC
Labels: itype:bug, area:inline

**Comment by soronpo** [comment] 2021-11-26 12:47
You see, I completely forgot about this issue so that evidently I was the one who submitted the previous issue that was closed as a duplicate. It's such a huge issue and very annoying to work around.
