### ISSUE TITLE
Cannot pass system properties in comand line

### ISSUE THREAD

**Issue by acaproni** [lampepfl/dotty#14005] opened 2021-11-26 09:03 UTC
With scala 3.1.0 (installed from the tar file), it is not possible to pass system properties in the shell command line:

```
[ias@centos8 ~]$ which scala
/opt/scala3-3.1.0/bin/scala
[ias@centos8 ~]$ scala -version
Scala code runner version 3.1.0 -- Copyright 2002-2021, LAMP/EPFL
[ias@centos8 ~]$ scala -Dprop.name=propValue
bad option '-Dprop.name=propValue' was ignored
Welcome to Scala 3.1.0 (11.0.9.1, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala>
```

**Comment by michelou** [comment] 2021-12-07 15:50
Temporary workaround : 
```
$ scalac -Dprop.name=propValue -repl
Welcome to Scala 3.1.0 (11.0.11, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> util.Properties.propOrNull("prop.name")
val res0: String = propValue
```
In your example argument `-Dprop.name=propValue` is passed to object [`dotty.tools.MainGenericRunner`](https://github.com/lampepfl/dotty/blob/fc7e8c340b3e8c02a03de1e2e25754e996c6a4fd/dist/bin/scala#L34) (and *not* to `java.exe`) in bash script [`scala`](https://github.com/lampepfl/dotty/blob/master/dist/bin/scala); thus it is the responsability of object [`MainGenericRunner`](https://github.com/lampepfl/dotty/blob/fc7e8c340b3e8c02a03de1e2e25754e996c6a4fd/compiler/src/dotty/tools/MainGenericRunner.scala#L94) to deal appropriately with the argument.

I guess method [`def process(...)`](https://github.com/lampepfl/dotty/blob/ae03590a2bf4dee618da57435b661e20baea4f4b/compiler/src/dotty/tools/MainGenericRunner.scala#L102) in object [`MainGenericRunner`](https://github.com/lampepfl/dotty/blob/fc7e8c340b3e8c02a03de1e2e25754e996c6a4fd/compiler/src/dotty/tools/MainGenericRunner.scala#L94) needs to be modified.

**Comment by acaproni** [comment] 2021-12-08 07:46
Thanks for the workaround michelou. REPL was an example. We have the same problem running a scala executable (.jar). This bug forbids to deploy the scala tool in production.

**Comment by dwijnand** [comment] 2021-12-13 14:32
With 3.1.1 coming up soon, I'm moving this, because it's not a regression in 3.1.0 and it has a workaround.

**Comment by acaproni** [comment] 2021-12-13 15:50
@dwijnand, thanks for the update.
Ddoes it mean that we have to wait v3.2 to have the fix in production as the workaround upon is for REPL only?

**Closed** 2021-12-13 16:18 UTC
Labels: prio:high, area:repl, area:tooling

**Comment by dwijnand** [comment] 2021-12-13 18:54
No, it can be part of 3.1.2.

**Comment by BarkingBad** [comment] 2021-12-13 20:23
You can do manual fix with replacing the `scala` bash script at your `/usr/bin/scala` or wherever you have `scala` installed with the newer one from [here](https://github.com/lampepfl/dotty/blob/master/dist/bin/scala)
