### ISSUE TITLE
Hello world! is hardcoded in scala3-repl

### ISSUE THREAD

**Issue by jacobus** [lampepfl/dotty#12880] opened 2021-06-18 19:37 UTC
## CLI Input
```
scala3-repl --version
```

## CLI Output
```
Scala code runner version 3.0.0 -- Copyright 2002-2021, LAMP/EPFL
```

## Minimized code

Hello.scala file content:

```Scala
@main def hello = println("Hello, Mars!!")
```

## Scala Repl
> scala3-repl --version
Scala code runner version 3.0.0 -- Copyright 2002-2021, LAMP/EPFL
> scala3-repl
scala> :load Hello.scala
def hello: Unit
scala> hello
Hello, world!
scala>        

## Expectation
Hello, Mars!! should be printed, not hello world.

**Comment by romanowski** [comment] 2021-06-18 20:41
Hi @jacobus, I am not able to reproduce your problem using both scala3-repl and repl from latest dotty master.

Do you have any other files in the directory where `Hello.scala` is defined?

**Comment by lrytz** [comment] 2021-06-21 07:32
Probably related to how the Scala 3 REPL treats the classpath. It prefers classfiles in the current directory over definitions form the current session.

If I first compile `object O { def f = 1 }` and then run the REPL:

```scala
scala> O.f
val res0: Int = 1

scala> object O { def f = "hi" }
// defined object O

scala> O.f
val res1: Int = 1
```

In the Scala 2 REPL, definitions within the REPL session hide existing ones from the classpath.

**Comment by griggt** [comment] 2021-06-21 07:59
> Probably related to how the Scala 3 REPL treats the classpath. It prefers classfiles in the current directory over definitions form the current session.

Note that this is changed/fixed in 3.0.1-RC1, and your example now gives

```scala
scala> O.f
val res1: String = hi
```

as does the Scala 2 REPL.

**Comment by lrytz** [comment] 2021-06-21 08:04
Great!

**Comment by jacobus** [comment] 2021-06-23 10:10
Seems like @lrytz is correct. To reproduce:

Hello.scala file content:
```Scala
@main def hello = println("Hello, World")
```

Compile:
```
scala3-compiler Hello.scala
```

Update Hello.scala file content:
```Scala
@main def hello = println("Hello, Mars!!")
```

## Scala Repl
> scala3-repl --version
Scala code runner version 3.0.0 -- Copyright 2002-2021, LAMP/EPFL
> scala3-repl
scala> :load Hello.scala
def hello: Unit
scala> hello
Hello, world!
scala>        

## Expectation
Hello, Mars!! should be printed, not hello world.

So if there is a hello classifier in the current directory it still uses it instead of the code that was loaded. This is with REPL Scala code runner version 3.0.0.

**Closed** 2021-06-29 11:43 UTC
Labels: itype:bug, stat:cannot reproduce
