### ISSUE TITLE
GADT pattern matching unsoundness.

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#3645] opened 2017-12-10 14:37 UTC
```scala
object App {
  def main(args: Array[String]): Unit = {
    trait AgeT {
      type T
      def subst[F[_]](fa: F[Int]): F[T]
    }
    type Age = Age.T
    final val Age: AgeT = new AgeT {
      type T = Int
      def subst[F[_]](fa: F[Int]): F[T] = fa
    }

    sealed abstract class K[A]
    final case object KAge extends K[Age]
    final case object KInt extends K[Int]

    val kint: K[Age] = Age.subst[K](KInt)
    def get(k: K[Age]): String = k match {
      case KAge => "Age"
    }

    get(kint)
  }
}
```

Produces no warnings but results in a runtime `MatchError` failure.

[Somewhat relevant paper](https://repository.upenn.edu/cgi/viewcontent.cgi?article=1598&context=cis_papers) (it describes a similar problem in Haskell that was solved by the introduction of `role`s, but I am not sure how applicable it is in the context of Scala).

**Comment by alexknvl** [comment] 2017-12-10 15:20
I think that the underlying issue is that type equality is used in negative positions in `SpaceLogic`. `if (!(tpe1 =:= tpe2))` means "types are not provably equal", not "types are provably unequal". This means that most occurrences of either `!(A =:= B)` or `!(A <:< B)` are likely to be bugs.

**Comment by liufengyun** [comment] 2017-12-10 17:58
Thanks a lot @alexknvl for reporting and the diagnosis. I just create a PR #3546 to handle this issue.

**Comment by alexknvl** [comment] 2017-12-10 18:36
The following snippet still compiles with the fix:
```scala
object App {
  def main(args: Array[String]): Unit = {
    trait FooT {
      type T
    }
    val Foo: FooT = new FooT {
      type T = Int
    }
    type Foo = Foo.T
    type Bar = Foo

    sealed abstract class K[A]
    final case object K1 extends K[Int]
    final case object K2 extends K[Foo]
    final case object K3 extends K[Bar]

    def get(k: K[Int]): Unit = k match {
      case K1 => ()
      // case K2 => ()
      // case K3 => ()
    }
  }
}
```

but it is similarly unsound.

**Comment by alexknvl** [comment] 2017-12-10 18:58
Running the code with debug output shows that:
```scala
candidates for K[Int] : [object K3, object K2, object K1]
[refine] unqualified child ousted: K3.type !< K[Int]
[refine] unqualified child ousted: K2.type !< K[Int]
K[Int] decomposes to [K1.type]
```
which is incorrect

**Comment by liufengyun** [comment] 2017-12-10 19:06
@alexknvl If you write `get(K2)` or `get(K3)`, there will be a typing error, so I think it's correct to assume that the pattern above is exhaustive.

**Comment by alexknvl** [comment] 2017-12-10 19:09
Here is an example that throws `MatchError` at runtime.
```scala
object App {
  def main(args: Array[String]): Unit = {
    trait FooT {
      type T
      def subst[F[_]](fa: F[T]): F[Int]
    }
    val Foo: FooT = new FooT {
      type T = Int

      def subst[F[_]](fa: F[T]): F[Int] = fa
    }
    type Foo = Foo.T
    type Bar = Foo

    sealed abstract class K[A]
    final case object K1 extends K[Int]
    final case object K2 extends K[Foo]
    final case object K3 extends K[Bar]

    val foo: K[Int] = Foo.subst[K](K2)
    def get(k: K[Int]): Unit = k match {
      case K1 => ()
      // case K2 => ()
      // case K3 => ()
    }

    get(foo)
  }
}
```

**Comment by alexknvl** [comment] 2017-12-11 02:49
With the most recent fixes:
```scala
object App {
  def main(args: Array[String]): Unit = {
    trait AT {
      type A

      trait FooT {
        type Type <: A
        def subst[F[_]](fa: F[Int]): F[Type]
      }

      val Foo: FooT
    }
    val A: AT = new AT {
      type A = Int

      val Foo: FooT = new FooT {
        type Type = Int
        def subst[F[_]](fa: F[Int]): F[Type] = fa
      }
    }
    type A = A.A
    type Foo = A.Foo.Type

    sealed abstract class K[F]
    final case object K1 extends K[Int]
    final case object K2 extends K[Foo]

    val kv: K[Foo] = A.Foo.subst[K](K1)
    def test(k: K[Foo]): Unit = k match {
      case K2 => ()
    }

    test(kv)
  }
}
```
fails at runtime with `MatchError`.

**Comment by alexknvl** [comment] 2017-12-11 15:17
Found a new snippet that fails:
```scala
object App {
  def main(args: Array[String]): Unit = {
    trait ModuleSig {
      type U2
      type U1

      trait FooSig {
        type Type = (U1 & U2)
        def subst[F[_]](fa: F[Int]): F[Type]
      }

      val Foo: FooSig
    }
    val Module: ModuleSig = new ModuleSig {
      type U1 = Int
      type U2 = Int

      val Foo: FooSig = new FooSig {
        // type Type = Int
        def subst[F[_]](fa: F[Int]): F[Type] = fa
      }
    }
    type Foo = Module.Foo.Type

    sealed abstract class K[F]
    final case object K1 extends K[Int]
    final case object K2 extends K[Foo]

    val kv: K[Foo] = Module.Foo.subst[K](K1)
    def test(k: K[Foo]): Unit = k match {
      case K2 => ()
    }

    test(kv)
  }
}
```

**Comment by alexknvl** [comment] 2017-12-11 16:28
Another one
```scala
object App {
  def main(args: Array[String]): Unit = {
    trait ModuleSig {
      type F[_]
      type U

      trait FooSig {
        type Type = F[U]
        def subst[F[_]](fa: F[Int]): F[Type]
      }

      val Foo: FooSig
    }
    val Module: ModuleSig = new ModuleSig {
      type F[A] = Int

      val Foo: FooSig = new FooSig {
        // type Type = Int
        def subst[F[_]](fa: F[Int]): F[Type] = fa
      }
    }
    type Foo = Module.Foo.Type

    sealed abstract class K[F]
    final case object K1 extends K[Int]
    final case object K2 extends K[Foo]

    val kv: K[Foo] = Module.Foo.subst[K](K1)
    def test(k: K[Foo]): Unit = k match {
      case K2 => ()
    }

    test(kv)
  }
}
```

**Comment by edmundnoble** [comment] 2017-12-11 17:55
I think it's a safe bet that there's no solution to this in general without roles (https://ghc.haskell.org/trac/ghc/wiki/Roles). It's either that, or admit that we *don't know* if abstract type members are subtypes of other types.

**Comment by alexknvl** [comment] 2017-12-11 18:25
From a phone. AFAIU the problem can be roughly summarized as: given two
types A and B with some free type variables (+ constraints), a) is A <:< B
for all instantiations of type vars b) for some c) for none. I don't
completely understand the code, but would it be fair to say that if there
was a way to constructively solve (b), that would resolve this issue? The
code seems to be doing some sort of type normalization and then check <:<,
which might not work in general, since <:< instantiates all type vars as if
they are completely independent modulo constraints (?). Negation of it =
for a particular instantiation !(A <:< B), not for all instantiations.

I don't think that roles are directly relevant since here we are not really
dealing with newtypes, just abstract types.

**Comment by alexknvl** [comment] 2017-12-11 18:38
Hm, on the other hand they are not really abstract (path.T for a stable
path) and in their behavior is very close to newtypes, so maybe it is
directly applicable :) I need to finish reading that paper...

**Comment by liufengyun** [comment] 2017-12-11 21:44
@alexknvl you are right, the solution I proposed in #3646 is basically to say if there's some instantiation of type variables such that `A <:< B`.

I'm yet to learn about roles, thanks for the pointer @edmundnoble .

**Comment by smarter** [comment] 2018-01-19 22:10
Reopening as it seems the issue is deeper than what #3646 fixed.

**Comment by Blaisorblade** [comment] 2018-02-15 01:26
> It's either that, or admit that we don't know if abstract type members are subtypes of other types.

👍 for the abstract types idea.

> Hm, on the other hand they are not really abstract (path.T for a stable
> path)

`path` is stable so `T` has a fixed definition, but that definition is hidden so `path.T` is still abstract. You can turn the `Module` into an argument so that it's more clearly abstract — I've done the exercise below.

I only have a vague idea about the code in #3646, but your intuition about what quantification is needed makes sense. IIUC, the code tries to reduce `A <:< B` to `A' <:< B'` (well, `childTypeMap.apply(parent) <:< parentTypeMap.apply(tp2)`) while preserving the result. It tries to compute `A'` and `B'` by picking a suitable substitution for type variables, but (a) in our scenario, we care about abstract type `Foo` in invariant position, so there's not much to maximize/minimize (b) the question we care for is "is there a type substitution G such that `G(A) <:< G(B)`, and in this case there is indeed such a substitution (`G(Foo) = Int`). Not sure how to find it in general; but `K[Foo] <:< K[Int]` reduces to `Foo =:= Int` by invariance, which can be solved by unification. Unification with subtyping's trickier, but we need some version of it for type inference?

@liufengyun any chance we can talk about this (maybe even tomorrow)? I'm sure I don't fully get the code but maybe we can help.

```scala
trait ModuleSig {
  type F[_]
  type U

  trait FooSig {
    type Type = F[U]
    def subst[F[_]](fa: F[Int]): F[Type]
  }

  val Foo: FooSig
}

class ModuleUser(Module: ModuleSig) {
  def foo(): Unit = {
    type Foo = Module.Foo.Type

    sealed abstract class K[F]
    final case object K1 extends K[Int]
    final case object K2 extends K[Foo]

    val kv: K[Foo] = Module.Foo.subst[K](K1)
    def test(k: K[Foo]): Unit = k match {
      case K2 => ()
    }

    test(kv)
  }
}

object App {
  val Module: ModuleSig = new ModuleSig {
    type F[A] = Int

    val Foo: FooSig = new FooSig {
      // type Type = Int
      def subst[F[_]](fa: F[Int]): F[Type] = fa
    }
  }
  def main(args: Array[String]): Unit =
    new ModuleUser(Module).foo()
}
```

**Comment by Blaisorblade** [comment] 2018-02-15 02:47
I'm looking at roles, but I'm still wondering if they're indeed applicable to our Scala scenario — I haven't decided but I still think not. Maybe I'm missing something?

Looking at "​Generative Type Abstraction and Type-level Computation":

- that paper focuses on newtypes, not abstract types, and newtypes don't quite behave as abstract types. For instance, they show this code
```haskell
data K a where
  KAge :: K Age
  KInt :: K Int
get :: K Age→ String
get KAge = "Age"
```

and claim that

> Since get’s type signature declares that its argument is of type K Age, the patterns in get are exhaustive.

But claiming `get` is exhaustive makes little sense if `Age` is an abstract type. Instead, `get` is exhaustive if `Age` is concrete and distinct from `Int`, as is the case in Haskell at role "code". Conversely, the check we're discussing (looking if there are instantiations of `Age` that enable matching with `KAge`) makes little  sense in Haskell, since `Age` isn't a type variable.

Overall, the goal is to take some hidden type equalities, and make them visible at role "type" (Sec. 3). But when typechecking `ModuleUser` we can't look at `Module` because of separate compilation (`Module` need not exist when we typecheck `ModuleUser`), so that idea doesn't translate so easily to our context. Sec. 1 claims the problem could arise with ML-style module systems, which are closer to Scala, and points to Sec. 7, but that doesn't show how the issues could arise with abstract types.

They add in Sec. 3.2 that:
> These kinds in turn support the key insight of this paper: it is only safe to lift coercions through functions with parametric kinds.

but since Scala has *abstract types*, we can soundly write the coercions we want ourselves (as you did), and they're sound by themselves, it's hard to blame the coercion lifting, and much easier to blame the match.

- in the end, Haskell doesn't implement roles as in "​Generative Type Abstraction and Type-level Computation", but uses the evolved variant in  "Safe Zero-cost Coercions for Haskell"; not sure if that complicates the picture, I might have to check it.

**Comment by Blaisorblade** [comment] 2018-02-20 13:08
Took a look, talked with @liufengyun, tried the examples, and #3646 seems to fix all the given ones. @liufengyun also explained me why using `<:<` does the right thing after the preprocessing for types in invariant position; for types in variant position, I think I can see why "maximizing" the type variable works (though I'm a bit wobblier there): If `K` is covariant and for some `X`, `K[X]` satisfies constraints, then `K[MaximizedX]` also does.

In particular, I learned the answer to this question:

> Unification and/or matching with subtyping are probably trickier, but we need some version of it for type inference?

In Dotty `<:<` is also a constraint solver for type variables.

**Comment by Blaisorblade** [comment] 2018-02-20 13:11
Since even the last example is in https://github.com/lampepfl/dotty/pull/3646/files#diff-4511d6b273cb5ec2facf7dbd0ef33330, closing.

**Closed by Blaisorblade** 2018-02-20 13:12 UTC

**Comment by Blaisorblade** [comment] 2018-03-04 14:42
It still seems possible avoiding the upcast might be a question for better inference, though a change here might be simpler.
But I've just found a formal statement that does work in F<: (and to some extent in DOT): narrowing (see TAPL, lemma 26.4.5, or the DOT papers).
I'm still confused how would you narrow type variables in contravariant positions (which is a separate question), but I guess have to check out F^omega<: (or even bigger systems).

Crucially, narrowing talks about type variables, so it is required to show preservation.
So, it’s not a substitution lemma, and I can’t recheck the theory for every handwaving, but this is a good reminder I should study better the theory of subtyping.

And indeed, trying to derive a preservation counterexample fails, and shows that `Bar <: Foo` does not hold, even though for all `X` we have `Bar[X] <: Foo[X]`. Which is consistent but unsatisfactory.

```scala
trait Foo[+A]
class Bar[A] extends Foo[A]
def f[H[+X] <: Foo[X]]: H[Int] = ???
f[Bar]
```

This gives an error:
```
scala> trait Foo[+A]
// defined trait Foo
scala> class Bar[A] extends Foo[A]
// defined class Bar
scala> def f[H[+X] <: Foo[X]]: H[Int]
1 |def f[H[+X] <: Foo[X]]: H[Int]
  |    ^
  |    only classes can have declared but undefined members
scala> def f[H[+X] <: Foo[X]]: H[Int] = ???
def f[H <: Foo] => H[Int]
scala> f[Bar]
1 |f[Bar]
  |  ^
  |  Type argument Bar does not conform to upper bound Foo
```

1. > the opposite (i.e. restricting variance in a subtype) should be disallowed.

That's now making sense to me, and it has bigger chances than the other part.

2. > variance in a subtype should be allowed to be looser than in the base type (as in the above snippet); 

I see it could be made sound, but I agree with @smarter that usability issues are tricky, and it's common to have incomplete type systems for usability reasons. I’d still like to see a more complete proposal, and this isn’t urgent enough I’ll have time for it soon.
