### ISSUE TITLE
Pattern match exhaustivity regression

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18177] opened 2023-07-10 11:24 UTC
Regression found in Open CB for rescala-lang/rescala

## Compiler version

Fails in 3.3.2-RC nightly
Fails in 3.3.1-RC3
Works in 3.3.0

Bisect points to 6b36cd97bf276b57c392cf63e281f283345610cc

## Minimized code

```Scala
//> using options -Xfatal-warnings

object core {
  trait ReSource {
    type State[_] = AnyRef
  }
  trait ReDerived extends ReSource

  object ReDerived {
    type of[S[_]] = ReDerived { type State[V] = S[V] }
  }
}

object Main {
  class TopoState[V]
  type State[V] <: TopoState[V]
  type ReDerived = core.ReDerived.of[State]

  val x: Option[ReDerived] = ???
  x match {
    case Some(value) => ???
    case None        => ???
  }
}

```

## Output

```scala
Compiling project (Scala 3.3.1-RC3, JVM)
[error] ./bisect/main.scala:20:3
[error] match may not be exhaustive.
[error] 
[error] It would fail on pattern case: Some(_)
[error]   x match {
[error]   ^
Error compiling project (Scala 3.3.1-RC3, JVM)
```

## Expectation
Should not trigger exhaustivity warning

**Comment by dwijnand** [comment] 2023-07-11 12:51
Duplicate of #17230

**Closed by dwijnand** 2023-07-11 12:51 UTC
Labels: itype:bug, area:pattern-matching, regression
