### ISSUE TITLE
`@static val`s on Scala.js are not initialized

### ISSUE THREAD

**Issue by armanbilge** [lampepfl/dotty#19441] opened 2024-01-13 16:56 UTC
## Compiler version

`3.4.0-RC1-bin-20240112-c50f2ff-NIGHTLY`

## Minimized code

```Scala
//> using scala 3.4.0-RC1-bin-20240112-c50f2ff-NIGHTLY
//> using platform js

import scala.annotation.static
class Foo
object Foo {
  @static val bar: String = "bar"

  @main def main() = println(bar)
}
```

## Output

```
undefined
```

## Expectation

```
bar
```

**Comment by sjrd** [comment] 2024-01-13 17:12
`@static` never made it into the language spec. It's a dotc "compiler feature" for the JVM, not a language feature. Use at your own risk.

That said, PR welcome to make it work on Scala.js anyway. Expect hard problems near initialization semantics, indeed.

**Comment by armanbilge** [comment] 2024-01-13 17:20
> It's a dotc "compiler feature" for the JVM, not a language feature.

Could an SJS-specific miniphase (or something) just drop the annotation?

**Comment by sjrd** [comment] 2024-01-13 17:36
Maybe, if it doesn't affect observable semantics?

**Comment by dwijnand** [comment] 2024-01-15 11:22
Duplicate of #14710

**Closed by dwijnand** 2024-01-15 11:22 UTC
Labels: itype:enhancement, help wanted, exp:advanced, area:scala.js
