### ISSUE TITLE
scaladoc error when parsing code, using promise.`then`

### ISSUE THREAD

**Issue by rssh** [lampepfl/dotty#12579] opened 2021-05-23 17:36 UTC
## Compiler version

3.0.0

## Minimized code

```Scala
package x

import scalajs.*

class MyClass:

   def fun(x:scala.Any): Unit =
     x match
       case p: js.Promise[_] =>
          p.`then`( x => println(x), e => println(e) )
       case _ =>
          println(x)
```

## Output

trying to generate documentation

```scala
info] welcome to sbt 1.5.2 (N/A Java 15.0.2)
[info] loading global plugins from /Users/rssh/.sbt/1.0/plugins
[info] loading settings for project scalajs-then-doc-build from plugins.sbt ...
[info] loading project definition from /Users/rssh/tests/dotty/scalajs-then-doc/project
[info] loading settings for project root from build.sbt ...
[info] set current project to test (in build file:/Users/rssh/tests/dotty/scalajs-then-doc/)
[info] Main Scala API documentation to /Users/rssh/tests/dotty/scalajs-then-doc/target/scala-3.0.0/api...
[warn] Setting -bootclasspath is currently not supported.
[error] -- Error: src/main/scala/x/X.scala:10:10 ---------------------------------------
[error] 10 |          p.`then`( x => println(x), e => println(e) )
[error]    |          ^^^^^^^^
[error]    |undefined: p.then # -1: TermRef(TermRef(NoPrefix,val p),then) at readTasty
[warn] one warning found
[error] one error found
[error] (Compile / doc) DottyDoc Compilation Failed

```

## Expectation

Documentation should be generated without error.

**Comment by rssh** [comment] 2021-05-23 17:38
[scalajs-then-doc.tar.gz](https://github.com/lampepfl/dotty/files/6528606/scalajs-then-doc.tar.gz)

full sbt project.
run
```
sbt doc
```
to reproduce.

**Comment by griggt** [comment] 2021-05-23 17:55
Looks like a duplicate of #11943

**Comment by smarter** [comment] 2021-05-23 22:47
Closing as duplicate

**Closed by smarter** 2021-05-23 22:47 UTC
Labels: itype:bug
