### ISSUE TITLE
Compatibility issue with Scala at runtime

### ISSUE THREAD

**Issue by newca12** [lampepfl/dotty#6450] opened 2019-05-04 16:23 UTC
This was initially reported [on the dotty gitter channel](https://gitter.im/lampepfl/dotty?at=5c740b5c5df86a456891486f)  by @Jasper-M but I did not find an open issue for that.
The behaviour is the same with -language:Scala2

Scala
```scala
scala> class Foo { def A(i: Double) = i; object A{ def apply(i: Int) = i+1 }; def foo = A(0) }
defined class Foo

scala> new Foo().foo
res6: Int = 1
```
Dotty
```scala
scala> class Foo { def A(i: Double) = i; object A{ def apply(i: Int) = i+1 }; def foo = A(0) }
// defined class Foo

scala> new Foo().foo
val res0: Double = 0.0
```

**Comment by anatoliykmetyuk** [comment] 2019-05-05 06:24
I believe this is a duplicate of #5074. What do you think @smarter?

**Comment by anatoliykmetyuk** [comment] 2019-05-05 06:28
@newca12 does it reproduce outside the repl?

**Comment by newca12** [comment] 2019-05-05 07:26
Yes we got the same behaviour outside the repl.

**Comment by smarter** [comment] 2019-05-05 11:46
Yeah this is a different issue.

**Closed** 2019-05-10 11:51 UTC
Labels: area:typer, compat:scala2
