### ISSUE TITLE
Whitebox macros and recursion do not go along well

### ISSUE THREAD

**Issue by letalvoj** [lampepfl/dotty#8779] opened 2020-04-23 09:56 UTC
## Minimized code

```Scala
import scala.compiletime._, scala.annotation.tailrec, scala.deriving.productElement

@tailrec inline def mapRec[T <: Tuple, A, B](p:Product)(i:Int)(f: A => B) <: Tuple = inline erasedValue[T] match
  case _: (A *: tt) => (f(productElement[A](p,i)) *: mapRec[tt,A,B](p)(i+1)(f))
  case _: (t *: tt) => (productElement[t](p,i) *: mapRec[tt,A,B](p)(i+1)(f))
  case _: Unit => () : Unit

mapRec[(Int,String),Int,String]((1,"lol"))(0)(_.toString)
```

## Output

```scala
val res1: String *: Tuple = (1,lol)
```

## Expectation
```scala
val res1: String *: String *: Unit = (1,lol)
```

**Comment by odersky** [comment] 2020-04-23 10:07
Duplicate of #8739

**Closed by odersky** 2020-04-23 10:07 UTC
Labels: itype:bug
