### ISSUE TITLE
Enum cases with single lowercase letter names cannot be all matched

### ISSUE THREAD

**Issue by SfarmaBit** [lampepfl/dotty#18524] opened 2023-09-06 22:43 UTC
## Compiler version

Scala 3.3.0 (11.0.17, Java OpenJDK 64-Bit Server VM)

## Minimized code

```
enum LowerCase(f:Double):
  case a extends LowerCase(1.0)
  case b extends LowerCase(2.0)
  case c extends LowerCase(2.0)
  def toText: String = this match
    case a => "A"
    case b => "B"
    case c => "C"
```
<script src="https://scastie.scala-lang.org/JfOcjUD2SYm1b738uTGvDg.js"></script>
## Output

```scala
case b => "B" // Unreachable case
case c => "C" // Unreachable case except for null (if this is intentional, consider writing case null => instead)
```

## Expectation
compile without error

**Comment by som-snytt** [comment] 2023-09-06 22:54
See https://github.com/lampepfl/dotty/issues/18496

Maybe the extra help text could kick in for an enum-valued scrutinee.

To answer OP, the normal usage is backticks:
```
case `a` =>
```

**Comment by nicolasstucki** [comment] 2023-09-07 06:42
In general, all lowercase names in pattern positions are bound variables. To reference values that have a name that is lower-cased we must always use backticks (as som-snytt suggested).

The two valid alternatives are:

```scala
  def toText: String = this match
    case `a` => "A"
    case `b` => "B"
    case `c` => "C"
```

```scala
  def toText: String = this match
    case LowerCase.a => "A"
    case LowerCase.b => "B"
    case LowerCase.c => "C"
```

**Comment by nicolasstucki** [comment] 2023-09-07 06:44
Maybe in those cases we might be able to give a hint that `case a =>` catches everything because it is just a binding.

**Comment by bishabosha** [comment] 2023-09-07 07:27
I'm closing as a duplicate of #18496

**Closed by bishabosha** 2023-09-07 07:27 UTC
Labels: area:pattern-matching
