### ISSUE TITLE
Scala 3.2.2 documentation is missing the intro page

### ISSUE THREAD

**Issue by SethTisue** [lampepfl/dotty#16802] opened 2023-02-01 21:20 UTC
at e.g. https://www.scala-lang.org/api/3.2.1/ we read:

> This is the documentation for the Scala standard library.
> Package structure: The [scala](https://www.scala-lang.org/api/3.2.1/scala.html) package contains core types like [Int](https://www.scala-lang.org/api/3.2.1/scala/Int.html), [Float](https://www.scala-lang.org/api/3.2.1/scala/Float.html), [Array](https://www.scala-lang.org/api/3.2.1/scala/Array.html) or [Option](https://www.scala-lang.org/api/3.2.1/scala/Option.html) which

but that text is missing from https://www.scala-lang.org/api/3.2.2/ — I think it's the package object docs

(not sure whose wheelhouse, maybe @Kordyjan ?)

**Comment by julienrf** [comment] 2023-05-30 07:58
FTR, the problem is fixed with 3.3.0:

https://scala-lang.org/api/3.3.0/

See also (for comparison):

https://scala-lang.org/api/3.2.2/
https://scala-lang.org/api/3.2.1/

**Closed** 2023-05-31 17:36 UTC
Labels: itype:bug, area:documentation, area:doctool
