### ISSUE TITLE
Eta expansion for polymorphic methods

### ISSUE THREAD

**Issue by Medowhill** [lampepfl/dotty#6927] opened 2019-07-24 13:21 UTC
## minimized code

```Scala
  def f[T](x: T): T = x
  val g: [T] => T => T = f
```

The code results in the following error:

```scala
3 |  val g: [T] => T => T = f
  |                         ^
  |                         Found:    Any => Any
  |                         Required: PolyFunction{apply: [T](x$1: T): T}
```

Can't polymorphic methods expand to polymorphic functions?

**Comment by smarter** [comment] 2019-07-24 17:22
> Can't polymorphic methods expand to polymorphic functions?

Not yet, this isn't implemented like most things related to polymorphic functions

**Comment by smarter** [comment] 2019-07-24 17:23
Duplicate of https://github.com/lampepfl/dotty/issues/6892

**Closed by smarter** 2019-07-24 17:23 UTC
Labels: itype:bug
