### ISSUE TITLE
Issue with Type inference?

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#1036] opened 2016-01-18 09:57 UTC
The following code snippet does not compile with Dotty but does with Scalac.
```scala
object Test {
  def second[A, B <: A](foo: A, bar: B): B = bar
  def expectString(s: String) = s

  def test = {
    second(Set.empty[String], Set.empty) map expectString
  }
}
```
It fails with the following error:
```scala
./tests/allan/Experiment.scala:7: error: type mismatch:
 found   : Any(s)
 required: String
    second(Set.empty[String], Set.empty) map expectString
                                             ^
```
It also fails to compile if `second` is defined as follow:
```scala
def second[A, B >: A](foo: A, bar: B): B = bar
```
with the following error:
```scala
./tests/allan/Experiment.scala:7: error: type mismatch:
 found   : (scala.collection.immutable.Set[String] | scala.collection.immutable.Set[Any]) @UnsafeNonvariant#A(s)
 required: String
    second(Set.empty[String], Set.empty) map expectString
                                             ^
```
Note that it does compile with `second` applied on `List` instead of `Set`:
```scala
second(List.empty[String], List.empty) map expectString
```
Not sure if it is a duplicate of #998

**Comment by odersky** [comment] 2016-01-18 10:10
It might well be a duplicate of #998. Thanks for the analysis!

**Comment by odersky** [comment] 2016-01-19 20:27
I verified that it is not a duplicate of #998, after all.

**Comment by allanrenucci** [comment] 2016-01-24 09:17
#1040 did not completely fix the bug. If I rewrite slightly the test case, it doesn't compile anymore.
```scala
second(Set.empty[String], Set.empty) map (s => expectString(s))
third(Set.empty[String], Set.empty) map (s => expectString(s))

// Instead of
second(Set.empty[String], Set.empty) map expectString
third(Set.empty[String], Set.empty) map expectString

```

**Comment by odersky** [comment] 2016-01-24 11:31
That looks like a bug / problem in scalac. scalac expands `f` to `x => f(x)` very early, before the checking
the rules of eta expansion. It then has to "assume" that `x => f(x)` was `f` in the user program. Dotty does eta expansion as part of adaptation, so it knows which is which. 

In the scenario given, we need to infer the parameter type for `s` from the expected type. The expected type is not fully defined, so it gets approximated. And that leads to the error. If we write `f` instead of `x => f x` we can apply an additional rule, which says that if the expected type of an eta expansion is not fully defined we take the parameter type of `f` instead. But doing this for general expressions looks like a lot of trouble, and I'd like us to stay out of it.

**Closed** 2016-01-24 11:31 UTC
Labels: Fix available

**Comment by smarter** [comment] 2016-01-24 11:48
> But doing this for general expressions looks like a lot of trouble, and I'd like us to stay out of it.

Do you have a specific example in mind where this could be problematic? It doesn't seem like such a bad idea to me.
