### ISSUE TITLE
infinite loop when evaluating a recursive given definition

### ISSUE THREAD

**Issue by Swoorup** [lampepfl/dotty#10947] opened 2020-12-29 06:57 UTC
When running a program which consumes opaque types as follows, it appears to be stuck on an infinite loop. Not sure what is going on here.

## Minimized code

```Scala
object Prices {
  opaque type Price = BigDecimal

  object Price{
    given Ordering[Price] = summon[Ordering[BigDecimal]]
  }

}

extension[K,V] (m1: Map[K,V]) def computeDiff(m2: Map[K,V])(using Ordering[K])(using orderAsc: Boolean = true): Unit = println("Ok....")

import Prices._
@main def mainz = {
    println("begin")
    val result = Map.empty[Price,Int].computeDiff(Map.empty[Price,Int])
    println(s"end $result")
}
```

Scastie link: https://scastie.scala-lang.org/ajEagvzvTbitmzbqFt0Oxw

## Output

```scala
begin
```

## Expectation
Should successfully print the following:
```scala
begin
Ok....
end
```

This works if the `Price` was swapped with `BigDecimal` in the line
```scala
  val result = Map.empty[Price,Int].computeDiff(Map.empty[Price,Int])
```

This is happening on 3.0.0-M3

**Comment by som-snytt** [comment] 2020-12-29 07:13
WFM
```
➜  snips scalac -version
Scala compiler version 3.0.0-M3 -- Copyright 2002-2020, LAMP/EPFL
➜  snips scalac -d /tmp i10947.scala
➜  snips scala -classpath /tmp mainz
begin
Ok....
end ()
```
Sorry I didn't look closely.
```
➜  snips cat i10947.scala

object Prices:
  opaque type Price = BigDecimal

  object Price:
    given Ordering[Price] = summon[Ordering[BigDecimal]]
  end Price

  extension[K,V] (m1: Map[K,V]) def computeDiff(m2: Map[K,V])(using Ordering[K])(using orderAsc: Boolean = true): Unit =
  println("Ok....")

  import Prices._

  @main def mainz =
    println("begin")
    val result = Map.empty[Price,Int].computeDiff(Map.empty[Price,Int])
    println(s"end $result")
```

**Comment by griggt** [comment] 2020-12-29 07:26
Seems like the issue occurs on Scastie but not locally (works for me too)

**Comment by Swoorup** [comment] 2020-12-29 07:28
@som-snytt @griggt please remove the indentation on the import and mainz block. It should occur then. I'll update the example to use curlies

```
  import Prices._

  @main def mainz =
    println("begin")
    val result = Map.empty[Price,Int].computeDiff(Map.empty[Price,Int])
    println(s"end $result")
```

**Comment by griggt** [comment] 2020-12-29 07:37
Still works for me locally, formatted with the curly braces (I had it indented as you intended without them also).

I am able to reproduce it on Scastie, however.

**Comment by julienrf** [comment] 2020-12-29 08:38
> ```scala
> object Prices {
>   opaque type Price = BigDecimal
> 
>   object Price{
>     given Ordering[Price] = summon[Ordering[BigDecimal]]
>   }
> 
> }
> ```

What happens here is that you have a recursive given definition. `summon[Ordering[BigDecimal]]` returns `Price.given_Ordering_Price` since the opaque type `Price` is equal to `BigDecimal` at that place.

What you need to do is to summon the `Ordering[BigDecimal]` instance at a place where the type `Price` is opaque (not transparent), or at a place where `Price.given_Ordering_Price` is not in scope.

It seems that the following works fine:

~~~ scala
object Prices {
  opaque type Price = BigDecimal

  private val orderingBigDecimal = summon[Ordering[BigDecimal]]
  object Price{
    given Ordering[Price] = orderingBigDecimal
  }

}

extension[K,V] (m1: Map[K,V]) def computeDiff(m2: Map[K,V])(using Ordering[K])(using orderAsc: Boolean = true): Unit = println("Ok....")

import Prices._
@main def mainz =
    println("begin")
    val result = Map.empty[Price,Int].computeDiff(Map.empty[Price,Int])
    println(s"end $result")
~~~

https://scastie.scala-lang.org/6gIRy2nwSLGcsIAvlvTVKw

**Comment by julienrf** [comment] 2020-12-29 08:44
I am not sure what we should do about this problem. I think the current behavior is expected. I don’t think we can reliably implement a detection mechanism for such loops at compilation time so I’m closing the issue. Feel free to re-open it if I miss something.

**Comment by Swoorup** [comment] 2020-12-29 08:58
It seems like an easy pitfall to fall into, but then again I am not sure how to best prevent these kind of issue myself.

I wonder there is any chance to eagarly evaluate givens for opaque type at compile time? I don't know if thats possible.

**Comment by julienrf** [comment] 2020-12-29 09:04
This is not specific to opaque types, the same issue can happen with regular type aliases, abstract type members, etc. It is easy to construct a recursive instance, but it is known to be a hard problem to detect such constructions at compile-time.

**Comment by Swoorup** [comment] 2020-12-29 09:11
😦 That is a bit worrying, hope we can think of something in the future.

**Comment by liufengyun** [comment] 2020-12-29 13:24
We could enhance the initialization check to check for possible non-termination of lazy fields. A related issue #9668.

**Comment by tel** [comment] 2021-01-15 23:37
What's interesting about this one is that one common use case is derivation (a la Haskell's generalize newtype deriving). Would it be possible to hook something into the derivation mechanism?

**Comment by som-snytt** [comment] 2021-01-16 02:46
It is a lint in Scala 2

```scala
➜  ~ scala -Xlint
Welcome to Scala 2.13.4 (OpenJDK 64-Bit Server VM, Java 15).
Type in expressions for evaluation. Or try :help.

scala> type Price = BigDecimal
type Price

scala> implicit val `order price`: Ordering[Price] = implicitly[Ordering[BigDecimal]]
                                                               ^
       warning: Implicit resolves to enclosing value order price
val order price: Ordering[Price] = null

scala>
```

**Comment by kubukoz** [comment] 2021-02-13 16:13
> What's interesting about this one is that one common use case is derivation (a la Haskell's generalize newtype deriving). Would it be possible to hook something into the derivation mechanism?

@tel I really wish this was possible. I don't see people switching from `@newtype` to opaque types anytime soon if this isn't made easier - I just bumped on the issue at question myself and the boilerplate needed to do it "properly" is very discouraging.

**Closed** 2022-06-20 14:27 UTC
Labels: itype:bug
