### ISSUE TITLE
Tasty hardening: Tasty with missing fields in classes isn't detected early enough

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4258] opened 2018-04-05 21:34 UTC
I keep getting, even on master, this failure on local runs:
```
> testOnly dotty.tools.dotc.FromTastyTests
[info] Cleaning the dotty-sbt-bridge cache
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for dotty-interfaces/test:testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for dotty-library/test:testOnly
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for dotty/test:testOnly
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Test run started
[info] Test dotty.tools.dotc.FromTastyTests.runTestFromTasty started
[=======================================] completed (944/944, 67s)
[=======================================] completed (898/898, 40s)  s)
[=======================================] completed (1/1, 0s)
[info] Test dotty.tools.dotc.FromTastyTests.posTestFromTasty started
[=======================================] completed (1466/1466, 71s)
undefined: B2.t.f # 6948988: TermRef(TermRef(ThisType(TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <root>)),module class <empty>)),module class B2$)),module t),f) at frontend
[=======================================] completed (1362/1362, 33s)
[error] Test dotty.tools.dotc.FromTastyTests.posTestFromTasty failed: java.lang.AssertionError: Expected no errors when compiling, failed for the following reason(s):
[error]
[error]   - encountered 1 error(s), took 104.822 sec
[error]     at dotty.tools.vulpix.ParallelTesting$CompilationTest.checkCompile(ParallelTesting.scala:958)
[error]     at dotty.tools.dotc.FromTastyTests.posTestFromTasty(FromTastyTests.scala:68)
[error]     ...

================================================================================
Test Report
================================================================================

4 passed, 1 failed, 5 total
    tests/pos/overloaded_ho_fun.scala failed


--------------------------------------------------------------------------------
Note - reproduction instructions have been dumped to log file:
    /Users/pgiarrusso/git/dotty/testlogs/tests-2018-04-05/tests-2018-04-05-T21-27-32.log
--------------------------------------------------------------------------------
[info] Test run finished: 1 failed, 0 ignored, 2 total, 214.307s
[error] Failed: Total 2, Failed 1, Errors 0, Passed 1
[error] Failed tests:
[error] 	dotty.tools.dotc.FromTastyTests
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for dotty-sbt-bridge/test:testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for dotty-doc/test:testOnly
[error] (dotty-compiler/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 218 s, completed Apr 5, 2018 9:31:08 PM
```

**Comment by Blaisorblade** [comment] 2018-04-05 21:51
Investigation with a debugger suggests, essentially, not enough information has been loaded for retypechecking the loaded tree. Still no clue why this only happens locally — I tried to clean the build deeper and deeper without making a difference. I might still be doing something wrong.

The error appears when loading and typing the tree, in the call to `t.f(fun)`. The issue is that `t.f` is overloaded but not enough information is there during loading (too many fields are `null`) to be able to disambiguate the overload.

```scala
  object t { def f(x: SAM[Int, Int]): Int = 0; def f(y: SAM[String, Int]): String = "1" }
  def fun(x: Int) = x
  def fun2[T] = (x: T) => 42
  t.f(fun) // different param type, monomorphic method
```

# Details (not sure if helpful)

During loading,  in the call to `tpd.Apply` (and `assignType`) from `TreeUnpickler`, `t.f`'s type is a `TermRef` with `Name("f") as `myDesignator` and no other info.

Here `t.f` is in fact overloaded, but the relevant internal data structures are so incomplete that `Types.NamedType.disambiguate` on the corresponding `MultiDenotation` fails (== returns `NoDenotation`), because `NamedType.currentSignature` finds `null` signature and denotation and returns `NotAMethod`, and eventually`computeDenot` on the `TermRef` for `t.f` fails with `NoDenotation`, which looks not even overloaded.

**Comment by allanrenucci** [comment] 2018-04-06 07:42
Try removing the output (i.e. `out`)  directory before running the tests. If this doesn't fix your problem, try running the tests locally after doing `git clean -Xfd`.

**Comment by Blaisorblade** [comment] 2018-04-06 09:28
Got the same error in the fresh clone.

**Comment by Blaisorblade** [comment] 2018-04-06 13:32
The test passes for me on Linux, so I'm gonna ask (a) can _anybody_ confirm they can run the test successfully on Mac (if yes, on APFS or HFS+?) (b) could this depend on the order files are read (even though IIRC we should have some code to prevent that issue, or at least Scalac has)?
Think @smarter knows better.

If I'm not still screwing up somehow, I have the setup to walk through the error, so maybe we can look at it together.

**Comment by allanrenucci** [comment] 2018-04-06 14:04
Not able to reproduce on latest master with macOS 10.13.4

**Comment by Blaisorblade** [comment] 2018-04-06 16:28
So I was screwing up a bit (sorry about that), and #4257 was relevant, but I'll look closer — I think some hardening might be warranted.

**Comment by OlivierBlanvillain** [comment] 2019-02-06 16:17
I'm gonna close this for now since it doesn't seam to be reproducible

**Closed by OlivierBlanvillain** 2019-02-06 16:17 UTC
