### ISSUE TITLE
SemanticDB is not being generated for extension methods

### ISSUE THREAD

**Issue by kpodsiad** [lampepfl/dotty#18570] opened 2023-09-19 08:49 UTC
Raised in https://github.com/scalameta/metals/issues/5478, I've encountered this on my own as well when defining extension methods in companion object for trait.

## Compiler version

3.3.1

## Minimized code
```scala
//> using scala "3.3.1"

opaque type Deck = Long

object Deck {
  extension (data: Deck) {
    def fooSize: Int = ???
  }
}

// import Deck.* // uncomment and semanticDB will be properly generated
object DeckUsage {
  val deck: Deck = ???
  deck.fooSize
}
```

## Output
Generated semanticDB file doesn't contain entries for `fooSize` usage in object `DeckUsage`

## Expectation
Generated semanticDB file doesn't contain entries for `fooSize` usage in object `DeckUsage`, without need for an additional import

**Comment by Kordyjan** [comment] 2023-09-19 09:09
@tanishiking can you take a look?

**Comment by tgodzik** [comment] 2023-09-19 10:01
There is the same issue in the presentation compiler, which seems unrelated. Could it due to those extension methods being resolved at a later phase?

**Comment by tanishiking** [comment] 2023-09-19 11:15
It seems like caused by the missing span for extension method
https://github.com/lampepfl/dotty/blob/a37dac66b1d48e8ac173dd4b2486b353f8574cc2/compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala#L243 and it might be https://github.com/lampepfl/dotty/pull/18557 will help 👍 FYI @kasiaMarek

**Comment by bishabosha** [comment] 2023-09-20 09:05
fixed by https://github.com/lampepfl/dotty/pull/18557

**Closed by bishabosha** 2023-09-20 09:05 UTC
Labels: itype:bug, area:semanticdb
