### ISSUE TITLE
Various literals allowed in postfix position on expr

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#5824] opened 2019-01-31 00:01 UTC
tested in Dotty REPL 0.12-RC1, I believe only these cases are an issue:
```scala
val foo = <expr> <booleanLiteral
                  | characterLiteral
                  | stringLiteral
                  | symbolLiteral
                  | "null">
```
e.g.
```scala
val foo = 123 'bar;
```

in Dotty REPL results in `val foo: Int = 123`, this is particularly bad as the Symbol literal is ignored, where otherwise an error is generated for their presence.

However, in Scala REPL 2.12.8 results in:
```
<console>:1: error: ';' expected but symbol literal found.
       val foo = 123 'bar;
                     ^
```

**Comment by odersky** [comment] 2019-02-01 08:44
Seems to be REPL only. I could not reproduce standalone.

**Comment by bishabosha** [comment] 2019-02-01 10:17
This compiles with dotc.

```scala
object Main {
  def main(args: Array[String]): Unit = {
    val foo = 123 "";
    println(foo)
  }
}
```

**Comment by Blaisorblade** [comment] 2019-02-06 01:22
Tokens are being swallowed and ignored — seems a dup of #4934.

**Comment by odersky** [comment] 2019-04-02 11:06
Fixed by #6209

**Closed by odersky** 2019-04-02 11:06 UTC
Labels: area:parser, itype:bug
