### ISSUE TITLE
"sbt consoleProject" does not work

### ISSUE THREAD

**Issue by xuwei-k** [lampepfl/dotty#8992] opened 2020-05-18 05:34 UTC
#### `build.sbt`

```scala
scalaVersion := "0.24.0-RC1"
```

#### `project/build.properties`

```
sbt.version=1.3.10
```

#### `project/plugins.sbt`

```scala
addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.1")
```

run: `sbt consoleProject`

## Output

```
[error] (run-main-0) java.lang.NoClassDefFoundError: dotty/tools/repl/ReplDriver
[error] java.lang.NoClassDefFoundError: dotty/tools/repl/ReplDriver
[error] 	at xsbt.ConsoleInterface.run(ConsoleInterface.java:43)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:210)
[error] 	at sbt.Console.console0$1(Console.scala:48)
[error] 	at sbt.Console.$anonfun$apply$2(Console.scala:51)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:257)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: dotty.tools.repl.ReplDriver
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at xsbt.ConsoleInterface.run(ConsoleInterface.java:43)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:210)
[error] 	at sbt.Console.console0$1(Console.scala:48)
[error] 	at sbt.Console.$anonfun$apply$2(Console.scala:51)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:257)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Nonzero exit code: 1
[error] (consoleProject) Nonzero exit code: 1
```

**Comment by OlivierBlanvillain** [comment] 2020-05-22 16:39
What's consoleProject?

**Comment by xuwei-k** [comment] 2020-05-22 18:21
https://github.com/sbt/sbt/blob/1f3ac6c8cd6fc38f8a6ad85ddca53ade346a7d34/main/src/main/scala/sbt/Keys.scala#L204

https://www.scala-sbt.org/1.x/docs/Console-Project.html

**Comment by bishabosha** [comment] 2020-12-14 10:01
@adpi2 is this something managed by zinc?

**Comment by adpi2** [comment] 2020-12-14 10:58
The Scala 3 compiler bridge contains an `xsbt.ConsoleInterface` implementation that is instantiated by Zinc using reflection on a Scala instance class loader. The problem here is that Scala instance class loader is on Scala 2.12 and not Scala 3.0.0 and the culprit is sbt:
https://github.com/sbt/sbt/blob/23fd24c838e6aa68688b01861a4c21f1154f9103/main/src/main/scala/sbt/internal/ConsoleProject.scala#L29-L32

In order to fix this in sbt-dotty we would have to fully overwrite the `consoleProject` task. But sbt-dotty will soon be merged into sbt, so I suggest to fix this directly in sbt as part of https://github.com/sbt/sbt/issues/6080.

**Comment by adpi2** [comment] 2020-12-23 10:44
I was wrong here, the problem is not that the Scala Instance is 2.12 but that the bridge is the Scala 3 compiler bridge and not the Scala 2.12 compiler bridge.

`consoleProject` must load the Scala 2.12 instance and the sbt class loader so that you can access your `build.sbt` definition.

**Closed** 2021-01-05 09:36 UTC
Labels: area:tooling, itype:bug
