### ISSUE TITLE
Difference in dotc and scalac for handling self types

### ISSUE THREAD

**Issue by Jasper-M** [lampepfl/dotty#2472] opened 2017-05-19 09:04 UTC
The following compiles with scalac but not dotc:
```
trait S1 { self: S2 => }
trait S2 { self: S3 => }
trait S3
```

Since https://github.com/lampepfl/dotty/commit/175499537c87c78d0b926d84b7a9030011e42c00

Discussion on https://gitter.im/lampepfl/dotty?at=591eac1433e9ee771cc14553

**Comment by propensive** [comment] 2017-05-19 09:17
The error is:
```
-- Error: fail.scala:1:6 -------------------------------------------------------
1 |trait S1 { self: S2 => }
  |      ^
  |missing requirement: self type S2 & S1 of trait S1 does not conform to self type S3 of required trait S2

one error found
```

This looks like it's related to #2467.

**Comment by odersky** [comment] 2017-07-20 14:32
It looks indeed like a duplicate of #2467.

**Closed by odersky** 2017-07-20 14:32 UTC
Labels: area:typer, exp:advanced, itype:bug, prio:medium
