### ISSUE TITLE
Type inference does not work when converting application to Polymorphic Function

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#12045] opened 2021-04-09 20:11 UTC
## Compiler version

3.0.0-RC2

## Minimized code

```Scala
trait Test[F[_], DbEffect[_]] {
  def doTx[A](t: DbEffect[A]): F[A] = ???
  
  def tx: [A] => DbEffect[A] => F[A] = doTx _ // error
  
  def tx2: [A] => DbEffect[A] => F[A] = eff => doTx(eff) //error
  
  def tx3: [A] => DbEffect[A] => F[A] = [A] => (eff: DbEffect[A]) => doTx(eff) //compiles successfully
}
```

## Output

```scala
Found:    DbEffect[Any] => F[Any]
Required: PolyFunction{apply: [A](x$1: DbEffect[A]): F[A]}
```

## Expectation
Successful compilation

**Comment by scf37** [comment] 2021-04-09 21:46
Similar problem with `identity`
```scala
trait Test[F[_]] {
  def foo: [A] => F[A] => F[A] = identity
  
  def foo2: [A] => F[A] => F[A] = identity[<WHAT EVEN SHOULD BE HERE?>]
}
```

**Comment by LPTK** [comment] 2021-04-10 06:39
This is a duplicate of https://github.com/lampepfl/dotty/issues/6892.

**Closed** 2021-04-13 00:04 UTC
Labels: itype:bug
