### ISSUE TITLE
REPL is spoiled after tab completion

### ISSUE THREAD

**Issue by punzik** [lampepfl/dotty#19173] opened 2023-12-03 11:05 UTC
## Compiler version

Scala 3.3.1 (19.0.2, Java OpenJDK 64-Bit Server VM).

## Repl log

```
Welcome to Scala 3.3.1 (19.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                        
scala> val a = (1, 2, 3)
val a: (Int, Int, Int) = (1,2,3)
                                                                                                                                        
scala> a.toList.map(_ + 1)
val res0: List[Int] = List(2, 3, 4)
                                                                                                                                        
scala> a.toList.map(_ + 1)
val res1: List[Int] = List(2, 3, 4)
                                                                                                                                        
scala> a.toList.map(_ + 1)
Bad symbolic reference. A signature
refers to JFunction1$mcII$sp/T in package scala.runtime.java8 which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling the signature.
1 error found
```

The first call `a.toList.map` is taken from the repl history (from the previous run), the second call is hand-typed, on the third call `toList` is taken from the Tab autocomplete. After the third call the `map` function stops working on any lists.

One of the first calls of 'a.toList.map` can be omitted, it breaks after autocomplete anyway.

## Expectation

The same result is expected as when the first two commands are called.

**Comment by hamzaremmal** [comment] 2023-12-03 16:10
I see that you are using Java 19. Have you tried using Java 21 ? See https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#scala-compatibility-table

**Comment by SethTisue** [comment] 2023-12-14 01:47
Offhand, looks like it could be simply a duplicate of #15562. Do you agree?

**Comment by SethTisue** [comment] 2023-12-21 00:56
@punzik if you feel there's helpful non-duplicate information in this ticket, please leave it as a comment on the other ticket

**Closed by SethTisue** 2023-12-21 00:56 UTC
Labels: itype:bug, area:repl

**Comment by som-snytt** [comment] 2023-12-21 02:53
`stat:clarification`
