### ISSUE TITLE
Backend should emit a warning when file names clash on case-insensitive FS

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#2679] opened 2017-06-04 10:45 UTC

**Comment by smarter** [comment] 2017-06-06 18:51
Look what I found in GenBCode :)
```scala
       // todo: add back those checks
        /*val lowercaseJavaClassName = claszSymbol.javaClassName.toLowerCase
        caseInsensitively.get(lowercaseJavaClassName) match {
          case None =>
            caseInsensitively.put(lowercaseJavaClassName, claszSymbol)
          case Some(dupClassSym) =>
            reporter.warning(
              claszSymbol.pos,
              s"Class ${claszSymbol.javaClassName} differs only in case from ${dupClassSym.javaClassName}. " +
                "Such classes will overwrite one another on case-insensitive filesystems."
            )
        }*/
```

**Comment by DarkDimius** [comment] 2017-06-06 18:52
:-) just remove comments around it and you're done :-)

**Comment by smarter** [comment] 2018-01-11 01:12
Duplicate of https://github.com/lampepfl/dotty/issues/1077

**Closed by smarter** 2018-01-11 01:12 UTC
