### ISSUE TITLE
REPL :type command sometimes prints color highlighting characters literally

### ISSUE THREAD

**Issue by deanwampler** [lampepfl/dotty#10615] opened 2020-12-03 04:03 UTC
## Minimized code

At the REPL prompt:

```Scala
:type if (true) 1.0 else 2L
 ```

## Output

```scala
(31m1.00m : Double) | (31m2L0m : Long)
```

## Expectation

```scala
(1.0 : Double) | (2L : Long)
```

I observed this on OS X Catalina,, in both Terminal and iTerm.

**Comment by som-snytt** [comment] 2020-12-03 06:57
It looks like `typeOf` already colorizes the literal types, and then `:type` munges the string with its highlighter pen.

I was hoping there was a quick way to say "give me a context with highlighting turned off while I perform an operation."

I tried just getting a "plain" printer but wound up with `scala.this.Double` badly colorized.

**Comment by ckipp01** [comment] 2022-02-20 13:39
I'm curios if this is now fixed? I can't seem to reproduce this and I'm also on OS X and using iTerm.

<img width="311" alt="Screenshot 2022-02-20 at 14 39 11" src="https://user-images.githubusercontent.com/13974112/154845366-10ca715c-d928-433f-a39e-a20886f3ad73.png">

**Comment by som-snytt** [comment] 2022-02-20 14:26
@ckipp01 this narrow issue is fixed by the linked PR. I don't remember why my PR doesn't say "fixes". Maybe because I was working on related string rendering and Scala 2 dragged heels on that PR?

**Closed** 2022-02-20 15:09 UTC
Labels: itype:bug, area:repl
