### ISSUE TITLE
scalaz.zio cross compilation dotty errors

### ISSUE THREAD

**Issue by fkowal** [lampepfl/dotty#6149] opened 2019-03-22 23:38 UTC
When adding dotty 0.13.0-RC1 as scalaVersion in https://github.com/scalaz/scalaz-zio/pull/674
I ran in to a few "regressions" compared to 2.12.8
- type inference
- implicit resolution
- pattern matching exhaustivity #6197
- compile time error _scala.MatchError: Ident(ACCEPTABLE)_ #6151
- runtime time error _java.lang.NoSuchMethodError: org.specs2.specification.create.S2StringContextCreation$specificationInStringContext.s2(Lscala/collection/Seq;)Lorg/specs2/specification/core/Fragments_ #6150

I am not sure how to report all of them.
Please have a look at the commit history, you can reproduce them by running:
> sbt ++0.13.0-RC1 coreJVM/test:compile

**Comment by smarter** [comment] 2019-03-23 00:09
> I am not sure how to report all of them.

For each issue, try to find the minimum amount of code required to reproduce it (try to get it down to one file, and then it's easy to just remove code from that file piece by piece to get something minimal). If this proves too cumbersome, then an issue which points to a single git commit that clearly shows the problem is also acceptable, but it'll take us much longer to fix it.

**Comment by AleksanderBG** [comment] 2019-03-26 09:18
@fkowal let me just add that all problems you mentioned are important issues for us to fix and you minimising them would be very helpful!

**Comment by fkowal** [comment] 2019-03-26 19:45
I’ll be sure. Get to try and narrow down the source of these errors. Two of them have already their own issues opened. So 3 more to go

**Comment by VladKopanev** [comment] 2019-04-01 09:30
I have created a ticket that is related to type inference and also was encountered during scalaz.zio compilation with dotty, please take look https://github.com/lampepfl/dotty/issues/6199

**Comment by liufengyun** [comment] 2019-07-19 10:25
It seems all bugs reported are fixed in the master branch.

@fkowal Could you please check if it indeed works? Thanks.

**Comment by OlivierBlanvillain** [comment] 2019-09-05 16:01
Closing this for now, feel free to open new issues as needed.

**Closed by OlivierBlanvillain** 2019-09-05 16:01 UTC
Labels: itype:meta
