### ISSUE TITLE
Unexpected completion content

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#4748] opened 2018-07-01 09:00 UTC
![image](https://user-images.githubusercontent.com/20694662/42132703-aea15ecc-7d4f-11e8-85ab-e2594bfdd2ab.png)
![image](https://user-images.githubusercontent.com/20694662/42132709-d7497008-7d4f-11e8-9645-5329eaafd6aa.png)

**Comment by allanrenucci** [comment] 2018-07-01 10:15
Duplicate of #4397

**Closed by allanrenucci** 2018-07-01 10:15 UTC
