### ISSUE TITLE
Interaction of enum widening and selecting extension

### ISSUE THREAD

**Issue by agilesteel** [lampepfl/dotty#13948] opened 2021-11-14 21:11 UTC
I stumbled on an issue that is related to cats but I wasn't sure if it's a Scala 3 issue or not. I'm simply creating this here to reference https://github.com/typelevel/cats/issues/4043.

**Comment by bishabosha** [comment] 2021-11-15 14:54
viewing typelevel/cats#4043 I would call this a duplicate of https://github.com/lampepfl/dotty/issues/12701

**Comment by bishabosha** [comment] 2021-11-15 16:09
If you compare these two gists:
https://gist.github.com/bishabosha/c45e90b7fe9765ea5ebe666cd4ae2fb4
and https://gist.github.com/agilesteel/05482df2e1f420f762dec7696088552d,

it seems that extension methods found through implicit conversions will not widen a class type, but Scala 3 extension methods with infix modifier will widen `Some[Int]` to `Option[Int]` e.g.

**Comment by odersky** [comment] 2021-12-09 08:17
It has nothing to do with extension methods. enums will widen to the enum type, unless the more precise type is expected.

**Closed by odersky** 2021-12-09 08:17 UTC
Labels: stat:needs minimization

**Comment by odersky** [comment] 2021-12-09 12:15
No idea. You have to dig deeper to find out.
