### ISSUE TITLE
Cyclic reference while unpickling definition

### ISSUE THREAD

**Issue by szeiger** [lampepfl/dotty#3919] opened 2018-01-25 18:17 UTC
We're getting an error compiling the tests in https://github.com/scala/collection-strawman/pull/361 on 0.6.0-RC1. The source of the error must be somewhere in the new `LazyList` implementation. The same error occurs with only those changes and none in the tests.

```
[info] exception occurred while compiling /home/travis/build/scala/collection-strawman/collections/src/test/scala/strawman/collection/test/Test.scala
java.lang.AssertionError: assertion failed: Cyclic reference while unpickling definition at address 94 in unit /home/travis/build/scala/collection-strawman/collections/src/test/scala/strawman/collection/test/Test.scala
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:36)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:637)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$Completer.complete(TreeUnpickler.scala:91)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:246)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:209)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:211)
	at dotty.tools.dotc.core.TypeApplications$.typeParams$extension(TypeApplications.scala:170)
	at dotty.tools.dotc.core.TypeApplications$.appliedTo$extension2(TypeApplications.scala:335)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthType$1(TreeUnpickler.scala:259)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readType(TreeUnpickler.scala:363)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$10(TreeUnpickler.scala:259)
	at dotty.tools.dotc.core.tasty.TastyReader.until(TastyReader.scala:125)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthType$1(TreeUnpickler.scala:259)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readType(TreeUnpickler.scala:363)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthType$1(TreeUnpickler.scala:265)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readType(TreeUnpickler.scala:363)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$8$$anonfun$2(TreeUnpickler.scala:224)
	at dotty.tools.dotc.core.Types$HKTypeLambda.<init>(Types.scala:2962)
	at dotty.tools.dotc.core.Types$HKTypeLambda$.apply(Types.scala:3013)
	at dotty.tools.dotc.core.Types$HKTypeLambda$.apply(Types.scala:3010)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$9(TreeUnpickler.scala:224)
	at scala.collection.MapLike.getOrElse(MapLike.scala:128)
	at scala.collection.MapLike.getOrElse$(MapLike.scala:126)
	at scala.collection.AbstractMap.getOrElse(Map.scala:59)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readMethodic$1(TreeUnpickler.scala:225)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthType$1(TreeUnpickler.scala:281)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readType(TreeUnpickler.scala:363)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthType$1(TreeUnpickler.scala:261)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readType(TreeUnpickler.scala:363)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTpt(TreeUnpickler.scala:1061)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:719)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:643)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedParams$$anonfun$2(TreeUnpickler.scala:869)
	at dotty.tools.dotc.core.tasty.TastyReader.collectWhile(TastyReader.scala:137)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedParams(TreeUnpickler.scala:869)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTemplate(TreeUnpickler.scala:770)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:717)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:643)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$Completer.complete(TreeUnpickler.scala:91)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:246)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:209)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:211)
	at dotty.tools.dotc.core.Types$NamedType.info(Types.scala:1642)
	at dotty.tools.dotc.core.Types$TypeRef.underlying(Types.scala:2072)
	at dotty.tools.dotc.core.Types$Type.termSymbol(Types.scala:419)
	at dotty.tools.dotc.core.Types$Type.isError(Types.scala:268)
	at dotty.tools.dotc.ast.tpd$.skipTransform(tpd.scala:627)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1123)
	at dotty.tools.dotc.ast.TreeTypeMap.transform(TreeTypeMap.scala:119)
	at dotty.tools.dotc.ast.TreeTypeMap.apply(TreeTypeMap.scala:140)
	at dotty.tools.dotc.ast.tpd$TreeOps$.loop$1(tpd.scala:666)
	at dotty.tools.dotc.ast.tpd$TreeOps$.changeOwner$extension(tpd.scala:669)
	at dotty.tools.dotc.core.tasty.TreeUnpickler.dotty$tools$dotc$core$tasty$TreeUnpickler$TreeReader$$_$_$$anonfun$10(TreeUnpickler.scala:789)
	at scala.collection.immutable.List.map(List.scala:287)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTemplate(TreeUnpickler.scala:789)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:717)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:643)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$Completer.complete(TreeUnpickler.scala:91)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:246)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:209)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:211)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:209)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:211)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:352)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.flags(SymDenotations.scala:152)
	at dotty.tools.dotc.core.SymDenotations$ModuleCompleter.complete(SymDenotations.scala:1950)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:246)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:209)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:211)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.isAccessibleFrom(SymDenotations.scala:723)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.accessibleFrom(Denotations.scala:683)
	at dotty.tools.dotc.typer.Typer.selection$2(Typer.scala:200)
	at dotty.tools.dotc.typer.Typer.unambiguousSelection$1(Typer.scala:222)
	at dotty.tools.dotc.typer.Typer.recur$1(Typer.scala:229)
	at dotty.tools.dotc.typer.Typer.namedImportRef$1(Typer.scala:236)
	at dotty.tools.dotc.typer.Typer.loop$1(Typer.scala:331)
	at dotty.tools.dotc.typer.Typer.findRef$1(Typer.scala:354)
	at dotty.tools.dotc.typer.Typer.typedIdent(Typer.scala:122)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1700)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1769)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1844)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:418)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:415)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1701)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1769)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1844)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:418)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:415)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1701)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1769)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1844)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:667)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:767)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1720)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1770)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1758)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1770)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Namer.typedAheadExpr$$anonfun$1(Namer.scala:954)
	at dotty.tools.dotc.typer.Namer.typedAheadImpl(Namer.scala:944)
	at dotty.tools.dotc.typer.Namer.typedAheadExpr(Namer.scala:954)
	at dotty.tools.dotc.typer.Namer.rhsType$2(Namer.scala:1072)
	at dotty.tools.dotc.typer.Namer.cookedRhsType$1(Namer.scala:1084)
	at dotty.tools.dotc.typer.Namer.lhsType$lzyINIT1$1(Namer.scala:1085)
	at dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:1085)
	at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1098)
	at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1106)
	at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:737)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:788)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:766)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:246)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:209)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:211)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:352)
	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:1673)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1698)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1769)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1809)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1832)
	at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:644)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:646)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1727)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1770)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1844)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1381)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1708)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1769)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1809)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1832)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1422)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1711)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1769)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1809)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1832)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1593)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1751)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1770)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1820)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1832)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1593)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1751)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1770)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1844)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:66)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:34)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:70)
	at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:95)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:95)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:123)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:136)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:141)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:88)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:143)
	at dotty.tools.dotc.Run.compileSources(Run.scala:94)
	at dotty.tools.dotc.Run.compile(Run.scala:78)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:29)
	at dotty.tools.dotc.Driver.process(Driver.scala:127)
...
```

Full build log: https://travis-ci.org/scala/collection-strawman/builds/333376532?utm_source=github_status&utm_medium=notification

**Comment by smarter** [comment] 2018-01-25 18:35
Duplicate of https://github.com/lampepfl/dotty/issues/3816

**Closed by smarter** 2018-01-25 18:35 UTC

**Comment by smarter** [comment] 2018-01-25 18:38
There's no workaround, except disabling the tests on Dotty.
