### ISSUE TITLE
Can't publish SJS code under 3.0.0

### ISSUE THREAD

**Issue by catap** [lampepfl/dotty#12581] opened 2021-05-23 22:44 UTC
## Compiler version

`3.0.0`

## Minimized code

```Scala
sealed class DomWebSocketException(e: dom.Event) extends IOException(s"Dom Web Socket error event: ${JSON.stringify(e)}")
```

## Output

```
[error] 17 |sealed class DomWebSocketException(e: dom.Event) extends IOException(s"Dom Web Socket error event: ${JSON.stringify(e)}")
[error]    |                                                                                                     ^^^^^^^^^^^^^^^^
[error]    |undefined: scala.scalajs.js.JSON.stringify # -1: TermRef(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class scalajs)),object js),JSON),stringify) at readTasty
```

## Expectation

Should be compiled and work as it is.

The only way to get this error is `sbt publishLocal` and this is happened on stage like `Main Scala API documentation to ...`

**Comment by smarter** [comment] 2021-05-23 22:47
Duplicate of https://github.com/lampepfl/dotty/issues/11943

**Closed by smarter** 2021-05-23 22:47 UTC
Labels: itype:bug
