### ISSUE TITLE
Some operators cause ClassFormatErrors in generic givens

### ISSUE THREAD

**Issue by travisbrown** [lampepfl/dotty#6920] opened 2019-07-23 20:54 UTC
## minimized code

```Scala
given [A] { def (xs: List[A]) < (ys: List[A]): Boolean = false }

List(1) < List(2)
```

<details>
<summary>Stack trace</summary>

```scala
java.lang.ClassFormatError: Method "<_of_List_A_given" in class rs$line$2$ has illegal signature "()Lrs$line$1$$_of_List_A_given;"
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
        at dotty.tools.repl.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:28)
        at dotty.tools.repl.AbstractFileClassLoader.loadClass(AbstractFileClassLoader.scala:32)
        at rs$line$2.res0(rs$line$2)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at dotty.tools.repl.Rendering.$anonfun$3(Rendering.scala:57)
        at scala.Option.map(Option.scala:163)
        at dotty.tools.repl.Rendering.valueOf(Rendering.scala:57)
        at dotty.tools.repl.Rendering.renderVal(Rendering.scala:80)
        at dotty.tools.repl.ReplDriver.displayMembers$3$$anonfun$3(ReplDriver.scala:274)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at dotty.tools.repl.ReplDriver.displayMembers$7(ReplDriver.scala:274)
        at dotty.tools.repl.ReplDriver.displayDefinitions$$anonfun$3$$anonfun$2(ReplDriver.scala:300)
        at scala.Option.map(Option.scala:163)
        at dotty.tools.repl.ReplDriver.displayDefinitions$$anonfun$1(ReplDriver.scala:300)
        at dotty.tools.dotc.core.Phases.atPhase$$anonfun$1(Phases.scala:35)
        at dotty.tools.dotc.core.Periods.atPhase(Periods.scala:25)
        at dotty.tools.dotc.core.Phases.atPhase(Phases.scala:35)
        at dotty.tools.dotc.core.Contexts$Context.atPhase(Contexts.scala:71)
        at dotty.tools.repl.ReplDriver.displayDefinitions(ReplDriver.scala:306)
        at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:230)
        at scala.util.Either.fold(Either.scala:191)
        at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:230)
        at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:182)
        at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:127)
        at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:130)
        at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$2$$anonfun$1(ReplDriver.scala:143)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$1(ReplDriver.scala:143)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:143)
        at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:130)
        at dotty.tools.repl.Main$.main(Main.scala:6)
        at dotty.tools.repl.Main.main(Main.scala)

```
</details>
The following works just fine:

```scala
scala> given { def (xs: List[Int]) < (ys: List[Int]): Boolean = false }
// defined object <_of_List_Int_given

scala> List(1) < List(2)
val res0: Boolean = false
```
Or:
```scala
scala> given [A] { def (xs: List[A]) lt (ys: List[A]): Boolean = false }
// defined class lt_of_List_A_given

scala> List(1) lt List(2)
val res1: Boolean = false
```

**Comment by smarter** [comment] 2019-07-23 21:02
This has the same root cause as https://github.com/lampepfl/dotty/issues/6902 and is therefore fixed in master, sadly the fix just missed the 0.17.0-RC1 release, but it'll be in the next nightly.

**Closed by smarter** 2019-07-23 21:02 UTC
Labels: itype:bug
