### ISSUE TITLE
Forbid case classes without parameter lists?

### ISSUE THREAD

**Issue by LPTK** [lampepfl/dotty#6969] opened 2019-07-30 16:03 UTC
Scalac rejects case classes such as:

```scala
@ case class A[T]
(console):1: case classes must have a parameter list; try 'case class A()' or 'case object A'
case class A[T]
               ^
```

Dotty currently accepts them. This can be confusing in pattern matching: it looks like pattern `case A =>` is matching on instances of class `A`, but it's actually matching on the companion object.

**Comment by smarter** [comment] 2019-07-30 16:08
Yes, we should emit the same error as scalac here.

**Comment by ashwinbhaskar** [comment] 2019-07-31 04:02
@smarter can I take this up? If so, can you please assign it to me as well.

**Comment by LPTK** [comment] 2019-07-31 06:40
BTW, you should make sure that `enum A { case B[C] }` has the same treatment.

**Comment by ashwinbhaskar** [comment] 2019-08-03 14:20
@smarter @LPTK I am not able to reproduce the issue. The dotty compiler does seem to report a syntax error. 
```
dotc experiments/CaseClass.scala 
-- [E004] Syntax Error: experiments/CaseClass.scala:2:13 -----------------------
2 |  case class A
  |             ^
  |             A case class must have at least one parameter list

longer explanation available when compiling with `-explain`
one error found
```

The `CaseClass` file 
```
object CaseClass extends App{
  case class A[T]
}
```

**Comment by ashwinbhaskar** [comment] 2019-08-06 03:37
@LPTK should this be allowed? 
```
enum A { case B }
```

**Comment by LPTK** [comment] 2019-08-06 06:49
@ashwinbhaskar yes, that's just a case _value_. You refer to it and match it as `B`, so there is no confusion here.

**Comment by ashwinbhaskar** [comment] 2019-08-07 04:43
@OlivierBlanvillain can the fix be merged now?

**Closed** 2019-08-07 07:38 UTC
Labels: area:parser, area:reporting, help wanted, itype:bug
