### ISSUE TITLE
Allow to silent the @experimental check

### ISSUE THREAD

**Issue by cchantep** [lampepfl/dotty#14389] opened 2022-01-31 13:29 UTC
When compiling with a non SNAPSHOT/nightly build, I don't see an easy way to silent the error raised when calling an experimental on purpose function, using `@nowarn` or `-Wconf`.

**Comment by nicolasstucki** [comment] 2022-01-31 14:09
What would be a case where you would like to call an experimental function on purpose from a non SNAPSHOT/nightly?

Unless this call is in an experimental method, it will always be wrong to call that method because there is no guarantee that it will exist (link).

**Comment by cchantep** [comment] 2022-01-31 15:26
Technically there is never guarantee.
I agree that the linkage error risk is increased for experimental feature, but considering the current transition period, if I need to publish a lib/app that requires a feature still in experimental, either I wait ... or I stay with a nightly compiler ... not sure what's better (but now there is no real choice).

**Comment by nicolasstucki** [comment] 2022-01-31 15:29
What features are you using?

**Comment by smarter** [comment] 2022-01-31 15:32
> either I wait ... or I stay with a nightly compiler

Yes, you should be using the nightly compiler, and the library/app you publish will be considered experimental. If we didn't enforce this, we wouldn't be able to evolve experimental features safely. This is similar to how rust operates: https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#unstable-features So I'll be closing this as working as intended.

**Closed by smarter** 2022-01-31 15:32 UTC

**Comment by cchantep** [comment] 2022-01-31 17:05
Then, a better tracking/planning of such experimental is required.

**Comment by nicolasstucki** [comment] 2022-02-01 08:15
@cchantep, if you really need that method you can implement it in your code and remove it when the other version is stable.
```scala
private def typeArgsOf(tpe: TypeRepr): List[TypeRepr] = tpe match
  case AppliedType(_, args) => args
  case _ => List.empty
```
