### ISSUE TITLE
Top-level defs cause "cannot merge" errors in ide

### ISSUE THREAD

**Issue by drdozer** [lampepfl/dotty#6605] opened 2019-06-05 11:14 UTC
![image](https://user-images.githubusercontent.com/583516/58952272-23a91c00-878b-11e9-89d8-70f36d13f46b.png)

I get a lot of these "cannot merge" errors when editing dotty code in visual studio code, run with `sbt launchIDE`. I can't nail down exactly what triggers it, other than it is a lot worse when the package contains the new allowed top-level declarations. Top-level defs and implied instances. In this case, `helloWorld` is a top-level def.

**Comment by smarter** [comment] 2019-06-05 11:19
Do you have a github repo where the problem is reproducible?

**Comment by drdozer** [comment] 2019-06-05 11:34
Trying to build one that's minimal which shows the fault reliably ... it seems to be a bit of a heizenbug

**Comment by drdozer** [comment] 2019-06-05 11:38
[cannotmerge.zip](https://github.com/lampepfl/dotty/files/3256948/cannotmerge.zip)

Here's a self-contained project. It fairly reliably does this for me in the file cannotMergeg.

```
sbt
launchIDE
```

Navigate in vs code to `src/main/scala/cannotMerge/Routs.scala`. Hover over line 11, the bracket before `choice`.

**Comment by smarter** [comment] 2019-06-05 16:21
Fixed by https://github.com/lampepfl/dotty/pull/6611, thanks for the minimization!

**Closed by smarter** 2019-06-05 16:21 UTC
