### ISSUE TITLE
Match on Nothing doesn't -Ycheck

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#5073] opened 2018-09-03 12:58 UTC
```scala
??? match {
  case Some(_) => ()
}
```

```
*** error while checking /home/olivier/workspace/dotty/tests/pos/annot-2.scala after phase splitter ***
exception occurred while compiling /home/olivier/workspace/dotty/tests/pos/annot-2.scala                                   Exception in thread "main" java.lang.AssertionError: assertion failed: symbols differ for x1.ne
was                 : method ne                                        
alternatives by type:  of types                                                               
qualifier type      : => Nothing(???)(x1)                                    
tree type           : ((x$0: Object): Boolean)(x1.ne) of class class dotty.tools.dotc.core.Types$CachedTermRef
```

scalac rejects that code in typer:

```scala
scala> ??? match {
     |   case Some(_) => ()
     | }
<console>:13: error: constructor cannot be instantiated to expected type;
 found   : Some[A]
 required: Nothing
         case Some(_) => ()
              ^
```

**Comment by abeln** [comment] 2018-09-03 16:34
This is a duplicate of https://github.com/lampepfl/dotty/issues/5067

**Comment by allanrenucci** [comment] 2018-09-03 16:40
Thanks @abeln

**Closed by allanrenucci** 2018-09-03 16:40 UTC
