### ISSUE TITLE
False positive unused warning with import alias

### ISSUE THREAD

**Issue by lenguyenthanh** [lampepfl/dotty#17460] opened 2023-05-10 17:10 UTC
## Compiler version
3.3.0-RC5

## Minimized code
```scala
//> using scala "3.3.0-RC5"
//> using options "-Wunused:all"


case class Foo(x: Int)

val foo = Foo(1)

@main def main =
  import foo.{x as y}
  println(y)

```
## Output

```
Compiling project (Scala 3.3.0-RC5, JVM)
./UnusedImport.scala:10:15
 unused import
   import foo.{x as y}
1
```

## Expectation

It shouldn't report any warning as the import is being used.

**Comment by KacperFKorban** [comment] 2023-05-15 13:20
Duplicate of https://github.com/lampepfl/dotty/issues/17315

**Closed by KacperFKorban** 2023-05-15 13:20 UTC
Labels: itype:bug, area:warn-unused
