### ISSUE TITLE
All CI jobs are failing to retrieve ch.epfl.lamp#dotty-sbt-bridge;0.19.0-RC1

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#7301] opened 2019-09-24 09:26 UTC
All CI jobs are failing to retrieve `ch.epfl.lamp#dotty-sbt-bridge;0.19.0-RC1`

* https://dotty-ci.epfl.ch/lampepfl/dotty/1555/1/3
* https://dotty-ci.epfl.ch/lampepfl/dotty/1554/1/3
* ...

```

[warn] 	module not found: ch.epfl.lamp#dotty-compiler_0.19;0.19.0-RC1
--
26 | [warn] ==== local: tried
27 | [warn]   /var/cache/drone/ivy2/local/ch.epfl.lamp/dotty-compiler_0.19/0.19.0-RC1/ivys/ivy.xml
28 | [warn] ==== public: tried
29 | [warn]   https://repo1.maven.org/maven2/ch/epfl/lamp/dotty-compiler_0.19/0.19.0-RC1/dotty-compiler_0.19-0.19.0-RC1.pom
30 | [warn] ==== local-preloaded-ivy: tried
31 | [warn]   /root/.sbt/preloaded/ch.epfl.lamp/dotty-compiler_0.19/0.19.0-RC1/ivys/ivy.xml
32 | [warn] ==== local-preloaded: tried
33 | [warn]   file:////root/.sbt/preloaded/ch/epfl/lamp/dotty-compiler_0.19/0.19.0-RC1/dotty-compiler_0.19-0.19.0-RC1.pom
34 | [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
35 | [warn] 	::          UNRESOLVED DEPENDENCIES         ::
36 | [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
37 | [warn] 	:: ch.epfl.lamp#dotty-compiler_0.19;0.19.0-RC1: not found
38 | [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
39 | [warn] 	module not found: ch.epfl.lamp#dotty-sbt-bridge;0.19.0-RC1

...
```

**Comment by anatoliykmetyuk** [comment] 2019-09-24 09:37
WDYT @smarter? The binaries appear to be there and the link mentioned in the output, [https://repo1.maven.org/maven2/ch/epfl/lamp/dotty-compiler_0.19/0.19.0-RC1/dotty-compiler_0.19-0.19.0-RC1.pom](https://repo1.maven.org/maven2/ch/epfl/lamp/dotty-compiler_0.19/0.19.0-RC1/dotty-compiler_0.19-0.19.0-RC1.pom), resolves correctly.

**Comment by anatoliykmetyuk** [comment] 2019-09-24 09:59
It must be something with the CI, it doesn't appear to be able to resolve anything. I tried to reproduce it locally using the command `./project/scripts/sbt ";compile; test"` after cleaning my ivy caches – the artefacts were resolved successfully. I had to remove the property specifying the ivy location for Drone since I don't have drone locally – #7302.

Also I tried compiling the [example project](https://github.com/lampepfl/dotty.g8) which also resolved the artefacts successfully. However, after removing the Ivy cache location property in #7302, it now fails to resolve the Scala standard library and not the compiler:

```
[warn] 	module not found: org.scala-lang#scala-library;2.12.7
6 | [warn] ==== typesafe-ivy-releases: tried
7 | [warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scala-lang/scala-library/2.12.7/ivys/ivy.xml
8 | [warn] ==== sbt-plugin-releases: tried
9 | [warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-lang/scala-library/2.12.7/ivys/ivy.xml
10 | [warn] ==== local: tried
11 | [warn]   /root/.ivy2/local/org.scala-lang/scala-library/2.12.7/ivys/ivy.xml
12 | [warn] ==== public: tried
13 | [warn]   https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom
14
```

The [https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom](https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom) link is resolvable though.

Reassigning it to @smarter since I don't have access to the CI machine.

**Comment by smarter** [comment] 2019-09-24 10:50
From lampsrv9, everything seems fine, but from lampsrv26:
```shell
$ curl https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>403 Forbidden</title>
  </head>
  <body>
    <h1>Error 403 Forbidden</h1>
    <p>You’ve been blocked from this operation due to violation of the Central terms of service. Please see https://central.sonatype.org/blacklisted to remediate this issue.</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-mdw17342-MDW 1536113084 3374708410</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by smarter** [comment] 2019-09-24 10:55
Opened an issue against sonatype: https://issues.sonatype.org/browse/MVNCENTRAL-5209

**Comment by smarter** [comment] 2019-09-24 10:57
I've temporarily taken down lampsrv26 since lampsrv9 seems to be working.

**Comment by smarter** [comment] 2019-09-24 15:33
Sonatype unblacklisted us, I've restarted the drone agent on lampsrv26 but it's having trouble connecting to the server apparently:
```
{"arch":"amd64","error":"context canceled","level":"warning","machine":"lampsrv26","msg":"runner: cannot get queue item","os":"linux","time":"2019-09-24T15:30:33Z"}
{"error":"context canceled","level":"warning","msg":"program terminated","time":"2019-09-24T15:30:33Z"}
```

**Comment by smarter** [comment] 2019-09-25 11:32
Seems to be fine now.

**Closed by smarter** 2019-09-25 11:32 UTC
Labels: prio:blocker
