### ISSUE TITLE
Macro values do not support `X with Singleton` upper-bound

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#12975] opened 2021-06-28 21:25 UTC
## Compiler version

v3.0.1-RC2 (also tested on nightly)

## Minimized code

```Scala
import scala.quoted.*
inline def foo[T <: Int with Singleton](value : T) : Unit = ${fooMacro('value)}
def fooMacro[T <: Int with Singleton](value : Expr[T]) : Expr[Unit] = ???
```
## Output

```scala
access to parameter value from wrong staging level:
 - the definition is at level 0,
 - but the access is at level -1.
```

## Expectation
No error.

**Comment by nicolasstucki** [comment] 2021-07-27 09:49
Minimized 
```scala
import scala.quoted.*
inline def foo(x : Any) : Unit = ${fooMacro[x.type]}
def fooMacro[T] : Expr[Unit] = ???
```

```
2 |inline def foo(x : Any) : Unit = ${fooMacro[x.type]}
  |                                            ^
  |                           access to parameter x from wrong staging level:
  |                            - the definition is at level 0,
  |                            - but the access is at level -1.
```

As `x` is used in a type and is erased at runtime it should be a staging level error. This must be fixed in `PCPCheckAndHeal`.

**Comment by nicolasstucki** [comment] 2021-11-19 13:26
Duplicate of #8887. See last minimization.

**Closed by nicolasstucki** 2021-11-19 13:26 UTC
Labels: itype:bug, area:metaprogramming
