### ISSUE TITLE
Exporting extension methods drops default arguments

### ISSUE THREAD

**Issue by dcascaval** [lampepfl/dotty#14159] opened 2021-12-21 19:32 UTC
## Compiler version

3.1.0 (this also reproduces on the latest nightly as of 12/20)

## Minimized code

```Scala
object api:
  export impl.*

object impl:
  class Bar
  extension (rcv: Bar)
    def foo(a: Int) = ()
    def bar(a: Int, b: Boolean = false) = ()

object Test1:
  import api.*
  val value = (new Bar).bar(0) // Error

object Test2:
  import impl.*
  val value = (new Bar).bar(0) // Works

object Test3:
  import api.*
  val value = (new Bar).foo(0) // Works
```

## Output

```scala
[error] 12 |  val value = (new Bar).bar(0) // Missing argument
[error]    |              ^^^^^^^^^^^^^^^^
[error]    |missing argument for parameter b of method bar in object api: (a: Int, b: Boolean): Unit
```

## Expectation

Hit this case when exporting extension method through a facade object `api` from an implementation object `impl`. Since exporting normal extension methods (e.g. `foo`) works, I would also expect the method `bar` to export such that it can be called omitting the second argument and having it be filled in by the default.

**Comment by smarter** [comment] 2021-12-21 19:48
> 3.1.0 (this also reproduces on the latest nightly as of 12/20)

I can't reproduce this with 3.1.2-RC1-bin-20211220-0b55c7d-NIGHTLY, this looks like it was fixed in https://github.com/lampepfl/dotty/pull/14051

**Closed by smarter** 2021-12-21 19:48 UTC
Labels: itype:bug
