### ISSUE TITLE
Dependencies not propagated properly within an implicit parameter block

### ISSUE THREAD

**Issue by milessabin** [lampepfl/dotty#5549] opened 2018-11-30 18:54 UTC
Given the following definitions,
```scala
trait Foo[A] {
  type T
  val t: T
}

trait Bar[A]
object Bar {
  implicit val barInt: Bar[Int] = new Bar[Int] {}
}

trait Quux
object Quux {
  implicit def fooQuux: Foo[Quux] { type T = Int } =
    new Foo[Quux] { type T = Int ; val t = 23 }
}
```

I would expect the following to compile successfully,
```
implicit def foo1[A](implicit foo: Foo[A], bar: Bar[foo.T]): Unit = ()
foo1[Quux]
```
However it fails with,
```
273 |  foo1[Quux]
    |            ^
    |no implicit argument of type Test.Bar[foo.T] was found for parameter bar of method
    |foo1 in object Test.
    |
    |I found:
    |
    |    barInt
    |
    |But value barInt in object Bar does not match type Test.Bar[foo.T].
```
The following two related definitions and uses compile successfully as expected,
```scala
implicit def foo2[A](foo: Foo[A])(implicit bar: Bar[foo.T]): Unit = ()
foo2[Quux](Quux.fooQuux)

implicit def foo3[A, fooT]
  (implicit foo: Foo[A] { type T = fooT }, bar: Bar[fooT]): Unit = ()
foo3[A = Quux]
```

**Comment by smarter** [comment] 2018-12-01 08:10
duplicate of https://github.com/lampepfl/dotty/issues/5427

**Closed by smarter** 2018-12-01 08:10 UTC
Labels: area:typer
