### ISSUE TITLE
Difference between HKT and type lambda

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#3128] opened 2017-09-15 11:19 UTC
Dotty sees a difference between `Option` and `[A] => Option[A]`, I think there shoudn't be:

```scala
trait Functor[F[_]]

object Functor {
  val a: Functor[Option] = ???
  val b: Functor[[A] => Option[A]] = a

  // Same result with scalac style type lambda:
  // val c: Functor[({ type l[A] = Option[A] })#l] = a
}
```

```scala
23 |  val b: Functor[[A] => Option[A]] = a
   |                                     ^
   |                                   found:    Functor[Option](Functor''.a)
   |                                   required: Functor[Option]
   |
   |                                   where:    Functor  is a trait
   |                                             Functor'' is a object

one error found
```

**Comment by smarter** [comment] 2017-09-15 13:24
Duplicate of https://github.com/lampepfl/dotty/issues/2989

**Comment by smarter** [comment] 2017-09-15 13:24
I'm working on a fix, but waiting for the native applied type stuff to be done before finishing it :).

**Closed by smarter** 2017-09-15 13:24 UTC
Labels: area:typer, itype:bug, prio:low

**Comment by odersky** [comment] 2017-09-17 11:41
I believe it has to do with variances. `Option` is `[+A] => Option[A]` not `[A] => Option[A]`
