### ISSUE TITLE
Cyclic reference involving class in java library 

### ISSUE THREAD

**Issue by qwerttyue** [lampepfl/dotty#10623] opened 2020-12-03 10:37 UTC
I want to use Avro Java library with dotty. But I get this error

```bash
[info] compiling 1 Scala source to /home/source/testdotty/target/scala-3.0.0-M2/classes ...
exception caught when loading class ArrayBuilder: Cyclic reference involving class ArrayBuilder
[error] -- [E046] Cyclic Error: /home/source/testdotty/src/main/scala/example/Test.scala:12:33 
[error] 12 |    Seq(new Schema.Field("list", SchemaBuilder.array().items(SchemaBuilder.builder.stringType))).asJava
[error]    |                                 ^
[error]    |                           Cyclic reference involving class ArrayBuilder
[error] one error found
```
My class is something like that

```scala
import org.apache.avro.{ SchemaBuilder, Schema }
import scala.collection.JavaConverters._

object Test:
  def main(args: Array[String]): Unit = 
    val schema = Schema.createRecord(
      "A",
      "",
      "",
      false,
      Seq(new Schema.Field("list", SchemaBuilder.array().items(SchemaBuilder.builder.stringType))).asJava
    )
    println(schema)
```
And I tried the same code with scala 2.13.3 and it works fine.

The avro dependency is "org.apache.avro" % "avro" % "1.9.2"

Is there a way to fix this error without change the library code?

**Comment by griggt** [comment] 2020-12-03 10:49
Probable duplicate of #10567

**Comment by b-studios** [comment] 2020-12-03 11:13
I added the example to #10567 and close this one as a duplicate.

**Closed by b-studios** 2020-12-03 11:13 UTC
