### ISSUE TITLE
Unable to find class in inherited scope

### ISSUE THREAD

**Issue by thesamet** [lampepfl/dotty#12566] opened 2021-05-22 17:50 UTC
## Compiler version

Using Scala 3.0.0, I am unable to compile Java code that is generated by protoc (protobuf compiler). The following is a minimized version of the generated code to demonstrate the issue.

## Minimized code

```java
// src/main/java/mytest/Ex.java
package mytest;

public final class Ex {
  private Ex() {}

  public static final class Foo extends MyInterface {
    private Foo() {
    }

    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Foo();
    }
  }
}
```

```java
// src/main/java/mytest/MyInterface.java
package mytest;

public class MyInterface {
    public static final class UnusedPrivateParameter {};
}
```

The Scala code doesn't matter, but it needs to exist:
```scala
// src/main/scala/Main.scala
package foo

object Main {}
```

## Output
```
sbt:ppp> compile
[info] compiling 1 Scala source and 2 Java sources to /tmp/ppp/target/scala-3.0.0/classes ...
[error] -- [E006] Not Found Error: /tmp/ppp/src/main/java/mytest/Ex.java:12:8 ----------
[error] 12 |        UnusedPrivateParameter unused) {
[error]    |        ^^^^^^^^^^^^^^^^^^^^^^
[error]    |        Not found: type UnusedPrivateParameter
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed May 22, 2021, 10:36:18 AM
```

## Expectation
Should compile with no errors.

## Workaround

Adding `compileOrder := CompileOrder.JavaThenScala` results in successful compilation.

**Comment by som-snytt** [comment] 2021-05-23 01:01
Scala 2 works, presumably due to fixes to looking up Java-defined members in Java sources.

The previous behavior was that statics belong to companions in the Scala language model and are not inherited.

**Comment by dylemma** [comment] 2021-05-23 01:43
(don't mind me, I typo'd the number of the issue I was trying to reference with that PR)

**Comment by odersky** [comment] 2021-05-23 08:58
It would be good to know when and how this was fixed in Scala 2. The normal behavior is that `UnusedPrivateMember` is not visible, so there must be a hack to make it visible for Java compiled code.

**Comment by som-snytt** [comment] 2021-05-23 09:13
Perhaps

https://github.com/scala/scala/pull/7671

with terms

`is:pr author:retronym is:closed java lookup `

**Comment by odersky** [comment] 2021-05-23 14:31
@som-snytt That looks like the probaby fix, yes. Maybe we can get a volunteer to forward port it?

**Comment by smarter** [comment] 2021-05-23 14:39
Closing as a duplicate of https://github.com/lampepfl/dotty/issues/6138 then

**Closed by smarter** 2021-05-23 14:39 UTC
Labels: help wanted, itype:bug

**Comment by som-snytt** [comment] 2021-05-23 14:49
OK I see someone is already looking into the other ticket. Oh wait, that was 2019. OSS is hard.
