### ISSUE TITLE
Inconsistent parsing of symbols wrapped in backticks

### ISSUE THREAD

**Issue by nrinaudo** [lampepfl/dotty#15547] opened 2022-06-29 07:53 UTC
## Compiler version

3.1.2

## Minimized code

```Scala
def `=`: String = "="
def `+`: String = "+"

val withEq: String   = `=` + "3"
val withPlus: String = `+` + "3"
```

## Output

Compile error on the last line:
```scala
; expected but string constant found
```

See https://scastie.scala-lang.org/WCnbXR7RRzOuc8zYkrlxUQ for a "live" reproduction

## Expectation
Either a compile error for both `withEq` and `withPlus`, or none, but this seems inconsistent.

**Comment by prolativ** [comment] 2022-06-29 09:48
Not sure of the source of the discrepancy but I'm getting slightly different errors with the same compiler version when trying to compile this locally
```scala
[error] Bug.scala:5:30: end of toplevel definition expected but string literal found
[error] val withPlus: String = `+` + "3"
[error]                              ^
[error] Bug.scala:5:24: value unary_+ is not a member of String
[error] val withPlus: String = `+` + "3"
[error]                        ^^^^^   
```
The point is that `+` is not really treated as a keyword by the parser while `=` is. This means that `+` and ` `+` ` are equivalent so you could write e.g.
```scala
def + : String = "+"
```
instead of
```scala
def `+`: String = "+"
```
while
```scala
def = : String = "="
```
would be syntactically incorrect.
Going further all of
```scala
+ + "3"
`+` + "3"
+ `+` "3"
`+` `+` "3"
```
mean the same and the first `+` is being interpreted as a prefix operator here.
This seems consistent with the behaviour in Scala 2.13 and I'm not sure if this could be changed. @odersky WDYT?

**Comment by odersky** [comment] 2022-06-29 10:26
I can't reproduce this on latest main. I remember we had a PR recently that changed the status of backticked unary operators. Maybe that fixed it.

**Comment by prolativ** [comment] 2022-06-29 10:39
Indeed seems to be fixed by https://github.com/lampepfl/dotty/pull/15198

**Closed by prolativ** 2022-06-29 10:39 UTC
Labels: itype:bug, stat:cannot reproduce

**Comment by som-snytt** [comment] 2022-06-29 16:48
was
```
PackageDef(Ident(<empty>), List(DefDef(f, List(), TypeTree(), PrefixOp(Ident(+), Ident(+)))))
```
now
```
PackageDef(Ident(<empty>), List(DefDef(f, List(), TypeTree(), InfixOp(Ident(+), Ident(+), Literal("*")))))
```
Noting that `-Vprint:parser -Ystop-after:parser` does not work as one might expect. (Result is empty.)
