### ISSUE TITLE
Move the gh-pages branch to a separate repository

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5248] opened 2018-10-12 12:21 UTC
Cloning the dotty repository is getting harder and harder because it keeps growing, and a big factor in that growth seems to be https://github.com/lampepfl/dotty/tree/gh-pages, instead of using a branch in the main repository we should use a separate repo for this.

**Comment by allanrenucci** [comment] 2018-10-12 13:30
Sure

**Comment by allanrenucci** [comment] 2018-10-12 21:03
Duplicate of #3236

**Closed as completed** 2018-10-26 13:23 UTC
Labels: area:infrastructure, prio:high
