### ISSUE TITLE
Accessing soft keywords params are sometimes not ok

### ISSUE THREAD

**Issue by Arthurm1** [lampepfl/dotty#15699] opened 2022-07-18 13:18 UTC
## Compiler version
3.1.3 using Scastie

lines following access of the `open` parameter refuse to compile

## Minimized code
```Scala
case class OHLCPrice(
    val open: Double
) {
  val price = OHLCPrice(1.0)
  val price1 = price.open
  val price2 = 1.0 // compiler error here `; expected but val found`
}
```

This compiles...
```Scala
case class OHLCPrice(
    val open: Double
) {
  val price = OHLCPrice(1.0)
  val price1 = price.open
}
```
as does this...
```Scala
case class OHLCPrice(
    val open: Double
) {
  val price = OHLCPrice(1.0)
  val price1 = price.open;
  val price2 = 1.0
}
```
and this...
```Scala
case class OHLCPrice(
    val open: Double
) {
  val price = OHLCPrice(1.0)
  val price1 = price.`open`
  val price2 = 1.0
}
```

[here](https://docs.scala-lang.org/scala3/guides/migration/incompat-syntactic.html#restricted-keywords) it doesn't list `open` as restricted so shouldn't I be able to access it as I would any normal parameter name?

I'm not sure if this is the same as https://github.com/lampepfl/dotty/issues/9041

**Comment by som-snytt** [comment] 2022-07-18 13:43
It compiles for me with scalac. I see the error on scastie but it doesn't output `-Vprint`; I've forgotten how scastie wraps snippets.

**Comment by som-snytt** [comment] 2022-07-18 13:54
more demonstratively,
```
Welcome to Scala 3.1.3 (18.0.1.1, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> case class OHLCPrice(
     |     val open: Double
     | ) {
     |   val price = OHLCPrice(1.0)
     |   val price1 = price.open
     |   val price2 = 1.0 // compiler error here `; expected but val found`
     | }
// defined case class OHLCPrice

scala> OHLCPrice(3.14)
java.lang.StackOverflowError
  at rs$line$1$OHLCPrice$.apply(rs$line$1:1)
  ... 1023 elided

scala> case class OHLCPrice(
     |     open: Double
     | ) {
     |   def price = OHLCPrice(1.0)
     |   def price1 = price.open
     |   val price2 = 1.0 // compiler error here `; expected but val found`
     | }
// defined case class OHLCPrice

scala> OHLCPrice(3.14)
val res1: OHLCPrice = OHLCPrice(3.14)

scala>
```

**Comment by szymon-rd** [comment] 2022-07-18 14:12
Thanks for the report! I created an issue on scalameta, but I am closing this one as it’s (probably) not caused by error in compiler.
https://github.com/scalameta/scalameta/issues/2786

**Closed by szymon-rd** 2022-07-18 14:12 UTC
Labels: itype:bug

**Comment by Arthurm1** [comment] 2022-07-18 14:14
Thanks for triaging - I did initially run into this in ScalaFmt but then I got the error in Scastie so assumed it was the compiler

**Comment by som-snytt** [comment] 2022-07-18 14:41
Indeed, scastie "format" says
```
Formatting failed: <input>:6: error: [dialect dialect] ; expected but val found
  val price2 = 1.0 // compiler error here `; expected but val found`
  ^
```
