### ISSUE TITLE
Compiler crash: is not a simple name while compiling

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#6626] opened 2019-06-06 20:18 UTC
```scala
class Test[T1] {
  class A[T2]

  object B  {
     def m(): A[B.type] = ???
  }
}
```
```scala
java.lang.UnsupportedOperationException: B[ModuleClass] is not a simple name while compiling tests/pos/ranks.scala
Exception in thread "main" java.lang.UnsupportedOperationException: B[ModuleClass] is not a simple name
        at dotty.tools.dotc.core.Names$DerivedName.asSimpleName(Names.scala:474)
        at dotty.tools.dotc.core.Names$DerivedName.asSimpleName(Names.scala:474)
        at dotty.tools.dotc.core.Names$TypeName.asSimpleName(Names.scala:441)
        at dotty.tools.dotc.transform.GenericSignatures$.classSig$2(GenericSignatures.scala:167)
        at dotty.tools.dotc.transform.GenericSignatures$.jsig$1(GenericSignatures.scala:228)
        at dotty.tools.dotc.transform.GenericSignatures$.boxedSig$1(GenericSignatures.scala:64)
        at dotty.tools.dotc.transform.GenericSignatures$.argSig$1(GenericSignatures.scala:145)
        at dotty.tools.dotc.transform.GenericSignatures$.classSig$1$$anonfun$1(GenericSignatures.scala:174)
```

scalac passes

**Comment by ashwinbhaskar** [comment] 2019-09-18 04:16
Can I give the fix a shot?

**Comment by biboudis** [comment] 2019-09-18 10:39
Yes, much appreciated! Try tracking the error using the guide can help 

> https://dotty.epfl.ch/docs/contributing/debugging.html

Either send a PR with the fix, ask questions on gitter or pot your progress here when you reach a point that you couldn't progress further 🎉

**Comment by ashwinbhaskar** [comment] 2019-09-18 11:53
thank you:) Can you assign the issue to me?

**Comment by biboudis** [comment] 2019-09-18 11:59
Feel free to work on it but if you feel that you don't want work on it anymore or it takes a long time (let's say more than a week without progress), don't fear the "Unassign me" button. This mark this up for grabs for others as well!

**Comment by ashwinbhaskar** [comment] 2019-09-19 03:48
@biboudis okay:) Yes it is reproducible on master

**Comment by ashwinbhaskar** [comment] 2019-09-19 04:44
@biboudis The method `def typed(tree: untpd.Tree, pt: Type, locked: TypeVars)(implicit ctx: Context): Tree` in file `/dotty/tools/dotc/typer/Typer.scala` seems to be the entry point in the dotty compiler.  What is the equivalent entry point in the Scalac compiler?

**Comment by ashwinbhaskar** [comment] 2019-09-21 05:13
Wanted to give an update on this issue.I have been debugging this and this look like the exception is thrown when it encounters this statement `sym.name.asSimpleName` where `sym.name` is `B$`. But this exception is not being thrown in the `scalac` compiler. 
I am trying to check the corresponding code in the Scalac compiler...

**Comment by ashwinbhaskar** [comment] 2019-09-25 07:46
can the PR be merged?

**Closed** 2019-09-26 11:31 UTC
Labels: area:backend, itype:crash
