### ISSUE TITLE
Can Dotty derive a typeclass instance at most once?

### ISSUE THREAD

**Issue by ryanberckmans** [lampepfl/dotty#8860] opened 2020-05-01 15:51 UTC
If Dotty derives a typeclass instance `Foo[Bar[T]]`, can this be derived only once and memoized?

Martin once [suggested](https://www.reddit.com/r/scala/comments/benhmb/whats_state_of_the_art_to_cache_typed_implicit/el7qei5/) that this was possible. Perhaps I misunderstood his remark.

Instantiating a derived typeclass instance each method invocation can decrease performance by orders of magnitude. For example, I write a game in Scala 2.13. Some of my hot code paths use `implicit vals` instead of `implicit defs`, because the game slows to the point of being unplayable if each method invocation re-instantiates instances.

## Minimized example

https://scastie.scala-lang.org/udIHKIPCRHyQaBfkPL1kJA

## Output

```bash
instantiate Show[List[T]]
instantiate Show[List[T]]
```

## Expectation

```bash
instantiate Show[List[T]] // only once
```

**Comment by smarter** [comment] 2020-05-01 16:53
The typeclass derivation mechanism Martin refers to is https://dotty.epfl.ch/docs/reference/contextual/derivation.html which allows one to write for example `case class Foo(x: Int) derives Eq` to get a `given Eq[Foo]` object in the companion of `Foo`, but for a polymorphic class, the generated given will be polymorphic and not memoized, there is nothing built into the compiler to optimize that.

Using inline almost works, but not quite:
```scala
trait Show[T] {
  def show(a: T): String
}

object Show {
  transparent inline def apply[T](using inline s: Show[T]) = s

  given Show[Int] {
    def show(a: Int) = a.toString
  }

  given listShow[T] (using show: Show[T]) as Show[List[T]] {
    inline def show(a: List[T]) = a.map(show.show(_)).mkString(", ")      
  }
}

object Run extends App {
  Show[List[Int]].show(List(1,2))
}
```
we get:
```scala
val a = List(1, 2)
val listShow_this: Show.listShow[Int] =  Show.listShow[Int](Show.given_Show_Int)
a.map(listShow_this.show.show(_)).mkString(", ")
```
The problem is that we can't mark the parameter of `listShow` as `inline`, so we're stuck with having a `listShow` instance to get to its parameter. @nicolasstucki has there been any discussion on whether this would be possible ?

**Comment by nicolasstucki** [comment] 2020-05-01 18:16
Not sure what you want to inline exactly.

But I notice that the following inline will never be inlined
```scala
  given listShow[T] (using show: Show[T]) as Show[List[T]] {
    inline def show(a: List[T]) = a.map(show.show(_)).mkString(", ")      
  }
```

A possible fix make sure that the `show` is inlined with 

```scala
  inline given listShow[T] (using show: Show[T]) as ShowList[T] = new ShowList[T](show)

  class ShowList[T](show: Show[T]) extends Show[List[T]] {
    inline def show(a: List[T]) = a.map(show.show(_)).mkString(", ")
  }
```

**Comment by smarter** [comment] 2020-05-01 18:50
> But I notice that the following inline will never be inlined

It does get inlined, see the code sample I posted, but there's still a reference to the `this` which is left around because we need it to get to the parameter of the class. To avoid that we need to be able to inline the getter somehow, https://github.com/lampepfl/dotty/issues/8294 proposes doing that for case classes but it's a more general problem as seen here.

**Comment by nicolasstucki** [comment] 2020-05-01 19:21
Still not sure what is the goal.

**Comment by smarter** [comment] 2020-05-01 19:51
To get:
```scala
Show[List[Int]].show(List(1,2))
```
to expand to:
```scala
val a = List(1,2)
a.map(Show.given_Show_Int.show(_)).mkString(", ")
```
instead of:
```scala
val a = List(1, 2)
val listShow_this: Show.listShow[Int] =  Show.listShow[Int](Show.given_Show_Int)
a.map(listShow_this.show.show(_)).mkString(", ")
```

**Comment by nicolasstucki** [comment] 2020-05-01 20:11
So the idea is to duplicate code rather than using memoization.

**Comment by smarter** [comment] 2020-05-01 20:15
Yes, it might not scale to more complex typeclasses, but it seemed like an ok solution here.

**Comment by nicolasstucki** [comment] 2020-05-01 20:15
With memoization it would be somthig like:
```scala
  val memo = new Memo[List]([T] => (s: Show[T]) =>
    new  Show[List[T]] {
      println("instantiate Show[List[T]]")
      def show(a: List[T]) = a.map(s.show(_)).mkString(", ")
    }
  )
  given listShow[T] (using show: Show[T]) as Show[List[T]] = memo(show)


  // Memo for any Show
  class Memo[F[_]](f: [T] => Show[T] => Show[F[T]]) {
    private[this] val cache = collection.mutable.Map.empty[Any, Any]
    def apply[T](show: Show[T]): Show[F[T]] =
      cache.asInstanceOf[collection.mutable.Map[Show[T], Show[F[T]]]].getOrElseUpdate(show, f(show))
  }
```

But it has a different kind of overhead.

**Comment by nicolasstucki** [comment] 2020-05-01 20:25
We can easly memoize it in some given scope with
```scala
...
transparent inline def memoShow[T](using Show[T])(inline body: Show[T] ?=> Any): Any = body

object Run extends App {
  memoShow[List[Int]] {
    Show[List[Int]].show(List(1,2))
    Show[List[Int]].show(List(1,2))
  }
//    val x$1: Show.listShow[Int] = Show.listShow[Int](Show.given_Show_Int)
//      {
//        Show.apply[List[Int]](x$1).show(List.apply[Int](1,2))
//        Show.apply[List[Int]](x$1).show(List.apply[Int](1,2))
//      }
}
```

**Comment by smarter** [comment] 2020-05-01 20:34
I'll close this issue because the original question has been answered: there is no automatic memoization mechanism for polymorphic typeclass instances in Dotty, and I don't think we'll ever get one, because the caching policy is going to depend on how that instance is being used. If the instance is being used with many different types, then caching won't help much and might blow up your memory, if the instance is only used with a few types, then manually defining some monomorphic instances seems like a good enough solution.

It's also worth noting that allocating an object on the JVM is cheap, and escape analysis can even get rid of that cost if the JIT does its job well enough (Graal is especially good at this), so it's not clear in which situation exactly memoization would be a net win.

**Closed by smarter** 2020-05-01 20:34 UTC

**Comment by ryanberckmans** [comment] 2020-05-01 22:52
@smarter, thanks for investigating this.

It would delight me for a solution to this issue to be supported at the compiler level. I feel that any sufficiently informed Scala developer of performance-critical software would be sympathetic to my cause here.

> It's also worth noting that allocating an object on the JVM is cheap, and escape analysis can even get rid of that cost if the JIT does its job well enough (Graal is especially good at this), so it's not clear in which situation exactly memoization would be a net win.

My experience with Scala 2.13, on hotspot or GraalVM, has been that the `implicit def` code can be orders of magnitude slower (example below). I'm hardly a JVM or Java expert, so perhaps I could do something better here.

The use of typeclasses, and automatic derivation for polymorphic typeclass instances, is a core benefit of Scala relative to other languages. Yet, any performance-critical code using `implicit def` will allocate O(method invocations) extraneous objects. This is a big drawback for anybody trying to make their code as fast as possible.

Hot code paths in my game engine are slow to the point of being unusable with `implicit def`. My current workaround is just to do the manual work of enumerating the many `implicit val`s for all combinations of polymorphic instances. I have a linter rule to warn on the use of `implicit def`.

Can there be no reasonable solution here to automatically memoize derived polymorphic typeclass instances, when such instances are discovered during compilation? It seems like this would fall under the remit of the "whole program optimization" feature listed on the Dotty homepage.

Here is a strawman solution: if the compiler detects that I need a `Contents[Zone, Item]`, it generates some code like `object MemoizedInstances { implicit val contentsZoneItem = ... }` and then wires in `MemoizedInstances.contentsZoneItem` at the call site. Since this feature trades time for space, and not much space at that, it could be enabled by default and disabled via a compiler flag.

**Comment by smarter** [comment] 2020-05-01 23:48
> My experience with Scala 2.13, on hotspot or GraalVM, has been that the implicit def code can be orders of magnitude slower (example below).

I don't see any example in your message?

> My current workaround is just to do the manual work of enumerating the many implicit vals for all combinations of polymorphic instances. 

Have you tried manually implementing memoization for these instances which are performance critical? If that requires too much boilerplate, maybe macros could help.

>  It seems like this would fall under the remit of the "whole program optimization" feature listed on the Dotty homepage.

Unfortunately the homepage is outdated: the work on whole program optimization did not succeed and has been shelved.

>  if the compiler detects that I need a Contents[Zone, Item], it generates some code like object MemoizedInstances { implicit val contentsZoneItem = ... } and then wires in MemoizedInstances.contentsZoneItem at the call site.

It's really tricky to do this sort of thing right in the context of separate compilation (it's easier when doing whole program optimization but as I mentioned above, this isn't being actively worked on)

> it could be enabled by default and disabled via a compiler flag.

As much as possible we try to avoid having flags which change the compiler behavior: each one of these flags doubles the number of configuration we have to test for, and when reading code one has to constantly remember which flags are enabled in the current project to understand what's going on.

If you'd like to discuss this more, https://contributors.scala-lang.org/ is the place to have more open-ended discussions!

**Comment by ryanberckmans** [comment] 2020-05-01 23:55
> I don't see any example in your message?
Oops, I ended up dropping the example.

Thanks for the suggestions and explanation of why my strawman solution isn't worth implementing. Much appreciated!
