### ISSUE TITLE
Add `ValueOf` equivalent of SIP23 (TLS) to dotty

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#2857] opened 2017-07-12 10:37 UTC
SIP23 will be merged into Scala 2.xx sometime in the future (currently merged into TLS).
Its implementation has a `ValueOf` type class that enables us to request the literal values from literal types. E.g.:
```
def foo[T](implicit i : ValueOf[T]) : T = valueOf[T]
```
Since we want to have Scala 2.xx and Scala 3.xx to be the same in the future, it is important to keep this feature.

**Comment by propensive** [comment] 2017-07-15 18:00
I would find this potentially very useful.

**Comment by smarter** [comment] 2018-01-11 01:16
Duplicate of https://github.com/lampepfl/dotty/issues/2616 (I'll fix it soon!)

**Closed by smarter** 2018-01-11 01:16 UTC
Labels: exp:expert, itype:language enhancement
