### ISSUE TITLE
implicit search for extension methods seems to give up too early

### ISSUE THREAD

**Issue by drdozer** [lampepfl/dotty#5781] opened 2019-01-22 21:34 UTC
When searching for extension methods, I'm finding categories of things that don't work which involve implicit defs to summon the instances.

```scala
trait Semigroup[T] {
  def (lhs: T) append (rhs: T): T
}

object Semigroup {
  implicit object stringAppend extends Semigroup[String] {
    override def (lhs: String) append (rhs: String): String = lhs + rhs
  }

  implicit def sumSemigroup[N](implicit N: Numeric[N]): Semigroup[N] = new {
    override def (lhs: N) append (rhs: N): N = N.plus(lhs, rhs)
  }
}


object Main {
  def main(args: Array[String]): Unit = {
    import Semigroup.stringAppend // necessary to make the extension method visible
    println("Hi" append " mum")

    import Semigroup.sumSemigroup // this is not sufficient
    println(1 append 2) // this won't compile

    implicit val intSumAppend: Semigroup[Int] = sumSemigroup[Int]
    println(3 append 4) // this will
  }
}
```

**Comment by LPTK** [comment] 2019-01-23 08:57
Seems like a duplicate of https://github.com/lampepfl/dotty/issues/5773, which I opened yesterday 😄

**Comment by drdozer** [comment] 2019-01-23 14:45
Could well be.

**Comment by Blaisorblade** [comment] 2019-01-23 14:53
Closing for now as duplicate; feel free to add the example to the other issue.

**Closed by Blaisorblade** 2019-01-23 14:53 UTC
