### ISSUE TITLE
Unexpected tree could not be interpreted

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#5097] opened 2018-09-12 13:06 UTC
```scala
// Foo.scala
import scala.quoted._

class Foo {
  rewrite def foo1: String = ~Foo.impl
}

object Foo {
  rewrite def foo2: String = ~Foo.impl
  private def impl: Expr[String] = '("")
}
```
```scala
// Test.scala
class Test {
  def test1: String = (new Foo).foo1 // error
  def test2: String = Foo.foo2       // ok
}
```
```
> dotc -d out Foo.scala
> dotc -classpath out Test.scala
-- Error: Test.scala:2:22 ---------------------------------
2 |  def test1: String = (new Foo).foo1
  |                      ^
  |                      Unexpected tree could not be interpreted: Select(Ident(Foo_this),inline$impl)
```
If `def impl` is not private, the code compiles

**Comment by odersky** [comment] 2018-09-12 16:17
That's because of the inline accessor. We either need to "see through" such accessors or forbid them (but then a better error message would help).

**Comment by biboudis** [comment] 2018-09-13 14:04
@odersky if there is nothing fundamental that I miss I can make it see through (dunno e.g., an argument for separate compilation). WDYT?

**Comment by nicolasstucki** [comment] 2018-09-19 06:54
The issue is that we are generating the accessor a private member of the object in the class.

If we have the following code
```scala
class Foo {
  rewrite def foo0: String = Foo.impl1
}

object Foo {
  rewrite def foo1: String = Foo.impl1
  rewrite def foo2: String = Foo.impl2

  private def impl1: String = ""
  private def impl2: String = ""
}
```
after typer we currently have
```scala
result of Foo.scala after frontend:
package <empty> {
  class Foo() extends Object() { 
    rewrite def foo0: String = Foo.impl1
    def inline$impl1: String = Foo.impl1
  }
  final lazy module val Foo: Foo$ = new Foo$()
  final module class Foo$() extends Object() { this: Foo.type => 
    rewrite def foo1: String = Foo.impl1
    rewrite def foo2: String = Foo.impl2
    private def impl1: String = ""
    private def impl2: String = ""
    def inline$impl1: String = Foo.impl1
    def inline$impl2: String = Foo.impl2
  }
}
```
Note that we generated one `inline$impl1` for `foo0` in `class Foo` and one for `foo1` in `object Foo`. Instead we should only generate `inline$impl1` in `object Foo` and use that one for `foo0`.

**Comment by biboudis** [comment] 2018-09-24 16:16
Check if still occurs after #5138 is merged.

**Closed** 2018-12-17 15:23 UTC
Labels: area:meta-programming, itype:bug
