### ISSUE TITLE
Match type aren't reduced

### ISSUE THREAD

**Issue by IndiscriminateCoding** [lampepfl/dotty#10370] opened 2020-11-18 05:18 UTC
## Minimized code

```Scala
type T >: String

type Res[A] = A match
  case Int => Int
  case T => Boolean

def run[A](a: A): Res[A] = a match
  case i: Int => 123
  case t: T => false

@main
def undotty: Unit = {
  val x: Boolean = run[T]("")
  println(x)
}

```

## Output

```
Found:    Res[T]
Required: Boolean
```

## Expectation
`Res[T]` reduced to `Boolean`

**Comment by odersky** [comment] 2022-04-06 13:35
We now get a more detailed explanation:
```
-- [E007] Type Mismatch Error: test.scala:13:25 --------------------------------
13 |  val x: Boolean = run[T]("")
   |                   ^^^^^^^^^^
   |             Found:    Res[T]
   |             Required: Boolean
   |
   |             Note: a match type could not be fully reduced:
   |
   |               trying to reduce  Res[T]
   |               failed since selector  T
   |               does not match  case Int => Int
   |               and cannot be shown to be disjoint from it either.
   |               Therefore, reduction cannot advance to the remaining case
   |
   |                 case T => Boolean
   |
   | longer explanation available when compiling with `-explain`
1 error found
```
But I am not sure the explanation is correct. `String` is disjoint from `Int`. Should not a type `T >: String` be disjoint
from `Int` also?

**Comment by LPTK** [comment] 2022-04-06 13:46
> `String` is disjoint from `Int`. Should not a type `T >: String` be disjoint from `Int` also?

No. `Any >: String`, but `Any` is not disjoint from `Int`.

**Comment by odersky** [comment] 2022-04-06 16:55
But matching checks whether scrutinee is a subtype of pattern type. Disjoint means: No possible instantiation of scrutinee could possibly be a subtype. So it's still not clear to me. @OlivierBlanvillain what is your interpretation?

**Comment by OlivierBlanvillain** [comment] 2022-04-06 17:24
> Disjoint means: No possible instantiation of scrutinee could possibly be a subtype.

If wanted to define disjointness in terms of subtyping, I think the definition would be that `disj(A, B)` holds iff there is no non-empty type `C` such that `C <: A` and `C <: B`. It's really just like the set theoretical version!

We would quickly get in trouble if we reduced `Res[T]` to `Boolean`:

```scala
class A:
  type T >: String

  type Res[A] = A match
    case Int => Int
    case T => Boolean

  def run[A](a: A): Res[A] = a match
    case i: Int => 123
    case t: T => false

class B extends A:
  type T = Any

  val notOK = run[T](1) && true // class cast exception
```

**Comment by OlivierBlanvillain** [comment] 2022-04-06 17:25
I'm closing this issue since this is working as intended.

**Closed by OlivierBlanvillain** 2022-04-06 17:25 UTC
Labels: itype:bug, area:match-types

**Comment by odersky** [comment] 2022-04-06 19:28
Thanks for the example. That's quite illuminating.
