### ISSUE TITLE
Unsoundness due to initialization-produced null

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#4042] opened 2018-02-26 23:08 UTC
Similar to #4031. Derived from [this gist](https://gist.github.com/alexknvl/56028633ef73faeec0f5d3e7e3a14746), which works in Scala2.

```scala
object App {
  def coerce[U, V](u: U): V = {
    trait X { type R >: U }
    trait Y { type R = V }

    class T[A <: X](val a: A)(val value: a.R)

    object O { val x : Y & X = x }

    val a = new T[Y & X](O.x)(u)
    a.value
  }

  def main(args: Array[String]): Unit = {
    val x: Int = coerce[String, Int]("a")
    println(x + 1)
  }
}

/////////////////////////////////

Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)
	at App$.main(HelloWorld.scala:15)
	at App.main(HelloWorld.scala)
```

Tested on the most recent master branch.

**Comment by Blaisorblade** [comment] 2018-02-28 23:12
Ok, finally found time to read it. I’m almost asleep, but I’m guessing that O.x ends up being null, assuming that’s right, we know null introduces unsoundness in Scala and Java (all versions) and null-tracking is not yet implemented, though we plan to get to it. I’ll figure out how to sort this snippet among “pending” testcases for null-tracking.

**Comment by Blaisorblade** [comment] 2018-03-01 17:45
Confirm that `O.x` is null.
So the issue is a duplicate of (the null-related part of) #50 (see https://github.com/lampepfl/dotty/issues/50#issuecomment-257296832 for the latest comment).

**Closed** 2021-03-17 17:27 UTC
Labels: area:initialization, area:typer, exp:expert, itype:bug, itype:enhancement, itype:language enhancement, stat:revisit
