### ISSUE TITLE
Wrong position for self definitions

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#5584] opened 2018-12-10 09:49 UTC
A position of the definition of `self` is wrong

```scala
class Foo { self =>
   // ^ currently it point here but shoud be the `self`
}
```

It can be reproduced in `dotty.tools.languageserver.DefinitionTest` with

```scala
  @Test def goToSelf: Unit = {
    withSources(
      code"""class Foo { ${m1}self${m2} =>
        |  ${m3}self${m4}.hashCode()
        |}"""
    ) .definition(m3 to m4, List(m1 to m2))
  }
```

**Comment by smarter** [comment] 2018-12-10 15:35
duplicate of https://github.com/lampepfl/dotty/issues/5450

**Closed by smarter** 2018-12-10 15:35 UTC
Labels: area:ide, itype:bug
