### ISSUE TITLE
Attempting string interpolation in REPL yields ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kavedaa** [lampepfl/dotty#6794] opened 2019-07-03 10:47 UTC
## minimized code

Opening a REPL console in any project and typing `s"` yields ArrayIndexOutOfBoundsException.

Version: 0.16.0-RC3

<details>
<summary>Stack trace</summary>

```scala
scala> s[error] (run-main-0) java.lang.ArrayIndexOutOfBoundsException: 2
[error] java.lang.ArrayIndexOutOfBoundsException: 2
[error]         at dotty.tools.dotc.parsing.Parsers$Parser.interpolatedString(Parsers.scala:802)
[error]         at dotty.tools.dotc.parsing.Parsers$Parser.literal(Parsers.scala:790)
[error]         at dotty.tools.dotc.parsing.Parsers$Parser.simpleExpr(Parsers.scala:1636)
[error]         at dotty.tools.dotc.parsing.Parsers$Parser.$init$$$anonfun$6(Parsers.scala:1572)
[error]         at dotty.tools.dotc.parsing.Parsers$Parser.postfixExpr(Parsers.scala:1559)
[error]         at dotty.tools.dotc.parsing.Parsers$Parser.expr1(Parsers.scala:1403)
[error]         at dotty.tools.dotc.parsing.Parsers$Parser.expr(Parsers.scala:1306)
[error]         at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq$$anonfun$1(Parsers.scala:3112)
[error]         at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:444)
[error]         at dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq(Parsers.scala:3133)
[error]         at dotty.tools.dotc.printing.SyntaxHighlighting$.highlight(SyntaxHighlighting.scala:121)
[error]         at dotty.tools.repl.JLineTerminal$Highlighter.highlight(JLineTerminal.scala:76)
[error]         at org.jline.reader.impl.LineReaderImpl.getHighlightedBuffer(LineReaderImpl.java:3633)
[error]         at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:3615)
[error]         at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3554)
[error]         at org.jline.reader.impl.LineReaderImpl.doCleanup(LineReaderImpl.java:2340)
[error]         at org.jline.reader.impl.LineReaderImpl.cleanup(LineReaderImpl.java:2332)
[error]         at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:626)
[error]         at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:404)
[error]         at dotty.tools.repl.JLineTerminal.readLine(JLineTerminal.scala:68)
[error]         at dotty.tools.repl.ReplDriver.readLine$1(ReplDriver.scala:115)
[error]         at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:125)
[error]         at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:130)
[error]         at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$2$$anonfun$1(ReplDriver.scala:143)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error]         at scala.Console$.withErr(Console.scala:196)
[error]         at dotty.tools.repl.ReplDriver.withRedirectedOutput$$anonfun$1(ReplDriver.scala:143)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error]         at scala.Console$.withOut(Console.scala:167)
[error]         at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:143)
[error]         at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:130)
[error]         at xsbt.ConsoleInterface.run(ConsoleInterface.java:52)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error]         at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:199)
[error]         at sbt.Console.console0$1(Console.scala:48)
[error]         at sbt.Console.$anonfun$apply$2(Console.scala:51)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:253)
[error]         at java.lang.Thread.run(Thread.java:748)```
</details>

**Comment by OlivierBlanvillain** [comment] 2019-07-03 13:19
Duplicate of #6676

**Closed by OlivierBlanvillain** 2019-07-03 13:19 UTC
Labels: itype:bug
