### ISSUE TITLE
Roll your own Enum will not compile

### ISSUE THREAD

**Issue by ekrich** [lampepfl/dotty#7390] opened 2019-10-08 16:20 UTC
## minimized code

```Scala
import java.{lang => jl}

final class ConfigIncludeKind private (name: String, ordinal: Int)
    extends jl.Enum[ConfigIncludeKind](name, ordinal)

object ConfigIncludeKind {

  final val URL       = new ConfigIncludeKind("URL", 0)
  final val FILE      = new ConfigIncludeKind("FILE", 1)
  final val CLASSPATH = new ConfigIncludeKind("CLASSPATH", 2)
  final val HEURISTIC = new ConfigIncludeKind("HEURISTIC", 3)

  private[this] final val _values: Array[ConfigIncludeKind] =
    Array(URL, FILE, CLASSPATH, HEURISTIC)

  def values: Array[ConfigIncludeKind] = _values.clone()

  def valueOf(name: String): ConfigIncludeKind =
    _values.find(_.name == name).getOrElse {
      throw new IllegalArgumentException(
        "No enum const ConfigIncludeKind." + name)
    }
}
```

## observation
```Scala
[info] Compiling 1 Scala source to /Users/eric/workspace/dotty-cross/target/scala-0.19/classes ...
[error] -- Error: /Users/eric/workspace/dotty-cross/src/main/scala/Main.scala:70:39 ----
[error] 70 |    extends jl.Enum[ConfigIncludeKind](name, ordinal)
[error]    |                                       ^^^^
[error]    |    too many arguments for constructor Enum: (): Enum[ConfigIncludeKind]
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 2 s, completed Oct 8, 2019 9:17:30 AM
```

## expectation

Should compile and work.

**Comment by smarter** [comment] 2019-10-08 16:23
Duplicate of https://github.com/lampepfl/dotty/issues/7174

**Closed by smarter** 2019-10-08 16:23 UTC
Labels: itype:bug

**Comment by ekrich** [comment] 2019-10-08 17:11
Sorry about that, I couldn't find it.
