### ISSUE TITLE
SAM type does not support type bounds

### ISSUE THREAD

**Issue by jvican** [lampepfl/dotty#3619] opened 2017-12-01 17:37 UTC
With SAMs in 2.12 the following works, but it fails in Dotty. I think this is Dotty's fault, correct me if I'm wrong.

```scala
  def addIfMissing(from: AbsolutePath, computeBuild: AbsolutePath => Build): Unit =
    cache.computeIfAbsent(from, path => computeBuild(path))
```
  
Error:
```
[error] -- [E007] Type Mismatch Error: /data/rw/code/scala/loop/rewo
rk/src/main/scala/bloop/State.scala:29:58
[error] 29 |    cache.computeIfAbsent(from, path => computeBuild(pat
h))[error]    |
  ^[error]    |found:    bloop.io.AbsolutePath => bloop.Build
[error]    |required: java.util.function.Function[_ >: bloop.io.Abso
lutePath, _ <: bloop.Build]
[error]    |
```
  
If you replace `path => computeBuild(path)` for the shorter `computeBuild` or even `computeBuild(_)` it also fails. I guess this is because Dotty does not have support for SAM types?
  
Scala 2 mode is enabled, didn't try without it.

**Comment by jvican** [comment] 2017-12-01 17:38
I didn't explicitly say it, but the data structure backing up `cache` is a `ConcurrentHashMap`.

**Comment by jvican** [comment] 2017-12-01 17:52
This is a normal workaround people can use:
  
```scala
object Compat {
  implicit class JavaFunction[T, R](f: T => R) {
    import java.util.function.Function
    def toJava: Function[T, R] = new Function[T, R] {
      def apply(t: T): R = f(t)
    }
  }
}
```

**Comment by allanrenucci** [comment] 2017-12-01 18:39
We do support SAM types. This is a bug. Here is a minimised version
```scala
class MyMap[K, V] {
  def computeIfAbsent(key: K, mappingFunction: java.util.function.Function[_  <: K, _ <: V]) = ()
}

class Test {
  val map = new MyMap[Int, Int]
  map.computeIfAbsent(1, (x: Int) => x)
}
```
```scala
-- [E007] Type Mismatch Error: tests/allan/Test.scala:7:38 ---------------------
7 |  map.computeIfAbsent(1, (x: Int) => x)
  |                                      ^
  |                 found:    Int => Int
  |                 required: java.util.function.Function[_ <: Int, _ <: Int]
  |                 
one error found
```

**Comment by allanrenucci** [comment] 2017-12-20 09:07
The issue arises when the SAM type has type bounds
```scala
class Test {
  def foo(x: java.util.concurrent.Callable[_ <: Int]) = ???
  foo(() => 1)
}
```
```scala
-- [E007] Type Mismatch Error: tests/allan/Test.scala:3:13 ---------------------
3 |  foo(() => 1)
  |             ^
  |found:    scala.this.Function0[scala.this.Int]
  |required: <root>.this.java.util.concurrent.Callable[_ <: <root>.this.scala.Int]
  |
```

**Comment by smarter** [comment] 2017-12-20 11:21
Duplicate of https://github.com/lampepfl/dotty/issues/2732. I tried and failed to make a proper fix for it in https://github.com/lampepfl/dotty/pull/3347. I agree that this is urgent and worth fixing.

**Closed by smarter** 2017-12-20 11:21 UTC
Labels: area:typer, exp:advanced, itype:bug, prio:high
