### ISSUE TITLE
Wrong constructor type for trait constructor with implicits

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2794] opened 2017-06-23 07:29 UTC
```scala
trait Foo(implicit n: Int)
class Bar extends Foo(1)
```
fails with 

```scala
2 |class Bar extends Foo(1)
  |                      ^
  |                      too many arguments for constructor Foo: ()(implicit n: Int)Foo
```

**Comment by nicolasstucki** [comment] 2017-06-23 07:29
The original code that I was trying to compile was something like this
```scala
trait Foo[T: ClassTag]
class Bar extends Foo[Int]
```

**Comment by nicolasstucki** [comment] 2017-06-23 07:31
Currently a workaround is to put the non implicit parameters of the constructor explicitly
```scala
trait Foo()(implicit n: Int)
class Bar extends Foo()(1)
```

**Comment by odersky** [comment] 2017-07-16 09:56
This is actually a duplicate of #2576.

**Closed by odersky** 2017-07-16 09:56 UTC
Labels: exp:advanced, itype:bug, prio:medium
