### ISSUE TITLE
Annotation on constructor field get lost

### ISSUE THREAD

**Issue by wiwiwa** [lampepfl/dotty#13569] opened 2021-09-21 02:33 UTC
## Compiler version

3.0.2

## Minimized code

```Scala
import scala.annotation.meta.{field, getter}

case class TestCaseClass(
  @(Deprecated @field) val conField: String
):
  @Deprecated val memberField: String = null

@main def test() =
  val clazz = classOf[TestCaseClass]
  val conFieldAnn = clazz.getDeclaredField("conField").getDeclaredAnnotations.toList
  println(conFieldAnn)
  val memberFieldAnn = clazz.getDeclaredField("memberField").getDeclaredAnnotations.toList
  println(memberFieldAnn)
```

## Output

```scala
List()
List(@java.lang.Deprecated(forRemoval=false, since=""))
```

## Expectation

Both `println` should output same annotation list.
```scala
List(@java.lang.Deprecated(forRemoval=false, since=""))
List(@java.lang.Deprecated(forRemoval=false, since=""))
```

**Comment by smarter** [comment] 2021-09-22 13:30
Duplicate of https://github.com/lampepfl/dotty/issues/12492

**Closed by smarter** 2021-09-22 13:30 UTC
Labels: itype:bug, area:annotations
