### ISSUE TITLE
`isDefinedAt` always returns true on PartialFunction that returns a context function

### ISSUE THREAD

**Issue by ysthakur** [lampepfl/dotty#16332] opened 2022-11-14 04:15 UTC
## Compiler version

3.1.1

## Minimized code

[Here's](https://scastie.scala-lang.org/QFb3KL5iS2i91R4CRfM8Fg) a Scastie.

```Scala
class Foo

val f: PartialFunction[Int, Foo ?=> Int] = {
  case x if x > 0 => x
}

given Foo = Foo()

println(f.isDefinedAt(0)) // true

val g: PartialFunction[Int, Int] = {
  case x if x > 0 => x
}

println(g.isDefinedAt(0)) // false
```

## Output

```scala
true
false
```

## Expectation

I'd expect both `isDefinedAt`s to return false. It seems like the extra context parameter in the first one is making the compiler think the function is always defined. Not sure why. `isDefinedAt` is a feature I'm heavily relying on for a project of mine, so if someone narrows down the issue and it's something a beginner can handle, I would love to contribute to the fix.

**Comment by dwijnand** [comment] 2022-11-14 09:38
Duplicate of #15741

**Closed by dwijnand** 2022-11-14 09:38 UTC
Labels: itype:bug
