### ISSUE TITLE
Can't summon Mirror for a sealed trait containing another sealed trait

### ISSUE THREAD

**Issue by ghostdogpr** [lampepfl/dotty#12308] opened 2021-05-02 07:22 UTC
## Compiler version

3.0.0-RC3

## Minimized code

```Scala
import scala.deriving.Mirror
import scala.compiletime._

sealed trait SomeTrait
object SomeTrait {
  case class B(a: Int) extends SomeTrait
  case class C(a: Int) extends SomeTrait
  sealed trait SomeOtherTrait extends SomeTrait
  case class D(a: Int) extends SomeOtherTrait
}

summonInline[Mirror.Of[SomeTrait]]
```

## Output

```scala
cannot reduce summonFrom with
 patterns :  case given t @ _:deriving.Mirror.Of[SomeTrait]
```

## Expectation
A mirror is summoned.

I am currently trying to cross-build a library with Scala 3 and rewriting the typeclass derivation logic. I ran into this issue when dealing with nested sealed traits. Is that intended? Is there any workaround?

**Comment by odersky** [comment] 2021-05-03 10:10
That's not supported yet. See https://github.com/lampepfl/dotty/pull/11686

**Comment by dwijnand** [comment] 2021-05-04 09:29
Duplicate of https://github.com/lampepfl/dotty-feature-requests/issues/161.

**Closed by dwijnand** 2021-05-04 09:29 UTC
Labels: itype:language enhancement
