### ISSUE TITLE
Please fix the Macros Typeclass Derivation Page in the New Docs

### ISSUE THREAD

**Issue by deusaquilus** [lampepfl/dotty#10468] opened 2020-11-24 08:37 UTC
## Output
This URL does not work:
https://dotty.epfl.ch/docs/reference/contextual/derivation-macro.md

## Expectation
Um... it should. please fix it.

Thanks!

**Comment by griggt** [comment] 2020-11-24 08:40
Duplicate of #10465

**Comment by julienrf** [comment] 2020-11-24 08:44
Closing in favor of #10465

**Closed by julienrf** 2020-11-24 08:44 UTC
Labels: itype:bug
