### ISSUE TITLE
scala3doc contains artifacts from JCenter

### ISSUE THREAD

**Issue by eed3si9n** [lampepfl/dotty#10904] opened 2020-12-23 15:22 UTC
## Minimized code

Fix the Dotty build locally then, 

```
show scala3doc/Compile/externalDependencyClasspath
```

## Output

```scala
sbt:scala3> show scala3doc/Compile/externalDependencyClasspath
[info] * Attributed(.../https/jcenter.bintray.com/org/jetbrains/dokka/dokka-core/1.4.10.2/dokka-core-1.4.10.2.jar)
[info] * Attributed(.../https/jcenter.bintray.com/org/jetbrains/dokka/dokka-base/1.4.10.2/dokka-base-1.4.10.2.jar)
[info] * Attributed(.../https/jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/kotlinx-html-jvm-0.7.2.jar)
[info] * Attributed(.../https/repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-all/0.42.12/flexmark-all-0.42.12.jar)
...
[info] * Attributed(.../https/jcenter.bintray.com/org/jetbrains/markdown/0.1.45/markdown-0.1.45.jar)
...
[info] * Attributed(.../https/jcenter.bintray.com/org/jetbrains/dokka/dokka-analysis/1.4.10.2/dokka-analysis-1.4.10.2.jar)
...
[info] * Attributed(.../https/jcenter.bintray.com/org/jetbrains/dokka/kotlin-analysis-intellij/1.4.10.2/kotlin-analysis-intellij-1.4.10.2.jar)
[info] * Attributed(.../https/jcenter.bintray.com/org/jetbrains/dokka/kotlin-analysis-compiler/1.4.10.2/kotlin-analysis-compiler-1.4.10.2.jar)
```

## Expectation

Tooling for Scala 3 should be available on Maven Central. If scala3doc becomes part of ScalaInstance dependencies in sbt, these JARs will be downloaded by CI environments both open source and corporate environment. Adding JCenter binary would add extra hurdle in terms of network latency and proxy management. If we're eventually removing them, that's ok, but if we're keeping them maybe it would be good to ask Kotlin team to sync them to Maven Central (some Kotlin artifacts are synced), or we should make a fat JAR that gets published to Maven Central?

**Comment by smarter** [comment] 2020-12-23 15:27
Duplicate of https://github.com/lampepfl/scala3doc/issues/226 (I think scala3doc issues should be mgirated to this repo to avoid people missing them, /cc @romanowski )

**Closed by smarter** 2020-12-23 15:27 UTC
Labels: itype:bug
