### ISSUE TITLE
Extension methods and implicit class defs do not always interact well

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#14450] opened 2022-02-11 00:22 UTC
Extension methods and implicit class defs do  not always interact well and we can get unrelated ambiguity.
I minimized this to the example below. There are various crucial elements for this error recipe:
* Two implicit class defs that differ in number of argument blocks (but no ambiguity under normal circumstances).
* One extension def applied on the same type of the implicit classes.
* The extended _type must be an alias from another namespace_ (just change `BlaB.Foo` to a class and this example will compile).
* Implicit context argument for the definitions.

## Compiler version

v3.1.2-RC1

## Minimized code

https://scastie.scala-lang.org/IwKSNqrxSZSnd6LVmBXJHg

```Scala
object BlaA:
  class Foo

object BlaB:
  trait Ctx
  type Foo = BlaA.Foo
  implicit class __FooExt(dfVal: Foo):
    def prev(step: Int)(implicit dfc: Ctx): Foo = ???
    def prev(implicit dfc: Ctx): Foo = ???
  extension (lhs: Foo) def baz: Foo = ???

  given Ctx = ???
  val f: Foo = new Foo
  val x = f.prev.baz
end BlaB
```

## Output

```scala
None of the overloaded alternatives of method prev in class __FooExt with types
 (implicit dfc: Playground.BlaB.Ctx): Playground.BlaB.Foo
 (step: Int)(implicit dfc: Playground.BlaB.Ctx): Playground.BlaB.Foo
match expected type ?{ baz: ? }
```

## Expectation
No error.

**Comment by som-snytt** [comment] 2022-02-11 01:37
Moving the extension to the companion of `BlaA.Foo` works.

Guessing that you get a pass with lexically scoped givens, then the second pass with implicitly scoped givens plus other implicit conversions. For the resolution of the second selection, it doesn't hop back to first pass resolution. 

Maybe that is because of some subtlety of how `f.prev` is typechecked during overload resolution.

It doesn't work to just change the alias to an import. It doesn't work to make the implicit class extend AnyVal.

It doesn't work to make it an opaque alias and create an anchor `object Foo` with the extension, though that might be a bug, as I would expect it to work the same as the "regular" companion `object Foo` that does work. Oh wait, it's because it is not opaque to us. Moving it into a "closet" module works.

```
  object stuff:
    opaque type Foo = BlaA.Foo
    object Foo:
      extension (lhs: Foo) def baz: Foo = ???
    def foo: Foo = new Foo
  end stuff
  import stuff.*
```

This ticket reads like a subplot of Agatha Christie's Death on the Nile.

**Comment by odersky** [comment] 2022-02-21 09:18
I don't think it's worth to out much more effort into this, since implicit classes will be get deprecated in the future. I'll close but if someone volunteers to take this one, please re-open.

**Closed by odersky** 2022-02-21 09:18 UTC
Labels: itype:bug, stat:revisit, area:extension-methods

**Comment by soronpo** [comment] 2022-02-21 16:24
@odersky I don't understand the policy on closing this. The bug exists. Whether it's portant or not is relevant for tag, IMO. The reason is simple. If someone looks for an existing open issue they look under OPEN issues.

**Comment by soronpo** [comment] 2022-02-21 16:28
And additionally, when interacting with Scala 2 libraries you get this issue even if implicit classes do not exist at all in your codebase.

**Comment by odersky** [comment] 2022-02-21 17:12
We currently have 766 open issues, and have to prioritize between issues that we think are worth fixing and issues where it is less likely. Issues that are currently not on the horizon for a possible fix get closed with stat:revisit. If someone _wants_ to have a go at solving them they can be re-opened at any moment. But otherwise, if we leave an issue open, we should also assign someone to spend potentially a lot of time solving it. And I don't see anyone we could assign this to right now.

**Comment by som-snytt** [comment] 2022-02-21 17:49
"It would be nice" to have a place to park knowledge about migration.

Oh I guess https://dotty.epfl.ch/docs/contributing/contribute-knowledge.html was the mechanism.

Maybe that repo was tilted toward "internals", or maybe it could still work for "user" knowledge. (Maybe link it from the Migration Guide.)

Searching tickets is pretty miserable, especially after a long time trying to understand why your code doesn't compile.

Also, leaving "won't fix" or "as designed but maybe a design bug" tickets open as doc is an invitation for "will this ever get fixed" frustrations.

**Comment by soronpo** [comment] 2022-02-22 01:04
Keeping the issue open with a flag costs us nothing  Closing the issue can potentially cost another person valuabke time in minimizing and debugging the same issue yet again.

**Comment by odersky** [comment] 2022-02-22 08:20
@soronpo That's a good point. We'll discuss what to do with stat:revisit issues, and whether another category is more appropriate.
