### ISSUE TITLE
Bug with context bounds and functional return types

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#5310] opened 2018-10-23 06:43 UTC
The following code declares a trait `C` with a method and a context bound. `s.fun(g)` does not type check unless we use `s.fun.apply(g)`. This issue will appear with the typical uses and implicit function types (as we discussed with @nicolasstucki) so I am including the similar snippet as well, for our pos tests.

/cc @yallop who discovered it

```scala
object Test {
  trait B[A]

  trait C {
    def fun[A: B]: Int => Int
  }

  def ex[A: B](s: C) = {
    s.fun(3) // ok with s.fun.apply(3)
  }
}
```

```scala
object Test {

 type Stringly[X] = implicit String => X

 trait C {
   def fun: Stringly[Int => Int]
 }

 def ex(s: C): Stringly[Int] = {
   s.fun(3) // ok with s.fun.apply(3)
 }
}
```

**Comment by odersky** [comment] 2018-10-23 10:13
Yes, this is a known shortcoming. To fix it, we need something like `.explicitly`. My talk "What to leave implicit gives the details". The main issue is devising a good migration scheme.

I am closing this one since it's really a language feature request (which I believe has been mentioned elsewhere), not a bug.

**Closed by odersky** 2018-10-23 10:13 UTC
Labels: area:typer, exp:intermediate, itype:bug
