### ISSUE TITLE
Local package objects conflict with imported package objects

### ISSUE THREAD

**Issue by propensive** [lampepfl/dotty#868] opened 2015-10-25 22:05 UTC
A wildcard import from a package with a package object defined makes it impossible to define a package object locally.

Both this:
```
package foo
import scala.collection._
package object bar
```
and
```
package foo.bar
import scala.collection._
object `package`
```
fail with the error:
```
pkg.scala:3: error: reference to package is ambiguous;
it is both imported by import collection._
and defined subsequently in package bar
object `package`
                ^
one error found
```

**Comment by odersky** [comment] 2015-10-30 07:57
Duplicate of #884.

**Closed by odersky** 2015-10-30 07:57 UTC
