### ISSUE TITLE
dotty.tools.dottydoc.api.java.Dottydoc.main is not static

### ISSUE THREAD

**Issue by cvogt** [lampepfl/dotty#1547] opened 2016-09-29 01:34 UTC
meaning dotty.tools.dottydoc.api.java.Dottydoc can't be invoked from the command line via java

**Comment by smarter** [comment] 2018-01-11 00:44
Closing as duplicate of https://github.com/lampepfl/dotty/issues/1548 which has more info.

**Closed by smarter** 2018-01-11 00:44 UTC
