### ISSUE TITLE
sourcecode links from official scala API site is broken

### ISSUE THREAD

**Issue by rssh** [lampepfl/dotty#13559] opened 2021-09-18 14:19 UTC
open https://scala-lang.org/api/3.x/scala/collection/ArrayOps.html

click on source link - url is
https://github.com/lampepfl/dotty/blob/3.0.2/out/bootstrap/stdlib-bootstrapped/scala-3.0.3-RC1-bin-SNAPSHOT-nonbootstrapped/src_managed/main/scala-library-src/scala/collection/ArrayOps.scala#L189

which is 404

**Comment by griggt** [comment] 2021-09-18 15:50
Duplicate of #13488  (and https://github.com/scala/docs.scala-lang/issues/2177)

**Closed by griggt** 2021-09-18 15:50 UTC
Labels: itype:bug
