### ISSUE TITLE
Require `case` prefix for patterns in for-comprehension generators

### ISSUE THREAD

**Issue by propensive** [lampepfl/dotty#5511] opened 2018-11-24 12:17 UTC
A common beginners' mistake when using `for`-comprehensions is to write a pattern on the left-side of a generator, and to not realize that it desugars to `filter`/`withFilter`.

I propose that this behavior should be supported only if the patter is prefixed with the keyword `case`, for example,
```
def collect(xs: List[Option[Int]]) = for {
  case Some(i) <- xs
} yield i
```
This would be a compile error:
```
def collect(xs: List[Option[Int]]) = for { Some(i) <- xs } yield i
```

**Comment by dwijnand** [comment] 2018-11-24 12:29
Using `case` makes it look like it'll match error.

What about `if`?  Then it's obviously like other if filters.  (Also it's similar to Rust's `if let`.)

**Comment by hepin1989** [comment] 2018-11-24 12:41
![image](https://user-images.githubusercontent.com/501740/48968344-4ebaf200-f029-11e8-8151-7cca353b2f59.png)

```
def collect(xs: List[Option[Int]]) = for {
   Some(i) ?<- xs
} yield i
```

**Comment by lihaoyi** [comment] 2018-11-24 12:59
duplicate of https://github.com/lampepfl/dotty/issues/2578

**Comment by DavidGregory084** [comment] 2018-11-24 13:41
See also https://github.com/oleg-py/better-monadic-for/blob/master/README.md which changes the desugaring to use map and match

**Comment by propensive** [comment] 2018-11-24 14:06
@dwijnand No strong feelings either way in using `case` or `if`. The former does certainly cause a potential match error everywhere else, so that might be worth keeping as a universal truth.

**Comment by smarter** [comment] 2018-11-24 16:38
So there's been a lot of proposals related to improving for-comprehensions, but it seems like there's just no one working on Dotty currently who's motivated enough to lead the redesign. To move forward, I suggest people who are interested in the topic build consensus and collaboratively write a SIP. Once we have an accepted SIP, the implementation should be easy. Therefore, I'm going to close this and redirect people to https://contributors.scala-lang.org/t/making-for-simpler-and-more-regular/2160 where the discussion has already started.

**Closed by smarter** 2018-11-24 16:38 UTC
