### ISSUE TITLE
scala.compiletime.ops.any.== has overly restrictive type bounds

### ISSUE THREAD

**Issue by noelwelsh** [lampepfl/dotty#8721] opened 2020-04-14 14:46 UTC
## Minimized code

Using an example from the documentation of `any.==`

```Scala
import scala.compiletime.ops.any._
val eq3: "1" == "1" = true
```

## Output

```scala
1 |val eq3: "1" == "1" = true
  |         ^
  |       Type argument ("1" : String) does not conform to upper bound AnyVal
1 |val eq3: "1" == "1" = true
  |                ^
  |       Type argument ("1" : String) does not conform to upper bound AnyVal
```

## Expectation

This code should compile to the value `true`. The overly restrictive type bound on `any.==` prevents string type literals being used with `any.==`.

**Comment by liufengyun** [comment] 2020-04-14 15:17
This is due to the restriction that `X <: AnyVal`, while `String` is not a value type.

```Scala
    @infix type ==[X <: AnyVal, Y <: AnyVal] <: Boolean
```

/cc: @MaximeKjaer @OlivierBlanvillain

**Comment by bishabosha** [comment] 2020-04-14 16:09
this is a duplicate of #8392

**Closed by bishabosha** 2020-04-14 16:09 UTC
Labels: area:library, stat:needs spec
