### ISSUE TITLE
`unapply` cannot return generic tuples

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#13969] opened 2021-11-17 09:23 UTC
## Compiler version

3.1.0

## Minimized example

```Scala
object Bar:
  def unapply(x: Any): Int *: Int *: EmptyTuple = ??? // Works it returns a `Tuple2[Int, Int]`

def test =
  "" match
    case Bar(a, b) =>
```

## Output

```scala
10 |    case Bar(a, b) =>
   |         ^^^^^^^^^
   |         Wrong number of argument patterns for Bar; expected: ()
```

## Expectation

Should be supported.

**Comment by dwijnand** [comment] 2021-11-17 15:20
This doesn't work because Tuple's product arity is 0 ("expected: ()").  I guess we need to teach `productArity` to walk the type to count the arity.

**Comment by nicolasstucki** [comment] 2021-11-18 08:54
It seems that in the example of #13968 we do calculate the arity correctly. We should see how it is handled there and why it was not done here.

**Comment by dwijnand** [comment] 2021-12-19 16:53
Duplicate of #11008

**Closed by dwijnand** 2021-12-19 16:53 UTC
Labels: itype:language enhancement, area:pattern-matching
