### ISSUE TITLE
dotc -Ytest-pickler fails on cyclic reference in valid Scala 2.12 code

### ISSUE THREAD

**Issue by AleksanderBG** [lampepfl/dotty#3479] opened 2017-11-15 16:05 UTC
`dotc -Ytest-pickler` fails on the following code:

```scala
sealed trait TermConstraint {
  final def neg: TermConstraint = this match {
    case Neg(c) => c
    case c: PositiveTermConstraint => Neg(c)
  }
}
case class Neg(c: PositiveTermConstraint) extends TermConstraint
sealed trait PositiveTermConstraint extends TermConstraint

case object Dummy extends PositiveTermConstraint
```

<details>
  <summary>Compiler output</summary>
  <p>

```
cannot take signature of (c: PositiveTermConstraint): Neg

cannot take signature of (): PositiveTermConstraint

exception occurred while compiling sample/3
Exception in thread "main" dotty.tools.dotc.core.Types$CyclicReference: cyclic reference involving class PositiveTermConstraint
	at dotty.tools.dotc.core.Types$CyclicReference$.apply(Types.scala:4432)
	at dotty.tools.dotc.core.SymDenotations$BaseDataImpl.apply(SymDenotations.scala:2111)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseData(SymDenotations.scala:1418)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseClassSet(SymDenotations.scala:1429)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.derivesFrom(SymDenotations.scala:1448)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.isValueClass(SymDenotations.scala:650)
	at dotty.tools.dotc.transform.ValueClasses$.isDerivedValueClass(ValueClasses.scala:19)
	at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:516)
	at dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:142)
	at dotty.tools.dotc.core.Signature$$anonfun$prepend$1.applyOrElse(Signature.scala:87)
	at dotty.tools.dotc.core.Signature$$anonfun$prepend$1.applyOrElse(Signature.scala:87)
	at scala.collection.immutable.List.collect(List.scala:305)
	at dotty.tools.dotc.core.Signature.prepend(Signature.scala:87)
	at dotty.tools.dotc.core.Types$MethodType.computeSignature(Types.scala:2746)
	at dotty.tools.dotc.core.Types$MethodicType.signature(Types.scala:2503)
	at dotty.tools.dotc.core.Types$MethodicType.signature$(Types.scala:2501)
	at dotty.tools.dotc.core.Types$MethodType.signature(Types.scala:2728)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:609)
	at dotty.tools.dotc.core.Types$TermRef$.apply(Types.scala:2056)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.termRef(SymDenotations.scala:1136)
	at dotty.tools.dotc.typer.TypeAssigner.$anonfun$assignType$31(TypeAssigner.scala:526)
	at dotty.tools.dotc.core.Types$Type.orElse(Types.scala:104)
	at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:526)
	at dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:525)
	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:69)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.DefDef$1(TreeUnpickler.scala:634)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:661)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:607)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTemplate(TreeUnpickler.scala:751)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:680)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:607)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$Completer.complete(TreeUnpickler.scala:85)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:241)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:204)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:206)
	at dotty.tools.dotc.core.Types$NamedType.info(Types.scala:1808)
	at dotty.tools.dotc.core.Types$Type.isRef(Types.scala:129)
	at dotty.tools.dotc.typer.Checking$.preCheckKind(Checking.scala:113)
	at dotty.tools.dotc.typer.Checking$.$anonfun$preCheckKinds$1(Checking.scala:117)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.zipWithConserve$extension(Decorators.scala:108)
	at dotty.tools.dotc.typer.Checking$.preCheckKinds(Checking.scala:117)
	at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:411)
	at dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:363)
	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:69)
	at dotty.tools.dotc.ast.tpd$.TypeApply(tpd.scala:47)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:947)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1038)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:938)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1038)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$readModifiers$2(TreeUnpickler.scala:530)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$LazyReader.complete(TreeUnpickler.scala:1099)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$readModifiers$4(TreeUnpickler.scala:533)
	at dotty.tools.dotc.core.Annotations$Annotation$$anon$2.complete(Annotations.scala:132)
	at dotty.tools.dotc.core.Annotations$LazyAnnotation.tree(Annotations.scala:43)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$readNewDef$9(TreeUnpickler.scala:705)
	at scala.collection.immutable.List.map(List.scala:287)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:705)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:607)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$Completer.complete(TreeUnpickler.scala:85)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:241)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:204)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:206)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.classParents(SymDenotations.scala:1365)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeBaseData(SymDenotations.scala:1434)
	at dotty.tools.dotc.core.SymDenotations$BaseDataImpl.apply(SymDenotations.scala:2115)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseData(SymDenotations.scala:1418)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseClasses(SymDenotations.scala:1425)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.$anonfun$computeBaseData$1(SymDenotations.scala:1439)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeBaseData(SymDenotations.scala:1437)
	at dotty.tools.dotc.core.SymDenotations$BaseDataImpl.apply(SymDenotations.scala:2115)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseData(SymDenotations.scala:1418)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseClassSet(SymDenotations.scala:1429)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.derivesFrom(SymDenotations.scala:1448)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.isValueClass(SymDenotations.scala:650)
	at dotty.tools.dotc.transform.ValueClasses$.isDerivedValueClass(ValueClasses.scala:19)
	at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:516)
	at dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:142)
	at dotty.tools.dotc.core.Signature$.apply(Signature.scala:117)
	at dotty.tools.dotc.core.Types$MethodicType.resultSignature(Types.scala:2493)
	at dotty.tools.dotc.core.Types$MethodicType.resultSignature$(Types.scala:2489)
	at dotty.tools.dotc.core.Types$MethodType.resultSignature(Types.scala:2728)
	at dotty.tools.dotc.core.Types$MethodType.computeSignature(Types.scala:2746)
	at dotty.tools.dotc.core.Types$MethodicType.signature(Types.scala:2503)
	at dotty.tools.dotc.core.Types$MethodicType.signature$(Types.scala:2501)
	at dotty.tools.dotc.core.Types$MethodType.signature(Types.scala:2728)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:609)
	at dotty.tools.dotc.core.Types$TermRef$.apply(Types.scala:2056)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.termRef(SymDenotations.scala:1136)
	at dotty.tools.dotc.typer.TypeAssigner.$anonfun$assignType$31(TypeAssigner.scala:526)
	at dotty.tools.dotc.core.Types$Type.orElse(Types.scala:104)
	at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:526)
	at dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:525)
	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:69)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.DefDef$1(TreeUnpickler.scala:634)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:661)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:607)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTemplate(TreeUnpickler.scala:751)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:680)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:607)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStat(TreeUnpickler.scala:796)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$readIndexedStats$1(TreeUnpickler.scala:834)
	at dotty.tools.dotc.core.tasty.TastyReader.until(TastyReader.scala:125)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStats(TreeUnpickler.scala:834)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$readIndexedStat$2(TreeUnpickler.scala:802)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.processPackage(TreeUnpickler.scala:580)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStat(TreeUnpickler.scala:801)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.read$1(TreeUnpickler.scala:786)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTopLevel(TreeUnpickler.scala:791)
	at dotty.tools.dotc.core.tasty.TreeUnpickler.unpickle(TreeUnpickler.scala:77)
	at dotty.tools.dotc.core.tasty.DottyUnpickler.computeBody$1(DottyUnpickler.scala:53)
	at dotty.tools.dotc.core.tasty.DottyUnpickler.body(DottyUnpickler.scala:58)
	at dotty.tools.dotc.transform.Pickler.$anonfun$testUnpickler$6(Pickler.scala:98)
	at dotty.tools.dotc.transform.Pickler.$anonfun$testUnpickler$6$adapted(Pickler.scala:97)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at dotty.tools.dotc.transform.Pickler.testUnpickler(Pickler.scala:97)
	at dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:83)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$3(Run.scala:125)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.trackTime(Stats.scala:47)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2(Run.scala:123)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2$adapted(Run.scala:121)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:121)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:141)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:86)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:107)
	at dotty.tools.dotc.Run.compileSources(Run.scala:94)
	at dotty.tools.dotc.Run.compile(Run.scala:78)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
	at dotty.tools.dotc.Driver.process(Driver.scala:124)
	at dotty.tools.dotc.Driver.process(Driver.scala:93)
	at dotty.tools.dotc.Driver.process(Driver.scala:105)
	at dotty.tools.dotc.Driver.main(Driver.scala:132)
	at dotty.tools.dotc.Main.main(Main.scala)
```
  </p>
</summary>

**Comment by odersky** [comment] 2017-11-16 16:29
I could not reproduce it. It seems to work fine for me.

**Comment by AleksanderBG** [comment] 2017-11-16 17:02
Confirmed - it works for me on master as well. Closest commit I've tested where it still breaks is 253f5059b22d090e883d2fd4d86b7c1ddaaf2fe5.

**Comment by AleksanderBG** [comment] 2017-11-16 17:37
@odersky @smarter reopen? The exception still happens if a package is added:

```scala
package dotty.tools.dotc.transform.patmat

sealed trait TermConstraint {
  final def neg: TermConstraint = this match {
    case Neg(c) => c
    case c: PositiveTermConstraint => Neg(c)
  }
}
case class Neg(c: PositiveTermConstraint) extends TermConstraint
sealed trait PositiveTermConstraint extends TermConstraint

case object Dummy extends PositiveTermConstraint
```

<details><summary>Exception</summary>
  <p>

```
cannot take signature of (c: dotty.tools.dotc.transform.patmat.PositiveTermConstraint):
  dotty.tools.dotc.transform.patmat.Neg

cannot take signature of (): dotty.tools.dotc.transform.patmat.PositiveTermConstraint

exception occurred while compiling sample/3
Exception in thread "main" dotty.tools.dotc.core.Types$CyclicReference: cyclic reference involving class PositiveTermConstraint
	at dotty.tools.dotc.core.Types$CyclicReference$.apply(Types.scala:4435)
	at dotty.tools.dotc.core.SymDenotations$BaseDataImpl.apply(SymDenotations.scala:2111)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseData(SymDenotations.scala:1418)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseClassSet(SymDenotations.scala:1429)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.derivesFrom(SymDenotations.scala:1448)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.isValueClass(SymDenotations.scala:650)
	at dotty.tools.dotc.transform.ValueClasses$.isDerivedValueClass(ValueClasses.scala:19)
	at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:516)
	at dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:142)
	at dotty.tools.dotc.core.Signature$$anonfun$prepend$1.applyOrElse(Signature.scala:87)
	at dotty.tools.dotc.core.Signature$$anonfun$prepend$1.applyOrElse(Signature.scala:87)
	at scala.collection.immutable.List.collect(List.scala:305)
	at dotty.tools.dotc.core.Signature.prepend(Signature.scala:87)
	at dotty.tools.dotc.core.Types$MethodType.computeSignature(Types.scala:2746)
	at dotty.tools.dotc.core.Types$MethodicType.signature(Types.scala:2503)
	at dotty.tools.dotc.core.Types$MethodicType.signature$(Types.scala:2501)
	at dotty.tools.dotc.core.Types$MethodType.signature(Types.scala:2728)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:609)
	at dotty.tools.dotc.core.Types$TermRef$.apply(Types.scala:2056)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.termRef(SymDenotations.scala:1136)
	at dotty.tools.dotc.typer.TypeAssigner.$anonfun$assignType$31(TypeAssigner.scala:526)
	at dotty.tools.dotc.core.Types$Type.orElse(Types.scala:104)
	at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:526)
	at dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:525)
	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:69)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.DefDef$1(TreeUnpickler.scala:634)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:661)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:607)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTemplate(TreeUnpickler.scala:751)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:680)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:607)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$Completer.complete(TreeUnpickler.scala:85)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:241)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:204)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:206)
	at dotty.tools.dotc.core.Types$NamedType.info(Types.scala:1808)
	at dotty.tools.dotc.core.Types$Type.isRef(Types.scala:129)
	at dotty.tools.dotc.typer.Checking$.preCheckKind(Checking.scala:113)
	at dotty.tools.dotc.typer.Checking$.$anonfun$preCheckKinds$1(Checking.scala:117)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.zipWithConserve$extension(Decorators.scala:108)
	at dotty.tools.dotc.typer.Checking$.preCheckKinds(Checking.scala:117)
	at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:411)
	at dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:363)
	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:69)
	at dotty.tools.dotc.ast.tpd$.TypeApply(tpd.scala:47)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:947)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1038)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:938)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1038)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$readModifiers$2(TreeUnpickler.scala:530)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$LazyReader.complete(TreeUnpickler.scala:1099)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$readModifiers$4(TreeUnpickler.scala:533)
	at dotty.tools.dotc.core.Annotations$Annotation$$anon$2.complete(Annotations.scala:132)
	at dotty.tools.dotc.core.Annotations$LazyAnnotation.tree(Annotations.scala:43)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$readNewDef$9(TreeUnpickler.scala:705)
	at scala.collection.immutable.List.map(List.scala:287)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:705)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:607)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$Completer.complete(TreeUnpickler.scala:85)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:241)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:204)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:206)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.classParents(SymDenotations.scala:1365)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeBaseData(SymDenotations.scala:1434)
	at dotty.tools.dotc.core.SymDenotations$BaseDataImpl.apply(SymDenotations.scala:2115)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseData(SymDenotations.scala:1418)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseClasses(SymDenotations.scala:1425)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.$anonfun$computeBaseData$1(SymDenotations.scala:1439)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.computeBaseData(SymDenotations.scala:1437)
	at dotty.tools.dotc.core.SymDenotations$BaseDataImpl.apply(SymDenotations.scala:2115)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseData(SymDenotations.scala:1418)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.baseClassSet(SymDenotations.scala:1429)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.derivesFrom(SymDenotations.scala:1448)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.isValueClass(SymDenotations.scala:650)
	at dotty.tools.dotc.transform.ValueClasses$.isDerivedValueClass(ValueClasses.scala:19)
	at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:516)
	at dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:142)
	at dotty.tools.dotc.core.Signature$.apply(Signature.scala:117)
	at dotty.tools.dotc.core.Types$MethodicType.resultSignature(Types.scala:2493)
	at dotty.tools.dotc.core.Types$MethodicType.resultSignature$(Types.scala:2489)
	at dotty.tools.dotc.core.Types$MethodType.resultSignature(Types.scala:2728)
	at dotty.tools.dotc.core.Types$MethodType.computeSignature(Types.scala:2746)
	at dotty.tools.dotc.core.Types$MethodicType.signature(Types.scala:2503)
	at dotty.tools.dotc.core.Types$MethodicType.signature$(Types.scala:2501)
	at dotty.tools.dotc.core.Types$MethodType.signature(Types.scala:2728)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:609)
	at dotty.tools.dotc.core.Types$TermRef$.apply(Types.scala:2056)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.termRef(SymDenotations.scala:1136)
	at dotty.tools.dotc.typer.TypeAssigner.$anonfun$assignType$31(TypeAssigner.scala:526)
	at dotty.tools.dotc.core.Types$Type.orElse(Types.scala:104)
	at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:526)
	at dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:525)
	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:69)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.DefDef$1(TreeUnpickler.scala:634)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:661)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:607)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTemplate(TreeUnpickler.scala:751)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:680)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:607)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStat(TreeUnpickler.scala:796)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$readIndexedStats$1(TreeUnpickler.scala:834)
	at dotty.tools.dotc.core.tasty.TastyReader.until(TastyReader.scala:125)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStats(TreeUnpickler.scala:834)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$readIndexedStat$2(TreeUnpickler.scala:802)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.processPackage(TreeUnpickler.scala:580)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStat(TreeUnpickler.scala:801)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.read$1(TreeUnpickler.scala:786)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTopLevel(TreeUnpickler.scala:791)
	at dotty.tools.dotc.core.tasty.TreeUnpickler.unpickle(TreeUnpickler.scala:77)
	at dotty.tools.dotc.core.tasty.DottyUnpickler.computeBody$1(DottyUnpickler.scala:53)
	at dotty.tools.dotc.core.tasty.DottyUnpickler.body(DottyUnpickler.scala:58)
	at dotty.tools.dotc.transform.Pickler.$anonfun$testUnpickler$6(Pickler.scala:98)
	at dotty.tools.dotc.transform.Pickler.$anonfun$testUnpickler$6$adapted(Pickler.scala:97)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at dotty.tools.dotc.transform.Pickler.testUnpickler(Pickler.scala:97)
	at dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:83)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$3(Run.scala:125)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.trackTime(Stats.scala:47)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2(Run.scala:123)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2$adapted(Run.scala:121)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:121)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:141)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:86)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:107)
	at dotty.tools.dotc.Run.compileSources(Run.scala:94)
	at dotty.tools.dotc.Run.compile(Run.scala:78)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:29)
	at dotty.tools.dotc.Driver.process(Driver.scala:127)
	at dotty.tools.dotc.Driver.process(Driver.scala:96)
	at dotty.tools.dotc.Driver.process(Driver.scala:108)
	at dotty.tools.dotc.Driver.main(Driver.scala:135)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</p>
</details>

The file on which this occurs is [this](https://github.com/AleksanderBG/dotty/blob/4f6adb1d322cd39157a31af099bf1d08b6e7e79f/compiler/src/dotty/tools/dotc/transform/patmat/Spaces.scala). I'll try to rewrite the code to not trigger this and see if an exception doesn't happen somewhere else on that branch.

**Comment by AleksanderBG** [comment] 2017-11-16 18:09
After testing, it appears that `neg` method is actually irrelevant. The smallest file with which I've triggered the exception is:

```scala
package dotty.tools
sealed trait TermConstraint
case class Neg(c: PositiveTermConstraint) extends TermConstraint
trait PositiveTermConstraint extends TermConstraint
```

Removing anything will stop triggering the problem, including removing either package name.

**Comment by allanrenucci** [comment] 2017-11-16 19:50
Inverting the last two definitions also solves the issue.

**Comment by AleksanderBG** [comment] 2017-11-20 21:00
I've been to apply the above workaround to #3454 after rebasing it, without any success. While inverting the definitions works for the minimal example, it doesn't work for the original file. For instance, on current master cc43c3444da86929eb45f02d82159d2d31eb1906, running `dotc -classpath interfaces/target/dotty-interfaces-0.5.0-bin-SNAPSHOT.jar   -Ytest-pickler sample/3a`, where `sample/3a` is:

```scala
package dotty.tools.dotc.transform.patmat
sealed trait TermConstraint
sealed trait PositiveTermConstraint extends TermConstraint
case class Neg(c: PositiveTermConstraint) extends TermConstraint
case object Dummy extends PositiveTermConstraint
case object AlwaysSatisfied extends PositiveTermConstraint
```

emits the same error. This time, commenting out either Dummy or AlwaysSatisfied works, but commenting out Dummy (almost unused) in the real file doesn't.

I've uploaded the rebased PR at AleksanderBG/dotty@04b6d5c7172b4b75e471c06aa092c3b885d99bfb. If that's relevant, I've been running the pickler tests with `testOnly dotty.tools.dotc.CompilationTests -- --tests=testPickling`.

**Comment by allanrenucci** [comment] 2017-11-20 21:13
This issue seems to be a duplicate of #1932

**Comment by AleksanderBG** [comment] 2017-11-21 07:27
@allanrenucci That's actually very helpful, thanks! I just quickly checked and removing `sealed` from `TermConstraint` works  on the rebased PR - I should've tried that from the beginning. If this issue is a duplicate, then I guess it can be closed now.

**Comment by odersky** [comment] 2018-01-02 11:37
#1932 works OK for me now. Can someone check whether the issue here is also fixed?

**Comment by AleksanderBG** [comment] 2018-01-04 09:09
Work OK for me too on latest master.

**Closed** 2018-01-15 12:42 UTC
Labels: area:pickling, exp:expert, itype:bug, prio:high
