### ISSUE TITLE
Tuples created through *: do not have a Mirror.Of[T]

### ISSUE THREAD

**Issue by juanjovazquez** [lampepfl/dotty#14127] opened 2021-12-17 15:48 UTC
## Compiler version
3.1.1-RC1
3.1.0

## Minimized code

```Scala
summon[Mirror.Of[Int *: String *: Boolean *: EmptyTuple]]
```

## Output

```scala
no implicit argument of type deriving.Mirror.Of[Int *: String *: Boolean *: EmptyTuple] was found for parameter x of method summon in object Predef
```

## Expectation
Output should be the same as:

```Scala
summon[Mirror.Of[(Int, String, Boolean)]]
```

since

```Scala
summon[(Int, String, Boolean) =:= (Int *: String *: Boolean *: EmptyTuple)]
```

The cause seems related to the fact that `*:` is an abstract class and those are excluded from being generic products. Relevant links:
https://github.com/lampepfl/dotty/blob/7a473349b3fb64e7c6c9dfcfb02758f4a2e3756c/library/src/scala/Tuple.scala#L318

https://github.com/lampepfl/dotty/blob/7a473349b3fb64e7c6c9dfcfb02758f4a2e3756c/compiler/src/dotty/tools/dotc/typer/Synthesizer.scala#L233

https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/SymUtils.scala#L77-L88

**Comment by odersky** [comment] 2021-12-19 11:24
Isn't that a duplicate of some other issues? I could swear I have seen that discussed recently.

**Comment by bishabosha** [comment] 2021-12-20 08:57
This seems related to https://github.com/lampepfl/dotty/issues/11008 maybe (not the same underlying issue, just whether we consider generic tuple types a Product)

**Comment by joroKr21** [comment] 2021-12-24 11:32
What should be the element names? `_n` beyond 22? Just realised we can't call `_n` on an inductive tuple.

**Comment by nicolasstucki** [comment] 2022-01-03 11:43
Beyond 22 we do not use `_` names. There we use the `apply` method to access the elements by index (0 based in that casse).

**Comment by joroKr21** [comment] 2022-01-03 11:52
Right but if we implement `Mirror` for `*:` tuples we need to provide something as the field names, otherwise it won't work. And we can't call `_n` on `*:` below 22 either.

**Comment by nicolasstucki** [comment] 2022-01-03 12:15
Then we probably are missing a generalization/extension for mirrors that can handle generic tuples.

**Comment by armanbilge** [comment] 2022-04-16 17:51
Not sure if it deserves its own issue, but seems that `EmptyTuple` itself doesn't have a `Mirror`.

**Comment by bishabosha** [comment] 2022-04-19 10:42
> Not sure if it deserves its own issue, but seems that `EmptyTuple` itself doesn't have a `Mirror`.

seems that `EmptyTuple` was never made a case object, so that's why (@nicolasstucki do you remember why?)

**Comment by nicolasstucki** [comment] 2022-04-19 14:53
There was no real reason why we did not make `EmptyTuple` a `case object`. Maybe we followed the design of the `*:`.

The `*:` cannot be a case class because it is not a real runtime class. The `TupleN` classes from Scala 2 are used and a new `TupleXXL` for larger cases (above 22).

I'm trying to make `EmptyTuple` a `case object` in #14972 to see if we can.

**Comment by bishabosha** [comment] 2022-04-22 14:41
> Right but if we implement `Mirror` for `*:` tuples we need to provide something as the field names, otherwise it won't work. And we can't call `_n` on `*:` below 22 either.

there is no requirement that Mirrors have the `MirroredElemLabels` type member, so we could avoid adding that refinement for generic tuples?

**Comment by bishabosha** [comment] 2022-05-20 13:04
perhaps for tupleXXL we can use as labels `(..., "apply(22)", "apply(23)",...)`?

**Closed** 2022-05-31 12:56 UTC
Labels: itype:bug, area:typeclass-derivation
