### ISSUE TITLE
Extension Methods do not support property assignment syntax

### ISSUE THREAD

**Issue by edolgy** [lampepfl/dotty#9383] opened 2020-07-18 11:05 UTC
```Scala
class Foo:
  var i = 0
  def property: Int      = i
  def property_=(v: Int) = i = v

extension on (x: Foo):
  def xProperty: Int      = x.i
  def xProperty_=(v: Int) = x.i = v

object Bar:
  val foo = Foo()
  foo.property  = 12  // Works as expected
  foo.xProperty = 12  // Fails with: Reassignment to val xProperty
```
## Expectation
Given "extension methods" MUST support property assignments. 

When using opaque type wrappers, almost all methods are always 'extensions', and this problem prevents creating Scala like property access (forcing to use  AnyVal wrappers instead of opaques)

**Comment by TheElectronWill** [comment] 2020-07-19 08:51
Duplicate of #9248

**Closed by TheElectronWill** 2020-07-19 08:51 UTC
Labels: itype:bug
