### ISSUE TITLE
dotty visual studio doesn't seem to understand top-level implicits

### ISSUE THREAD

**Issue by drdozer** [lampepfl/dotty#6130] opened 2019-03-20 21:15 UTC
I'm seeing a lot of problems like the one below. variations on a theme. The code that triggers this is:

```
object Category {
  implied [⟶[_, _], ⨯[_, _]] given Monoidal[⟶, ⨯] for Category[⟶] =
    the[Monoidal[⟶, ⨯]].category
}
```

It smells like the implied instance is visible once in a synthetic package object and once again in the top level of the package.

```
cannot merge
  method NumericIsNumberCat in package ct of type [N](implicit N: Numeric[N]): ct.categories$package.NumericIsNumberCat[N]  and
  method NumericIsNumberCat in package ct of type [N]
  (implicit N: Numeric[N]): 
    ct.file:///home/nmrp3/devel/turingatemyhamster/finally-tagless-dotty/src/main/scala/ct/categories$package
      .
    NumericIsNumberCat[N]
they are both defined in package ct but have matching signatures
  [N](implicit N: Numeric[N]): ct.categories$package.NumericIsNumberCat[N] and
  [N]
  (implicit N: Numeric[N]): 
    ct.file:///home/nmrp3/devel/turingatemyhamster/finally-tagless-dotty/src/main/scala/ct/categories$package
      .
    NumericIsNumberCat[N]
as members of package ct
       (-1)
```

**Comment by smarter** [comment] 2019-03-21 14:05
Can you provide a full project that reproduces the issue ? Also can you check if the issue is reproducible outside of the IDE ?

**Comment by smarter** [comment] 2019-03-28 15:09
Closing because this is lacking enough details to be actionable, feel free to re-open once more information has been provided.

**Closed by smarter** 2019-03-28 15:09 UTC
Labels: area:implicits, area:typer, itype:bug
