### ISSUE TITLE
Inline macro expansion used as default value causes CyclicReference exception

### ISSUE THREAD

**Issue by hmf** [lampepfl/dotty#10403] opened 2020-11-20 09:41 UTC
## Minimized code

Don't know if this is a bug or if it is even a valid use of inline methods. 

In one file I have:
```Scala
object Constants {
  import scala.compiletime.erasedValue
  import scala.compiletime.{error, code}

  inline def defaultValue[T] = inline erasedValue[T] match {
    case _: Byte => 0: Byte
    case _: Char => 0: Char
    case _: Short => 0: Short
    case _: Int => 0
    case _: Long => 0L
    case _: Float => 0.0f
    case _: Double => 0.0d
    case _: Boolean => false
    case _: Unit => ()
    case _ =>  error(code"defaultValue failed on: ${erasedValue[T]}")
  }
}
```

In another I have:

```Scala
  import macros.Constants._

  def possible[T: Numeric](step: T = defaultValue[T]): Unit = {
    ???
  }
```

## Output

```scala
[error] -- Error: /home/hmf/IdeaProjects/pdm_toyadmos/dcase2020/src/data/synthetic/TimeSeries.scala:138:49 
[error] 138 |  def possible[T: Numeric](step: T = defaultValue[T]): Unit = {
[error]     |                                     ^^^^^^^^^^^^^^^
[error]     |Exception occurred while executing macro expansion.
[error]     |dotty.tools.dotc.core.CyclicReference: 
[error]     |	at dotty.tools.dotc.core.CyclicReference$.apply(TypeErrors.scala:155)
[error]     |	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:164)
[error]     |	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:188)
[error]     |	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:190)
[error]     |	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:368)
[error]     |	at dotty.tools.dotc.core.SymDenotations$SymDenotation.flags(SymDenotations.scala:65)
[error]     |	at dotty.tools.dotc.quoted.QuoteContextImpl$reflect$SymbolMethodsImpl$.extension_flags(QuoteContextImpl.scala:2285)
[error]     |	at dotty.tools.dotc.quoted.QuoteContextImpl$reflect$SymbolMethodsImpl$.extension_flags(QuoteContextImpl.scala:2285)
[error]     |	at scala.tasty.reflect.SourceCodePrinter$Buffer.printType(SourceCodePrinter.scala:1079)
[error]     |	at scala.tasty.reflect.SourceCodePrinter$Buffer.printTypeAndAnnots$1(SourceCodePrinter.scala:996)
[error]     |	at scala.tasty.reflect.SourceCodePrinter$Buffer.printTypeTree(SourceCodePrinter.scala:998)
[error]     |	at scala.tasty.reflect.SourceCodePrinter$Buffer.printTree(SourceCodePrinter.scala:525)
[error]     |	at scala.tasty.reflect.SourceCodePrinter$Buffer.printTrees$$anonfun$1(SourceCodePrinter.scala:649)
[error]     |	at scala.tasty.reflect.SourceCodePrinter$Buffer.printSeparated$3(SourceCodePrinter.scala:638)
[error]     |	at scala.tasty.reflect.SourceCodePrinter$Buffer.printList(SourceCodePrinter.scala:644)
[error]     |	at scala.tasty.reflect.SourceCodePrinter$Buffer.printTrees(SourceCodePrinter.scala:649)
[error]     |	at scala.tasty.reflect.SourceCodePrinter$Buffer.printTree$$anonfun$6(SourceCodePrinter.scala:415)
[error]     |	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]     |	at scala.tasty.reflect.SourceCodePrinter$Buffer.inSquare(SourceCodePrinter.scala:82)
[error]     |	at scala.tasty.reflect.SourceCodePrinter$Buffer.printTree(SourceCodePrinter.scala:415)
[error]     |	at scala.tasty.reflect.SourceCodePrinter.showTree(SourceCodePrinter.scala:13)
[error]     |	at dotty.tools.dotc.quoted.QuoteContextImpl$reflect$TreeMethodsImpl$.extension_showWith(QuoteContextImpl.scala:74)
[error]     |	at dotty.tools.dotc.quoted.QuoteContextImpl$reflect$TreeMethodsImpl$.extension_showWith(QuoteContextImpl.scala:73)
[error]     |	at scala.quoted.Expr.show(Expr.scala:11)
[error]     |	at dotty.internal.CompileTimeMacros$.codeExpr$$anonfun$2(CompileTimeMacros.scala:9)
[error]     |	at scala.collection.immutable.List.map(List.scala:246)
[error]     |	at scala.collection.immutable.List.map(List.scala:79)
[error]     |	at dotty.internal.CompileTimeMacros$.codeExpr(CompileTimeMacros.scala:9)
[error]     |
[error]     | This location contains code that was inlined from TimeSeries.scala:138
[error]     | This location contains code that was inlined from Constants.scala:18
[error] one error found
1 targets failed
```

## Expectation

I was expecting the compilation to succeed and be able to use the method with an automatically generated default value.

**Comment by prolativ** [comment] 2020-11-20 16:12
@hmf the problem you're getting is somehow more specifically caused by using `erasedValue` inside of `code` and can be reproduced with this minimalized code:
```scala
import scala.compiletime.erasedValue
import scala.compiletime.{code, error}

inline def defaultValue[T]: Any = error(code"defaultValue failed on: ${erasedValue[T]}")

def possible[T](step: Any = defaultValue[T]): Unit = ???
```

However this is not going to be a problem itself anymore because `code` interpolator has been recently replaced with `codeOf` method which doesn't seem to blow up the compiler in this situation

```scala
object Constants {
  import scala.compiletime.erasedValue
  import scala.compiletime.{codeOf, error}

  inline def defaultValue[T: Numeric] = inline erasedValue[T] match {
    case _: Byte => 0: Byte
    case _: Char => 0: Char
    case _: Short => 0: Short
    case _: Int => 0
    case _: Long => 0L
    case _: Float => 0.0f
    case _: Double => 0.0d
    case _: Boolean => false
    case _: Unit => ()
    case _ =>
      error("defaultValue failed on: " + codeOf(erasedValue[T]))
  }
}

import Constants._

def possible[T](using Numeric[T])(step: T = defaultValue[T]): Unit = {}
```

However this still doesn't compile
```scala
def possible[T](using Numeric[T])(step: T = defaultValue[T]): Unit = {}
                                            ^^^^^^^^^^^^^^^
                defaultValue failed on: scala.compiletime.erasedValue[T]
```

Alternatively you could try something like this to achieve the desired effect

```scala
object Constants {
  opaque type Default[X] = X

  given Default[Byte] = 0
  given Default[Char] = 0
  given Default[Short] = 0
  given Default[Int] = 0
  given Default[Long] = 0
  given Default[Float] = 0
  given Default[Double] = 0
  given Default[Boolean] = false
  given Default[Unit] = ()
}

import Constants._
import annotation.targetName

def takeStep[T](step: T): Unit = println(s"step: $step")

@targetName("takeStep_implicit")
def takeStep[T](using step: Default[T]): Unit = println(s"step: $step")
```

then you can call e.g.

```scala
takeStep[Int]
takeStep[Boolean]
takeStep(BigInt(1))
```

**Comment by hmf** [comment] 2020-11-23 17:45
@prolativ thank you for the solution. I will try this with a nightly. Should I close?

**Comment by prolativ** [comment] 2020-11-24 08:23
I'm closing it. It can get reopened if you happen to somehow reproduce the error with nightly

**Closed by prolativ** 2020-11-24 08:23 UTC
Labels: itype:bug
