### ISSUE TITLE
Interacting with Java's PolymorphicSignature seems broken

### ISSUE THREAD

**Issue by oscar-broman** [lampepfl/dotty#15550] opened 2022-06-29 13:41 UTC
## Compiler version

Tried 3.1.3 and 3.2.0-RC1

## Minimized code

Since this example uses the foreign incubator API, `javaOptions` and `javacOptions` must contain `--add-modules=jdk.incubator.foreign`

```Scala
object Test {
  def main(args: Array[String]): Unit = {
    import jdk.incubator.foreign.ValueLayout.{JAVA_DOUBLE, JAVA_INT, JAVA_LONG, ADDRESS}
    import jdk.incubator.foreign.{CLinker, ResourceScope, MemorySegment, FunctionDescriptor}

    val linker = CLinker.systemCLinker()
    val strlen = linker.downcallHandle(
      linker.lookup("strlen").get(),
      FunctionDescriptor.of(JAVA_LONG, ADDRESS),
    )

    val scope = ResourceScope.newSharedScope()
    val x = MemorySegment.allocateNative(10, scope)
    x.setUtf8String(0, "Hello")
    val len = strlen.invoke(x.address())
    println(s"len = $len")
  }
}
```

## Output

```scala
[info] running (fork) Test
[error] WARNING: Using incubator modules: jdk.incubator.foreign
[error] Exception in thread "main" java.lang.IllegalCallerException: Illegal native access from: unnamed module @2c7b84de
[error] 	at java.base/jdk.internal.reflect.Reflection.ensureNativeAccess(Reflection.java:114)
[error] 	at jdk.incubator.foreign/jdk.incubator.foreign.CLinker.systemCLinker(CLinker.java:162)
[error] 	at Test$.main(Test.scala:2)
[error] 	at Test.main(Test.scala)
[error] Nonzero exit code returned from runner: 1
[error] (Compile / run) Nonzero exit code returned from runner: 1
```

## Expectation
The code should run just fine, and print `len = 5`. It works in Scala 2.

**Comment by smarter** [comment] 2022-06-29 13:42
Duplicate of https://github.com/lampepfl/dotty/issues/11332

**Closed by smarter** 2022-06-29 13:42 UTC
Labels: itype:bug, stat:needs triage
