### ISSUE TITLE
Compiler cannot unify types of a GADT (2/2)

### ISSUE THREAD

**Issue by regiskuckaertz** [lampepfl/dotty#12391] opened 2021-05-09 15:06 UTC
## Compiler version

3.0.0-RC3

## Minimized code

```Scala
enum Func[-A, +B] {
  case Double extends Func[Int, Int]
  case ToString extends Func[Float, String]
}

def runFunc[A, B](func: Func[A, B], input: A): B =
  (func, input) match {
    case (Func.Double, i) => i * 2
    case (Func.ToString, f) => f.toString
  }
```

## Output

<img width="921" alt="Screenshot 2021-05-09 at 16 05 55" src="https://user-images.githubusercontent.com/629976/117577136-778fae80-b0e0-11eb-8507-20a9e1b4a8c8.png">

## Expectation

The compiler should be able to unify input and output types depending on the case being evaluated.

**Comment by LPTK** [comment] 2021-05-10 02:50
Duplicate of https://github.com/lampepfl/dotty/issues/12390

**Closed** 2021-05-10 07:22 UTC
Labels: itype:bug
