### ISSUE TITLE
Re-implement lazy vals.

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#7140] opened 2019-08-30 12:55 UTC
- Do a prototype implementation of lazy vals along the lines of #6979. 
 - Validate its correctness.
 - Benchmark its performance.

**Comment by liufengyun** [comment] 2020-08-03 10:46
Once this is implemented, we should address one TODO in the following PR:

https://github.com/lampepfl/dotty/pull/9181/files#diff-8dc5ee2dbf11efaad4326519edfa4e45R132

The problem is that the current encoding assumes bitmap fields are non-static, thus in #9181 we cannot mark all fields of module classes as `static`.

**Comment by olsdavis** [comment] 2021-07-20 14:41
Hi, I'm currently working on this, assuming the latest scheme is in this [file](https://github.com/lampepfl/dotty/blob/master/tests/run/lazy-impl.scala), in the heading comment. Implementing it, I have realized I would need to sort a few things out (I will be referring to lines in the code I linked):

- in `case Evaluating`, why is the CAS performed on `x` instead of `_x`? I guess it's a small typo;
- in `case current: Waiting`, why is `_x` assigned to `current.awaitRelease()`, given that the latter returns `Unit`? I believe this is a trace of the first version of the [new scheme](https://github.com/lampepfl/dotty/pull/6979);
- in `case null`, how to assign the special value `NULL` to `result`, given it is of type `A`? I have assumed that `Evaluating` and `NULL` could be represented as runtime `object`s, leveraging the `AnyRef` type of `_x` like the class `Waiting` does; but maybe there is a better way to represent these states. If using `object`s isn't an issue, then maybe we could/should change `result` to an `AnyRef`.

**Comment by olsdavis** [comment] 2021-07-31 14:33
Hi, I've also noticed that `PatternMatcher` comes before `LazyVals`, so I guess I will have to express it directly with _if_ s.

**Comment by odersky** [comment] 2021-10-04 13:31
You mean for local lazy vals? I think we might need to box them, which means we have an enclosing object for them. Note that the current lazyvals implementation does the same thing.

**Comment by olsdavis** [comment] 2022-01-11 10:47
Hi, @anatoliykmetyuk. I'm back on it. 

The only issue I'm having is that I want to write this Java expression in Scala: `Class<?> c = CurrentClass.class;`. I tried using `classOf[CurrentClass]` from `Predef`, but when I try invoking it, it claims that the function takes no type parameter. I guess it is because type parameters get erased at a previous stage. So how can I refer to the class object of a symbol?

Why I am asking that, it is because the first argument of the CAS is the instance "over which" the CAS should be done. In static context, giving the class instead of an instance works.

Therefore, I also need to know how to determine whether a field is going to be "static". (So I can know what to CAS over.)

**Comment by smarter** [comment] 2022-01-11 15:18
Instead of generating a classOf tree you can use [`tpd.clsOf`](https://github.com/lampepfl/dotty/blob/1292246c9646db12391cb7e42ce951722ac7fd03/compiler/src/dotty/tools/dotc/ast/tpd.scala#L1226-L1231) which will generate the appropriate tree for the current compiler phase.

**Comment by olsdavis** [comment] 2022-02-03 10:45
All Tasty tests seem to pass. However, some `CompilationTests` fail. Namely, `i1692`.

I must say that I do not understand why it expects the results it requires. Does anyone have more knowledge about this specific test?

Basically, there is the following class:
```scala
class LazyNullable(a: => Int) {
  lazy val l0 = a // null out a
  // ...
}
```
It is instantiated with `'A'.toInt` and the test expects that 1. `l0 == 'A'.toInt` (reasonable), 2. `a` is null. The second assertion fails with my code, but why would `a` be null anyway? Is it some odd semantic of lazy vals? If so, is it needed?

**Comment by smarter** [comment] 2022-02-03 11:17
Yes, this is needed to avoid memory leaks, it's only done if a is private and the compiler is sure that it isn't used anywhere else, see the pr where this was impleemnted in dotty (scala 2 did the same before): https://github.com/lampepfl/dotty/pull/4289

**Comment by sjrd** [comment] 2022-02-03 11:18
This is needed for memory management. We should release references to `a` as soon as possible so that any memory that `a` holds on to can be reclaimed by the GC. To do that, there is an overall guarantee that:
* If there is a `private[this]` field `f`, and
* `f` is only read in the body of a `lazy val x`,
* then after `x` is computed, `f` is zeroed out (nulled out)

**Comment by olsdavis** [comment] 2022-02-07 11:15
OK, thanks a lot. I think I am almost done.

**Comment by olsdavis** [comment] 2022-02-20 14:46
Hi, so, when I last wrote I just had a few small issues with the tests, as almost all pass except for the following:

- `DottyBytecodeTests.scala` verifies whether the size of the generated bytecode is equal to some value, but I have changed the way the offset is stored to just a simple long variable. Should I re-apply the same "compression" that was applied to fix this? Even if I do so, I don't believe that the bytecode will be equal in size anyway, or should it? If not, then probably the test should be changed, I guess;
- The test `7723_1.scala` fails because of a name conflict `7721_1.scala`, in `tests/run/alpha-modules-2`. I don't believe it has anything to do with my code, but why is it so? Is it probably just a local installation issue?

Thanks in advance!

**Comment by odersky** [comment] 2022-02-20 15:30
I am not sure about the `DottyBytecodeTests` issue. What test fails, and what compression are we talking about?

The `7723_1.scala` failure is probably a local installation issue. You can try deleting all class files in your output directory, that is likely to fix the problem.

**Comment by olsdavis** [comment] 2022-02-20 22:28
A clean build did fix `7723_1.scala`, thank you.

Sorry for the lack of precision: in `DottyBytecodeTests`, the test `lazyFields` verifies that the number of instructions in the end bytecode generated by the thread-safe lazy val is equal to 94. I believe this constant should be updated, shouldn't it? (The new answer would be 126.)

I am glad to announce that the latter is actually the only test not to pass!

**Comment by odersky** [comment] 2022-02-21 09:56
> Sorry for the lack of precision: in DottyBytecodeTests, the test lazyFields verifies that the number of instructions in the end bytecode generated by the thread-safe lazy val is equal to 94. I believe this constant should be updated, shouldn't it? (The new answer would be 126.)

Yes, a difference would be expected here. The only question to ask is whether we are comfortable with the increase in code size. But that's best done by a discussion on a PR. 

Congrats and thank you for getting this far! Looking forward to see the PR.

**Comment by SethTisue** [comment] 2022-07-25 20:43
superseded by #15296

**Comment by dwijnand** [comment] 2022-07-26 10:53
This is the issue that #15296 fixes.

**Comment by SethTisue** [comment] 2022-07-26 14:53
I'm sorry, I don't know how I confused that.

**Comment by som-snytt** [comment] 2022-07-26 16:42
I'll take this opportunity to say that I totally get the confusion. I often have to pause and ask is this the issue or the PR? and I've seen others mix them up when commenting, as well.

Sorry for the O/T observation that github needs a threading model.

I want "one-stop shopping" for the comments and abandoned PRs for a topic.

To complement the threading model, I want a "needle" feature that will filter for just the current PR.

**Closed** 2022-10-29 11:18 UTC
Labels: Semester Project, stat:taken
