### ISSUE TITLE
Doctool: Extra "api" directory under target

### ISSUE THREAD

**Issue by eed3si9n** [lampepfl/dotty#11412] opened 2021-02-14 17:47 UTC
## Compiler version

3.0.0-M4-bin-20210212-0273336-NIGHTLY

## Minimized code

```Scala
package foo

final val foo = "Foo"

object A:
  /**
   * @param i An argument
   */
  def x(i:Int)=3
```

Then run `doc` from sbt 1.5.0-M2.

## Output

It creates `target/scala-3.0.0-M4/api/api` directory.
For example `target/scala-3.0.0-M4/api/api/foo/A$.html`.

## Expectation

I expect HTML files to be under `target/scala-3.0.0-M4/api/` directory. Note that the term `api` is set by sbt as `Compile/doc/target`.

See the output of Scala 2.x's output - https://scopt.github.io/scopt/4.0.0/api/index.html

Directly under `api/` it would create directory names corresponding to the package like `scopt`, and https://scopt.github.io/scopt/4.0.0/api/scopt/index.html would list the classes under `scopt` package.

**Comment by eed3si9n** [comment] 2021-02-14 18:03
cc @romanowski, @pikinier20

**Comment by pikinier20** [comment] 2021-02-23 10:11
@romanowski Maybe we should adjust our directory structure to match old scaladoc. If that is the case, we should move our resources inside `lib/` folder and move documentation to root folder. I only wonder what to do in case when there's `lib` package in project because it leads to name conflict.

**Comment by eed3si9n** [comment] 2021-02-23 13:10
Maybe you could use a reserve word like `object/`.

**Comment by abgruszecki** [comment] 2021-03-16 11:07
@eed3si9n can you clarify what exactly is the problem with having two `api` directories?

**Comment by eed3si9n** [comment] 2021-03-16 13:01
Scaladoc is meant to be published to the web. Whenever possible we should maintain the backward compatibility of the URL since these pages are often linked from Stackoverflow or documentations.

**Comment by abgruszecki** [comment] 2021-03-16 13:45
@romanowski what's our current position on full backwards link compat with old Scaladoc?

**Comment by SethTisue** [comment] 2021-09-07 22:53
did https://github.com/lampepfl/dotty/pull/13130 affect this?

**Comment by BarkingBad** [comment] 2021-09-07 23:06
I guess #13130 should have "fixed" the issue (I can confirm that and close it tomorrow). At least as long as someone doesn't run the scaladoc with `-Yapi-subdirectory` setting toggled on.

**Comment by BarkingBad** [comment] 2021-09-16 08:15
I just checked it and indeed, the default behaviour now is to skip the `api` subdirectory, unless someone provides `-Yapi-subdirectory` flag, so I guess the issue is resolved. On the other hand, you demand to have `index.html` listing members of the package. Currently, if you have package `foo.bar` the listing will be under `foo/bar.html`. I don't know if we should change it.

**Comment by pikinier20** [comment] 2022-01-10 11:46
@BarkingBad Is this issue up-to-date?

**Comment by Dedelweiss** [comment] 2023-07-17 10:03
Hello, as far as I can see from my test, the issue seems to have been corrected.

<img width="384" alt="Screenshot 2023-07-17 at 11 58 56" src="https://github.com/lampepfl/dotty/assets/44496264/8efc0322-df78-4a4c-b58b-61531f5c75b8">
<img width="219" alt="Screenshot 2023-07-17 at 11 58 49" src="https://github.com/lampepfl/dotty/assets/44496264/0552611d-1da0-4f36-89b8-409af5816fdc">
<img width="278" alt="Screenshot 2023-07-17 at 11 59 12" src="https://github.com/lampepfl/dotty/assets/44496264/f398471b-e2a3-4e14-8b98-36102617f2f4">

**Closed** 2023-07-17 10:10 UTC
Labels: itype:enhancement, area:doctool
