### ISSUE TITLE
Cannot rewrite recursive call: it targets a supertype

### ISSUE THREAD

**Issue by ohze** [lampepfl/dotty#9054] opened 2020-05-26 18:40 UTC
## Minimized code

```Scala
import scala.annotation.tailrec

trait Iterator { def hasNext: Boolean }

object Iterable {
  val i1: Iterator = ???
  val iterator = new Iterator {
    @tailrec def hasNext: Boolean =
      if (!i1.hasNext) false
      else {/* i1.next; */ hasNext}
  }
}
```

## Output

```scala
[error] 10 |      if (!i1.hasNext) false
[error]    |           ^^^^^^^^^^
[error]    |           Cannot rewrite recursive call: it targets a supertype
```

## Expectation
compile successfully as in scala 2

## Notes
+ Scala 2 compile to while/for loop:
```scala
public final class Iterable$$anon.Iterable$$anon$1 implements Iterator {
    public boolean hasNext() {
        while($outer.Iterable$$i1.hasNext()) ;
        return false;
    }
    private final Iterable $outer;
...
```
+ When I remove the `@tailrec`, dotty also compile to while/for loop:
```scala
private static final class Iterable$$anon$1 implements Iterator {
  private final Iterable $outer;

  public boolean hasNext() {
      for (Iterator iterator = (Iterator)this; iterator.Iterable$_$$anon$$$outer().Iterable$$i1.hasNext(); iterator = iterator) {}
      return false;
  }
...
```
It means that dotty can get rid of all calls to the method. So it should NOT throw compile errors when we add `@tailrec`?
+ Real code from akka: [Collections](https://github.com/akka/akka/blob/v2.6.5/akka-actor/src/main/scala/akka/util/Collections.scala#L31), [LightArrayRevolverScheduler](https://github.com/akka/akka/blob/v2.6.5/akka-actor/src/main/scala/akka/actor/LightArrayRevolverScheduler.scala#L131), [Scheduler](https://github.com/akka/akka/blob/v2.6.5/akka-actor/src/main/scala/akka/actor/Scheduler.scala#L102), and [Mailbox](https://github.com/akka/akka/blob/v2.6.5/akka-actor/src/main/scala/akka/dispatch/Mailbox.scala#L959)

**Comment by smarter** [comment] 2020-05-26 18:46
Both dotty and scalac do not rewrite the recursive call `i1.hasNext`. I think it's reasonable for `@tailrec` to tell you when this happen, and so I would just remove `@tailrec` from the method call.

**Comment by giabao** [comment] 2020-05-26 19:42
I think only the second `hasNext` call (in `else` clause) is recursive.
Or not? 😁

**Comment by smarter** [comment] 2020-05-26 19:47
To be precise, we don't know statically whether it's a recursive call to the same `hasNext` method or not, it depends on the runtime class of `i1`, so `@tailrec` conservatively disallows it.

**Comment by smarter** [comment] 2020-05-26 19:50
Note that `@tailrec` does not require recursive calls to be on the same class instance, for example this is valid:
```scala
  @tailrec
  final def foo(cond: Boolean, that: Test): Boolean =
    if (cond)
      that.foo(!cond, this)
    else
      cond
```
The call to `that.foo` is considered to be a recursive call to `foo` with a different receiver.

**Comment by smarter** [comment] 2020-05-27 11:22
Closing as "working as intended"

**Closed by smarter** 2020-05-27 11:22 UTC
Labels: itype:bug
