### ISSUE TITLE
Compiler changes method signature leading to errors elsewhere

### ISSUE THREAD

**Issue by elfprince13** [lampepfl/dotty#10824] opened 2020-12-16 22:26 UTC
Problem occurs on at least 3.0.0-M2 and 3.0.0-M3. MWE minimized from code which previously worked fine in both Scala 2.12 and Dotty 0.12.0-RC1. It appears both that an `|` is being converted to an `&` and that type parameters are being lost.

## Minimized code

```Scala
trait BNode[DNode <: BNode[DNode]] {}

object MWE {
  sealed trait Status[+T]
  sealed trait Unsuccessful extends Status[Nothing] {}
  case class Succeeded[DNode <: BNode[DNode], +T] (read:T,from:DNode) extends Status[T] { }
  case object Failed extends Unsuccessful {}

  def main(args:Array[String]):Unit = {
    class MyNode extends BNode[MyNode] {}
    def read(node:MyNode):MyNode = { node }
    def success(proof:Succeeded[MyNode, MyNode]) = Console.println("yay")

    val node = new MyNode
    val mwe = new MWE[MyNode]
    mwe(node) match {
      case Failed => Console.println("sad")
      case s@Succeeded(_,_) => success(s) 
    }
  }
}

class MWE[DNode <: BNode[DNode]] {
  def apply(dNode:DNode):(MWE.Unsuccessful | MWE.Succeeded[DNode, DNode]) = MWE.Succeeded(dNode,dNode)
}

```

## Output

```scala
[error] -- [E007] Type Mismatch Error: src/main/scala/MWE.scala:20:39
[error] 20 |      case s@Succeeded(_,_) => success(s)
[error]    |                                       ^
[error]    |Found:    (s : MWE.Unsuccessful & MWE.Succeeded[DNode$1, Any]
[error]    |
[error]    | MWE.Succeeded[MyNode, MyNode] &
[error]    | MWE.Succeeded[DNode$1, Any]
[error]    |)
[error]    |Required: MWE.Succeeded[MyNode, MyNode]
[error]    |
[error]    |where:    DNode$1 is a type in method main with bounds <: BNode[LazyRef(DNode)]
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

## Expectation

`mwe(node` should have type `MWE.Unsuccessful | MWE.Succeeded[MyNode,MNode]` and `s` should have type `MWE.Succeeded[MyNode, MyNode]`.

**Comment by elfprince13** [comment] 2020-12-16 22:35
If I add an `.asInstanceOf` invocation to try and coerce `s` to the right type:
```Scala
case s@Succeeded(_,_) => success(s.asInstanceOf[Succeeded[MyNode,MyNode]])
```

I instead get this error:
```Scala
[error] -- [E057] Type Mismatch Error: src/main/scala/MWE.scala:20:22
[error] 20 |      case s@Succeeded(_,_) => success(s.asInstanceOf[Succeeded[MyNode,MyNode]])
[error]    |                      ^
[error]    |Type argument DNode$1 does not conform to upper bound BNode[LazyRef(DNode$1)]
```

**Comment by smarter** [comment] 2020-12-16 23:20
>  It appears both that an | is being converted to an &

That's not what's happening here, the type of the scrutinee (the thing being matched on) is `MWE.Unsuccessful | MWE.Succeeded[MyNode, MyNode]`, the type of the case being matched is `Succeeded[DNode$1, Any`, so the type of `s` is the intersection of both of these types, this intersection is distributed in each part of the union, for some reason there's a `|` missing in the error message you posted, but I tried it locally and it printed correctly:
```scala
   |Found:    (s : MWE.Unsuccessful & MWE.Succeeded[DNode$1, Any] |
   |  MWE.Succeeded[MyNode, MyNode]
   | & MWE.Succeeded[DNode$1, Any])
   |Required: MWE.Succeeded[MyNode, MyNode]
```

So the failure comes from the compiler not being able to equal the `DNode$1` fresh type variable it generated with `MyNode`. The problem goes away if we give a more precise result type to MWE#apply:
```scala
class MWE[DNode <: BNode[DNode]] {
  def apply(dNode:DNode): MWE.Succeeded[DNode, DNode] = MWE.Succeeded(dNode,dNode)
}
```
We can also keep the union but replace `Unsuccessful` by its sole member:
```scala
class MWE[DNode <: BNode[DNode]] {
  def apply(dNode:DNode):(MWE.Failed.type | MWE.Succeeded[DNode, DNode]) = MWE.Succeeded(dNode,dNode)
}
```

The testcase can be simplified to avoid F-bounds (and thus headaches) while still reproducing the problem:
```scala
object MWE {
  sealed trait Status[+T]
  sealed trait Unsuccessful extends Status[Nothing] {}
  case class Succeeded[+T](read: T) extends Status[T] { }
  case object Failed extends Unsuccessful {}

  def main(args:Array[String]):Unit = {
    class MyNode
    def success(proof: Succeeded[MyNode]) = Console.println("yay")

    val node = new MyNode
    val mwe = new MWE[MyNode]
    mwe(node) match {
      case Failed => Console.println("sad")
      case s @ Succeeded(_) => success(s) 
    }
  }
}

class MWE[DNode] {
  def apply(dNode: DNode): MWE.Succeeded[DNode] | MWE.Unsuccessful = MWE.Succeeded(dNode)
}
```

So essentially the problem is that given:
```scala
Succeeded[DNode$1] <:< Succeeded[MyNode] | MWE.Unsuccessful 
```
We cannot deduce:
```scala
DNode$1 =: MyNode
```
But that would be really tricky for the compiler to do: this is only true because `Succeeded` and `Unsuccessful` are disjoint, but proving that requires enumerating all children of `Unsuccessful` which is a pretty elaborate thing to do in the middle of a subtype check. Given that there are alternative ways to write the code which don't run into this issue, I'm going to close this as "won't fix" (but open to discussion if people disagree).

**Closed by smarter** 2020-12-16 23:20 UTC
Labels: itype:bug

**Comment by smarter** [comment] 2020-12-16 23:22
(the fact that it worked fine previous compiler versions is very likely due to soundness holes in these compilers and not better reasoning on their part).

**Comment by elfprince13** [comment] 2020-12-17 00:32
Three thoughts here:
- “this is a pretty elaborate thing to do” seems at odds with the
philosophy of using sealed traits to improve exhaustiveness checking.
- Would I have gotten different results if Succeeded were final and thus
provably not subclassed elsewhere with Unsuccessful?
- At minimum an error message saying “we didn’t implement a full subtype
check here for compiler performance reasons. Try this other pattern instead
to exercise a different code path in the compiler” seems in order when the
compiler is getting results that are clearly at odds with what a human can
see.
-- 
~Thomas

**Comment by smarter** [comment] 2020-12-17 00:44
> Would I have gotten different results if Succeeded were final and thus provably not subclassed elsewhere with Unsuccessful?

Just tried it and that seems to also fix the problem, nice!

Concerning your other points, it's worth keeping in mind that the compiler easily goes through millions of subtyping checks in any given program, thus we can't make them arbitrarily complicated and must accept some level of incompleteness, tracing back a specific error to a specific decision taken in a subtype check to give a better error message would be extremely hard (my guess is the error would be just as likely to be misleading as useful), but it's an interesting reseach problem if someone is looking for a PhD topic I guess :) (in fact, some prior art comes to mind: https://infoscience.epfl.ch/record/214757)
