### ISSUE TITLE
Error 404 when accessing the source code via the documentation

### ISSUE THREAD

**Issue by hamzaremmal** [lampepfl/dotty#17534] opened 2023-05-18 12:37 UTC
When accessing the source file of a class/trait/object in https://www.scala-lang.org/api/3.2.2, an error 404 (page not found) is triggered. 

For example, when trying to access the source code of [`Array`](https://www.scala-lang.org/files/archive/api/3.2.2/scala/Array.html#),

![lamp-dotty-source-bug](https://github.com/lampepfl/dotty/assets/56235032/6ef4a5cd-d26e-4e91-8bd9-4fc1a3a8f696)

the link redirects to https://github.com/lampepfl/dotty/blob/3.2.2/out/bootstrap/stdlib-bootstrapped/scala-3.2.1-bin-SNAPSHOT-nonbootstrapped/src_managed/main/scala-library-src/scala/Array.scala#L658

ℹ️ It seems that this error happens for all the classes/traits/objects not only `Array`

**Comment by spamegg1** [comment] 2023-05-18 13:28
See #15689

**Comment by julienrf** [comment] 2023-05-25 15:27
Duplicate of #15689

**Closed by julienrf** 2023-05-25 15:27 UTC
Labels: itype:bug, area:doctool
