### ISSUE TITLE
No generic signature emitted for def in object

### ISSUE THREAD

**Issue by ohze** [lampepfl/dotty#8631] opened 2020-03-29 19:13 UTC
## minimized code
+ scala
```Scala
import java.util.function.{Function => JFunction}

class Behavior[T]
class BehaviorBuilder[T] {
  def onMessage(handler: JFunction[T, Behavior[T]]): BehaviorBuilder[T] = ???
}
object Behaviors {
  def same[T]: Behavior[T] = ???
}
```
+ BehaviorTestKitTest.java
```java
class BehaviorTestKitTest {
    static class X {
        void foo(){}
    }
    void test() {
        BehaviorBuilder<X> b = null;
        b.onMessage(
            x -> {
                x.foo();
                return Behaviors.same();
            })
        .onMessage(
            x -> {
                x.foo(); // error here
                return Behaviors.same();
            });
    }
}
```
## Compilation output

```scala
[error] /dotty-example/src/main/java/BehaviorTestKitTest.java:14:1: cannot find symbol
[error]   symbol:   method foo()
[error]   location: variable x of type java.lang.Object
[error] x.foo
[info] /dotty-example/src/main/java/BehaviorTestKitTest.java: /dotty-example/src/main/java/BehaviorTestKitTest.java uses unchecked or unsafe operations.
```

## expectation
compile successfully as in scala 2

## inspect
Decompile Behaviors.class using Procyon v0.5.36:
+ dotty's output:
```java
public final class Behaviors {
    public static Behavior same() {
        return Behaviors$.MODULE$.same();
    }
}
```
+ scala 2.13.1 output:
```java
public final class Behaviors {
    public static <T> Behavior<T> same() {
        return Behaviors$.MODULE$.same();
    }
}
```
Notice the lack of generic signature on `same()` method.

maybe relate: #6350

**Comment by odersky** [comment] 2020-04-05 10:43
The issue here is that the Dotty backend does not demand a generic signature for forwarders. Both scalac and dotc generate a static signature for `same` in the object class `Bahavior$`. But only scalac generates a static signature for the stati forwarder of `same` in class `Bahavior`. 

I verified that the `BCode` backend simply never makes the call to demand a signature for the forwarder. Hopefully this will be fixed once we switch to scalac's backend. Assigning to @lrytz for tracking this.

**Comment by smarter** [comment] 2020-11-16 22:54
Closing as a duplicate of #10347 where I provided a workaround: https://github.com/lampepfl/dotty/issues/10347#issuecomment-728355975

**Closed by smarter** 2020-11-16 22:54 UTC
Labels: compat:java, itype:bug
