### ISSUE TITLE
`-Wunused:all` and higher kinded type type parameter

### ISSUE THREAD

**Issue by amumurst** [lampepfl/dotty#16681] opened 2023-01-13 12:30 UTC
I tried adding the new unused flag (from https://github.com/lampepfl/dotty/pull/16157) to my work codebase and was surprised that it warned about unused import when used with the `cats` libraries IO type. A minimal reproducer independent of cats is below.

## Compiler version
With nightly: `3.3.0-RC1-bin-20230112-be10bc6-NIGHTLY`

## Minimized code
```scala
//> using scala "3.3.0-RC1-bin-20230112-be10bc6-NIGHTLY"
//> using option "-Wunused:all"

object myPackage:
   case class HKT[A](a: A)

trait Thing[F[_]]
import myPackage.HKT
val x = new Thing[HKT]{}
```

## Output

```scala
[warn] ./unused-higher-order-type-param.sc:8:18: unused import
[warn] import myPackage.HKT
[warn]                  ^^^
```

## Expectation
HKT is used as the instance of F in Thing, and hence should not be reported as unused.

**Comment by szymon-rd** [comment] 2023-01-13 12:32
Thank you for reporting all these errors! We will promptly address them :)

**Comment by amumurst** [comment] 2023-01-13 12:34
No worries, I am working my way through the app hacking around them for now, happy to help out 👍

**Comment by cb372** [comment] 2023-01-13 12:51
I beat you to this one by a few minutes 😄 

This is the same issue as #16680

**Comment by dwijnand** [comment] 2023-01-13 15:39
Duplicate of #16680

**Closed by dwijnand** 2023-01-13 15:39 UTC
Labels: itype:bug, area:reporting
