### ISSUE TITLE
Error appears randomly over REPL Sessions

### ISSUE THREAD

**Issue by cruiztorresj** [lampepfl/dotty#16897] opened 2023-02-12 20:44 UTC
## Scala code runner version 3.2.1 -- Copyright 2002-2022, LAMP/EPFL

The following error appears randomly[1], so I am not sure you actually will be able to reproduce it.

## Minimized code

```Scala
scala> val arreglo: Array[Int] = Array(1, 2, 3, 4, 3, 2, 1)
scala> arreglo.sortWith(_ < _)
scala> val (sorted1: Array[Int], sorted2: Array[Int]) = arreglo.sortWith(_ < _).splitAt(arreglo.length / 2)
```

## Output

```scala
Bad symbolic reference. A signature
refers to JFunction2$mcZII$sp/T in package scala.runtime.java8 which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling the signature.
1 error found
```

## Expectation
No error should be happening.

## Underlying System Info.
The Scala REPL is running on top of Java 17 over a Windows Subsystem for Linux 2 (WSL2) installation.

```Scala
Welcome to Scala 3.2.1 (17.0.5, Java Java HotSpot(TM) 64-Bit Server VM).
```
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
```
[1]
![RandomErrorInREPL](https://user-images.githubusercontent.com/75508473/218336031-48d1b580-9d75-4970-a2de-7bd98a135320.png)

Thanks.

--
Caleb

**Comment by smarter** [comment] 2023-02-12 22:13
Duplicate of https://github.com/lampepfl/dotty/issues/15562, would you mind posting the content of your issue as a comment there? It could help track down the root cause.

**Closed by smarter** 2023-02-12 22:13 UTC
Labels: itype:bug, stat:needs triage
