### ISSUE TITLE
Implicit conversion failing with implicit class and def in same scope.

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#1382] opened 2016-07-11 15:15 UTC
``` scala
dotty>  class Foo(n: Int) {
           def foo(p: => Foo): Foo = new Foo(1)
           override def toString(): String = "Foo" + n
         } 
defined class Foo

dotty>   implicit def bool2Foo(b: Boolean): Foo = new Foo(2) 
dotty>   implicit class ExtendedBoolean(b: => Boolean) {
           def foo(p: => Foo): Foo = new Foo(2)
         } 
defined class ExtendedBoolean
dotty>   true.foo(true) 
       ^
  true.foo(true)
<console>:30: error: foo is not a member of Boolean(true)
```

``` scala
scala>   class Foo(n: Int) {
     |     def foo(p: => Foo): Foo = new Foo(1)
     |     override def toString(): String = "Foo" + n
     |   }
defined class Foo

scala>   implicit def bool2Foo(b: Boolean): Foo = new Foo(2)
bool2Foo: (b: Boolean)Foo

scala>   implicit class ExtendedBoolean(b: => Boolean) {
     |     def foo(p: => Foo): Foo = new Foo(2)
     |   }
defined class ExtendedBoolean

scala>   true.foo(true)
res0: Foo = Foo1
```

**Comment by odersky** [comment] 2016-07-14 08:43
Can you add a self-contained file please? That makes it easier to reproduce the issue and will serve as a test case once it is fixed.

**Comment by odersky** [comment] 2016-07-14 08:51
scalac succeeds here because of a quirk: The implicit class takes a `=> Boolean` as parameter, not a `Boolean`. It seems plain `Boolean`s are searched before `=> Boolean`s. But I would classify this is as an irregularity of scalac, nit a feature. Our rewrite tool should be able to address this by adding the implicit conversion explicitly. Closing for that reason.

**Comment by nicolasstucki** [comment] 2016-07-14 10:53
Here is a self-contained version of the code.
```scala
object Bar {
  class Foo {
    def foo(p: => Foo): Foo = new Foo
  }

  implicit def bool2Foo(b: Boolean): Foo = new Foo

  implicit class ExtendedBoolean(b: => Boolean) {
    def foo(p: => Foo): Foo = new Foo
  }

  true.foo(true)
}
```

**Comment by smarter** [comment] 2018-03-23 22:36
Closing since we explicitly don't want to imitate scalac behavior.

**Closed by smarter** 2018-03-23 22:36 UTC
Labels: area:rewriting tool
