### ISSUE TITLE
Inline match does not work on `List`

### ISSUE THREAD

**Issue by jto** [lampepfl/dotty#8103] opened 2020-01-27 16:35 UTC
The following example was tested in a worksheet, created from `dotty-example-project` (commit `b135f5a`) and Dotty `0.21.0-RC1`

## minimized code

```Scala
inline def test(cs: List[Int]) <: Any =
  inline cs match
    case 1 :: Nil => 1
    case _ => scala.compiletime.error("Not one")

test(List(1)) // compilation error ("Not one")
```
## expectation

in the given example, the first case should be matched and the value `1` of type `1` should be inlined.

**Comment by nicolasstucki** [comment] 2020-01-27 17:43
It would require an `inline` parameter (see #8060). Also removing the default case helps to see the term that is not reduced.
```scala
class Test {
  inline def test(inline cs: List[Int]) <: Any =
    inline cs match
      case 1 :: Nil => 1

  test(1 :: Nil)
  test(List(1))
}
```

```
-- Error: i8103.scala:6:6 ------------------------------------------------------
6 |  test(1 :: Nil)
  |  ^^^^^^^^^^^^^^
  |  cannot reduce inline match with
  |   scrutinee:  {
  |    Nil.::[Int](1)
  |  } : List[Int]
  |   patterns :  case ::.unapply[Int](1, Nil):::[Int]
```

**Comment by nicolasstucki** [comment] 2020-01-27 17:48
See https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/typer/Inliner.scala#L842

**Comment by jto** [comment] 2020-01-28 09:16
Hi @nicolasstucki,
Thanks for your reply :)
Looking forward to test `inline` params!

**Comment by odersky** [comment] 2020-01-29 10:24
Should we close this?

**Comment by jto** [comment] 2020-01-29 10:48
I just tested on master and it seems to still fail :(

```scala
scala> class Test {
     |   inline def test(inline cs: List[Int]) <: Any =
     |     inline cs match
     |       case 1 :: Nil => 1
     |
     |   test(1 :: Nil)
     |   test(List(1))
     | }
6 |  test(1 :: Nil)
  |  ^^^^^^^^^^^^^^
  |  cannot reduce inline match with
  |   scrutinee:  {
  |    Nil.::[Int](1)
  |  } : List[Int]
  |   patterns :  case ::.unapply[Int](1, Nil):::[Int]
  | This location contains code that was inlined from rs$line$1:3

```

Am I missing something ?

**Comment by AleksanderBG** [comment] 2020-01-29 10:57
If I remember correctly, all inline pattern matching works based on scrutinee type, not the "shape" of the argument. Here the type of the scrutinee is `List[Int]`, so a pattern for `::` won't match.

**Comment by jto** [comment] 2020-01-29 12:31
@AleksanderBG I don't understand what you mean by `pattern matching works based on scrutinee type`. Could you explain how would you rewrite the example ?

**Comment by AleksanderBG** [comment] 2020-01-29 15:12
@jto to make it work, you mean? The below code works:

```scala
scala> class Test {                                                                                                                                                                                                
     |   inline def test(inline cs: List[Int]) <: Any =
     |     inline cs match
     |       case 1 :: _ => 1
     | 
     |   val i: 1 = test(new ::[1](1, Nil))
     | }
// defined class Test
```

And so does the following:
```scala
scala> class Test {                                                                                                                                                                                                
     |   inline def test(inline cs: List[Int]) <: Any =
     |     inline cs match
     |       case _ :: _ => 1
     | 
     |   val i: 1 = test(new ::(1, Nil))
     | }
// defined class Test
```

But neither of the below:

```scala
scala> class Test {                                                                                                                                                                                                
     |   inline def test(inline cs: List[Int]) <: Any =
     |     inline cs match
     |       case _ :: Nil => 1
     | 
     |   val i: 1 = test(new ::(1, Nil))
     | }
6 |  val i: 1 = test(new ::(1, Nil))
  |             ^^^^^^^^^^^^^^^^^^^^
  |             cannot reduce inline match with
  |              scrutinee:  {
  |               new ::[Int](1, Nil)
  |             } : ::[Int]
  |              patterns :  case ::.unapply[Int](_, Nil):::[Int]
  | This location contains code that was inlined from rs$line$3:3

scala> class Test {                                                                                                                                                                                                
     |   inline def test(inline cs: List[Int]) <: Any =
     |     inline cs match
     |       case 1 :: _ => 1
     | 
     |   val i: 1 = test(new ::(1, Nil))
     | }
6 |  val i: 1 = test(new ::(1, Nil))
  |             ^^^^^^^^^^^^^^^^^^^^
  |             cannot reduce inline match with
  |              scrutinee:  {
  |               new ::[Int](1, Nil)
  |             } : ::[Int]
  |              patterns :  case ::.unapply[Int](1, _):::[Int]
  | This location contains code that was inlined from rs$line$3:3
```

It's clear to us that inline patmat semantics are a bit confusing, but it's just that no one got to improving this part yet.

**Comment by jto** [comment] 2020-01-29 15:29
Okay I understand now. Thanks for the examples.

**Comment by AleksanderBG** [comment] 2020-03-23 08:36
Closing as a duplicate of #6781.

**Closed** 2020-03-23 08:38 UTC
Labels: area:inlining, itype:enhancement
