### ISSUE TITLE
pass Array to scala 2 method causes ClassCastException

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#12202] opened 2021-04-23 10:55 UTC
## Compiler version

3.0.0-RC2

## Minimized code

```Scala
// compile with Scala 2.13.5
package scala2Erasure

class Z {
  def foo(x: Array[Array[_ <: AnyVal] with Int]): Unit = {}
}
```

```Scala
// compile with Scala 3.0.0-RC2
@main def Test =
  val z = new scala2Erasure.Z
  z.foo(new Array(0))
```

## Output

```scala
java.lang.ClassCastException: [I cannot be cast to [Ljava.lang.Object;
```

## Expectation
no error.

## Notes
the descriptor of `scala2Erasure.Z.foo` is `([[Ljava/lang/Object)V`, if scala 3 compiles `Z` then it is `([I)V`

**Comment by odersky** [comment] 2021-04-23 11:15
I verified this is fixed in master. Can you add a regression test please?

**Comment by smarter** [comment] 2021-04-23 11:28
This doesn't appear to be fixed in master, but I investigated and it turns out that the way Scala 2 erases intersections involving Arrays is incorrect and leads to CCE in Scala 2, so there's nothing we can do here until Scala 2 is fixed: https://github.com/scala/bug/issues/12381

**Comment by smarter** [comment] 2021-04-23 11:28
To be precise: the way we erase these intersections is the way Scala 2 should erase them, so once https://github.com/scala/bug/issues/12381 is fixed we shouldn't have to do anything.

**Closed by smarter** 2021-04-23 11:28 UTC
Labels: compat:scala2, itype:bug
