### ISSUE TITLE
DuplicateBind error triggered by same variable name in alternative pattern

### ISSUE THREAD

**Issue by ShaneDelmore** [lampepfl/dotty#1612] opened 2016-10-18 20:31 UTC
I believe the issue is in Typer.transform.  Here is an example snippet and output:

```
object Test {
  def g(p:(Int,Int)) = p match {
    case (10,n) | (n,10) => println(n) 
    case _ => println("nope")
  }
}
```

On compile this error is returned:

```
-- [E005] Naming Error: test.scala -------------------------------------------------------------------------------------
9 |    case (10,n) | (n,10) => println(n)
  |                   ^
  |                   duplicate pattern variable: `n`

longer explanation available when compiling with `-explain`
```

**Comment by ShaneDelmore** [comment] 2016-10-18 20:32
Tagging @DarkDimius and @liufengyun at @felixmulder request.

**Comment by odersky** [comment] 2016-10-19 19:02
There's clearly an error here, but not the one that's flagged. scalac says:

error: illegal variable in pattern alternative

**Comment by ShaneDelmore** [comment] 2016-10-25 00:46
@odersky This is actually how I found this bug, I was attempting to improve the error message for "illegal variable in pattern alternative" and found I could not trigger the error message in Dotty as I could in Scala.

**Comment by odersky** [comment] 2016-10-25 07:25
@ShaneDelmore You want to give it a try to add the error message? I believe it should be in Typer. The thing to watch out for are Bind nodes that bind a name other than `_` inside Alternative nodes. 
Maybe add a Mode bit that we are inside an alternative that gets tested in the Bind node?

**Comment by ShaneDelmore** [comment] 2016-10-25 19:16
I will take a look at it this weekend and see if I can make any headway on it.

**Comment by ShaneDelmore** [comment] 2016-11-07 17:28
I started looking into this bug last weekend and think I should be able to come up with a fix.  Besides the error message, is there any reason not to just allow multiple variable bindings if they exist in every alternative with the same name and same type?

**Comment by felixmulder** [comment] 2016-11-09 11:22
This sounds like a judgement call for @odersky, the spec doesn't specifically prohibit this. It might make the desugaring inside `PatternMatcher` harder - unclear.

**Comment by odersky** [comment] 2017-11-01 18:15
Duplicate of #3332.

**Closed by odersky** 2017-11-01 18:15 UTC
Labels: area:typer, exp:intermediate, itype:bug, prio:medium
