### ISSUE TITLE
GADT type unification 

### ISSUE THREAD

**Issue by erdeszt** [lampepfl/dotty#13743] opened 2021-10-13 20:01 UTC
## Compiler version

`3.0.1`

## Minimized code

```Scala
// Dependencies:
"org.atnos" %% "eff" % "5.20.0",
"org.atnos" %% "eff-doobie" % "5.20.0",
"org.tpolecat" %% "doobie-core" % "1.0.0-RC1",
```

```Scala
package superduper

import doobie.syntax.string.*
import org.atnos.eff.*
import org.atnos.eff.addon.doobie.connectionio.*
import org.atnos.eff.interpret.*

final case class Issue()

sealed trait Storage[+A]
final case class GetIssues() extends Storage[List[Issue]]

def evalStorage[R, U, A](effect: Eff[R, A])(using Member.Aux[Storage, R, U], _connectionIO[U]): Eff[U, A] =
  translate(effect)(new Translate[Storage, U] {
    override def apply[X](op: Storage[X]): Eff[U, X] =
      op match
        case GetIssues() => fromConnectionIO(sql"select * from issue".query[Issue].to[List].map(identity))
  })
```

## Output

The above code works fine but if I remove the `.map(identity)` part I get:

```scala
[error] -- [E007] Type Mismatch Error: E:\Documents\dev\superduper\src\main\scala\superduper\Storage.scala:22:47
[error] 22 |          case GetIssues() => fromConnectionIO(sql"select * from issue".query[Issue].to[List]) // .map(identity))
[error]    |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Found:    doobie.free.connection.ConnectionIO[List[superduper.Issue]]
[error]    |Required: doobie.free.connection.ConnectionIO[X]
[error]    |
[error]    |where:    X is a type in method apply with bounds >: List[superduper.Issue]
[error] one error found
```

## Expectation

I expected the code to work without the `.map(identity)` part.

Edit: I was looking through the old bug tracker and noticed an issue that might be related: https://github.com/scala/bug/issues/10208 I think it might be an issue with HK types as well because `ConnectionIO[A]` is just ` Free[ConnectionOp, A]` and the first type argument of `Free` is higher kinded and I don't get this issue (the need for `.map(identity)`) when I interpret into a simpler type like `IO` from `cats-effec`.

**Comment by smarter** [comment] 2021-10-13 20:12
I believe the compiler is correct here, you constructed a `ConnectionIO[List[Issue]]`, and you need a `CollectionIO[X]` where the compiler only knows that `X >: List[Issue]`. We can't assume that `X =:= List[Issue]` because `Storage` has a covariant type parameter, so you could pass `GetIssues: Storage[Any]` as an argument for example. If `ConnectionIO` was itself covariant that would be fine, but it isn't (I don't know if there's any deep reason for that /cc @tpolecat), however it's a Functor so I believe you can write `.widen` instead of `.map(identity)`

**Comment by smarter** [comment] 2021-10-13 20:14
> I don't get this issue (the need for .map(identity)) when I interpret into a simpler type like IO from cats-effec

That's because cats-effect IO is covariant: https://github.com/typelevel/cats-effect/blob/5dde92ed39b6f3e265d00570f3169d85f46045fb/core/shared/src/main/scala/cats/effect/IO.scala#L102

Based on this and the previous commit I'll close this as working as intended.

**Closed as completed by smarter** 2021-10-13 20:14 UTC
Labels: itype:bug
