### ISSUE TITLE
Pattern matching reports cycle unless nested in object

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#8645] opened 2020-03-31 22:39 UTC
## Minimized code
Compiles:
```Scala
case class :>[+A, +B]()

object nested:
  type Foo[X] = X match
    case prev :> last =>
      Baz[prev, last]
    case _ =>
      Int

  type Baz[API, Next] = API match
    case prev :> last =>
      last match
        case Int =>
          Baz[prev, Int => Next]
    case Int =>
      Next
```

Does not compile:
```scala
case class :>[+A, +B]()

type Foo[X] = X match
  case prev :> last =>
    Baz[prev, last]
  case _ =>
    Int

type Baz[API, Next] = API match
  case prev :> last =>
    last match
      case Int =>
        Baz[prev, Int => Next]
  case Int =>
    Next
```

## Output

```scala
[error] -- [E046] Cyclic Error: /Users/fixel/.src/slave/src/main/scala/Serviteur/API.scala:60:4
[error] 60 |    Baz[prev, last]
[error]    |    ^
[error]    |    Cyclic reference involving type Baz
```

**Comment by OlivierBlanvillain** [comment] 2020-04-01 11:38
Duplicate of #6362

**Closed by OlivierBlanvillain** 2020-04-01 11:38 UTC
Labels: itype:bug
