### ISSUE TITLE
Classes can't have unit fields?

### ISSUE THREAD

**Issue by travisbrown** [lampepfl/dotty#8036] opened 2020-01-19 16:53 UTC
## minimized code

```Scala
class UnitClass(val x: Unit)

object Test {
  def main(args: Array[String]): Unit = {
    println(new UnitClass(()))
  }
}
```

<details>
<summary>Compiles but fails at runtime</summary>

```scala
Exception in thread "main" java.lang.NoSuchFieldError: UnitClass.x
	at UnitClass.<init>(Test.scala:1)
	at Test$.main(Test.scala:5)
	at Test.main(Test.scala)
```
</details>

## expectation

It works fine on Scala 2. It also works fine if you change the `Unit` to e.g. `Int` or `String`.

**Comment by travisbrown** [comment] 2020-01-19 17:07
FWIW this isn't from the Cats tests but is something I ran into while trying to minimize the issue in #8035.

**Comment by smarter** [comment] 2020-01-19 17:11
Duplicate of https://github.com/lampepfl/dotty/issues/6987

**Closed by smarter** 2020-01-19 17:11 UTC
Labels: itype:bug

**Comment by travisbrown** [comment] 2020-01-19 17:21
Oh, thanks, I should have looked more closely.
