### ISSUE TITLE
Dotty website has no theme

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#8136] opened 2020-01-30 10:02 UTC

**Comment by nicolasstucki** [comment] 2020-01-30 10:03
Duplicate of #8133 (which is fixed).

Waiting for https://dotty-ci.epfl.ch/lampepfl/dotty/3943 to finish and republish.

**Comment by anatoliykmetyuk** [comment] 2020-01-30 10:55
Already works

**Closed by anatoliykmetyuk** 2020-01-30 10:55 UTC
Labels: area:documentation, itype:bug, stat:fix available
