### ISSUE TITLE
Bridge generation error for AnyVal classes

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#14009] opened 2021-11-27 23:16 UTC
## Compiler version

3.1.0
## Minimized code

```Scala
class Nullable[A](val value: A | Null) extends AnyVal

def f[A] = {
  new (Nullable[A] => A | Null) {
    def apply(nullable: Nullable[A]) = nullable.value
  }
}
```

## Output

```scala
bridge generated for member method apply(nullable: Playground.Nullable[A]): A | Null in anonymous class Object with Function1 {...}
which overrides method apply(v1: T1): R in trait Function1
clashes with definition of the member itself; both have erased type (nullable: Object): Object."
```

## Expectation

It should compile

**Comment by noti0na1** [comment] 2022-01-17 17:53
The issue is not related to explicit nulls. The same error can be triggered without the `| Null`:

```scala
class C[A](val value: A) extends AnyVal

class F[A] extends (C[A] => A):
  def apply(x: C[A]) = x.value
```

```
    |  def apply(x: C[A]) = x.value
    |      ^
    |bridge generated for member method apply(x: C[A]): A in class F
    |which overrides method apply(v1: T1): R in trait Function1
    |clashes with definition of the member itself; both have erased type (x: Object): Object."
```

@odersky @smarter Is this related to #1905 and #7023?

**Comment by smarter** [comment] 2022-01-17 18:01
Yes this is the same as https://github.com/lampepfl/dotty/issues/1905 which is an unfixable limitaiton of value classes (at least until valhalla lands), so closing as won't fix unfortunately.

**Closed by smarter** 2022-01-17 18:01 UTC
Labels: itype:bug
