### ISSUE TITLE
Self type without type ascription introduces type requirements

### ISSUE THREAD

**Issue by robmwalsh** [lampepfl/dotty#16407] opened 2022-11-24 04:41 UTC
## Compiler version
3.2.0

## Minimized code
```Scala
trait X { //missing requirement: self type Z[?] & X of trait X does not conform to self type Z[X.this.A] of required trait Z
  self: Z[?] => 
}

trait Z[A] extends X {
  self => // comment this to compile successfully
}
```

## Output

```scala
compiler error:
missing requirement: self type Z[?] & X of trait X does not conform to self type Z[X.this.A]
of required trait Z
```

## Expectation
The code should compile. Having a self type without a type ascription (i.e. just aliasing `this`) should not introduce any additional type requirements

Related comment from Aly https://discord.com/channels/632150470000902164/632150470000902166/1045191632049405992

**Comment by szymon-rd** [comment] 2022-11-25 13:52
Thank you for reporting and reproduction!

**Comment by Kordyjan** [comment] 2022-12-07 10:07
I thought it may have been fixed in #16441, but the bug is still reproducible in `3.3.0-RC1-bin-20221206-cfcdefa-NIGHTLY`.

**Comment by prolativ** [comment] 2022-12-07 11:19
It looks like `extends X` is not necessary to reproduce the problem:

```scala
trait X { //missing requirement: self type Z[?] & X of trait X does not conform to self type Z[X.this.A] of required trait Z
  self: Z[?] =>
}

trait Z[A] {
  self => // comment this to compile successfully
}
```

gives the same error message

**Comment by odersky** [comment] 2023-01-10 10:56
Scala 3 requires that self types are "closed". See #702 that introduced this requirement. Closed means: 
If class Z appears in the self type of some trait X then the self type of X must conform to the self type of Z. This example violates the condition. Z appears in the self type of X, but Z[?] does not conform to Z[A]. 

Going back to 2015, it seems the requirement was introduced to avoid a crash and to get some sanity about self type checking. I don't know whether lifting the requirement would constitute a soundness hold or not. But I believe it's better to be conservative.

**Closed** 2023-01-12 16:08 UTC
Labels: itype:bug, area:typer

**Comment by robmwalsh** [comment] 2023-01-12 18:55
Thanks for the explanation and the fix!
