### ISSUE TITLE
enum inside macro impl

### ISSUE THREAD

**Issue by rnd4222** [lampepfl/dotty#9902] opened 2020-09-28 13:26 UTC
## Minimized code

```Scala
    enum T:
      case N
      case C(i: Int, t: T)
    T.C(1, T.C(2, T.N))
```

## Output

```
[error]    |  Exception occurred while executing macro expansion.
[error]    |  java.lang.StackOverflowError
```

## Expectation
When this example is defined in a regular code, it works fine.
When used inside of a macro implementation, it causes StackOverflow.
Workaround is to replace `case N` with `case N()` or replace `enum` with a sealed trait hierarchy.

**Comment by bishabosha** [comment] 2020-09-28 13:33
reproduced in REPL with this code:
```scala
import quoted._

inline def someMacro: Any = ${ someMacroImpl }

def someMacroImpl(using QuoteContext): Expr[Any] = {
  enum T:
    case N
    case C(i: Int, t: T)
  T.C(1, T.C(2, T.N))
  '{null}
}
```
```scala
scala> someMacro                                                                                                        
1 |someMacro
  |^^^^^^^^^
  |Exception occurred while executing macro expansion.
  |java.lang.StackOverflowError
  |
  | This location contains code that was inlined from rs$line$4:1

```

**Comment by bishabosha** [comment] 2020-09-28 13:36
this is due to a local enum in a method:

```scala
def foo: Any = {
   enum T:
     case N
     case C(i: Int, t: T)
   T.C(1, T.C(2, T.N))
   null
 }
```
this has an infinite loop in the construction of `object T`

**Comment by bishabosha** [comment] 2020-09-28 13:41
this is already fixed in https://github.com/lampepfl/dotty/pull/9677

**Closed** 2020-09-28 13:43 UTC
Labels: itype:bug
