### ISSUE TITLE
Variance checking for higher-kinded types

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#5100] opened 2018-09-13 07:05 UTC
Variance is currently not checked in higher-kinded types. The following lines should all give an error but don't:
```scala
  type F[-X] = X => X
  type G[+X] = X => X
  type H = [-X] => X => X
  type I = [+X] => X => X
```

**Comment by smarter** [comment] 2018-09-13 15:28
Duplicate of https://github.com/lampepfl/dotty/issues/1252

**Closed by smarter** 2018-09-13 15:28 UTC
