### ISSUE TITLE
intermediate abstract trait in ADT  hierarchy break generation of Mirror.sumOf. during derivation

### ISSUE THREAD

**Issue by rssh** [lampepfl/dotty#11177] opened 2021-01-20 10:32 UTC
## Minimized code

```Scala
package x

import scala.compiletime._
import scala.deriving._


trait Printer[T]  {

  def print(data:T): String

}

object Printer {

 inline def summonAll[T <: Tuple]: List[Printer[?]] =
    inline erasedValue[T] match
      case _: EmptyTuple => Nil
      case _: (head *: tail) => summonInline[Printer[head]]::summonAll[tail]

 inline given derived[T](using m: Mirror.SumOf[T]): Printer[T] =
     val elemInstances = summonAll[m.MirroredElemTypes].toIndexedSeq
     new Printer[T]:
       def print(t:T): String  =
          elemInstances(m.ordinal(t)).asInstanceOf[Printer[Any]].print(t)


}
extension [T](t:T)(using Printer[T])
   def print(): String =
     summon[Printer[T]].print(t)


sealed trait Base

sealed trait A extends Base
case object A extends A
//works:
//case object A extends Base

case class B(data: String)  extends Base

given Printer[Base] = Printer.derived

given Printer[A] with
   def print(a:A) = "a"

//works:
//given aPrinter:Printer[A.type] with
//   def print(a:A.type) = "a"

given Printer[B] with
   def print(t:B) = "b:"+t.data


object Main {

  def main(args:Array[String]):Unit =
    val x: Base = B("aaa")
    System.out.println(x.print())

}
```

## Output

```scala
error] -- Error: /Users/rssh/tests/dotty/sumon_derive/src/main/scala/x/Main.scala:44:37 
[error] 44 |given Printer[Base] = Printer.derived
[error]    |                                     ^
[error]    |no implicit argument of type deriving.Mirror.SumOf/T[x.Base/T] was found for parameter m of given instance derived in object Printer/T
[error] one error found

```

## Expectation

compiled and output "b:aaa" when run

**Comment by bishabosha** [comment] 2021-01-20 12:16
minimised to 
```scala
sealed trait Base

sealed trait A extends Base
case object A extends A

def test = summon[deriving.Mirror.Of[Base]]
```

This is not a bug, a mirror will only be generated for a type where all of its children are case class/case object/enum value

**Comment by bishabosha** [comment] 2021-01-20 12:19
closing, we have a feature request for this: https://github.com/lampepfl/dotty-feature-requests/issues/161

**Closed** 2021-01-20 12:20 UTC
Labels: itype:enhancement
