### ISSUE TITLE
children of trait A were already queried before object X was discovered

### ISSUE THREAD

**Issue by note** [lampepfl/dotty#17034] opened 2023-03-02 17:25 UTC
## Compiler version

`3.2.2` (tried 3.3.0-RC2 as well and got the some results)

## Minimized code

```scala
//> using scala "3.2.2"

object Main:
  @main
  def hello(): Unit =
    println(summon[scala.deriving.Mirror.Of[A]])

sealed trait A
object A:
  object Nested:
    case object X extends A
```

## Output

```
[error] ./mirror.scala:8:48: No given instance of type deriving.Mirror.Of[A] was found for parameter x of method summon in object Predef. Failed to synthesize an instance of type deriving.Mirror.Of[A]:
[error] 	* trait A is not a generic product because it is not a case class
[error] 	* trait A is not a generic sum because it does not have subclasses
[error]     println(summon[scala.deriving.Mirror.Of[A]])
[error]                                                ^
[error] ./mirror.scala:15:5: children of trait A were already queried before object X was discovered.
[error] As a remedy, you could move object X on the same nesting level as trait A.
[error]     case object X extends A
[error]     ^
Error compiling project (Scala 3.2.2, JVM)
```

## Expectation

I would expect that code to compile

## Other

I believe that the "No given instance of type deriving.Mirror.Of[A]..." part is a red herring and the real issue is the "children of trait A were already" part. I think so as for a very similar code:

```scala
sealed trait A
object A:
  object B extends A
  object Nested:
    case object X extends A
```

I got only the second message, i.e.:

```
[error] ./mirror.scala:16:5: children of trait A were already queried before object X was discovered.
[error] As a remedy, you could move object X on the same nesting level as trait A.
[error]     case object X extends A
[error]     ^
Error compiling project (Scala 3.2.2, JVM)
```

Also, the circumstances in which the issue shows up seem very fragile. Some examples of tiny code transformations that make the issue go away:

* put the method `main` on outside of `Main`
* moving `object Main` below hierarchy definition

**Comment by bishabosha** [comment] 2023-03-02 17:56
yeah it seems the compiler is pretty weak at resolving sealed children that are nested more than one level difference - perhaps for preventing "cycles".

**Comment by odersky** [comment] 2023-03-02 19:13
> yeah it seems the compiler is pretty weak at resolving sealed children from the same file that are nested more than one level difference - perhaps for preventing "cycles".

Correct. The error message is quite specific what needs to be done. The whole thing is carefully calibrated and I see no reasonable way to change this. So definitely not a bug.

**Closed by odersky** 2023-03-02 19:13 UTC
Labels: itype:bug, area:typer
