### ISSUE TITLE
Concrete trait member should take precedence over deferred method

### ISSUE THREAD

**Issue by adriaanm** [lampepfl/dotty#2072] opened 2017-03-09 19:49 UTC
```scala
trait T { lazy val x: String = "foo" }
abstract class AC extends T { def x: Any }
```

compiles to:
```java
public abstract class AC implements T {
    public AC() { super.x();   }

    public abstract Object x(); // where did my lazy val go?
}

public interface T {
    default public void $init$() { }

    default public String x() {
        return "foo";
    }
}
```

See https://issues.scala-lang.org/browse/SI-10223

**Comment by adriaanm** [comment] 2017-03-09 23:00
More generally, all of these are problematic:
```
trait T { def m = "" ; val v = "" ; lazy val lv = "" ; object o }

// deferred methods always lose against concrete ones, so none of these declarations actually survive in bytecode
// the mixed in members from T take precedence in the linearisation order
abstract class AC extends T {
  def m: Any
  def v: Any
  def lv: Any
  def o: Any
}
```

**Comment by odersky** [comment] 2017-03-12 16:25
It looks like a problem with bridge generation. Here's what we get after erasure:

      @scala.annotation.internal.SourceFile("i2072.scala") <trait> trait T() extends
      Object { 
        lazy <accessor> def x(): String = "foo"
      }
      @scala.annotation.internal.SourceFile("i2072.scala") abstract class AC()
         extends
       Object() with T { 
        def x(): Object
        def x(): String = this.x().asInstanceOf[String]
      }
    }

The bridge goes the wrong way. It should implement `def x(): Object` with the trait's `x` method,
but instead it links the trait's `x` method to the Object method in `AC`.

**Comment by DarkDimius** [comment] 2017-03-13 10:06
@odersky, the issue is even before erasure. We don't consider that trait methods can implement abstract methods in the class where they are mixed in:
```
trait T { def m = "" ; val v = "" ; lazy val lv = "" ; object o }

// deferred methods always lose against concrete ones, so none of these declarations actually survive in bytecode
// the mixed in members from T take precedence in the linearisation order
abstract class AC extends T {
  def m: Any
  def v: Any
  def lv: Any
  def o: Any
}

class C extends AC{}

```

```
-- Error: i2072.scala ----------------------------------------------------------
12 |class C extends AC{}
   |      ^
   |      class C needs to be abstract, since:
   |      it has 4 unimplemented members.
   |      /** As seen from class C, the missing signatures are as follows.
   |       *  For convenience, these are usable as stub implementations.
   |       */
   |        def lv: => Any = ???
   |        def m: => Any = ???
   |        def o: => Any = ???
   |        def v: => Any = ???
```

I suppose by the time of errasure we actually have overriding relatioship in wrong direction and erasure sets forwarders corrently based on info that it's provided. 
Going deeper to see why.

**Comment by DarkDimius** [comment] 2017-03-13 10:15
Note that scala 2.11.8 also rejects this with the same error message.

**Comment by DarkDimius** [comment] 2017-03-13 10:48
Ok, this seems to be a fundamental issue for dotty now.

Consider this example:

```
trait T { def m = "" ; val v = "" ; lazy val lv = "" }

abstract class AC extends T{
  def m: Any
  def v: Any
  def lv: Any
}

class C extends AC

abstract class AD {
  def m: Any
  def v: Any
  def lv: Any
}

class D extends AD with T
```

In case of `D` and `AD` all the phases do what they are supposed to do.
In case of both `C` and `AC` neither mixin, nor lazy vals, nor getters/memoize phases do the right job.
This is because all the compiler API internals assumes that methods defined in `AC` take precedence over members defined in `T` and all member selections return them.
Digging deeper.

**Comment by odersky** [comment] 2017-03-13 12:21
More interesting examples:

    trait T { lazy val x: String = "foo" }
    trait U { def x: Any }
    abstract class AC extends T with U // { def x: Any }

    abstract class B { def x: Any }
    class C extends B { def x: String = "abc" }

    package p2 {
    trait T1 { def f: Any }
    trait T2 extends T1 { def f: Number = ??? }
    trait T3 extends T1 { override def f: Integer = ??? }
    class C extends T2 with T3
    }

    package p3 {

      trait A { def f: Any }
      trait B extends A { def f: String }
      class C extends B { def f = "abc" }

    }

**Comment by Blaisorblade** [comment] 2019-12-22 06:58
This issue was in limbo, took the liberty to unassign. And to drop "fix available" given the PR is old.

This code still fails:
```
trait T { lazy val x: String = "foo" }
abstract class AC extends T { def x: Any }
class C extends AC {}
```

```
-- Error: baz.scala:3:6 --------------------------------------------------------
3 |class C extends AC {}
  |      ^
  |      class C needs to be abstract, since def x: => Any is not defined
```

but without `class C`, the bridge goes the right way around.

*However*, this seems now a duplicate of https://github.com/lampepfl/dotty/issues/4770#issuecomment-403090584, which is marked as an intentional change and "not an issue", except for Scala2.

So I'm closing as dup — feel free to reopen.

**Closed by Blaisorblade** 2019-12-22 06:58 UTC
