### ISSUE TITLE
Deprecation warning despite @nowarn

### ISSUE THREAD

**Issue by hnrklssn** [lampepfl/dotty#13038] opened 2021-07-09 12:31 UTC
## Compiler version

3.0.1-RC2

## Minimized code

```Scala
import scala.annotation.nowarn
trait A
case class Test(s: String) extends A
@nowarn def f(): String => A = Test
```

## Output

```
[warn] -- Warning: Test.scala:4:31 ------
[warn] 4  |@nowarn def f(): String => A = Test
[warn]    |                               ^^^^
[warn]    |The method `apply` is inserted. The auto insertion will be deprecated, please write `Test.apply` explicitly.
```

## Expectation
No warnings emitted originating in `f()`.

**Comment by lrytz** [comment] 2021-07-09 12:52
`@nowarn` support is in the works https://github.com/lampepfl/dotty/pull/12857

**Comment by dwijnand** [comment] 2021-07-13 12:29
Duplicate of #8908

**Closed by dwijnand** 2021-07-13 12:29 UTC
Labels: itype:bug
