### ISSUE TITLE
summonFrom and summon use different scopes for implicit search

### ISSUE THREAD

**Issue by heksesang** [lampepfl/dotty#11538] opened 2021-02-25 20:07 UTC
## Compiler version

3.0.0-RC1

## Minimized code

https://scastie.scala-lang.org/KfWryGwAT3SW7xwpv6k6OA

## Output

Compiler error due to the fact that `summonFrom` only seems to do the implicit search within the closest enclosing scope (it compiles if the given is imported in the same scope as the `summonFrom` call).

## Expectation

The calls to `summon` and `summonFrom` should obey the same rules for implicit search.

**Comment by nicolasstucki** [comment] 2021-02-26 12:37
They use different scopes by design. `summon` uses the scope where it is called while `summonFrom` uses the implicit scope at the inline site.

Though in the example you hit #11479, which is a bug.

**Comment by nicolasstucki** [comment] 2021-02-26 12:38
I will add this example as a test for #11479 and close this issue

**Comment by nicolasstucki** [comment] 2021-02-26 12:49
Minimized
```scala
package a:
  type Foo
  given foo: Foo = ???

import a.{Foo, given}
object test:
  inline def summonInlineFoo = scala.compiletime.summonInline[Foo]
  val summoned = summon[Foo]
  val summonedInline = summonInlineFoo
```

Moving the `import` into `test` fixed the issue

**Comment by nicolasstucki** [comment] 2021-02-26 12:52
It is related but not exaclty  #11479

**Closed** 2021-03-04 13:11 UTC
Labels: itype:bug
