### ISSUE TITLE
Extension methods ambiguity when type argument is added

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#14451] opened 2022-02-11 01:02 UTC
Just adding a type argument causes the compiler to report ambiguity where there is none.

## Compiler version

v3.1.2-RC1

## Minimized code
https://scastie.scala-lang.org/cI1XmUISRwmnIqc8rOThSw

```Scala
class Foo

extension (dfVal: Foo)
  def prevOK(step: Int): Foo = ???
  def prevOK: Foo = ???
val ok = (new Foo).prevOK

extension (dfVal: Foo)
  def prevErr[S <: Int](step: S): Foo = ???
  def prevErr: Foo = ???
val err = (new Foo).prevErr
```

## Output

```scala
value prevErr is not a member of Playground.Foo.
Extension methods were tried, but could not be fully constructed:

    Playground.prevErr(new Playground.Foo())

    prevErr(new Playground.Foo())    failed with

        Ambiguous overload. The overloaded alternatives of method prevErr in object Playground with types
         (dfVal: Playground.Foo): Playground.Foo
         (dfVal: Playground.Foo): [S <: Int](step: S): Playground.Foo
        both match arguments (Playground.Foo)
```

## Expectation
No error.

**Comment by soronpo** [comment] 2022-02-11 01:03
May be related to #14450

**Comment by prolativ** [comment] 2022-02-11 10:17
If you paste your examples you should see the reason why this doesn't work.
First one has keep in mind that extension methods eventually get desugared to normal methods.
So for
```scala
extension (dfVal: Foo)
  def prevOK(step: Int): Foo = ???
  def prevOK: Foo = ???
```
you get
```scala
def prevOK(dfVal: Foo)(step: Int): Foo
def prevOK(dfVal: Foo): Foo
```
This is an overloaded method with a different number of parameter lists but the compiler is smart enough to distinguish between them at compile time in most cases.

But in case of
```scala
def prevErr(dfVal: Foo): [S <: Int](step: S): Foo
def prevErr(dfVal: Foo): Foo
```
you get
```scala
def prevErr(dfVal: Foo): [S <: Int](step: S): Foo
def prevErr(dfVal: Foo): Foo
```
Now both of the overloaded variants take just a single parameter but they have different return types and it's not clear for the compiler which one you would like when writing
```scala
val err = (new Foo).prevErr
```
The reason for a different desugaring is that currently you cannot have a method like `def prevErr(dfVal: Foo)[S <: Int](step: S): Foo` with interweaved value and type parameters. I hope this restriction will get releaxed soon but I'm not sure of its status https://github.com/lampepfl/dotty/pull/14019

You can make your example compile by specifying the result type explicitly, e.g.
```scala
val err: Foo = (new Foo).prevErr
```

**Comment by som-snytt** [comment] 2022-02-11 17:25
The docs on the change to overload resolution say that it's to accommodate extension methods.

It's worth saying that the overload res can be fixed in advance of accepting explicit user syntax for the interweaved defs.

Interestingly, the proposed [spec changes](https://github.com/Sporarum/scala/pull/2/files) have nothing to say about overloading. Even if type inference has limitations, one might expect this example to "just work" so to speak.

I don't know what devil is in the details, but maybe a limitation in type inference means you can't even test for applicability?

> which one you would like when writing

Usually it doesn't matter what I wrote, except for applicability.

**Comment by Sporarum** [comment] 2022-02-17 15:42
> But in case of
> 
> ```scala
> extension (dfVal: Foo)
>   def prevErr[S <: Int](step: S): Foo = ???
>   def prevErr: Foo = ???
> ```
> 
> you get
> 
> ```scala
> def prevErr(dfVal: Foo): [S <: Int](step: S): Foo
> def prevErr(dfVal: Foo): Foo
> ```

This is somewhat incorrect, the actual translation is:
```scala
def prevErr(dfVal: Foo)[S <: Int](step: S): Foo
def prevErr(dfVal: Foo): Foo
```
Notice there is conceptually only one method, with a non-leading type parameter clause
The actual representation is a `MethodType`  returning a `PolyType` returning a `MethodType` returning a `Foo`
This is similar to the actual representation for prevOk: a `MethodType` returning a `MethodType` returning a `Foo`
This is because `MethodType` contains only one clause

[Clause Interweaving](https://github.com/lampepfl/dotty/pull/14019) doesn't change the representation inside the compiler, it uses the one introduced by https://github.com/lampepfl/dotty/pull/10950
(which I described above)

I believe the check that allows `ok` assumes there can only be `MethodType` as return, and doesn't handle `PolyType`.
(Thus the fix should be fairly easy)

Even if that is not the case, merging Clause Interweaving would not solve the problem 
(but solving the problem is important for Clause Interweaving)

**Comment by Sporarum** [comment] 2022-02-17 16:31
> The reason for a different desugaring is that currently you cannot have a method like `def prevErr(dfVal: Foo)[S <: Int](step: S): Foo` with interweaved value and type parameters.

My previous message could be simplified to simply: 

This method is completely allowed inside the compiler
But users can only create it through extension methods
[Clause Interweaving](https://github.com/lampepfl/dotty/pull/14019) only adds the ability for users to create those methods directly

**Comment by soronpo** [comment] 2022-04-09 14:17
It's good to document the workaround. We can move the type argument to the extension in many cases:
```scala
extension [S <: Int](dfVal: Foo)
  def prevErr(step: S): Foo = ???
  def prevErr: Foo = ???
val err = (new Foo).prevErr
```

**Comment by Sporarum** [comment] 2022-09-13 11:17
It turns out this is relatively easy to fix:
https://github.com/lampepfl/dotty/issues/14451

It does not require clause interleaving, but it would have made overloading with it very limited

**Closed** 2022-09-15 09:57 UTC
Labels: itype:enhancement, area:extension-methods
