### ISSUE TITLE
The "More details" link in doc page Macros is broken

### ISSUE THREAD

**Issue by ShapelessCat** [lampepfl/dotty#10480] opened 2020-11-25 00:04 UTC
The "More details" link in doc page _Macros_ is broken.
The link in the .md file in Github is fine, but in the generate .html page it still points to macros-spec.md (Not Found):
https://dotty.epfl.ch/docs/reference/metaprogramming/macros-spec.md

**Comment by griggt** [comment] 2020-11-25 00:08
Duplicate of #10465 

Thanks for reporting!  There is a link to preview the fix here https://github.com/lampepfl/dotty/issues/10465#issuecomment-732935016

**Closed by griggt** 2020-11-25 00:08 UTC
