### ISSUE TITLE
Type is inferred as Nothing when composing contravariant types

### ISSUE THREAD

**Issue by adamgfraser** [lampepfl/dotty#7791] opened 2019-12-17 14:28 UTC
## minimized code

```Scala
object Example extends App {
  
  def assert[A](value: A)(assertion: Assertion[A]): Boolean =
    assertion.run(value)
  
  trait Assertion[-A] { self =>
    def run(a: A): Boolean
    def ||[A1 <: A](that: Assertion[A1]): Assertion[A1] =
      a => self.run(a) && that.run(a)
  }
  
  def equalTo[A, B](expected: A)(implicit eq: Eql[A, B]): Assertion[B] =
    _ == expected
  
  def isGreaterThan(a: Int): Assertion[Int] =
    _ > a
  
  // okay
  assert(List(1, 2, 3))(equalTo(List.empty))
  
  // does not compile
  // values of type Int and String cannot be compared with ==  or != 
  // assert("Adam")(equalTo(1))
  
  // does not compile
  // expected Assertion[Int] but found Assertion[Nothing]
  // assert(10)(equalTo(5) || isGreaterThan(9))
}
```

## expectation

I would have expected the third assertion to compile. Both `assert(10)(equalTo(5))` and `assert(10)(isGreaterThan(9))` compile, so it seems like the compiler is able to correctly infer the type of a single assertion as `Assertion[Int]`. But when we combine two of them with `||` we get the type being inferred as `Assertion[Nothing]` instead of what I would have expected would be `Assertion[Int]`.

**Comment by julienrf** [comment] 2021-06-08 13:54
The signature of the `equalTo` method looks suspicious to me:

> ```scala
> def equalTo[A, B](expected: A)(implicit eq: CanEqual[A, B]): Assertion[B]
> ```

The type parameter `B` will be fixed according to the `CanEqual` instance found in the context.

Consider the following situation:

~~~ scala
given Eql[Int, UserID] = ...
given Eql[Int, VehicleID] = ...
~~~

Which one of the two givens should be picked by the compiler?

In your example, `assert(List(1, 2, 3))(equalTo(List.empty))` works because `assert(List(1, 2, 3))` does fix the type of the expected assertion to be `Assert[List[Int]]`, bt `equalTo(List.empty)` alone would have type `Assertion[collection.Seq[java.lang.Number]]` (because of the given definitions in `CanEqual`).

I’m not sure whether the problem is due to the usage of contravariance, or to the way `CanEqual` instances are synthesized by the compiler. For now, it seems that the process of synthesizing `CanEqual` instances requires the two type arguments to be already fixed, otherwise `Nothing` is inferred. In `strictEquality` mode, the compiler won’t synthesize a `CanEqual` instance unless both type arguments are fully known.

So, my conclusion would be that we should not rely on the summoned `CanEqual` to infer the type of the result, `Assertion[B]`.

**Comment by julienrf** [comment] 2021-06-08 13:56
I’m closing the issue because I believe the current behavior regarding `CanEqual` does make sense. That being said, feel free to re-open it if you come up with a reproduction that uses a custom-made `Equal` type class whose instances are not synthesized by the compiler.

**Closed by julienrf** 2021-06-08 13:56 UTC
Labels: itype:bug
