### ISSUE TITLE
Assertion failed when using int + string

### ISSUE THREAD

**Issue by fdietze** [lampepfl/dotty#14099] opened 2021-12-13 13:27 UTC
## Compiler version

Scala 3.1.0 with ScalaJS 1.7.0

## Minimized code

```Scala
List("a").map(str => List(5 + str))
```
https://scastie.scala-lang.org/7ZW1vEsBQFGKOKbeSLKXCg

## Output (click arrow to expand)
<details>
```
java.lang.AssertionError: assertion failed
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
	at dotty.tools.backend.sjs.JSCodeGen.genStringConcat(JSCodeGen.scala:2801)
	at dotty.tools.backend.sjs.JSCodeGen.genPrimitiveOp(JSCodeGen.scala:2409)
	at dotty.tools.backend.sjs.JSCodeGen.genApply(JSCodeGen.scala:2023)
	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1705)
	at dotty.tools.backend.sjs.JSCodeGen.genExpr(JSCodeGen.scala:1574)
	at dotty.tools.backend.sjs.JSCodeGen.$anonfun$36(JSCodeGen.scala:3166)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.backend.sjs.JSCodeGen.genJavaSeqLiteral(JSCodeGen.scala:3166)
	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1838)
	at dotty.tools.backend.sjs.JSCodeGen.genExpr(JSCodeGen.scala:1574)
	at dotty.tools.backend.sjs.JSCodeGen.genActualArgs$$anonfun$1(JSCodeGen.scala:3972)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.backend.sjs.JSCodeGen.genActualArgs(JSCodeGen.scala:3972)
	at dotty.tools.backend.sjs.JSCodeGen.genNormalApply(JSCodeGen.scala:2949)
	at dotty.tools.backend.sjs.JSCodeGen.genApply(JSCodeGen.scala:2033)
	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1705)
	at dotty.tools.backend.sjs.JSCodeGen.genExpr(JSCodeGen.scala:1574)
	at dotty.tools.backend.sjs.JSCodeGen.genActualArgs$$anonfun$1(JSCodeGen.scala:3972)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.backend.sjs.JSCodeGen.genActualArgs(JSCodeGen.scala:3972)
	at dotty.tools.backend.sjs.JSCodeGen.genNormalApply(JSCodeGen.scala:2949)
	at dotty.tools.backend.sjs.JSCodeGen.genApply(JSCodeGen.scala:2033)
	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1705)
	at dotty.tools.backend.sjs.JSCodeGen.genExpr(JSCodeGen.scala:1574)
	at dotty.tools.backend.sjs.JSCodeGen.genTypeApply(JSCodeGen.scala:3150)
	at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1708)
	at dotty.tools.backend.sjs.JSCodeGen.genExpr(JSCodeGen.scala:1574)
	at dotty.tools.backend.sjs.JSCodeGen.genBody$1(JSCodeGen.scala:1504)
	at dotty.tools.backend.sjs.JSCodeGen.genMethodDef(JSCodeGen.scala:1509)
	at dotty.tools.backend.sjs.JSCodeGen.genMethodWithCurrentLocalNameScope$$anonfun$1(JSCodeGen.scala:1476)
	at dotty.tools.backend.sjs.JSCodeGen.withPerMethodBodyState$$anonfun$1(JSCodeGen.scala:114)
	at dotty.tools.backend.sjs.ScopedVar$.withScopedVars(ScopedVar.scala:35)
	at dotty.tools.backend.sjs.JSCodeGen.withPerMethodBodyState(JSCodeGen.scala:115)
	at dotty.tools.backend.sjs.JSCodeGen.genMethodWithCurrentLocalNameScope(JSCodeGen.scala:1482)
	at dotty.tools.backend.sjs.JSCodeGen.genMethod$$anonfun$1(JSCodeGen.scala:1383)
	at dotty.tools.backend.sjs.ScopedVar$.withScopedVars(ScopedVar.scala:35)
	at dotty.tools.backend.sjs.JSCodeGen.genMethod(JSCodeGen.scala:1384)
	at dotty.tools.backend.sjs.JSCodeGen.genScalaClass$$anonfun$2(JSCodeGen.scala:370)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.sjs.JSCodeGen.genScalaClass(JSCodeGen.scala:375)
	at dotty.tools.backend.sjs.JSCodeGen.genCompilationUnit$$anonfun$8$$anonfun$1(JSCodeGen.scala:246)
	at dotty.tools.backend.sjs.ScopedVar$.withScopedVars(ScopedVar.scala:35)
	at dotty.tools.backend.sjs.JSCodeGen.genCompilationUnit$$anonfun$3(JSCodeGen.scala:250)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.sjs.JSCodeGen.genCompilationUnit(JSCodeGen.scala:252)
	at dotty.tools.backend.sjs.JSCodeGen.run(JSCodeGen.scala:164)
	at dotty.tools.backend.sjs.GenSJSIR.run(GenSJSIR.scala:15)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:308)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:309)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:261)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:272)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:280)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:289)
	at dotty.tools.dotc.Run.compileSources(Run.scala:222)
	at dotty.tools.dotc.Run.compile(Run.scala:206)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:175)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:173)
	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:501)
	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
	at sbt.internal.inc.Incremental$.apply(Incremental.scala:167)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2357)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
	at sbt.internal.io.Retry$.apply(Retry.scala:46)
	at sbt.internal.io.Retry$.apply(Retry.scala:28)
	at sbt.internal.io.Retry$.apply(Retry.scala:23)
	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2310)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
</details>

**Comment by sjrd** [comment] 2021-12-15 13:57
Duplicate of #13518. Already fixed for v3.1.1.

**Closed by sjrd** 2021-12-15 13:57 UTC
Labels: itype:bug, area:scala.js, itype:crash
