### ISSUE TITLE
Polymorphic function crashes when used from a Heterogenous Map

### ISSUE THREAD

**Issue by markehammons** [lampepfl/dotty#13511] opened 2021-09-12 09:01 UTC
## Compiler version
3.0.2

## Minimized code

```scala
class HMap[T <: Tuple](m: Map[Any, Any]):
  import HMap.*
  def add[K <: Singleton, V](k: K, v: V)(using
      NoMatch[T, K] =:= true
  ) = HMap[(K, V) *: T](m + (k -> v))

  def addUsing[K <: Singleton, V](
      k: K,
      fn: HMap[T] => V
  )(using
      NoMatch[T, K] =:= true
  ) = HMap[(K, V) *: T](m + (k -> fn(this)))

  def get[K <: Singleton](k: K)(using
      NoMatch[T, K] =:= false
  ): GetMatch[T, K] =
    m(k).asInstanceOf[GetMatch[T, K]]

object HMap:
  val empty: HMap[EmptyTuple] = HMap(Map.empty)

  type NoMatch[Tup <: Tuple, K] = Tup match
    case (K *: ? *: EmptyTuple) *: ?    => false
    case (? *: ? *: EmptyTuple) *: rest => NoMatch[rest, K]
    case EmptyTuple                     => true

  type GetMatch[Tup <: Tuple, K] = Tup match
    case EmptyTuple                     => Nothing
    case (K *: t *: EmptyTuple) *: ?    => t
    case (? *: ? *: EmptyTuple) *: rest => GetMatch[rest, K]

val hm = HMap
  .empty
  .add("foo", 4)
  .add("bar", (i: Int) => i + 2)
  .addUsing("mapFoo", _.get("foo").pipe(f => [G] => (fn: Int => G) => fn(f)))

hm.get("mapFoo")(_.toString)
```

## Output (click arrow to expand)
<details>

```scala
exception while typing hm.get[("mapFoo" : String)]("mapFoo")(<:<.refl[(false : Boolean)]).apply of class class dotty.tools.dotc.ast.Trees$Select # -1
exception while typing hm.get[("mapFoo" : String)]("mapFoo")(<:<.refl[(false : Boolean)]).apply[String] of class class dotty.tools.dotc.ast.Trees$TypeApply # -1
exception while typing hm.get[("mapFoo" : String)]("mapFoo")(<:<.refl[(false : Boolean)]).apply[String]
  (
{
  def $anonfun(_$1: Int): String = _$1.toString()
  closure($anonfun)
}
) of class class dotty.tools.dotc.ast.Trees$Apply # -1
exception while typing def res0: String = 
  hm.get[("mapFoo" : String)]("mapFoo")(<:<.refl[(false : Boolean)]).apply[
    String
  ](
    {
      def $anonfun(_$1: Int): String = _$1.toString()
      closure($anonfun)
    }
  ) of class class dotty.tools.dotc.ast.Trees$DefDef # -1
exception while typing @scala.annotation.internal.SourceFile("rs$line$4") final module class rs$line$4
  ()
 extends Object() {
  private def writeReplace(): AnyRef = 
    new scala.runtime.ModuleSerializationProxy(classOf[repl.rs$line$4.type])
  def res0: String = 
    hm.get[("mapFoo" : String)]("mapFoo")(<:<.refl[(false : Boolean)]).apply[
      String
    ](
      {
        def $anonfun(_$1: Int): String = _$1.toString()
        closure($anonfun)
      }
    )
} of class class dotty.tools.dotc.ast.Trees$TypeDef # -1
exception while typing package repl {
  final lazy module val rs$line$4: repl.rs$line$4 = new repl.rs$line$4()
  @scala.annotation.internal.SourceFile("rs$line$4") final module class 
    rs$line$4
  () extends Object() {
    private def writeReplace(): AnyRef = 
      new scala.runtime.ModuleSerializationProxy(classOf[repl.rs$line$4.type])
    def res0: String = 
      hm.get[("mapFoo" : String)]("mapFoo")(<:<.refl[(false : Boolean)]).apply[
        String
      ](
        {
          def $anonfun(_$1: Int): String = _$1.toString()
          closure($anonfun)
        }
      )
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # -1
Exception in thread "main" java.lang.AssertionError: assertion failed:  <none>
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.transform.Erasure$Typer.typedSelect(Erasure.scala:721)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2663)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2755)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
        at dotty.tools.dotc.transform.Erasure$Typer.typedTypeApply(Erasure.scala:815)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2712)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
        at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:837)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2693)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
        at dotty.tools.dotc.typer.Typer.$anonfun$34(Typer.scala:2156)
        at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:225)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2156)
        at dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:955)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2670)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2755)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2847)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2897)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1053)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2352)
        at dotty.tools.dotc.transform.Erasure$Typer.typedClassDef(Erasure.scala:1043)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2681)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2685)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2755)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2847)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2897)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1053)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2475)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2726)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
        at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:132)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:216)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:224)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:231)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:172)
        at dotty.tools.repl.ReplCompiler.runCompilationUnit(ReplCompiler.scala:152)
        at dotty.tools.repl.ReplCompiler.compile(ReplCompiler.scala:162)
        at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:250)
        at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:213)
        at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:147)
        at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:150)
        at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:169)
        at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:150)
        at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:116)
        at dotty.tools.repl.Main$.main(Main.scala:6)
        at dotty.tools.repl.Main.main(Main.scala)```
</details>

**Comment by smarter** [comment] 2021-09-12 10:09
Duplicate of https://github.com/lampepfl/dotty/issues/13304

**Closed by smarter** 2021-09-12 10:09 UTC
Labels: itype:bug, itype:crash
