### ISSUE TITLE
 scala.beans.BeanProperty does not propagate annotations

### ISSUE THREAD

**Issue by wiltonlazary** [lampepfl/dotty#17968] opened 2023-06-13 13:12 UTC
## Compiler version

3.3.0

## Minimized code

```Scala
class StructLocal {
  @BeanProperty
  @accs var namexxxxx: String = "My name" 
}
```

## Expectation

getNamexxxxx and setNamexxxxx bytecode to have the accs annotation

Macro code:
```
        val tps = tpr.typeSymbol
  
        tps.methodMembers
          .sortBy(_.name)
          .foreach { x =>
            val methodName = x.name
            val accs = x.annotations.find(it => it.tpe.typeSymbol.name == "accs")

            if (methodName == "getNamexxxxx") {
              report.error(s"annotations=${x.annotations} | ${x.toString}")
            }

            if (accs.nonEmpty) {
              val compositeName = (methodName.length > 3 && (!methodName(3).isLetter || methodName(3).isUpper))

              if (methodName.startsWith("set") && compositeName) {
                setters.append(setterStructAcessor(x))
              } else if (methodName.startsWith("get") && compositeName) {
                getters.append(getterStructAcessor(x))
              } else if (methodName.endsWith("_=")) {
                setters.append(setterStructAcessor(x))
              } else {
                getters.append(getterStructAcessor(x))
              }
            }
          }
```

**Comment by odersky** [comment] 2023-06-23 08:20
What does Scala 2 do in this case? 

We could fix this  by changing `BeanProperties.scala` which runs as part of `PostTyper`.

But maybe it's better to wait for macro annotations to be merged, then it can be done as a macro.

**Comment by wiltonlazary** [comment] 2023-06-28 13:11
Hi @odersky, It's was fine in 3.2.2, i think that @BeanProperty without annotation propagation will not fulfill the full purpose.

**Comment by Kordyjan** [comment] 2023-06-30 14:31
Caused by https://github.com/lampepfl/dotty/commit/e580aaaef8df2b162817050d2eb0f17483423359

**Comment by dwijnand** [comment] 2023-06-30 16:47
This isn't a regression it's a fix in line with the docs, in the `scala.annotation.meta` package:

> Annotations on fields by default only end up on the field.

If you want the annotation on the bean getter you need to use `@beanGetter` (from that meta package).

**Closed by dwijnand** 2023-06-30 16:47 UTC
Labels: itype:bug, area:annotations, area:transform

**Comment by wiltonlazary** [comment] 2023-07-01 00:06
don't get propagated:

```
class StructLocal {
  @(accs @beanGetter @beanSetter) @BeanProperty
  var prop1xxx: String = "Wilton"
}
```

**Comment by wiltonlazary** [comment] 2023-07-01 00:10
syntax error, can i pass a parameter for the annotation?

```
class StructLocal {
  @(accs("name") @beanGetter @beanSetter) @BeanProperty
  var prop1xxx: String = "Wilton"
}
```

**Comment by wiltonlazary** [comment] 2023-07-01 00:11
Thanks, i will refactor all the code.

**Comment by som-snytt** [comment] 2023-07-01 04:51
@wiltonlazary the hint in the doc is

```Scala
type beanaccs = accs @beanGetter @beanSetter
@beanaccs("name") @BeanProperty var x = "Lazary"
```
I guess there is no mechanism for what would be natural today:
```
type DS = deprecated["1.0"]  // or deprecated[since="1.0"]
```

Thanks @dwijnand for the refresher. I noticed that Scala `@deprecated` makes all the elements deprecated (with the attribute but not the annotation); for some reason, I assumed Java `@Deprecated` also emitted the attribute, but it is treated like an ordinary annotation.

**Comment by dwijnand** [comment] 2023-07-01 10:48
Also, if `@accs` is your own and it's always meant to apply to the java bean accessors, then you can annotate the annotation definition itself.

**Comment by wiltonlazary** [comment] 2023-07-01 15:44
@dwijnand and @som-snytt thanks for the patience and the great solution, it's worked with elegancy:

```
type baccs = accs @beanGetter @beanSetter
@baccs("name") @BeanProperty var x = "Lazary"
```

**Comment by wiltonlazary** [comment] 2023-07-01 16:55
i found this in the documentation, but i'm not sure why is not doing the job: 
[(https://dotty.epfl.ch/api/scala/annotation/meta.html]
```
  @getter @setter
  class accs(val key: String = "") extends Annotation
```

**Comment by dwijnand** [comment] 2023-07-01 18:20
Do you mean to be annotate that with `@beanGetter` and `@beanSetter`?

**Comment by som-snytt** [comment] 2023-07-01 19:41
It's tricky because that paragraph of the doc switches from "Java realm" to "Scala realm", where Java entities are presumed to be beans you don't own, and Scala annotations belong to you and you're not interested in interop with beans.

**Comment by wiltonlazary** [comment] 2023-07-01 22:03
@dwijnand @som-snytt,  i was exploring the possibilities, really the frontier between languages have some tricks, but i'm very happy with your support for the solution.

i think that when we can do macros annotations the next wave of metaprogramming power will come.

```
  // @experimental
  // class accs extends MacroAnnotation {
  //   override def transform(using quotes: Quotes)(tree: quotes.reflect.Definition): List[quotes.reflect.Definition] = {
  //     import quotes.reflect._
  //     import scala.quoted.*

  //   ...
  // }
```
