### ISSUE TITLE
Given instances, their extension methods with implicits, match types with type extractors – compile error

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#7087] opened 2019-08-22 15:05 UTC
```scala
type Foo

type G[A]

type F[T] = T match {
  case G[a] => String
}

given A {
  def (tup: T) g[T] given Foo: F[T] = ???
}

def f(x: G[Int]) given Foo: String = x.g
```

Out:

```scala
-- [E008] Member Not Found Error: ../pg/Macros3.scala:13:39 --------------------
13 |def f(x: G[Int]) given Foo: String = x.g
   |                                     ^^^
   |      value g is not a member of G[Int] - did you mean x.==?.
   |      An extension method was tried, but could not be fully constructed:
   |
   |          Macros3$package.A.g[T](x)
one error found
```

<details><summary>Working examples</summary>

```scala
type Foo

type G[A]

type F[T] = T match {
  case G[a] => String
}

// given A {
  def (tup: T) g[T] given Foo: F[T] = ???
// }

def f(x: G[Int]) given Foo: String = x.g
```

```scala
type Foo

type G[A]

type F[T] = T match {
  case G[a] => String
}

given A {
  def (tup: T) g[T]/* given Foo*/: F[T] = ???
}

def f(x: G[Int]) given Foo: String = x.g
```

```scala
type Foo

type G[A]

type F[T] = T match {
  case G[a] => String
}

given A {
  def (tup: T) g[T] given Foo: F[T] = ???
}

def f(x: G[Int]) given Foo/*: String*/ = x.g
```

```scala
type Foo

type G[A]

type F[T] = T match {
  case /*G[Int]*/Any => String
}

given A {
  def (tup: T) g[T] given Foo: F[T] = ???
}

def f(x: G[Int]) given Foo: String = x.g
```
</details>

Possibly related to #7084.

**Comment by odersky** [comment] 2019-08-24 10:35
Seems to be a duplicate of #7084. It's fixed by #7093.

**Closed by odersky** 2019-08-24 10:35 UTC
Labels: area:implicits, extension-methods, itype:bug
