### ISSUE TITLE
Have a list of trusted Java methods with explicitNulls

### ISSUE THREAD

**Issue by Lumintorious** [lampepfl/dotty#10379] opened 2020-11-18 21:08 UTC
Explicit nulls is great and even though you can use `.nn` and even though `unsafeNulls` might be coming, some methods in Java classes like `File` or `String` that are used in Scala all the time should have a list of trusted (maybe hard-coded) methods that are trusted to not return `UncheckedNull`. For example, I think there is no instance where calling `join`, `split`, `substring`, `trim` etc. on Strings with non-null parameters (non-null parameters also not being part of a use-case of the method either) could return null and having to use workarounds that "feel" unsafe when you can be sure that they are safe on methods that you would use all the time is a little cumbersome and makes the code look messy when it shouldn't be.

**Comment by bishabosha** [comment] 2020-11-18 21:42
I would say this is a duplicate of #7871

**Closed by bishabosha** 2020-11-18 21:42 UTC
