### ISSUE TITLE
Spurious exhaustiveness warning for union of tuple types

### ISSUE THREAD

**Issue by LPTK** [lampepfl/dotty#8690] opened 2020-04-07 17:58 UTC
## Minimized code

```Scala
class A
class B

def test(x: (A, B) | (B, A)) = x match {
  case (u: A, v) => (u, v)
  case (u: B, v) => (v, u)
}
```

https://scastie.scala-lang.org/ifiEqLPETBq2eruEbFXfFQ

## Output

```scala
match may not be exhaustive.
It would fail on pattern case: Tuple2(_, _)
```

Moreover, the type inferred for `v` is always `Object`, whereas it could be more precise here.

## Expectation

No warning, and more precise types.

**Comment by smarter** [comment] 2020-04-07 18:15
Might have the same root cause as https://github.com/lampepfl/dotty/issues/8681 ?

**Comment by liufengyun** [comment] 2020-04-09 15:01
The warning is fixed in #8698. This bug is caused by a different problem from #8681. The warning in the latter is issued during erasure.

However, it seems complex to give a more precise type to `v`.  Any ideas @smarter ?

**Comment by smarter** [comment] 2020-04-09 15:33
> However, it seems complex to give a more precise type to v. Any ideas @smarter ?

I had a quick look and it doesn't seem easy yeah, there's various places which assume that the unapply method type is fully inferred before typing the unapply arguments, I think that part of the issue should be considered a feature request and not a bug.

**Comment by LPTK** [comment] 2020-04-09 17:29
@smarter fair enough, as long as the fully-annotated version works:

```scala
def test(x: (A, B) | (B, A)) = x match {
  case (u: A, v: B) => (u, v)
  case (u: B, v: A) => (v, u)
}
```

(@liufengyun it would be good to test that code too.)

**Comment by liufengyun** [comment] 2020-04-09 17:48
@LPTK The exhaustivity check can handle the code above (thanks for the test), but in a later phase there's a warning saying:

```
the type test for A cannot be checked at runtime
```

So, you may need a `ClassTag` for `A` and `B`.

**Comment by LPTK** [comment] 2020-04-09 17:56
@liufengyun isn't that warning spurious? `A` and `B` are classes, not type parameters.

**Comment by liufengyun** [comment] 2020-04-09 19:01
@LPTK I adapted the test https://github.com/lampepfl/dotty/pull/8698/commits/030249b183601fb80c35bdf98b1069b4e6120579

**Closed** 2020-04-14 05:45 UTC
Labels: area:pattern-matching, itype:bug, stat:fix available
