### ISSUE TITLE
scalajs:  error when compiling enum with  definition without parameters

### ISSUE THREAD

**Issue by rssh** [lampepfl/dotty#9923] opened 2020-09-30 16:28 UTC
## Minimized code

```Scala
package x

enum CountSignal[+T]:
 case Data(data: T)
 case Finish
```

## Output

```scala
Latest Dotty nightly build version: 0.28.0-bin-20200928-09eaed7-NIGHTLY
[info] loading settings for project root from build.sbt ...
[info] set current project to test (in build file:/Users/rssh/tests/dotty/scalajs-test/)
[info] Compiling 1 Scala source to /Users/rssh/tests/dotty/scalajs-test/target/scala-0.28/classes ...
[info] exception occurred while compiling /Users/rssh/tests/dotty/scalajs-test/src/main/scala/x/Main.scala
[error] Assignment to static member x.CountSignal$.Finish not supported
```

## Expectation
Compiled.

Note, that 

```Scala
package x

enum CountSignal[+T]:
 case Data(data: T)
 case Finish()
```
 compiled

**Comment by sjrd** [comment] 2020-09-30 16:55
Duplicate of #9809

**Closed by sjrd** 2020-09-30 16:55 UTC
Labels: itype:bug
