### ISSUE TITLE
Type equality doesn't seem to propagate in match

### ISSUE THREAD

**Issue by durban** [lampepfl/dotty#11127] opened 2021-01-15 00:59 UTC
## Minimized code

```Scala
sealed abstract class Func[-A, +B] {
  def first[X]: Func[(A, X), (B, X)] = null
}

object Func {

  sealed abstract class Identity[A] extends Func[A, A]

  final class Lift[A, B, C](val func: A => B, val k: Func[B, C])
    extends Func[A, C] {

    def productImpl[D, E](that: Func[D, E]): Func[(A, D), (C, E)] = {
      that match {
        case _: Identity[_] =>
          // note, that D <:< E if we are here
          new Lift[(A, D), (B, D), (C, D)]({ ad => (func(ad._1), ad._2) }, k.first)
        case _ =>
          null
      }
    }
  }
}
```

## Output

```scala
[error] -- [E007] Type Mismatch Error: .../test.scala:17:10 
[error] 17 |          new Lift[(A, D), (B, D), (C, D)]({ ad => (func(ad._1), ad._2) }, k.first)
[error]    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |          Found:    Func.Lift[(A, D), (B, D), (C, D)]
[error]    |          Required: Func[(A, D), (C, E)]
```
(Tested with Scala 3.0.0-M3.)

## Expectation

I think it should compile without any error.

Other observations:

- If instead of `sealed abstract class Identity[A] ...` I have `final class Identity[A] ...`, then it compiles without error.
- With Scala 2.13.4, it compiles without error.

**Comment by smarter** [comment] 2021-01-15 01:20
>  // note, that D =:= E if we are here

I don't think that's true, even with `final class Identity[A]` I can write:
```scala
val x: Func[Nothing, Any] = new Identity[Int]
```
so the only thing we can conclude from the type parameters of `Func` from the fact that it is an instance  of `Identity` is that the first one is a subtype of the second one.

**Comment by durban** [comment] 2021-01-15 01:57
Of course, you're right, sorry about that. Removing the variance indeed fixes the compile error. (However, then why making it `final` also fixes the compile error?)

**Comment by durban** [comment] 2021-01-15 02:09
Ok, so I've updated the comment to `D <:< E`, as you've wrote. Thinking about it some more, I still think the original code should also compile. Here is my reasoning:

The compile error is, that it found a `Lift[(A, D), (B, D), (C, D)]` instead of a `Func[(A, D), (C, E)]`. However, I think, that in fact _if_ `D <:< E`, _then_  `Lift[(A, D), (B, D), (C, D)]` <:< `Func[(A, D), (C, E)]`. I think this is due to the variance of `Func` (and Tuple2).

To verify my thinking, this compiles without error:
```scala
    def foo[E, D <: E](that: Func[D, E]): Func[(A, D), (C, E)] = {
      new Lift[(A, D), (B, D), (C, D)](???, ???)
    }
```

**Comment by odersky** [comment] 2021-01-15 12:51
Is this gadt related? /cc @abgruszecki 

Generally, it would be good to have some more solid grounds to decide this. "It should work like this" is the immediate precursor for a soundness bug tomorrow. So we need more than an example. If we had precise rules what should be implemented and a proof sketch why this is sound we could probably make progress on this.

**Comment by LPTK** [comment] 2021-01-15 21:39
> so I've updated the comment to `D <:< E`, as you've wrote

Even this we cannot know. Here is a way of building a counter example:

```scala
  trait F[A, B] extends Func[A, B]
  new Identity[Int] with F[Any, Nothing] : Func[Any, Nothing]
```

So we have an instance of `F[Any, Nothing]` that's also an `Identity`, which would imply `Any <: Nothing`, according to your reasoning.

I think this is legit: type `Func[Any, Nothing]` is not incompatible with type `Func[Int, Int]` – their intersection is `Func[Any | Int, Nothing & Int]`, which is `Func[Any, Nothing]`.

---

The underlying issue is that the class `Identity` can still have its type parameters refined, because they are variant. Once you make the class `final`, it "sets in stone" the given parameters, which is why it works in that case. And the compiler does not reason about `sealed` in the sam way – it would be much more complex/impossible to implement completely (you'd have to analyze everywhere the class is refined, which could be in random places not yet type checked).

If you want to enforce the fact that `D <:< E`, you can do so with a type member, leveraged like this:

(this compiles)
```scala
sealed abstract class Func[-A, +B] {
  type A0 >: A
  type B0 <: B
  def first[X]: Func[(A, X), (B, X)] = null
}

object Func {

  sealed abstract class Identity[A] extends Func[A, A]:
    type Ev >: A0 <: B0

  final class Lift[A, B, C](val func: A => B, val k: Func[B, C])
    extends Func[A, C] {

    def productImpl[D, E](that: Func[D, E]): Func[(A, D), (C, E)] = {
      that match {
        case id: Identity[_] =>
          // note, that D <:< E if we are here
          new Lift[(A, id.Ev), (B, id.Ev), (C, id.Ev)]({ ad => (func(ad._1), ad._2) }, k.first)
        case _ =>
          null
      }
    }
  }
}
```

Note the type of `Lift[(A, id.Ev), (B, id.Ev), (C, id.Ev)]`, which is required for the expression to type check.

Also note that the counter example no longer compiles:
```
anonymous class Func.Identity[Int] with Func.F[Any, Nothing] {...} cannot be instantiated since it has a member Ev with possibly conflicting bounds A0 <: ... <: B0
```

**Comment by abgruszecki** [comment] 2021-01-16 13:13
Yep, Lionel is spot-on. Here's how I view things.

`Fun[a, b]` corresponds to the following structural type: `{ type A >: a; type B <: b }`.
`Identity[c]` corresponds to: `{ type C = c; type A >: c; type B <: c }`
`final Identity[c]` corresponds to `{ type C = c; type A = c; type B = c }` - note the equalities!

If we have an `x : Fun[a, b]` and we find out that it's a `final Identity[c]`, then it _must_ be the case that `a <: b`, because `a <: A = c`, and `c = B <: b`.

OTOH, if the `Identity` isn't final, then we get the following constraint:

```
a <: A
B <: b
C <: A
B <: C
```

And, if we want `a <: b` to be false, we can do it like this:

```
trait Fun[-A, +B]; trait Identity[C] extends Fun[C, C]

trait TA
trait Tb
trait TB extends TA, Tb
trait Ta extends TA

trait UnsoundIdentity extends Identity[TB] with Fun[Ta, Tb]
```

@durban: so it seems that everything is working as intended here. Why did you want to have the original example working? Did it come from a previously compiling codebase? I'm asking since there's other ways to make this work aside from what @LPTK suggested, and ensuring that already existing codebases keep on working is a good incentive to implement those other ways in the compiler.

/cc @mario-bucev - this is an interesting example, you should take a look at it.

**Comment by durban** [comment] 2021-01-18 21:32
Thank you for the detailed explanation! I think I understand it now.

@abgruszecki Yes, the example came from a codebase which compiled in scala 2.13. I that case, I could easily make the class `final` instead of `sealed abstract`, so that's what I did in this commit: https://github.com/durban/choam/commit/f81d62f076bec1916dea207df2656c47592e0181#diff-34104aa3ae69c7e35eaefbb45b7b3a63f3065c41a104b97e8929e5aa709910bcL350.

**Comment by LPTK** [comment] 2021-01-18 22:58
Note that another way of making this work AFAIK is to make the class a `case class`, because they're treated specially by the compiler. This way, the class can still be extended (though not by other case classes).

**Comment by abgruszecki** [comment] 2021-01-20 10:54
Right, `case` works similarly to `final` in this regard. IIRC, it's not possible to further refine the type arguments of classes that a case class extends.

@durban thanks for showing the source of the example, I'm going to take note of it. Seeing as the problem was fixed, I'd say we can close this issue. In case you run into similar problems, please don't hesitate to open a new issue, even knowing that those problems exist is valuable.

**Closed by abgruszecki** 2021-01-20 10:54 UTC
Labels: area:gadt, discussion
