### ISSUE TITLE
No static $init$ in pure trait extending impure trait

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#9970] opened 2020-10-08 14:59 UTC
## Minimized code

```Scala
trait IOApp {
  protected val foo = 23

  def run(args: List[String]): Int

  final def main(args: Array[String]): Unit = {
    sys.exit(run(args.toList))
  }

}
object IOApp {
  trait Simple extends IOApp {
    def run: Unit

    final def run(args: List[String]): Int = {
      run
      0
    }
  }
}
```

## Output

IOApp compiled by dotty `0.27.0-RC1`:
```java
public static interface IOApp.Simple
extends IOApp {
    public void run();

    public static int run$(IOApp.Simple $this, List args) {
        return $this.run((List<String>)args);
    }

    @Override
    default public int run(List<String> args) {
        this.run();
        return 0;
    }
}
```

## Expectation

IOApp compiled by `Scala 2.13.3`:

```java
public static interface IOApp.Simple
extends IOApp {
    public void run();

    public static /* synthetic */ int run$(IOApp.Simple $this, List args) {
        return $this.run((List<String>)args);
    }

    @Override
    default public int run(List<String> args) {
        this.run();
        return 0;
    }

    public static void $init$(IOApp.Simple $this) {
    }
}
```

This means we can't use cats-effect-3 (compiled by dotty) in scala 2.13, as extending `IOApp.Simple` expects the static `IOApp.Simple.$init$` method to exist

**Comment by bishabosha** [comment] 2020-10-08 15:08
Additionally I guess classes extending `IOApp.Simple` should be calling `IOApp.Simple.$init$(this)`

**Comment by sjrd** [comment] 2020-10-08 15:14
The `Mixin` and `Constructors` phase trust the `NoInits` flag to know whether or not a `$init$` method should be emitted/called.

That would mean that the computation of the `NoInits` flag for `IOApp.Simple` is not looking at the parents. That is done in `Namer` and `Scala2Unpickler`, which I'm not familiar with. I suggest assigning to someone who knows these areas.

**Comment by odersky** [comment] 2020-10-10 16:30
Hmm. But there are no initializers; the $init$method is empty. So `NoInits` works as intended.

**Comment by sjrd** [comment] 2020-10-10 16:40
There is no initializer in `Simple` itself, but there is one in its super trait `IOApp`. So `Simple` should inherit the fact that it needs an init.

**Comment by bishabosha** [comment] 2020-10-10 17:22
its not that simple because in this case IOApp.Simple should not get an initialiser:

```scala
trait IOApp {
  val foo = 23
}
object IOApp {
  trait Simple extends IOApp
}
```

**Comment by bishabosha** [comment] 2020-10-19 14:26
i refer to my comment above that  when IOApp and Simple defines no methods Simple should not get an init

**Comment by sjrd** [comment] 2020-11-26 14:55
Some notes about my investigation so far:

* In scalac, there is no equivalent of the `NoInits` flag. Instead, a trait either has a `$init$` method or it doesn't have one at all. This is the only thing that distinguishes a trait with or without initialization. A call to a super `T.$init$` method is generated if and only if `T.$init$` *exists*.
* The decision to generate that method is taken during *parsing*, based on the body of the template:
  * If all the elements of the body satisfy the [`TreeInfo.isInterfaceMember` predicate](https://github.com/scala/scala/blob/7772bdd4f40d691ac84acaf1bea4ef22b43afcd1/src/reflect/scala/reflect/internal/TreeInfo.scala#L50-L59), then no `$init$` is generated; otherwise, a `$init$` is generated.
* In dotty, `NoInits` has a dual purpose:
  * to identify classes and traits whose constructors are *pure* (for elimination in inlining, I believe)
  * and, for traits, to determine whether or not they should receive a `$init$` method

For Scala 2 interop, we need to generate a `$init$` and calls to it if and only if Scala 2 does/would do so. Or, at the very least,
* we need to generate a `$init$` if Scala 2 would do so (because Scala 2 classes inheriting our trait will want to call it)
* we must not call a `$init$` if Scala 2 would not do so (because we would attempt to call a non-existing method)

We *may*, if necessary:
* generate more `$init$` methods, as long as we don't *call* them
* omit to call a `$init$` method even if it exists, if we know that it's a no-op

I don't think those "may"s would help the implementation, though. So I would stick with generate-and-call `$init$` if and only if Scala 2 does.

That means that we sometimes must not generate an `$init$` even though a supertrait has a non-pure constructor. This directly contradicts the first purpose of `NoInits` in dotty: for inlining and its eliminations to be sound, such a trait must not have `NoInits`, but we still must not generate (definitely not *call*) a `$init$`.

Consequently, we need to decouple the generation of `$init$` from the `NoInits` flag.

**Comment by sjrd** [comment] 2020-11-26 15:57
@bishabosha What does the Tasty reader in 2.13 do about this? Does it try to ignore the `$init$` methods coming from TASTy at all when the trait should not have an init?

**Comment by bishabosha** [comment] 2020-11-26 16:30
> @bishabosha What does the Tasty reader in 2.13 do about this? Does it try to ignore the `$init$` methods coming from TASTy at all when the trait should not have an init?

Currently, any `<init>` method owned by a trait is renamed to `$init$` and if it has a stable flag then it will be entered in the trait's scope

**Comment by sjrd** [comment] 2020-11-26 16:39
Thanks. What do you mean by "if it is stable"? I was not aware that a constructor could ever be stable.

**Comment by bishabosha** [comment] 2020-11-26 17:06
Sorry, I actually meant that if the constructor has a stable flag then it will not be entered

**Comment by sjrd** [comment] 2020-11-27 08:56
Oh OK. So yes, apparently class and mixin constructors receive the `StableRealizable` flag (aka `Stable` in TASTy) in `Namer` when their owner satisfied `isNoInitsClass`. Thanks. I'm not sure what I'm going to do with all that yet, but I think I have everything I need now.

**Comment by sjrd** [comment] 2020-11-27 12:35
@bishabosha How could I write a test for the original issue? Is my only option to write a scripted test, or do we have better now?

**Comment by bishabosha** [comment] 2020-11-27 13:04
> do we have better now?

I think thats the only option, without creating your own test framework

**Comment by bishabosha** [comment] 2020-11-27 13:07
Alternatively, I can propose a bytecode test/java reflection test where you curate some examples based on what scala 2 does

**Comment by sjrd** [comment] 2020-11-27 13:18
> Alternatively, I can propose a bytecode test/java reflection test where you curate some examples based on what scala 2 does, without comparing to scala 2 code

That wouldn't work in the solution that I have, because eventually I found a way not to completely align with what Scala 2 does, while still correctly *communicate* to Scala 2 what to do with our traits.

**Comment by sjrd** [comment] 2020-11-27 15:03
Ah! I can't even write a scripted test, because I would need to use Scala 2.13.4 with `-Ytasty-reader`, but that doesn't work because the TASTy has format has already changed since Scala 2.13.4 😬 I'm not even sure how I can possibly test it by hand once, to check whether a future version of the TASTy reader would do the right thing, with my changes.

**Closed** 2020-12-09 11:46 UTC
Labels: M3:high-prio, compat:scala2, exp:intermediate, itype:bug
