### ISSUE TITLE
Exception occurred while typechecking

### ISSUE THREAD

**Issue by liewhite** [lampepfl/dotty#19114] opened 2023-12-01 09:08 UTC
## Compiler version
3.3.1

## Minimized code

With zio imported
```Scala
import zio.stream.*
import zio.*

object Main extends ZIOAppDefault {
  def run: ZIO[Any & (ZIOAppArgs & Scope), Any, Any] = {
    ZStream.range(1,10).collectSome.runDrain
  }
}
```

## Output (click arrow to expand)
[info]      while compiling: <no file>
[info]         during phase: <no phase>
[info]                 mode: Mode(ImplicitsEnabled)
[info]      library version: version 2.13.10
[info]     compiler version: version 3.3.1

**Comment by WojciechMazur** [comment] 2023-12-01 09:49
Duplicate of #18999, works with 3.3.0 and 3.nightly. We should make sure that the fix is backported to LTS branch for 3.3.2

**Closed** 2023-12-04 15:40 UTC
Labels: itype:bug, stat:duplicate, itype:crash, area:library
