### ISSUE TITLE
accepts invalid code with undefined type 

### ISSUE THREAD

**Issue by zhendongsu** [lampepfl/dotty#1701] opened 2016-11-12 07:47 UTC
``` bash
$ scalac-2.12.0 t.scala
t.scala:2: error: not found: type test
  def test (x : test) : Int
                ^
one error found
$ 
$ dotc -version

Dotty compiler version 0.01 -- (c) 2013 LAMP/EPFL
$ 
$ dotc t.scala
Warning: mocking up superclass for module class test
$ 
$ cat t.scala
trait Foo {
  def test (x : test) : Int
} 
$ 
```

**Comment by liufengyun** [comment] 2016-11-13 09:20
Thanks for reporting, @zhendongsu , this is a very good error reporting.

It turns out that the problem is that by default all subdirectory names will be added to `<root>` as package module class and object.  `x: project`, `x: src` and `x: src.dotty` also type check.

I see two fixes here:

- By default, don't add current sub dirs to `-classpath` ( current dir `.` can be added)
- When resolving a TypeName, disqualify package names.

WDYT @smarter  @DarkDimius ?

**Comment by zhendongsu** [comment] 2016-11-13 22:53
Thank you for looking into it, Fengyun!

**Comment by odersky** [comment] 2016-11-16 14:23
@liufengyun I think (2) is the right choice: When resolving a TypeName, disqualify package names.

**Closed** 2016-11-17 10:22 UTC
Labels: area:typer, exp:intermediate, itype:bug, prio:medium, stat:in progress
