### ISSUE TITLE
Potentially unnecessary athrow is emitted when return is inside a nested block

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#5064] opened 2018-08-31 12:36 UTC
The following snippet generates an `athrow` instruction if `return` is used inside a nested block.

```scala
class Test {
  def fun: Int = {
    var a = 10;
    { // throw is generated only when return is nested
      return a
    }
  }
}
```

This seems like e a backend issue and may not be related with how [return expressions](https://www.scala-lang.org/files/archive/spec/2.12/06-expressions.html#return-expressions) are translated (because `NonLocalReturns` phase has no effect).

**Comment by allanrenucci** [comment] 2018-08-31 12:39
Here is the generated bytecode:
```
Compiled from "Test.scala"
public class Test {
  public Test();
    Code:
       0: aload_0
       1: invokespecial #9                  // Method java/lang/Object."<init>":()V
       4: return

  public int fun();
    Code:
       0: bipush        10
       2: istore_1
       3: iload_1
       4: ireturn
       5: athrow
}
```

**Comment by sjrd** [comment] 2024-02-19 09:25
The generated code is now
```
public class Test {
  public Test();
    Code:
       0: aload_0
       1: invokespecial #9                  // Method java/lang/Object."<init>":()V
       4: return

  public int fun();
    Code:
       0: bipush        10
       2: istore_1
       3: iload_1
       4: ireturn
}
```
So this is fixed. It was probably fixed by https://github.com/lampepfl/dotty/pull/14890

Not adding a regression test because it's not an actual error and it most likely covered by the tests in the PR anyway.

**Closed by sjrd** 2024-02-19 09:25 UTC
Labels: prio:low, area:backend, itype:performance
