### ISSUE TITLE
Annotating case class parameter annotates constructor parameter but not field

### ISSUE THREAD

**Issue by sabenuse** [lampepfl/dotty#15665] opened 2022-07-13 13:55 UTC
## Minimized code

```Scala
case class StVo(id: Int, @(Length@field)(32) name: String)

```

## Output

When I call `getAnnotation` on the `name` field of `StVo`:

```java
Length len = namefield.getAnnotation(Length.class);
```

`len` is `null`.

Decompiled code:

```java
public class StVo implements Product, Serializable {
   private final int id;
   // fixme: I need @Length(32) here 
   private final String name;

   // fixme: why is @Length(32) here?
   public StVo(final int id, @Length(32) final String name) {
      this.id = id;
      this.name = name;
   }

   // ...
}
```

**Comment by noti0na1** [comment] 2022-07-23 04:45
The logic is at `PostTyper.removeUnwantedAnnotations`, and documents about the meta annotations: [
scala.annotation.meta](https://www.scala-lang.org/api/current/scala/annotation/meta/index.html).

I'm not sure about the definition of the `Length` annotation in the minimized code. 

> By default, annotations on (val-, var- or plain) constructor parameters end up on the parameter, not on any other entity.

If you want to keep the annotation at the field, you should add `@field` to the annotation definition.

It seems Scala 2 has the same behaviour.

**Comment by smarter** [comment] 2022-07-23 09:58
Duplicate of https://github.com/lampepfl/dotty/issues/12492

**Closed by smarter** 2022-07-23 09:58 UTC
Labels: itype:bug, area:desugar
