### ISSUE TITLE
Opaque types are not usable in the REPL under Java 9+

### ISSUE THREAD

**Issue by mpilquist** [lampepfl/dotty#11884] opened 2021-03-24 17:21 UTC
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
➜  scala3-repl
scala> opaque type Foo = Int
1 |opaque type Foo = Int
  |^^^^^^
  |Illegal start of statement: no modifiers allowed here

scala> object Module:
     |   opaque type Foo = Int
     |   object Foo:
     |     def fromInt(i: Int): Foo = i
     |
// defined object Module

scala> import Module.*

scala> def bar(f: Foo) = println(f)
1 |def bar(f: Foo) = println(f)
  |           ^^^
  |           Not found: type Foo

scala> def bar(f: Module.Foo) = println(f)
1 |def bar(f: Module.Foo) = println(f)
  |           ^^^^^^^^^^
  |           type Foo is not a member of object Module

scala> :reset

scala> object Module:
     |   opaque type Foo = Int
     |   object Foo:
     |     def fromInt(i: Int): Foo = i
     |   def bar(f: Foo) = println(f)
     |   def baz = bar(42)
     |
// defined object Module
```

## Expectation

The top-level definition bug is tracked here: https://github.com/lampepfl/dotty/issues/9879

Not sure what's going on with (1) inability to reference an opaque type defined in an object and (2) lack of opaque type enforcement in the last Module definition. Feels like something about the REPL encoding scheme is at odds with the opaque type implementation scheme.

**Comment by bishabosha** [comment] 2021-03-24 23:50
I can't reproduce this, I tried homebrew distribution and coursier `scala3-repl` and they both work.

Perhaps there is some other `Module` on the classpath that interferes, e.g. if I compile `object Module` and add it to the classpath then I can reproduce.

**Comment by mpilquist** [comment] 2021-03-24 23:56
Aha! It works for me when running RC1 REPL under Java 8 and fails on Java 9+

```scala
➜  java -version
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)
➜  scala3-repl
scala> object Module:
     |   opaque type Foo = Int
     |   object Foo:
     |     def fromInt(i: Int): Foo = i
     |
// defined object Module

scala> def bar(f: Module.Foo) = println(f)
1 |def bar(f: Module.Foo) = println(f)
  |           ^^^^^^^^^^
  |           type Foo is not a member of object Module

scala>
➜  setjdk 1.8
➜  java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.272-b10, mixed mode)
➜  scala3-repl
scala> object Module:
     |   opaque type Foo = Int
     |   object Foo:
     |     def fromInt(i: Int): Foo = i
     |
// defined object Module

scala> def bar(f: Module.Foo) = println(f)
def bar(f: Module.Foo): Unit

scala>
```

**Comment by mpilquist** [comment] 2021-03-24 23:56
Aha! It works for me when running RC1 REPL under Java 8 and fails on Java 9+

```scala
➜  java -version
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)
➜  scala3-repl
scala> object Module:
     |   opaque type Foo = Int
     |   object Foo:
     |     def fromInt(i: Int): Foo = i
     |
// defined object Module

scala> def bar(f: Module.Foo) = println(f)
1 |def bar(f: Module.Foo) = println(f)
  |           ^^^^^^^^^^
  |           type Foo is not a member of object Module

scala>
➜  setjdk 1.8
➜  java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.272-b10, mixed mode)
➜  scala3-repl
scala> object Module:
     |   opaque type Foo = Int
     |   object Foo:
     |     def fromInt(i: Int): Foo = i
     |
// defined object Module

scala> def bar(f: Module.Foo) = println(f)
def bar(f: Module.Foo): Unit

scala>
```

**Comment by bishabosha** [comment] 2021-03-25 00:05
Thanks, yes changing to JDK 14 breaks it for me

**Comment by griggt** [comment] 2021-03-25 00:05
Is this not a duplicate of #11146?  Because `java.lang.Module` exists since JDK 9

**Comment by bishabosha** [comment] 2021-03-25 00:06
> Is this not a duplicate of #11146? Because `java.lang.Module` exists since JDK 9

yes I would say so

**Closed by bishabosha** 2021-03-25 00:06 UTC
Labels: itype:bug

**Comment by mpilquist** [comment] 2021-03-25 00:13
Wow, great find. I almost never use the word `Module` in Scala and just happened to do so here to work around #9879.
