### ISSUE TITLE
[TreeUnpickler] hitting assertion failure: `-Yread-docs` enabled, but no `docCtx` is set.

### ISSUE THREAD

**Issue by tpolecat** [lampepfl/dotty#14190] opened 2021-12-30 16:24 UTC
Hi,

I'm running into an assertion failure [here](https://github.com/lampepfl/dotty/blob/b735803a229586e198bd773f6397ad4d4d085349/compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala#L901) when trying to use Scala 3 with Metals (which uses `InteractiveDriver`, which seems to set the `-Yread-docs` option).

```
Exception in thread "pool-10-thread-9" java.lang.AssertionError: assertion failed: `-Yread-docs` enabled, but no `docCtx` is set.
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:901)
        at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:776)
        ...
```

This only happens for me as far as I can tell (nobody can reproduce it) but it's consistent. I was hoping someone here might be able to explain the circumstance in which this assertion would be triggered, to help us track down what's going on.

The related Metals issue is https://github.com/scalameta/metals/issues/3414

Thanks!

rob

**Comment by tgodzik** [comment] 2021-12-30 17:37
We checked and this seems to happen only on `graalvm-ce-java8` and most likely MacOS

**Comment by kpodsiad** [comment] 2021-12-30 17:40
It happens also on `openjdk_1.8.0_292`, so it may be related to the java version and not just the vendor.

**Comment by smarter** [comment] 2021-12-30 17:40
This needs reproduction steps to be actionable.

**Comment by tgodzik** [comment] 2021-12-30 17:52
It seems that it works if we generate Bloop configuration from sbt, but not scalacli, so this might actually be some misconfiguration in scalacli. I will come back with some more info.

**Comment by tgodzik** [comment] 2022-01-18 11:20
I dug a bit deeper here and it seems this is failing due to a release flag:
```
8 is not a valid choice for -release
  scalac -help  gives more information
exception caught when loading module class package$: java.lang.AssertionError: assertion failed: `-Yread-docs` enabled, but no `docCtx` is set.
exception caught when loading module class language$: java.lang.AssertionError: assertion failed: `-Yread-docs` enabled, but no `docCtx` is set.
Exception in thread "pool-6-thread-5" java.lang.AssertionError: assertion failed: `-Yread-docs` enabled, but no `docCtx` is set.
```

If I remove `-release 8` it works, but `8` should be a valid choice here. Why would it break?

**Comment by tgodzik** [comment] 2022-01-18 12:06
Actually, this got already fixed by https://github.com/lampepfl/dotty/pull/13811

**Closed by tgodzik** 2022-01-18 12:06 UTC
Labels: itype:bug, area:ide, stat:needs info
