### ISSUE TITLE
repl: io from standard library obscures io

### ISSUE THREAD

**Issue by oivulf** [lampepfl/dotty#16549] opened 2022-12-17 15:13 UTC
Dear Scala developers,
I have a project using io.getquill
Importing io.getquill from the console works fine in scala 3.1.1 however it is not found in scala 3.2.1 (from coursier).
console completion suggests StdIn, AnsiColor and other packages in io, but not getquill.
import _root_.io.getquill works fine.
thanks.

**Comment by dwijnand** [comment] 2022-12-17 16:42
Duplicate of #15904

**Closed by dwijnand** 2022-12-17 16:42 UTC
