### ISSUE TITLE
`-coverage-out` generates coverage information for macro code coming from referenced libraries

### ISSUE THREAD

**Issue by arixmkii** [lampepfl/dotty#15490] opened 2022-06-21 10:37 UTC
## Compiler version

3.2.0-RC1

If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized code

*Macro.scala*
```scala
package excludeme

import scala.quoted.*

object Macro {

  inline def toUpperS(s: String): String = ${ Macro.toUpperSImpl('s) }

  def toUpperSImpl(s: Expr[String])(using q: Quotes): Expr[String] = '{ ($s.toUpperCase) } // will add coverage info
}
```

*Main.scala*
```scala
import excludeme.*

@main def main: Unit =
  println(Macro.toUpperS("test"))
```

## Minimized code (using third party library)

Keeping this for the sake of history how it was originally reported.

```Scala
import io.circe.*
import io.circe.generic.semiauto.*
import io.circe.syntax.*

implicit val basicCodec: Codec[Tuple1[String]] = deriveCodec[Tuple1[String]]

@main def main: Unit =
  println(Tuple1("value").asJson.noSpaces)
```

Full project is here https://github.com/arixmkii/macro_cov_3.2.0-RC1
I will think about a better minimal example, because `circe-generic` is a heavy one. May be with 2 source files and using one with macro as pre-compiled class.

## Output

`scoverage.coverage` file contains records of
```
modules/core/shared/src/main/scala-3/io/circe/Derivation.scala
```

## Expectation

No coverage data for third party libraries as source might not be provided for them.

Originally posted here https://github.com/scoverage/scalac-scoverage-plugin/issues/474 I think that workarounds could be added to report generation to handle such cases (probably giving out a warning by default), but I'm not sure if this is the right approach for dealing with macros from referenced libraries.

**Comment by Kordyjan** [comment] 2022-06-22 11:55
Thanks for the minimalization!

**Comment by nicolasstucki** [comment] 2022-06-22 14:19
What is work in the minimized version? What is the expected output? Which command should I use to reproduce the issue?

**Comment by arixmkii** [comment] 2022-06-22 14:44
```bash
# compile Macro
./scala3-3.2.0-RC1/bin/scalac Macro.scala
# remove source (for clean experiment) and keep only compiled
rm Macro.scala
# compile program with coverage
./scala3-3.2.0-RC1/bin/scalac -coverage-out:. Main.scala
# check coverage data
cat scoverage.coverage | grep -A14 Macro.scala
```

Outputs
```
Macro.scala
<empty>
Main$package$
Object
<empty>.Main$package$
main
203
217
8
toUpperCase
Apply
false
0
false

```

But we removed this source and used only compiled module. So, there should be no coverage info for this. Same is true for macros coming from third party libraries (which then breaks coverage report, because sources can't be found).

I expect that there will be no coverage info generated from code instantiated via macro.

**Comment by lefou** [comment] 2022-10-20 13:06
I think, generating coverage data for code that comes from macros is a nice thing. In scoverage 1.x, it was not possible at all to get coverage for macro code. (E.g. is was not easily possible, to get coverage data for Mill targets which are written with the help of the `T{ }`). But the reporter should be _a)_ able to gracefully handle missing source files and _b)_  only count those macros into metrics which are part of the actual code base. As a consequence, we need to distinguish between own and foreign macro code, otherwise we might generate incorrect coverage metrics.

**Comment by smarter** [comment] 2022-11-22 15:36
@TheElectronWill is this issue already fixed by https://github.com/lampepfl/dotty/pull/16235/commits/743f3cc1552f92d2b24bdf37e2b2f19298e71ba8 ?

**Comment by larochef** [comment] 2022-11-23 13:57
@smarter I have the same issue, if I use scala 3.2.2-RC1 the coverage generation is successful

**Comment by TheElectronWill** [comment] 2022-11-23 14:01
I was about to say that we should check that it's fixed by my PR, by trying to reproduce the bug with the latest version of the compiler :smile:
It seems that it worked as intended. Thank you @larochef :)

**Closed by TheElectronWill** 2022-11-23 14:01 UTC
Labels: itype:bug, area:coverage
