### ISSUE TITLE
Type projection should be enabled on type bounds even when -strict flag is on.

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#4278] opened 2018-04-09 10:33 UTC
Currently, type projection is enabled only when -strict flag is off.

However, type projection is actually sound when only using it on type bounds.

I created an example to demonstrate that:

``` scala
object Main {
  
  trait X[U] {
    type R >: U
  }
  trait Y[V] {
    type R <: V
  }

  abstract class Converter[U, V] {
    val r: Y[V] & X[U]
    type R = r.R
  }

  def soundCast[U, V, C <: Converter[U, V], R >: C#R <: C#R](u: U): V = {
    (u : R)
  }

  def main(arguments: Array[String]): Unit = {
    val myConverter = new Converter[Seq[String], Iterable[Any]] {
      val r = new Y[Iterable[Any]] with X[Seq[String]] {}
    }

    soundCast[Seq[String], Iterable[Any], myConverter.type, myConverter.R](List("foo"))
  }
  
  
}
```
https://scastie.scala-lang.org/Atry/rZb4NN4UQnK891XmzlI8Qg

`soundCast` sounds because there is a soundness check on the type application when calling `soundCast`. The soundness check at the definitions of type bounds of `soundCast` is unnecessary.

**Comment by Blaisorblade** [comment] 2018-04-09 21:53
Wouldn't that allow this unsound example?

```scala
object Main {
  trait X[U] {
    type R >: U
  }
  trait Y[V] {
    type R <: V
  }

  abstract class Converter[U, V] {
    val r: Y[V] & X[U]
    type R = r.R
  }

  def unsoundCast[U, V, C <: Converter[U, V], R1 <: C#R, R2 >: C#R](u: U): R2 = {
    (u : R2)
  }
  // unsoundCast is equivalent to:
  // def unsoundCast2[U, V, C <: Converter[U, V]](u: U): V = {
  //   (u : C#R)
  // }
  def soundNoncast[U, V, C <: Converter[U, V]](u: U): U = u

  def main(arguments: Array[String]): Unit = {
    val myConverter = new Converter[Seq[String], Iterable[Any]] {
      val r = new Y[Iterable[Any]] with X[Seq[String]] {}
    }
    type MyConv = Converter[Int, String]

    // unsoundCast[Seq[String], Iterable[Any], myConverter.type, myConverter.R](List("foo"))
    unsoundCast[Int, String, MyConv, Int, String](1): String
    //soundCast[Seq[String], Iterable[Any], myConverter.type, myConverter.R](List("foo"))
    //unsoundCast2[Int, String, MyConv](1)
    soundNoncast[Int, String, MyConv](1)
  }
}
```

Current output:
```scala
$ sbt
> dotc -strict -d out tests/pos/i4278a.scala
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Running dotty.tools.dotc.Main -classpath /Users/pgiarrusso/git/dotty/library/target/scala-2.12/dotty-library_2.12-0.8.0-bin-SNAPSHOT-nonbootstrapped.jar -strict -d out tests/pos/i4278a.scala
-- Error: tests/pos/i4278a.scala:14:52 -----------------------------------------
14 |  def unsoundCast[U, V, C <: Converter[U, V], R1 <: C#R, R2 >: C#R](u: U): R2 = {
   |                                                    ^
   |                                         C is not a legal path
   |                                         since it is not a concrete type
-- Error: tests/pos/i4278a.scala:14:63 -----------------------------------------
14 |  def unsoundCast[U, V, C <: Converter[U, V], R1 <: C#R, R2 >: C#R](u: U): R2 = {
   |                                                               ^
   |                                         C is not a legal path
   |                                         since it is not a concrete type
two errors found
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last dotty-compiler/compile:runMain for the full output.
[error] (dotty-compiler/compile:runMain) Nonzero exit code returned from runner: 1
[error] Total time: 2 s, completed Apr 9, 2018 11:50:35 PM
```

**Comment by Atry** [comment] 2018-04-10 02:28
`unsoundCast[Int, String, MyConv, Int, String]` should not compile if there is a totality check for the prefix `MyConv` when for unify `Int` with `>: MyConv#R`.

If I understand correctly, the idea of DOT calculus is delay all type bounds check until class instantiation. Method call can be treated the same as class instantiation.

**Comment by Atry** [comment] 2018-04-10 02:33
Note that current implementation of dotty does not have totality check feature, there is a stability check instead, which is unsound on infinite loops.

A totality check should allow `nullaryTotalMethod.T` when `nullaryTotalMethod` is total but not stable.

**Comment by Blaisorblade** [comment] 2018-04-10 19:59
First, all type systems will reject sound programs; the question is which programs matter enough to make the effort to support them. Do you have significant amounts of real-world code where this pattern is essential?

> If I understand correctly, the idea of DOT calculus is delay all type bounds check until class instantiation. Method call can be treated the same as class instantiation.

The intuition is somewhat correct, though DOT cannot be easily extended with type projections from classes — in fact, it's thanks to DOT that we learned that type projections are unsound, and that most strategies that seem to work fail miserably.
Type members of objects are known to have consistent bounds, but that doesn't hold for classes.
Right now we only allow type projections on types known to be realizable, and we don't know that for type variables.

> unsoundCast[Int, String, MyConv, Int, String] should not compile if there is an existence check for the prefix MyConv when unifying Int with >: MyConv#R.

OK, so while initially you propose to rely on an existing check, now you propose to add a check and reject programs that are currently accepted. Checking all arguments for realizability seems likely to break too many programs — realizability in strict mode requires that _all non-mutable fields_ are known to be realizable.

Maybe you only want to check `MyConv` because it's used in a way that requires it to be realizable? But that idea doesn't work immediately, because I can make `MyConv` and `R2` part of separate type applications:

```scala
class Foo[U, V, C <: Converter[U, V]] {
  def unsoundCastInside[R1 <: C#R, R2 >: C#R]: R2 = {
  }
}
def unsoundCastOutside[U, V, C <: Converter[U, V]](u: U) = new Foo[U, V, C]
unsoundCastOutside[Int, String, MyConv](1).unsoundCastInside[Int, String]
```

The best interpretation I can give it is:
- distinguish types and realizable types "somehow" — one standard way would be to make that part of the kind (though Scala doesn't really have kinds right now);
- if you project out of a type argument `T`, infer that `T` must have a "realizability-requiring" kind;
- if a type parameter has a "realizability-requiring" kind, check that the corresponding type argument is realizable at application-site.

In this variant I can't immediately find a loophole (though there might be one), but that doesn't mean this extension is sound. Also, somebody should figure out how "realizability-requiring" propagates.

Overall, I'm convinced this proposal isn't complete, and I'm not sure it's completable.

**Comment by Atry** [comment] 2018-04-11 02:34
On the type application `unsoundCastInside[Int, String]`, you are unifying `Int` with `<: MyConv#R` and `String` with `>: MyConv#R`, which should be sound only when `MyConv` is a singleton type.

Type projection can be seen as an existential type (`A#B` vs `a.B forSome { val a: A }`), and existential types are sound in Coq and other languages.

Why are they unsound in Dotty? I think the cause is type unification.

**Comment by Atry** [comment] 2018-04-11 02:39
Thought, I agree that Dotty does not have to be complete in type system, as those evidence of realizability can be emulated in objects, especially objects of phantom types.

**Comment by odersky** [comment] 2018-04-11 07:06
@Atry I think to understand unsoundness, you need to read the papers on DOT and ideally also the theses by Nada Amin and Sandro Stucki. It has nothing to do with implementation issues. No, existential quantification is not sound in Scala or in DOT, at least not if you take the naive definition. Why is Scala different from Coq here? In a nutshell: Scala has type definitions embedded in records and it also has intersections. This means you may get conflicting type definitions (the so called bad bounds problem). Nada Amin has shown that this problem is unavoidable once you combine type members with bounds and intersection types.

**Comment by Atry** [comment] 2018-04-11 19:06
@odersky I did not mean type projection is generally sound. I mean type projection is actually sound **when only using it on type bounds**, along with a realizability check when unifying a type argument with type bound of type projection.

**Comment by odersky** [comment] 2018-04-11 21:33
But why? We'd need a proof that this is the case. For the moment I am not even sure what the exact statement is you are making.

**Comment by Blaisorblade** [comment] 2018-04-13 16:07
@odersky 
Thinking about it again, I now might understand what @Atry proposes. A variant where soundness is more plausible is to have type variables ranging only over realizable types, but it's hard to design an API for that — using supertype or subtype constraints, à la `X <: Singleton`, is unsound.

What @Atry proposes might be implementable, but soundness is less obvious. But before deciding whether I like it or not, I'd like to finish #4036.

**Comment by Atry** [comment] 2018-04-13 18:24
My proposal is:

``` scala
trait A {
  type B // Allowed
}

trait C {

  // Try to create an alias of type projection. Disallowed.
  // type Alias = A#B

  type D >: A#B // Allowed
  type E <: A#B // Allowed
  type F >: A#B <: A#B // Allowed
}

def a(p: A#B) = ??? // Allowed

def b(p: (A { type B >: Int <: String })#B) = ??? // Allowed

def c(p: (A { type B <: Int })#B) = ??? // Allowed

def d[X <: (A { type B >: Int <: String })#B](i: Int): String = i: X : String // Allowed

def e[X <: (A { type B >: Int <: AnyVal)#B](i: Int): AnyVal = i: X : AnyVal // Allowed

/*
def f(i: Int) : String = {
  // Try to instantiate a type of type projection. Disallowed.
  type X = (A { type B >: Int <: String })#B;
  i: X: String
}

def g(i: Int) : String = {
  // Try to instantiate a type of type projection. Disallowed.
  i: (A { type B >: Int <: String })#B: String
}

def h(ab: A#B) = {
  // Try to instantiate a type of type projection. Disallowed.
  Predef.identity[A#B](ab)
}

*/

// Allowed
def i(ab: A#B) = {
  Predef.identity[ab.type](ab)
}

b(1) // Disallowed
b("a") // Disallowed
c(2) // Disallowed

c {
  val evidence = new A { type B = Int }
  3 : evidence.B
} // Allowed

// Try to instantiate a type of type projection. Disallowed.
d[(A { type B >: Int <: String })#B](4) 

val evidence = new A { type B = Int }
e[evidence.B](5) // Allowed
```

**Comment by Atry** [comment] 2018-04-13 19:00
//We actually does not have to ch

I finally found that the realizability check is actually unnecessary. I think just check if the type argument is an abstract type is enough, because an abstract type must have been proven realize in another places

**Comment by Blaisorblade** [comment] 2018-04-13 19:38
> If you need a proof, I can create the identical code of all the above examples in Coq.

That's not a type soundness proof. [This](https://github.com/TiarkRompf/minidot/blob/master/popl17/dot.v) is a soundness proof.

**Comment by Blaisorblade** [comment] 2018-04-13 20:28
@Atry 
I still haven't seen an argument why we should add "this feature" or even discuss it.

But that doesn't matter. I'm afraid I have to close this proposal because it appears to be unfinished, vague, evolving and full of unsupported and unproven claims of soundness.

The problem isn't that you don't have evidence. The problem is that you keep making claims that are either too vague to have meaning (see https://en.wikipedia.org/wiki/Not_even_wrong) or that are false.

For instance "the identical code of all the above examples in Coq" makes no sense.

Your "example rules" aren't actual rules, and reference concepts that don't exist in DOT ("type unification"?) or are ambiguous ("definition of the type projection"?).

If you are interested and motivated, I encourage you to learn how to actually do soundness proofs. https://softwarefoundations.cis.upenn.edu/ is a good starting point.

**Closed by Blaisorblade** 2018-04-13 20:28 UTC
Labels: itype:language enhancement

**Comment by Atry** [comment] 2018-04-13 21:18
I just want to figure out that this is not a discussion of adding a feature. Instead, it's about how to fix an existing feature.

Secondly, I admit I am not familiar with dotty's implementation details. Those suggestion about typer may be vague or ambiguous. However, the basic idea is simple and clear:

 * Type projection can be allowed on type bounds or the type of terms
