### ISSUE TITLE
Opaque type aliases not working as top level statements in repl

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#12748] opened 2021-06-08 13:58 UTC
Trying to define opaque type as a top-level statement in the repl is causing a parser error. It is also not working if opaque type definition is loaded from the file that is normally passing the compilation, using `:l`. Wrapping opaque type in object solves the problem.

## Compiler version
master branch as of commit d7d4a9f

## Minimized code
Any opaque type definition for example:
```Scala
opaque type L = Int
```

## Output

```scala
1 |opaque type L = Int
  |^^^^^^
  |Illegal start of statement: this modifier is not allowed here
```

## Expectation
Opaque type is defined without errors

**Comment by tgodzik** [comment] 2021-06-08 14:03
This looks like an issue in the Parsers:

https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/parsing/Parsers.scala#L3829

Seems that somehow `isDefIntro(modifierTokens)` is false despite there being an explicit check for soft modifiers. Does the REPL wrap the code somehow, that might be causing this issue?

**Comment by bishabosha** [comment] 2021-06-08 14:06
duplicate of https://github.com/lampepfl/dotty/issues/9879

**Closed by bishabosha** 2021-06-08 14:06 UTC
Labels: area:parser, itype:bug
