### ISSUE TITLE
given declaration picks wrong type

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#12802] opened 2021-06-12 16:57 UTC
## Compiler version

3.0.0

## Minimized code

```Scala
import scala.quoted._

object Boo:
  def foo(using Quotes): Unit =
    import quotes.reflect._
    given Option[Symbol] = Some[Symbol](???)
```

## Output

```scala
Found:    Some[x$1.reflect.Symbol]
Required: Option[Symbol²]

where:    Symbol  is a type in trait reflectModule with bounds <: AnyRef
          Symbol² is a class in package scala
```

## Expectation
Successful compilation since both 'Symbol' should refer to reflect.Symbol and not scala.Symbol

**Comment by odersky** [comment] 2021-06-13 16:43
The problem is that resolving `quotes.reflect` requires an implicit search, which will need to evaluate the `given`, which will again need to look at the import that's currently being completed. If the import is a wildcard import, it is skipped, which explains the error message. if the import is explicit, as in
```scala
  def bar(using Quotes): Unit =
    import quotes.reflect.Symbol
    given Option[Symbol] = Some[Symbol](???)
```
one gets a Cyclic error message instead:
```
-- [E046] Cyclic Error: i12802.scala:9:17 --------------------------------------
9 |    given Option[Symbol] = Some[Symbol](???)
  |                 ^
  |                 Cyclic reference involving val <import>

longer explanation available when compiling with `-explain`
```

**Closed** 2021-06-15 14:42 UTC
Labels: itype:bug
