### ISSUE TITLE
Newlines should be added after each interaction in REPL

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#4486] opened 2018-05-08 16:56 UTC
![image](https://user-images.githubusercontent.com/20694662/39770977-3ab93daa-5323-11e8-8e97-38963e35d7a8.png)
Content in the REPL now appears to be overcrowded, making it difficult for users to distinguish between various kinds of information.I think Dotty REPL should insert extra line breaks like Ammonite and Scala 2's REPL to reduce reading difficulty.

**Comment by smarter** [comment] 2018-05-08 17:30
Duplicate of https://github.com/lampepfl/dotty/issues/1369, WIP PR at https://github.com/lampepfl/dotty/pull/3911

**Closed by smarter** 2018-05-08 17:30 UTC
