### ISSUE TITLE
case objects desugaring needs to implement Product0

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#915] opened 2015-11-02 17:06 UTC
```scala
./scala-scala/src/library/scala/collection/immutable/List.scala:417: error: object creation impossible, since:
it has 2 unimplemented members.
/** As seen from module class Nil$, the missing signatures are as follows.
 *  For convenience, these are usable as stub implementations.
 */
  def productArity: => Int = ???
  def productElement: (n: Int)Any = ???

case object Nil extends List[Nothing] {
                  ^
```

**Comment by smarter** [comment] 2015-11-02 22:11
Duplicate of #723.

**Comment by odersky** [comment] 2015-11-05 14:00
Fixed by now.

**Closed by odersky** 2015-11-05 14:00 UTC
Labels: Stdlib
