### ISSUE TITLE
Sealed traits passed as inline arguments cause an NPE

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#9655] opened 2020-08-27 14:42 UTC
Sealed traits passed as inline arguments cause an NPE
```scala
inline def foo[T](inline body: T): T = body

def test = foo {
  sealed trait Status
  object Active extends Status
}
```

_Originally posted by @nicolasstucki in https://github.com/lampepfl/dotty/issues/9572#issuecomment-681991323_

**Comment by odersky** [comment] 2020-08-28 18:08
Duplicate of #9572

**Closed** 2020-08-29 07:09 UTC
