### ISSUE TITLE
3.2.0 regression around match types

### ISSUE THREAD

**Issue by Bersier** [lampepfl/dotty#15926] opened 2022-08-27 15:08 UTC
## Compiler version

3.2-RC1, 3.2-RC2, 3.2-RC3, 3.2-RC4

## Minimized code

```Scala
@main def main(): Unit =
  println(summon[Sum[Minus[Succ[Zero]], Minus[Succ[Zero]]] =:= Minus[Succ[Succ[Zero]]]])

sealed trait IntT
sealed trait NatT extends IntT
final case class Zero() extends NatT
final case class Succ[+N <: NatT](n: N) extends NatT
final case class Minus[+N <: Succ[NatT]](n: N) extends IntT

type NatSum[X <: NatT, Y <: NatT] <: NatT = Y match
  case Zero => X
  case Succ[y] => NatSum[Succ[X], y]

type NatDif[X <: NatT, Y <: NatT] <: IntT = Y match
  case Zero => X
  case Succ[y] => X match
    case Zero => Minus[Y]
    case Succ[x] => NatDif[x, y]

type Sum[X <: IntT, Y <: IntT] <: IntT = Y match
  case Zero => X
  case Minus[y] => X match
    case Minus[x] => Minus[NatSum[x, y]]
    case _ => NatDif[X, y]
  case _ => X match
    case Minus[x] => NatDif[Y, x]
    case _ => NatSum[X, Y]
```

## Output

```scala
Cannot prove that Minus[NatSum[Succ[Succ[Zero]], NatT]] =:= Minus[Succ[Succ[Zero]]].

Note: a match type could not be fully reduced:

  trying to reduce  NatSum[Succ[Succ[Zero]], NatT]
  failed since selector  NatT
  does not match  case Zero => Succ[Succ[Zero]]
  and cannot be shown to be disjoint from it either.
  Therefore, reduction cannot advance to the remaining case

    case Succ[y] => NatSum[Succ[Succ[Succ[Zero]]], y]
```

## Expectation
Code should compile, as in Scala 3.1.3.

**Comment by WojciechMazur** [comment] 2022-08-27 16:08
Bisect points to https://github.com/lampepfl/dotty/commit/02f775f791272cac4dd7777a8808e5979c057007 
What's interesting Scala 3.1.3 is the only final version allowing to compile this snippet (started working since 3.1.3-RC2)

**Comment by Bersier** [comment] 2022-08-27 16:51
Expected reduction:
```Scala
Sum[Minus[Succ[Zero]], Minus[Succ[Zero]]]
```
```Scala
Minus[NatSum[Succ[Zero], Succ[Zero]]]
```
```Scala
Minus[NatSum[Succ[Succ[Zero]], Zero]]
```
```Scala
Minus[Succ[Succ[Zero]]]
```
Apparent reduction:
```Scala
Sum[Minus[Succ[Zero]], Minus[Succ[Zero]]]
```
```Scala
Minus[NatSum[Succ[Zero], Succ[Zero]]]
```
```Scala
Minus[NatSum[Succ[Succ[Zero]], NatT]]
```

**Comment by SethTisue** [comment] 2022-10-18 15:31
notes on the minimization:
- changing `Zero` to a `case object` (and using `Zero.type` in place of `Zero`) doesn't matter, so I guess we'll leave that as is
- `NatDif` plays no role here, so we can delete it and write `Sum` and `NatSum` as follows:

```scala
type NatSum[X <: NatT, Y <: NatT] <: NatT = Y match                                                 
  case Zero => X                                                                                    
  case Succ[y] => NatSum[Succ[X], y]                                                                
                                                                                                    
type Sum[X <: IntT, Y <: IntT] <: IntT = Y match                                                    
  case Minus[y] => X match                                                                          
    case Minus[x] => Minus[NatSum[x, y]]                                                            
```

here's a little script for verifying the pos/neg status on the three Scala versions:

```bash
scala-cli compile -S 3.1.2     . || echo "it failed on 3.1.2"
scala-cli compile -S 3.1.3     . && echo "it compiled on 3.1.3"
scala-cli compile -S 3.2.0-RC1 . || echo "it failed on 3.2.0-RC1"
```

**Comment by SethTisue** [comment] 2022-10-18 15:36
and sadly, the bug only reproduces if you go through the first reduction step first. if you just write the second reduction step directly:

```scala
summon[Minus[NatSum[Succ[Zero], Succ[Zero]]] =:= Minus[NatSum[Succ[Succ[Zero]], Zero]]]
```

then it compiles in all four Scala versions

**Comment by SethTisue** [comment] 2022-10-18 15:50
We hope to find some connection with type avoidance, since that's the subject of the reverted PR that briefly made this work.

Dale observes that in this code:

```
type Sum[X <: IntT, Y <: IntT] <: IntT = Y match                                                    
  case Minus[y] => X match                                                                          
    case Minus[x] => Minus[NatSum[x, y]]
```

perhaps type avoidance (the subject of the reverted PR) is inappropriately kicking in thinking that `y` needs to be avoided in `NatSum[x,y]`

**Comment by SethTisue** [comment] 2022-10-18 16:04
Wojiech's bisect points to #15341 which partially reverted Olivier's #13780. But understanding that involves understanding a bigger, rather convoluted story which is summarized at #15373. Along the way, Guillaume's big type avoidance PR #14026 was first merged, then reverted, but not completely — the code was kept, but put behind a flag. A more recent development is Martin's level-checking PR, #15746.

(I hope I haven't misrepresented the story. At minimum, these are relevant issue and PR numbers.)

**Comment by SethTisue** [comment] 2022-10-18 16:51
I failed to find any further useful minimizations, but I'm also not sure I tried every possible avenue :-/

**Comment by smarter** [comment] 2022-10-18 16:59
We ruled out type avoidance (turning it off completely doesn't make a difference), the issue does go away if canWidenAbstract is forced to true in https://github.com/lampepfl/dotty/blob/96d4ccdcfc3e0ff4d62e969374b92b6db590ccd3/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L3117

**Comment by mbovel** [comment] 2022-10-18 19:24
Extracting the inner match makes the code compile:

```scala
type Sum[X <: IntT, Y <: IntT] <: IntT = Y match
  case Zero => X
  case Minus[y] => Sum1[X, y]
  case _ => X match
    case Minus[x] => NatDif[Y, x]
    case _ => NatSum[X, Y]

type Sum1[X <: IntT, y <: IntT] <: IntT = X match
  case Minus[x] => Minus[NatSum[x, y]]
  case _ => NatDif[X, y]
```

**Comment by mbovel** [comment] 2022-10-18 21:08
That would also solves this issue:

```diff
diff --git a/compiler/src/dotty/tools/dotc/core/TypeComparer.scala b/compiler/src/dotty/tools/dotc/core/TypeComparer.scala
index 8eb6a490010..dbe89ec385e 100644
-      else if matches(canWidenAbstract = true) then
+      else if !caseLambda.exists && matches(canWidenAbstract = true) then
```

But make these 2 `OK` tests fail:

https://github.com/lampepfl/dotty/blob/96d4ccdcfc3e0ff4d62e969374b92b6db590ccd3/tests/neg/wildcard-match.scala#L26-L37

It's really about the heuristics of when to widen abstract types and when not to.

**Closed** 2023-06-06 12:48 UTC
Labels: itype:bug, area:typer, area:match-types
