### ISSUE TITLE
Unreachable case warning

### ISSUE THREAD

**Issue by tusharmath** [lampepfl/dotty#16379] opened 2022-11-19 08:44 UTC
## Compiler version

3.2.2-RC1

## Minimized code

```Scala
trait Tag extends Any
type Base = List[String]

type Field = Base with Tag
sealed trait Foo {
  self =>
  def path: Field
}

object Foo {

  type Labelled = (String, Foo)

  final case class Foo0(override val path: Field) extends Foo
  final case class Foo1(override val path: Field) extends Foo

  def foo(ast: Foo): Unit = ast match
    case Foo0(_) => ???
    case Foo1(_) => ???
    case _       => ???
}
```

## Output

```bash
Unreachable case
Unreachable case
```

## Expectation
```
Unreachable case except for null
```

Related to #16379

**Comment by KacperFKorban** [comment] 2022-11-19 09:44
Minimized a bit:
```scala
trait Tag
type Field = Option[String] & Tag // has to be an intersection type

sealed trait Foo {
  def path: Field
}
final case class Bar(path: Field) extends Foo

def foo(ast: Foo): Unit = ast match {
  case Bar(_) => ??? // if we change it to `_: Bar` it is no longer unreachable
  case _       => ???
}
```

**Comment by tusharmath** [comment] 2022-11-19 14:07
Minimized it a little further

```scala
  trait Tag

  type Field = List[String] & Tag
  sealed trait Foo

  final case class Foo0(path: Field) extends Foo

  def foo(ast: Foo): Unit = ast match
    case Foo0(_) => ???
    case _       => ???

```

**Comment by odersky** [comment] 2022-11-20 10:31
I guess it has to do with the fact that type `Field` is empty. There are no values except `null` that populate it, and under `-Yexplicit-nulls` even `null` is not possible. But without `-Yexplicit-nulls`, `null` is a possible instance, so the warning looks wrong to me.

**Comment by tusharmath** [comment] 2022-11-20 10:50
Updated the issue, it should have returned `Unreachable case except for null`.

**Comment by SethTisue** [comment] 2022-12-21 16:53
We currently only emit such a warning about the scrutinee itself being null, not about some arbitrary subcomponent of the scrutinee being null. So it seems everything here is working as designed. Therefore, it seems we should just close this, since it's merely just a perhaps-theoretically-arguably-improvable warning message.

**Closed** 2022-12-21 16:54 UTC
Labels: itype:bug, area:pattern-matching
