### ISSUE TITLE
Missing DOS batch files in Scala 3?

### ISSUE THREAD

**Issue by cebaraldi** [lampepfl/dotty#12593] opened 2021-05-25 11:21 UTC
Hello!

Sorry for bothering you w/ such details. I am missing the usually available dos batch for the Windows version of Scala 3. 

As a workaround and because I hoped these batch files could be created as a side-effect, So I tried to compile this version myself. The sbt compile command stopped w/ the following lines:
--------------------------------------------------------
sbt:scala3> compile
[info] Unpacking scalajs-ir sources to C:\Users\ceb\Downloads\dotty-3.0.0\compiler\target\scala-3.0.0-RC2-bin-20210325-ab2664f-NIGHTLY\src_managed\main\scalajs-ir-src...
[info] compiling 7 Java sources to C:\Users\ceb\Downloads\dotty-3.0.0\interfaces\target\classes ...
[info] compiling 66 Scala sources and 25 Java sources to C:\Users\ceb\Downloads\dotty-3.0.0\library\target\scala-3.0.0-RC2-bin-20210325-ab2664f-NIGHTLY\classes ...
[info] compiling 7 Scala sources to C:\Users\ceb\Downloads\dotty-3.0.0\tasty\target\scala-3.0.0-RC2-bin-20210325-ab2664f-NIGHTLY\classes ...
[info] compiling 480 Scala sources and 6 Java sources to C:\Users\ceb\Downloads\dotty-3.0.0\compiler\target\scala-3.0.0-RC2-bin-20210325-ab2664f-NIGHTLY\classes ...
[error] stack trace is suppressed; run last scala3-compiler / Compile / managedResources for the full output
[error] (scala3-compiler / Compile / managedResources) java.lang.IllegalArgumentException: One of setGitDir or setWorkTree must be called.
[error] Total time: 168 s (02:48), completed 25 May 2021, 13:01:45
--------------------------------------------------------

What am I missing and/or what is my mistake?

Possibly it would be easier to edit the batch files from a previous version like 2.13.6? As you will notice, I am eager to try Scala 3 out. In the meantime I will start first from my usual Linux OS.

Congratulations for the new release! Thanks a lot and kind regards

Claudio

**Comment by michelou** [comment] 2021-05-25 11:45
Duplicate of #12551.

**Closed by michelou** 2021-05-25 11:45 UTC
