### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by okarmusk** [lampepfl/dotty#12851] opened 2021-06-16 20:39 UTC
I'm not sure but I found unexpected behavior after compilation `Scala 3` code with `SBT`.
`build.sbt` looks like:

```
name := "scala-cheat-sheet"
version := "1.0"
scalaVersion := "3.0.0"

Compile/mainClass := Some("com.okarmusk.Main")
```

The main object is located under `src/main/scala/com/okarmusk` and looks like:
```
package com.okarmusk

object Main {
  def main(args: Array[String]): Unit = {
    println("Hello world!")
  }
}
```

I sequentially run commands:
* `sbt clean`
* `sbt package`
* `scala target/scala-3.0.0/scala-cheat-sheet_3-1.0.jar`

As the result I obtained:
```
Error: Could not find or load main class target.scala-3.0.0.scala-cheat-sheet_3-1.0.jar
Caused by: java.lang.ClassNotFoundException: target.scala-3.0.0.scala-cheat-sheet_3-1.0.jar
```

Problem exists on scala 3 version `Scala code runner version 3.0.1-RC1 -- Copyright 2002-2021, LAMP/EPFL`, on scala 2 example works as expected.

OS: xubuntu 20.04
sbt: 1.5.2
scala: 3.0.1 RC

Issue exists also in official scala 3.0.0 version

It is worth to notice that when I run `sbt run` the program executes correctly.

**Comment by SethTisue** [comment] 2021-06-16 20:43
duplicate of https://github.com/lampepfl/dotty/issues/12569 ?

**Comment by okarmusk** [comment] 2021-06-16 20:48
If needed, you can pin it as duplicate, but in this issue I want to underline, that issue exists on pure scala 3 binary, not wrapped by `snips sdk` or any other stuff.
Btw I feel that topic [#12569](https://github.com/lampepfl/dotty/issues/12569) died cause of no response...

**Comment by som-snytt** [comment] 2021-06-16 20:51
I'll update here if the fix is scala-only and not sbt. btw, snips is a dir name in my prompt.

**Comment by okarmusk** [comment] 2021-06-16 20:56
I've created issue on `sbt` repo and it was redirect as scala 3 issue. For more information, please check [#6541](https://github.com/sbt/sbt/issues/6541).
I've been terrified when I saw such kind of error, especially when I switch back to scala 2 and everything works.

**Comment by SethTisue** [comment] 2021-06-16 21:11
> but in this issue I want to underline, that issue exists on pure scala 3 binary, not wrapped by snips sdk or any other stuff

(that would be appropriate as a comment on the other ticket)

**Closed by SethTisue** 2021-06-16 21:11 UTC
Labels: itype:bug
