### ISSUE TITLE
Dotty Doc Table of content does not unfold level 3 

### ISSUE THREAD

**Issue by MasseGuillaume** [lampepfl/dotty#3057] opened 2017-09-04 12:46 UTC
## To reproduce:

open http://dotty.epfl.ch/docs/reference/union-types.html

click on "NEW TYPES" in the Table of content (unfolds level 3)

click on "Union types" in the Table of content

## Obtained:

```
BLOG
USAGE 
REFERENCE
  NEW TYPES
  ENUMS
  OTHER NEW FEATURES
  CHANGED FEATURES
  DROPPED FEATURES
CONTRIBUTING
INTERNALS
RESOURCES
```

## Expected

```
BLOG
USAGE 
REFERENCE
  NEW TYPES
    Intersection types
    Union types
    Type lambdas
    Implicit Function Types
    Phantom Types
    Literal Singleton Types
  ENUMS
  OTHER NEW FEATURES
  CHANGED FEATURES
  DROPPED FEATURES
CONTRIBUTING
INTERNALS
RESOURCES
```

## Bonus point

it would be nice to show the active page in the TOC

**Comment by smarter** [comment] 2018-01-11 01:24
Duplicate of https://github.com/lampepfl/dotty/issues/2659

**Closed by smarter** 2018-01-11 01:24 UTC
