### ISSUE TITLE
Java interop: NoSuchMethodError for Java method returning T <: Object & Comparable

### ISSUE THREAD

**Issue by sjrd** [lampepfl/dotty#9441] opened 2020-07-27 11:34 UTC
## Minimized code

```Scala
object Test {
  def main(args: Array[String]): Unit = {
    val list = new java.util.ArrayList[String]()
    println(java.util.Collections.min(list))
  }
}

```

## Output

```scala
Exception in thread "main" java.lang.NoSuchMethodError: java.util.Collections.min(Ljava/util/Collection;)Ljava/lang/Comparable;
        at Test$.main(hello.scala:4)
        at Test.main(hello.scala)
```

## Expectation

I expect this to run correctly.

## Notes

[JavaDoc of `java.util.Collections.min`](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#min-java.util.Collection-)
```java
public static <T extends Object & Comparable<? super T>> T min(Collection<? extends T> coll)
```
For Java (and Scala 2), the erasure of that method is
```java
min(Collection)Object
```
but Dotty thinks its erasure is
```java
min(Collection)Comparable
```
hence the `NoSuchMethodError`.

This issue prevents the Scala.js test `CollectionsOnCollectionsTest.testMinMax1` from linking, at the following 2 lines:
https://github.com/scala-js/scala-js/blob/6b9f04b0c0531d889235726d8956cb01a4c7476d/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/CollectionsOnCollectionsTest.scala#L36-L37

Possibly related to #9175

**Comment by smarter** [comment] 2020-07-30 13:59
Duplicate of https://github.com/lampepfl/dotty/issues/7963

**Closed by smarter** 2020-07-30 13:59 UTC
Labels: compat:java, itype:bug
