### ISSUE TITLE
Methods not accepted as polymorphic function arg

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11812] opened 2021-03-19 02:09 UTC
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
object X:
  def asd(f: [A] => List[A] ?=> Int): Int =
    f[Unit](using Nil)

  val test1 = asd([A] => (a: List[A]) ?=> a.length)

  def f2[A](using List[A]): Int = summon[List[A]].length
  val test2 = asd(f2) // error

  def f3[A](n: Int)(using List[A]): Int = summon[List[A]].length + n
  val test3 = asd(f3(3)) // error
```

## Output

```
[error] 15 |  val test2 = asd(f2)
[error]    |                    ^
[error]    |no implicit argument of type List[A] was found for parameter x$1 of method f2 in object X

[error] 18 |  val test3 = asd(f3(3))
[error]    |                       ^
[error]    |no implicit argument of type List[A] was found for parameter x$2 of method f3 in object X```
```

## Expectation

It should compile.

**Comment by bishabosha** [comment] 2021-03-19 09:52
this is a duplicate of #6927 which is being aggregated as part of #6892

**Closed by bishabosha** 2021-03-19 09:52 UTC
Labels: itype:bug, stat:duplicate
