### ISSUE TITLE
Make REPL understand package; regression from Scala2

### ISSUE THREAD

**Issue by bjornregnell** [lampepfl/dotty#13595] opened 2021-09-23 11:53 UTC
## Compiler version

3.0.2

## Minimized code and output

```Scala
scala> package x { def f = 42 }
-- Error:
1 |package x { def f = 42 }
  |^^^^^^^
  |this kind of statement is not allowed here
```

## Expectation

There should, as in Scala 2, be some way to play with code that has packages (also nested):

```Scala
Welcome to Scala 2.13.6 (OpenJDK 64-Bit Server VM, Java 11.0.11).
Type in expressions for evaluation. Or try :help.

scala> :paste 
// Entering paste mode (ctrl-D to finish)

package X { package X { object X { val x = 42 } } }

// Exiting paste mode, now interpreting.

scala> X.X.X.x
val res0: Int = 42
```

**Comment by michelou** [comment] 2021-09-23 11:58
Related to [issue 6367](https://github.com/lampepfl/dotty/issues/6367) opened on April 24, 2019.

**Comment by smarter** [comment] 2021-09-23 12:00
Duplicate of https://github.com/lampepfl/dotty-feature-requests/issues/131

**Closed by smarter** 2021-09-23 12:00 UTC
Labels: itype:bug

**Comment by bjornregnell** [comment] 2021-09-23 13:00
Aha. Missed that despite searching for package and repl. Thanks.
