### ISSUE TITLE
Tail call optimisation captures `this`

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4158] opened 2018-03-22 17:25 UTC
```scala
class Test {
  @tailrec final def test(x: Int): Boolean  =
    if (x == 0) true
    else if (x == 1) false
    else test(x / 2)
}
```
Compiling the code above in Dotty produces
```java
public class Test {
    public final boolean test(int x) {
        int n = x;
        Test test = this;
        while (n != 0) {
            if (n == 1) {
                return false;
            }
            n /= 2;
        }
        return true;
    }
}
```
Scalac seems to be able to optimise away the local variable `Test test = this`.

**Comment by smarter** [comment] 2018-03-22 17:44
I think this is just because scalac always does some DCE, so duplicate of https://github.com/lampepfl/dotty/issues/3271

**Closed by smarter** 2018-03-22 17:44 UTC
Labels: itype:enhancement
