### ISSUE TITLE
REPL crashes at completion after `BigInt` ("assertion failed: missing implicit parameter")

### ISSUE THREAD

**Issue by ansvonwa** [lampepfl/dotty#16551] opened 2022-12-18 20:00 UTC
## Compiler version
`3.2.1`, `3.2.2-RC1-bin-20221017-b88aa12-NIGHTLY-git-b88aa12`, but not `3.2.0`

## Minimized code

```scala
scala> BigInt(1).<tab>
```

## Output (click arrow to expand)
<details>

```scala
Welcome to Scala 3.2.2-RC1-bin-20221017-b88aa12-NIGHTLY-git-b88aa12 (11.0.17, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                        
scala> BigInt(1).<tab>
Exception in thread "main" java.lang.AssertionError: assertion failed: missing implicit parameter of type Ordering[BigInt] after typer at phase parser
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.typer.Implicits.inferImplicit(Implicits.scala:1009)
	at dotty.tools.dotc.typer.Implicits.inferImplicit$(Implicits.scala:811)
	at dotty.tools.dotc.typer.Typer.inferImplicit(Typer.scala:121)
	at dotty.tools.dotc.typer.Implicits.inferImplicitArg(Implicits.scala:877)
	at dotty.tools.dotc.typer.Implicits.inferImplicitArg$(Implicits.scala:811)
	at dotty.tools.dotc.typer.Typer.inferImplicitArg(Typer.scala:121)
	at dotty.tools.dotc.typer.Typer.implicitArgs$1(Typer.scala:3525)
	at dotty.tools.dotc.typer.Typer.addImplicitArgs$1(Typer.scala:3561)
	at dotty.tools.dotc.typer.Typer.adaptNoArgsImplicitMethod$1(Typer.scala:3637)
	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3825)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:4068)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3403)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3022)
	at dotty.tools.dotc.typer.Implicits.tryConversion$1(Implicits.scala:1103)
	at dotty.tools.dotc.typer.Implicits.typedImplicit(Implicits.scala:1134)
	at dotty.tools.dotc.typer.Implicits.typedImplicit$(Implicits.scala:811)
	at dotty.tools.dotc.typer.Typer.typedImplicit(Typer.scala:121)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.tryImplicit(Implicits.scala:1206)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.$anonfun$9(Implicits.scala:1544)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.allImplicits(Implicits.scala:1544)
	at dotty.tools.dotc.interactive.Completion$Completer.implicitConversionTargets(Completion.scala:513)
	at dotty.tools.dotc.interactive.Completion$Completer.implicitConversionMemberCompletions(Completion.scala:378)
	at dotty.tools.dotc.interactive.Completion$Completer.selectionCompletions(Completion.scala:320)
	at dotty.tools.dotc.interactive.Completion$.computeCompletions(Completion.scala:143)
	at dotty.tools.dotc.interactive.Completion$.completions(Completion.scala:48)
	at dotty.tools.repl.ReplDriver.completions$$anonfun$1(ReplDriver.scala:239)
	at scala.util.Either.map(Either.scala:382)
	at dotty.tools.repl.ReplDriver.completions(ReplDriver.scala:240)
	at dotty.tools.repl.ReplDriver.$anonfun$1(ReplDriver.scala:151)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4412)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4378)
	at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4317)
	at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3809)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:679)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468)
	at dotty.tools.repl.JLineTerminal.readLine(JLineTerminal.scala:74)
	at dotty.tools.repl.ReplDriver.readLine$1(ReplDriver.scala:156)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:166)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:171)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:191)
	at dotty.tools.repl.ReplDriver.runBody$$anonfun$1(ReplDriver.scala:179)
	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
	at dotty.tools.repl.ReplDriver.runBody(ReplDriver.scala:179)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:171)
	at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:133)
	at dotty.tools.repl.Main$.main(Main.scala:7)
	at dotty.tools.repl.Main.main(Main.scala)
```
</details>

**Comment by prolativ** [comment] 2022-12-19 11:05
Bisected to https://github.com/lampepfl/dotty/commit/5f4653dbc43a8130a31499623ca885d360300461 @som-snytt

**Comment by dwijnand** [comment] 2022-12-19 11:31
I think this might be enough to fix it:

```diff
diff --git compiler/src/dotty/tools/repl/ReplDriver.scala compiler/src/dotty/tools/repl/ReplDriver.scala
index f076333cf4..aa11806332 100644
--- compiler/src/dotty/tools/repl/ReplDriver.scala
+++ compiler/src/dotty/tools/repl/ReplDriver.scala
@@ -239,7 +239,7 @@ class ReplDriver(settings: Array[String],
           val file = SourceFile.virtual("<completions>", expr, maybeIncomplete = true)
           val unit = CompilationUnit(file)(using state.context)
           unit.tpdTree = tree
-          given Context = state.context.fresh.setCompilationUnit(unit)
+          given Context = state.context.fresh.setCompilationUnit(unit).setPhase(state.context.base.typerPhase)
           val srcPos = SourcePosition(file, Span(cursor))
           val (_, completions) = Completion.completions(srcPos)
           completions.map(_.label).distinct.map(makeCandidate)
```

**Comment by som-snytt** [comment] 2022-12-19 15:51
I'll follow up Dale's suggestion and look for other phase dependencies.

**Comment by som-snytt** [comment] 2022-12-19 18:12
Duplicates https://github.com/lampepfl/dotty/issues/16360

**Comment by dwijnand** [comment] 2022-12-19 20:32
Duplicate of #16360

**Comment by dwijnand** [comment] 2022-12-19 20:33
It's fixed in master is good enough imo.

**Closed by dwijnand** 2022-12-19 20:32 UTC
Labels: itype:bug, area:repl, itype:crash, regression
