### ISSUE TITLE
False "match may not be exhaustive" warning in pattern matching

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#12155] opened 2021-04-20 10:12 UTC
## Compiler version

Scala 3.0.0-RC2

## Minimized code

```Scala
val list : List[List[Int]] = List(1, 2, 3, 4) match {
  case head :: Nil => List(List(head))
  case head :: tail :: Nil => List(List(head), List(tail))
  case head :: (mid :+ tail) => List(List(head), mid, List(tail))
  case Nil => List(List())
}
```

## Output

```scala
match may not be exhaustive.
It would fail on pattern case: List(_, _, _, _*)
```
It's interesting to see that Scala 2.13 also (falsely) warns, but on different case `List(_,_,_)`.
See https://github.com/scala/bug/issues/12377

## Expectation
No warning.

**Comment by mrArkwright** [comment] 2021-05-24 11:24
The issue you're describing seems to be present in a simpler scenario as well:
```scala
val list = List(1, 2, 3, 4) match {
  case init :+ last => ???
  case Nil => ???
}
```
The problem is that the type checker can't know that `:+`'s `unapply` matches on all non empty lists. For that it would need to understand the actual implementation of that `unapply` (which is implemented in terms of `.isEmpty`) which it can't. So I guess this is expected behaviour.

Note that this is different from matching the head and tail of a list with `::` which is a constructor of `List` so the compiler can use that information to prove exhaustivity.

**Comment by dwijnand** [comment] 2021-06-01 19:43
See https://contributors.scala-lang.org/t/sip-sealed-types/5082

**Comment by som-snytt** [comment] 2021-10-31 01:09
Duplicates https://github.com/lampepfl/dotty/issues/10961 which seems like a long time ago but just Dec 2020. Much discussion there but no link to the SIP.

**Comment by dwijnand** [comment] 2021-11-01 08:58
Duplicate of #10961

**Closed by dwijnand** 2021-11-01 08:58 UTC
Labels: itype:bug, area:pattern-matching
