### ISSUE TITLE
Cannot Define Recursive MatchTypes at the Toplevel

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#8755] opened 2020-04-20 16:12 UTC
## Minimized example

```Scala
trait HList
case object HNil extends HList
case class HCons[H, T <: HList](h: H, t: T) extends HList

  type Concat[Xs, Ys <: HList] <: HList = Xs match
    case HNil.type => Ys
    case HCons[x, xs1] => HCons[x, Concat[xs1, Ys]]
```

## Output

```scala
5 |type Concat[Xs <: HList, Ys <: HList] <: HList = Xs match
  |^
  |Cyclic reference involving type Concat
```

## Expectation

Should compile. It works when I place `Concat` in an object.

**Comment by OlivierBlanvillain** [comment] 2020-04-22 06:56
Duplicate of #6362

**Closed by OlivierBlanvillain** 2020-04-22 06:56 UTC
