### ISSUE TITLE
NPE during type inference with HKT + type function

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#3544] opened 2017-11-23 15:34 UTC
```scala
object Test {
  case class Tuple2K[F[_], G[_], A](f: F[A], g: G[A])

  val p0: Tuple2K[[X] => Int, [X] => String, Any] = Tuple2K(1, "s")
  p0 == Tuple2K(List(1), Option("s"))
}
```

**Comment by allanrenucci** [comment] 2017-11-23 15:40
I think it is a duplicate of #3470

**Comment by nerush** [comment] 2017-11-24 08:44
PR [3472](https://github.com/lampepfl/dotty/pull/3472) fixes this problem, but I am not sure whether that fix is the most appropriate one.

**Comment by nerush** [comment] 2017-11-24 08:50
@olafurpg Do not you mind if I add your example to positive tests ?

**Closed** 2018-01-14 00:19 UTC
