### ISSUE TITLE
view.updated not a member of IndexedSeqView in CC library

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#19660] opened 2024-02-09 15:46 UTC
Minimization of `tests/run/t5328.scala`

```scala
// Test.scala
def test = Vector(1).view.updated(0,2)
```

```
sbt> set ThisBuild/Build.scala2Library := Build.Scala2LibraryCCTasty
sbt> scala3-bootstrapped/scalac Test.scala
```

```scala
1 |def test = Vector(1).view.updated(0,2)
  |           ^^^^^^^^^^^^^^^^^^^^^^
  |     value updated is not a member of scala.collection.IndexedSeqView[Int]
```

_Originally posted by @nicolasstucki in https://github.com/lampepfl/dotty/issues/19652#issuecomment-1935559226_

**Comment by Linyxus** [comment] 2024-02-21 15:09
So I checked the issue and discovered that this is actually not a bug in the capture checker and an outcome of a change made in the capture checked stdlib. In the original stdlib, the `updated` function of `IndexedSeqView` comes from the `SeqOps` trait. But now `IndexedSeqView` extends `IndexedSeqViewOps`, which in the end extends `IterableOps` instead of `SeqOps`, as explained in the comment [here](https://github.com/lampepfl/dotty/blob/4e6a502687ad14b0f88b89a3fa8fb26fc92da2b9/scala2-library-cc/src/scala/collection/SeqView.scala#L21-L38).

I'm not quite confident about how it should be fixed. Should we add a method in `SeqViewOps`? /cc @odersky

**Comment by odersky** [comment] 2024-02-21 15:36
That's a tricky one. Maybe we can add `updated` to `SeqViewOps` as an inline method? That should be backwards Tasty compatible.

**Closed** 2024-02-27 18:58 UTC
Labels: itype:bug, area:experimental:cc
