### ISSUE TITLE
Overload resolution for extension methods fails in some cases where named parameters are involved.

### ISSUE THREAD

**Issue by rmgk** [lampepfl/dotty#15287] opened 2022-05-24 22:15 UTC
## Compiler version

3.1.3-RC3, 3.2.0-RC1-bin-20220519-ee9cc8f-NIGHTLY-git-ee9cc8f

## Minimized code

```Scala
extension (x: Char)
  def f(someParam: String): String = "a"
  def f(min: Boolean, max: Int = 4): String = "b"

@main def run() = 'c'.f(false)
```

## Output

```
Test.scala:7:19: value f is not a member of Char.
An extension method was tried, but could not be fully constructed:

    extensionOverload.f()    failed with

        value f: <overloaded extensionOverload.f> does not take parameters [7:19]
```

## Expectation

Compile just fine, return "b"

**Comment by pikinier20** [comment] 2022-05-25 08:25
Invoking f as a standard method:
```scala
f('c')(false)
```
fails with:
```
[error] ./cli.scala:5:19: None of the overloaded alternatives of method f with types
[error]  (x: Char)(min: Boolean, max: Int): String
[error]  (x: Char)(someParam: String): String
[error] match arguments (('c' : Char))
[error] @main def run() = f('c')(false)
```
After specyfing default parameter explicitely, everything compiles

**Comment by pikinier20** [comment] 2022-05-25 09:56
This problem occurs also for standard methods:
```
def f(x: Char)(someParam: String): String = "a"
def f(x: Char)(min: Boolean, max: Int = 4): String = "b"

@main def run() = f('c')(false)
```

**Comment by pikinier20** [comment] 2022-05-25 10:35
The problem is that compiler expects the default getter name: `f$default$2` when actually it is: `f$default$3`

**Comment by pikinier20** [comment] 2022-05-26 09:03
I give up on this as it turned out to be too complicated case. Resolving overloaded methods for curried methods goes param clause per param clause and it's not aware how it should work with default parameters for further parameter clauses.

**Comment by odersky** [comment] 2022-05-29 10:59
One way to fix this for now is to reject overloaded extension methods that have default arguments.

**Comment by odersky** [comment] 2022-06-13 10:17
I have decided not to attack errors involving default parameters using the old scheme of default parameters any more. It's better to focus on fixing the scheme to use inline which would fix lots of other problems as well. If people want fixes now, someone else should take this on, or we move to backlog.

**Closed** 2022-10-09 10:57 UTC
Labels: itype:bug, area:default-parameters
