### ISSUE TITLE
Polymorphic functions variance not working as expected

### ISSUE THREAD

**Issue by guyde2011** [lampepfl/dotty#6918] opened 2019-07-23 18:59 UTC
## minimized code
```Scala
val aiPoly: [T] => Any => Int = [T] => (a: Any) => 5
val iiPoly: [T] => Int => Int = aiPoly // <-- this part fails
```
Does not compile, producing the error:
Found:    PolyFunction{apply: [T](x$1: Any): Int}(aiPoly)
Required: PolyFunction{apply: [T](x$1: Int): Int}

## expectation
Expected the polymorhpic case to behave the same way as normal functions do:
```Scala
val ai: Any => Int = (a: Any) => 5
val ii: Int => Int = ai // <-- compiles and works with no errors
```

**Comment by smarter** [comment] 2019-07-23 21:19
Same root cause as https://github.com/lampepfl/dotty/issues/6357 since dependent and polymorphic function types share a similar encoding, closing this one as a duplicate since I'll either manage to fix both at the same time or none (details of my current plan here: http://guillaume.martres.me/talks/dotty-funs-scala19/)

**Closed by smarter** 2019-07-23 21:19 UTC
Labels: itype:bug
