### ISSUE TITLE
Function type parameters can be instantiated to types which capture the root cap

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/dotty#15058] opened 2022-04-28 09:57 UTC
## Compiler version

Head of CC experiment.

## Minimized code

Both of the calls to `withSession` should be rejected (note the first one is also affected by https://github.com/lampepfl/dotty/issues/15057):

```Scala
scala> class Session
// defined class Session

scala> def withSession[T](thunk : ({*} Session) => T): T = thunk(new Session)
def withSession[T](thunk: ({*} Session) => T): T

scala> withSession(t => t)
val res1: Session = Session@7866a0b3

scala> withSession[{*} Session](t => t)
val res2: {*} Session = Session@14e53307
```

**Comment by odersky** [comment] 2022-04-29 09:20
Duplicate of #15049

**Comment by odersky** [comment] 2022-04-29 09:21
In fact, maybe it's not a duplicate since there's an explicit type parameter here.

**Comment by dwijnand** [comment] 2022-05-04 10:02
Fixed in the branch.  It didn't close because that's not the main branch.

**Closed** 2022-05-04 10:02 UTC
Labels: cc-experiment
