### ISSUE TITLE
assertion failed: duplicate type F#7718; previous was type F#7369 (using Scala 2 published `cats-effect`)

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#11984] opened 2021-04-04 10:30 UTC
## Compiler version

3.0.0-RC1 and 3.0.0-RC2

## Minimized code & Output

https://scastie.scala-lang.org/EzwUElRQS2uavuyN6TU4ow

Another one:
https://scastie.scala-lang.org/Kx6GbNFJRPenigB5LiOdxg

## Expectation

Successful compilation

**Comment by griggt** [comment] 2021-04-05 02:42
Both examples seem to work fine when depending on the Scala 3 published `cats-effect` artifact instead of using `.withDottyCompat` to get the Scala 2 artifact.

---

Aside: is there some reason that Scastie uses Scala 2 libraries and `.withDottyCompat` in Scala 3 build mode, even when Scala 3 published versions are available?  This doesn't always work and can be quite confusing, as seen here and in this recent issue on gitter re: ScalaTest: https://gitter.im/lampepfl/dotty?at=6067745692a3431fd66fa63b

**Comment by griggt** [comment] 2021-04-05 02:59
Duplicate of #11173

**Closed** 2021-04-17 14:35 UTC
Labels: area:pickling, compat:scala2, itype:bug, stat:duplicate
