### ISSUE TITLE
Undefined type when compiling a Dotty-compiled module that uses annotations

### ISSUE THREAD

**Issue by jvican** [lampepfl/dotty#3625] opened 2017-12-02 17:58 UTC
I have module A with the following source file:
```scala
import scala.scalajs.reflect.annotation.EnableReflectiveInstantiation

@EnableReflectiveInstantiation
trait AbstractTestSuite {
  def properties: Properties[_]
}
```
  
Then, I have module B that uses `AbstractTestSuite` somehow. When compiling module B, I get the following error:
```
[error] undefined: new <notype> # 163215: TermRef(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class reflect)),annotation),EnableReflectiveInstantiation),<init>)
```
  
Looks like an error of annotations + tasty?
  
For context, see https://github.com/jvican/minitest/commit/5d372261fbdfd2f6eaace52df50960f95ecee6ee.

**Comment by OlivierBlanvillain** [comment] 2017-12-02 21:09
Couldn't reproduce with the following:

*a.scala*:
```scala
class EnableReflectiveInstantiation extends scala.annotation.Annotation

trait Properties[T]

@EnableReflectiveInstantiation
trait AbstractTestSuite {
  def properties: Properties[_]
}
```

*b.scala*:
```scala
object Test {
  val a = new AbstractTestSuite {
    def properties = new Properties[Any] {}
  }
}
```

```
$ dotc a.scala
$ dotc b.scala
```

**Comment by smarter** [comment] 2017-12-03 00:47
I can reproduce but only if scalajs-library is missing from the classpath when compiling the second file.

`A.scala`:
```scala
import scala.scalajs.reflect.annotation.EnableReflectiveInstantiation

trait Properties[T]

@EnableReflectiveInstantiation
trait AbstractTestSuite {
  def properties: Properties[_]
}
```
`B.scala`:
```scala
object Test {
  val a = new AbstractTestSuite {
    def properties = new Properties[Any] {}
  }
}
```

```shell
% dotc -classpath "$(coursier fetch -p org.scala-js:scalajs-library_2.12:0.6.21)" A.scala
% dotc -classpath "$(coursier fetch -p org.scala-js:scalajs-library_2.12:0.6.21)":. B.scala
% dotc -classpath . B.scala
undefined: new <notype> # 74: TermRef(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class reflect)),annotation),EnableReflectiveInstantiation),<init>)
```

@jvican Could you check if scalajs-library is missing from the classpath of your second module?

**Comment by ckipp01** [comment] 2023-05-11 07:58
Closing since no more information every came back on this, and it seems to also only be reproduced when it was missing on the classpath. @jvican if you ever come back to this, feel free to reopen.

**Closed by ckipp01** 2023-05-11 07:58 UTC
Labels: itype:bug, area:pickling, stat:needs info, backlog
