### ISSUE TITLE
scala.MatchError when updating build to sbt-dotty 0.5.0

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#10829] opened 2020-12-17 08:20 UTC
## Minimized code

```Scala
crossScalaVersions := Seq("2.13.3", "3.0.0-M2"),
libraryDependencies ++= Seq(
  ("org.http4s" %% "http4s-core" % "0.21.14").withDottyCompat(scalaVersion.value),
  ("org.http4s" %% "http4s-dsl" % "0.21.14").withDottyCompat(scalaVersion.value)
)
```

~~~ text
> update
~~~

## Output

~~~ text
[error] (update) scala.MatchError: (org.scodec:scodec-bits_2.13:1.1.21 (),Some(org.scodec:scodec-bits_2.13:1.1.22:default ()),Some(ScalaModuleInfo(3.0.0-M2, 3.0.0-M2, Vector(), false, false, false, org.scala-lang, Vector(scala-library, scala-compiler, scala-reflect, scala-actors, scalap)))) (of class scala.Tuple3)
~~~

## Expectation

sbt updates the dependencies.

See https://github.com/endpoints4s/endpoints4s/pull/703

**Comment by rparree** [comment] 2020-12-17 09:20
I had a similar problem. You can get rid of the scodec error using:

```scala
evictionWarningOptions := EvictionWarningOptions.empty
```

**Comment by smarter** [comment] 2020-12-17 13:53
I've opened https://github.com/sbt/sbt/issues/6210

**Comment by smarter** [comment] 2020-12-17 13:59
I don't think this has anything to do with the update to sbt-dotty 0.5.0, I can reproduce the problem on 0.4.6 too, it also happened on endpoints4s before you upgraded, but only after you upgraded http4s from 0.21.13 to 0.21.14.

**Comment by smarter** [comment] 2020-12-17 14:00
I'm going to close this in this repo because as far as I can tell this is an sbt bug, see https://github.com/sbt/sbt/issues/6210.

**Closed by smarter** 2020-12-17 14:00 UTC
Labels: area:tooling, itype:bug

**Comment by julienrf** [comment] 2020-12-17 16:13
Thanks for the investigation!

Sorry, I noticed the issue only when bumping sbt-dotty…
