### ISSUE TITLE
REPL not sufficiently isolated from class artifacts in current directory

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#12571] opened 2021-05-23 02:26 UTC
## Compiler version

3.0.0

## Minimized code

```Scala
➜  snips scala oq.scala
2
0
➜  snips
➜  snips scalac -version
Scala compiler version 3.0.0 -- Copyright 2002-2021, LAMP/EPFL
➜  snips rm *.class *.tasty
➜  snips scala oq.scala
2
2
```

## Output

This should never happen:
```Scala
➜  snips vi hi.scala
➜  snips cat hi.scala

@main def test() = println("hello, world")
➜  snips scala hi.scala
hello, world
➜  snips scalac hi.scala
➜  snips vi hi.scala
➜  snips scala hi.scala
hello, world
➜  snips cat hi.scala

@main def test() = println("goodbye, cruel world")
➜  snips
```

## Expectation

Running a script or interactive REPL actually runs the source text.

This is a follow-up to https://github.com/lampepfl/dotty/issues/7635 which was improperly closed.

Noticed again at https://gitter.im/scala/scala?at=60a9b889850bfa2d3bdaae09

**Comment by bjornregnell** [comment] 2021-06-04 20:53
See also:
https://gitter.im/scala/scala?at=60ba844621d6d00b1fb4fb3f

**Comment by SethTisue** [comment] 2021-11-13 21:38
This bit somebody again today: https://contributors.scala-lang.org/t/type-of-an-anonymous-class-derivation/5431/5

It routinely bites veterans as well as beginners.

**Comment by som-snytt** [comment] 2021-11-14 23:20
I just read the contributors thread, very funny! or sad! or one of those things! OOTT is that even a thing.

As in the OP "this should never happen". Also we should never waste the time of major contributors. We tend to focus on the "newbie experience".

**Comment by SethTisue** [comment] 2021-11-16 22:59
did somebody work on this at the spree today?

**Comment by griggt** [comment] 2021-11-16 23:06
I had originally signed up to work on it but was reassigned to a different issue.

**Comment by som-snytt** [comment] 2021-11-17 02:47
I finished the bedroom flooring today and next I have to look again at the f-interpolator. But I'd still be willing to put my money where my mouth is. I'll let you know when I come into some cash.

**Comment by bjornregnell** [comment] 2021-11-17 12:23
@som-snytt Beware of insufficient bedroom floor isolation and spurious artifacts in the same place. Cash is king.

**Comment by SethTisue** [comment] 2021-11-23 16:30
Note that #12607 includes `@Ignore`d tests for this

**Comment by som-snytt** [comment] 2021-11-23 16:47
TIL the word "subtle" is a portmanteau of "subdir util".

**Comment by bjornregnell** [comment] 2021-11-23 17:41
In Swedish "subtle" is "subtil", i.e. including explicitly an abbreviation of "today I learned" (which I learned today). 

I'm *so* grateful that you work on this, as this is kind of a "ticking" bomb in the sense that it can explode in a spending of a lot of time on"what!?"-stuff.

**Comment by SethTisue** [comment] 2021-11-23 18:54
The King James Bible also spells it "subtil". Famously: "the serpent was more subtil than any beast of the field..."

Dale and I spent about two hours looking at this today and we learned some things but don't really have a solution in sight yet. But both of us want to keep working on it, both for the importance of the bug itself, and because it's good learning and good saw-sharpening.

Some of the code we were studying:

* `ReplCompiler#newRun` is where each new thing entered in the REPL gets access to the bindings established earlier in the session; a fold repeatedly calls `importPreviousRun`, which does `ctx.fresh` and `.withRootImports(RootRef(() => requiredModuleRef(path)) :: Nil)` where `path` is successively `repl.rs$line$1`, `repl.rs$line$2`, and so on. (The `repl.` part was added by Tom in #12607.)

* References to names are resolved in `Typer` by `findRef` which calls `findRefRecur` which calls `checkNewOrShadowed`, which seems relevant and perhaps if we studied it (and/or added logging and/or stepped through it in a debugger) we'd have an aha moment.

At the broadest level, we still don't know:

* Does something go wrong at the time the directory in the file system is seen and a package symbol created for it?
* Or does something first go wrong at the point when the `def` or `val` is entered?
* Or is all of that working as intended, and the bug occurs only when you attempt to reference the `def` or `val`?

We sort of circled around between these three possibilities, dipping shallowly into each one, without committing yet to truly proving or disproving a particular one.

**Comment by bjornregnell** [comment] 2021-11-23 19:14
Thrilling excursions! Keeping fingers crossed for a :smoking: :gun:

**Comment by dwijnand** [comment] 2021-11-24 08:34
Looking at some debug output from `findRefRecur ` revealed that the package `foo` that blows up is found in the context in which `val foo` was previously defined.  So my current theory is that `val foo` type checks and returns but also forces the package foo into existence, in a way that it later wins over val foo.

**Comment by SethTisue** [comment] 2021-11-30 16:40
`Typer` line 339:

```scala
          // [...] Finally, for the root package
          // we switch back to the original test. This means that top-level packages in
          // the root package take priority over root imports. [...]
```

`ReplCompiler#newRun` uses root imports as the mechanism for giving successive REPL entries access to identifiers from previous entries, so surely this is the key piece of logic?

**Comment by SethTisue** [comment] 2021-11-30 17:44
The two basic possible solution paths are:

1) change `Typer` so that "top-level packages in the root package take priority over root imports" isn't always true (we need it not to be true when the root imports in question are REPL bindings)
2) change `REPLCompiler` to somehow avoid the whole issue

We probably want to consider 2 first, since `Typer` is complex and fragile. Could `REPLCompiler` use regular imports instead of root imports to bring previous REPL bindings into scope? Why was the choice made to have it use root imports?

**Comment by SethTisue** [comment] 2021-11-30 17:47
Here's a slight variant of this bug which doesn't involve a filesystem directory:

Scala 2:

```scala
scala 2.13.7> java
              ^
              error: package java is not a value

scala 2.13.7> val java = 3
val java: Int = 3

scala 2.13.7> java
val res1: Int = 3
```

whereas Scala 3 falls down:

```
Welcome to Scala 3.1.0 (1.8.0_292, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                        
scala> java
-- Error:
1 |java
  |^^^^
  |package java is not a value
                                                                                                                        
scala> val java = 3
javval java: Int = 3
                                                                                                                        
scala> java
-- Error:
1 |java
  |^^^^
  |package java is not a value
```

**Comment by som-snytt** [comment] 2021-11-30 18:08
Re "subtil", beloved grad school prof recently wrote: Ever since the serpent said to Eve, "Look at that pensile fruit!" has anyone, ever, used this word?

I replied: I will no longer even tell my daughter how to hold a pencil any more.

(School notified us this week that they are doing California sex ed in biology class. First of all, they should introduce it in math class, because it has to do with exponential growth.)

I haven't looked at the Scala 3 sitch yet, but we're just talking about pluggable root contexts ("root imports" is a misnomer). So the Nr 1 sounds wrong to me, but I haven't looked yet to understand it. Experience dictates that REPL must be in "mechanical sympathy" with the compiler, and "workarounds" should be avoided. My Scala 2 PR for REPL to "use actual root contexts" is closed, but that is an example.

**Comment by griggt** [comment] 2021-12-01 02:55
> `ReplCompiler#newRun` uses root imports as the mechanism for giving successive REPL entries access to identifiers from previous entries, so surely this is the key piece of logic?

While working on #12607 I recall I convinced myself that the use of the "root imports" mechanism was the crux of the matter and that the Scala 2 REPL perhaps used more localized imports? (but dunno, I'm not too familiar with the Scala 2 codebase and ran out of time to investigate)

**Comment by griggt** [comment] 2021-12-01 03:16
> The two basic possible solution paths are:
> 
>     1. change `Typer` so that "top-level packages in the root package take priority over root imports" isn't always true (we need it not to be true when the root imports in question are REPL bindings)
> 
>     2. leave `Typer` alone and change `REPLCompiler` to somehow avoid the whole issue

I previously considered something akin to (1) but it seemed like a bad idea.  I started down the path of (2) but stopped when it no longer looked quick and easy, and I wasn't even sure I was on the right track (but your new example and comments make me think that I was, and express so clearly the muddled mess that was in my head, thank you!)

> Why was the choice made to have it use root imports?

I'd love to know this as well.

**Comment by griggt** [comment] 2021-12-01 03:17
> My Scala 2 PR for REPL to "use actual root contexts" is closed, but that is an example.

Would you happen to have a link for that?  I'd love to have a look.

**Comment by som-snytt** [comment] 2021-12-01 03:23
Yes, it was pre-pandemic but github is easy for me to search.

https://github.com/scala/scala/pull/8593

Probably there is nothing wrong with whatever it was trying to solve. I like the general idea of "let me plug in whatever contexts I prefer", but that is not our current thinking, unlike plan 9 for instance.

**Comment by SethTisue** [comment] 2021-12-01 18:35
Dale is exploring a hypothesis: perhaps the problem is that the root imports for the previous REPL entries are being added to a context whose owner is the root package, whereas they should be added to a context whose owner is the REPL package (if we keep #12607) or the empty package (if we revert #12607).

**Comment by SethTisue** [comment] 2021-12-02 15:44
PR: #14021 (yes, that hypothesis was the way forward)

**Closed** 2021-12-13 02:46 UTC
Labels: itype:bug, exp:intermediate, area:repl, area:scripting
