### ISSUE TITLE
RankN Types Compiler Crash

### ISSUE THREAD

**Issue by ChristopherDavenport** [lampepfl/dotty#9905] opened 2020-09-28 14:34 UTC
Const generates failure when applied all in 1 spot.
 
## Minimized code

```Scala
object BugReport {
  val const: [A] => A => [B] => B => A = [A] => (a: A) => [B] => (b: B) => a

  val z = const(1)("") // ERROR HERE

  // val f = const(1)  // WORKS
  // val a = f("a")
  // val b = f(4)
}
```

## Output (click arrow to expand)
<details>

```scala
exception while typing Fun.const.apply[Int](1).apply of class class dotty.tools.dotc.ast.Trees$Select # 10786
exception while typing Fun.const.apply[Int](1).apply[String] of class class dotty.tools.dotc.ast.Trees$TypeApply # 10787
exception while typing Fun.const.apply[Int](1).apply[String]("") of class class dotty.tools.dotc.ast.Trees$Apply # 10788
exception while typing def z: Int = Fun.const.apply[Int](1).apply[String]("") of class class dotty.tools.dotc.ast.Trees$DefDef # 10791
exception while typing @scala.annotation.internal.SourceFile(
  | => root / Compile / compileIncremental 0s
    "/Users/cdavenport/Documents/Scala/Examples/dottyt/src/main/scala/TestApp.scala"
  
) final module class Fun$() extends Object() {
  private def writeReplace(): AnyRef = 
    new scala.runtime.ModuleSerializationProxy(classOf[Fun.type])
  def const: 
    PolyFunction{apply: [A](x$1: A): PolyFunction{apply: [B](x$1: B): A}}
   = 
    {
      final class $anon() extends Object(), PolyFunction {
        def apply[A](a: A): PolyFunction{apply: [B](b: B): A} = 
          {
            final class $anon() extends Object(), PolyFunction {
              def apply[B](b: B): A = a
            }
            new Object with PolyFunction {...}():
              PolyFunction{apply: [B](b: B): A}
          }
      }
      new Object with PolyFunction {...}():
        PolyFunction{apply: [A](a: A): PolyFunction{apply: [B](b: B): A}}
    }
  def z: Int = Fun.const.apply[Int](1).apply[String]("")
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 10793
exception while typing package <empty> {
  final lazy module val Fun: Fun$ = new Fun$()
  @scala.annotation.internal.SourceFile(
    
      "/Users/cdavenport/Documents/Scala/Examples/dottyt/src/main/scala/TestApp.scala"
    
  ) final module class Fun$() extends Object() {
    private def writeReplace(): AnyRef = 
      new scala.runtime.ModuleSerializationProxy(classOf[Fun.type])
    def const: 
      PolyFunction{apply: [A](x$1: A): PolyFunction{apply: [B](x$1: B): A}}
     = 
      {
        final class $anon() extends Object(), PolyFunction {
          def apply[A](a: A): PolyFunction{apply: [B](b: B): A} = 
            {
              final class $anon() extends Object(), PolyFunction {
                def apply[B](b: B): A = a
              }
              new Object with PolyFunction {...}():
                PolyFunction{apply: [B](b: B): A}
            }
        }
        new Object with PolyFunction {...}():
          PolyFunction{apply: [A](a: A): PolyFunction{apply: [B](b: B): A}}
      }
    def z: Int = Fun.const.apply[Int](1).apply[String]("")
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 10794
[info] exception occurred while compiling /Users/cdavenport/Documents/Scala/Examples/dottyt/src/main/scala/TestApp.scala
java.lang.AssertionError: assertion failed:  <none> while compiling /Users/cdavenport/Documents/Scala/Examples/dottyt/src/main/scala/TestApp.scala
[error] ## Exception when compiling 1 sources to /Users/cdavenport/Documents/Scala/Examples/dottyt/target/scala-0.27/classes
[error] java.lang.AssertionError: assertion failed:  <none>
[error] dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
[error] dotty.tools.dotc.transform.Erasure$Typer.typedSelect(Erasure.scala:662)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2426)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2516)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:122)
[error] dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2586)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2590)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2705)
[error] dotty.tools.dotc.transform.Erasure$Typer.typedTypeApply(Erasure.scala:756)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2474)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2517)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:122)
[error] dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2586)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2590)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2705)
[error] dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:778)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2456)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2517)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:122)
[error] dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2586)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2590)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2705)
[error] dotty.tools.dotc.typer.Typer.$anonfun$34(Typer.scala:1981)
[error] dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:217)
[error] dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1981)
[error] dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:892)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2433)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2516)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:122)
[error] dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2586)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2590)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2612)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2661)
[error] dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:979)
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2118)
[error] dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2444)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2448)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2516)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:122)
[error] dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2586)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2590)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2612)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2661)
[error] dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:979)
[error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2242)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2488)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2517)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:122)
[error] dotty.tools.dotc.typer.Typer.op$proxy16$1(Typer.scala:2586)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2587)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2590)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2705)
[error] dotty.tools.dotc.transform.Erasure.run(Erasure.scala:123)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:296)
[error] scala.collection.immutable.List.map(List.scala:246)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:297)
[error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:180)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$5(Run.scala:190)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:198)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:205)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:142)
[error] dotty.tools.dotc.Run.compile(Run.scala:124)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:38)
[error] dotty.tools.dotc.Driver.process(Driver.scala:195)
[error] dotty.tools.dotc.Main.process(Main.scala)
[error] xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error] xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] sbt.Execute.work(Execute.scala:290)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] stack trace is suppressed; run last Compile / compileIncremental for the full output
[error] (Compile / compileIncremental) java.lang.AssertionError: assertion failed:  <none>
[error] Total time: 1 s, completed Sep 28, 2020 7:32:18 AM
```
</details>

**Comment by b-studios** [comment] 2020-09-29 07:25
Just a remark: it does not crash if the second type argument (`B`) is moved to the top: `[A, B] => A => B => A`

**Comment by b-studios** [comment] 2020-09-29 07:34
Seems related to #8921

**Comment by b-studios** [comment] 2020-09-29 07:37
Thanks for reporting @ChristopherDavenport, I am closing it since it seems to be a duplicate of #6678

**Closed by b-studios** 2020-09-29 07:37 UTC
Labels: area:typer, itype:bug, itype:crash
