### ISSUE TITLE
current package not preferred over imported package

### ISSUE THREAD

**Issue by olhotak** [lampepfl/dotty#5206] opened 2018-10-04 21:24 UTC
I have three files:
```
package foo

object A {
  val x = 5
}
```

```
package foo.bar

object A {
  val x = "foo"
}
```

```
package foo
import foo.bar._

object B {
  val y: Int = A.x
}
```

They compile with Scala 2.12. With Dotty, I get:

```
-- [E007] Type Mismatch Error: /tmp/foo/B.scala:5:17 ---------------------------
5 |  val y: Int = A.x
  |               ^^^
  |               found:    String(foo.bar.A.x)
  |               required: Int
  |               
one error found
```

In object foo.B, Scala 2.12 prefers foo.A over foo.bar.A because foo.A is in the same package. But Dotty seems to prefer foo.bar.A over foo.A because foo.bar.A is being imported.

**Comment by milessabin** [comment] 2018-10-05 08:39
See also: https://github.com/scala/bug/issues/2458.

I prefer Dotty's behaviour and I'd like to see it backported to Scala 2.

**Comment by allanrenucci** [comment] 2018-10-05 09:17
Not that this is intended. If you compile with `-language:Scala2`, you get:
```
-- Migration Warning: Test.scala:16:17 -----------------------------
16 |    val y: Int = A.x
   |                 ^
   |               Name resolution will change.
   |                currently selected                     : foo.A.type
   |                in the future, without -language:Scala2: foo.bar.A'.type
   |               
   |               where:    A  is a object in package foo
   |                         A' is a object in package bar
one warning found
```

**Comment by allanrenucci** [comment] 2018-10-05 09:29
Oops. I meant "Note". Closing since it is intended behaviour

**Closed by allanrenucci** 2018-10-05 09:29 UTC

**Comment by SethTisue** [comment] 2018-10-05 15:36
> I prefer Dotty's behaviour and I'd like to see it backported to Scala 2.

you mean https://github.com/scala/scala/pull/6589?

**Comment by milessabin** [comment] 2018-10-05 16:13
@SethTisue how did I miss that?! :smile:
