### ISSUE TITLE
Match types on singletons crash the compiler more

### ISSUE THREAD

**Issue by LPTK** [lampepfl/dotty#7872] opened 2019-12-30 15:19 UTC
I found two new problems after the fixes in https://github.com/lampepfl/dotty/pull/7835 for the previous issue https://github.com/lampepfl/dotty/issues/7807; opening a new issue here for @OlivierBlanvillain to fix, as suggested by @odersky.

## minimized code

```Scala
object Test2 with
  type Flip[N <: 0 | 1] <: 0 | 1 = N match { case 0 => 1 case 1 => 0 }
  def flip: (x: 0 | 1) => Flip[x.type] = ???
  flip(0): 1 // ! does not type check
  flip(1): 0

object Test3 with
  type Flip[N <: 0 | 1] <: 0 | 1 = N match { case 0 => 1 case 1 => 0 }
  def flip(x: 0 | 1): Flip[x.type] = ???
  flip(0): 1 // ! causes: pickling difference for module class Test2$ in tests/pos/i7807.scala
  flip(1): 0
```

Note that the following works:

```Scala
object Test with
  def flip: (x: 0 | 1) => x.type match { case 0 => 1 case 1 => 0 } = ???
  flip(0): 1
  flip(1): 0
  flip(if ??? then 0 else 1)
  val n: 0 | 1 = if ??? then 0 else 1
  flip(n)
  val m: n.type match { case 0 => 1 case 1 => 0 } = flip(n)
```

**Comment by OlivierBlanvillain** [comment] 2020-01-29 17:28
I futher minimised the type checking issue to #8128, which doesn't involve match types. The pickling issue is probably a duplicate of the ones we already have in [pos-test-pickling.blacklist](https://github.com/lampepfl/dotty/blob/0058c7109db5bf91ef6517c3eaa9c7ac43e30f3c/compiler/test/dotc/pos-test-pickling.blacklist#L21-L26)

**Closed** 2020-03-10 15:00 UTC
Labels: itype:bug, itype:crash
