### ISSUE TITLE
ClassFormatException in Dotty

### ISSUE THREAD

**Issue by ctongfei** [lampepfl/dotty#2508] opened 2017-05-23 00:26 UTC
```scala
trait Eq[T] {
  def eq(a: T, b: T): Boolean
}

object Eq {
  implicit object int extends Eq[Int] {
    def eq(a: Int, b: Int) = a == b
  }
}

def f[T](a: T, b: T)(implicit T: Eq[T]) = T.eq(a, b)

println(f(1, 2))
```

Causes runtime exception (environment: Dotty in Scastie):

```
sbt: [error] (run-main-4f) java.lang.ClassFormatError: Illegal field modifiers in class Playground$Eq: 0x9
sbt: java.lang.ClassFormatError: Illegal field modifiers in class Playground$Eq: 0x9
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at Main$.<init>(main.scala:19)
	at Main$.<clinit>(main.scala)
	at Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run 'last compile:run' for the full output.
sbt: java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
```

**Comment by odersky** [comment] 2017-05-23 07:18
I could not reproduce this one. On my setup it prints `false`, as expected.

**Comment by liufengyun** [comment] 2017-05-23 07:41
The latest Dotty correctly gives `false` -- I think the problem is that `Scastie` is using an old version of Dotty.

**Comment by smarter** [comment] 2017-05-23 16:41
@MasseGuillaume What version of the jvm is running on scastie? (`java -version` output)

**Comment by allanrenucci** [comment] 2018-01-05 10:22
Closing this. It now prints `false` in Scastie as expected. We also already have a run test in our test suite: `tests/run/i2508.scala`

**Closed by allanrenucci** 2018-01-05 10:22 UTC
Labels: stat:cannot reproduce
