### ISSUE TITLE
Transparent `derived` doesn't preserve type's refinements

### ISSUE THREAD

**Issue by i-surkov** [lampepfl/dotty#13458] opened 2021-09-02 18:46 UTC
## Compiler version

3.0.2

## Minimized example

```Scala
trait TC[T]:
  type R
  def fun(value: T): R

object TC:

  type Aux[T, O] = TC[T] { type R = O }

  transparent inline given derived[T]: TC.Aux[T, _] = new TC[T]:
    type R = String
    def fun(value: T): String = value.toString

end TC

case class Foo(value: Int)
case class Bar(value: Int) derives TC

@main def app =

  val tcFoo = summon[TC[Foo]] // typechecks as TC[Foo] { type R = String }
  (tcFoo.fun(Foo(1)): String) // compiles

  val tcBar = TC.derived[Bar] // typechecks as TC[Bar] { type R = String }
  (tcBar.fun(Bar(1)): String) // also compiles

  val tcBar2 = summon[TC[Bar]] // only typechecks as TC[Bar]
  (tcBar2.fun(Bar(2)): String) // doesn't compile
```

## Output

```scala
[error] -- [E007] Type Mismatch Error: {...}/Test.scala:27:13 
[error] 27 |  (tcBar2.fun(Bar(2)): String) // doesn't compile
[error]    |   ^^^^^^^^^^^^^^^^^^
[error]    |   Found:    tcBar2.R
[error]    |   Required: String
```

## Expectation
(Not sure if it can be considered a bug, feature request, or it's just an expected behavior)
When we derive a type class using `derives` mechanism, type refinements that happened during derivation are not reflected in the type. On the other hand, if we use transparent `derived` method directly (explicitly, or implicitly), type refinements are preserved.

**Comment by bishabosha** [comment] 2021-09-02 21:36
duplicate of https://github.com/lampepfl/dotty/issues/10031

**Closed** 2021-09-02 21:37 UTC
Labels: stat:duplicate
