### ISSUE TITLE
Unexpected New (...) reached GenBCode

### ISSUE THREAD

**Issue by kubukoz** [lampepfl/dotty#16357] opened 2022-11-17 00:37 UTC
## Compiler version

3.2.1

## Minimized code

macros.scala

```scala
//> using scala "3.2.1"
import scala.quoted._
import scala.annotation.experimental

object macros {

  trait Suspend[A[_[_]]] {
    def sus[F[_]](fa: F[A[F]]): A[F]
  }

  inline def mkSuspend[Alg[_[_]]]: Suspend[Alg] = ${ mkSuspendImpl[Alg] }

  @experimental
  def mkSuspendImpl[Alg[_[_]]: Type](using Quotes): Expr[Suspend[Alg]] = {
    import quotes.reflect._
    def instance[F[_]: Type](fExpr: Expr[F[Alg[F]]]): Expr[Alg[F]] = {
      val cl = Symbol.newClass(
        Symbol.spliceOwner,
        "$anon",
        parents = List(
          TypeRepr.of[Object],
          TypeRepr.of[Alg].appliedTo(TypeRepr.of[F]),
        ),
        decls = _ => Nil,
        selfType = None,
      )

      val tree = New(
        TypeTree.of[Alg]
      )

      Block(
        List(
          ClassDef(cl, Nil, Nil)
        ),
        New(
          TypeTree.ref(cl)
        ),
      ).asExprOf[Alg[F]]
    }

    '{
      new Suspend[Alg] {
        def sus[F[_]](fa: F[Alg[F]]): Alg[F] = ${ instance('fa) }
      }
    }
  }

}
```

main.scala

```scala
//> using scala "3.2.1"
import macros.Suspend

object demo extends App {

  trait MyAlg[F[_]] {
    def hello(s: String): F[Int] = ???
  }

  macros.mkSuspend[MyAlg]
}
```

## Output (click arrow to expand)
<details>

```scala
Error: Unexpected New(... with ... {...}/TypeTree[TypeRef(NoPrefix,class demo$$anon$2)]) reached GenBCode.
  Call was genLoad(New(TypeTree[TypeRef(NoPrefix,class demo$$anon$2)]),Ldemo$MyAlg;)
Error compiling project (Scala 3.2.1, JVM)
Error: Unexpected error when compiling project_f0e8bc45bf: 'Unexpected New(... with ... {...}/TypeTree[TypeRef(NoPrefix,class demo$$anon$2)]) reached GenBCode.
  Call was genLoad(New(TypeTree[TypeRef(NoPrefix,class demo$$anon$2)]),Ldemo$MyAlg;)'
Compilation failed
```
</details>

**Comment by kubukoz** [comment] 2022-11-17 00:38
I think this one is related to the default implementation of `hello`...

**Comment by bishabosha** [comment] 2022-11-17 10:57
I think the problem is that you should be wrapping new in a call to the constructor,
```scala
Apply(
  Select(
    New(TypeTree.ref(cl)), cl.primaryConstructor
  ),
  Nil
)
```
since this is always needed, perhaps we should deprecate the old `New.apply` and only have a factory that has all the required pieces

**Comment by kubukoz** [comment] 2022-11-17 11:25
perhaps :) I know I'm very likely doing something wrong but it seemed like a message I shouldn't be seeing!

**Comment by nicolasstucki** [comment] 2023-01-23 08:18
By compiling this code with `-Ycheck:all` we get the following error:

```scala
checking t/Test_2.scala after phase inlining
java.lang.AssertionError: assertion failed: `New` node must be wrapped in a `Select`:
  parent = new Object with demo.MyAlg[F] {...}:demo.MyAlg[F]
  child = new Object with demo.MyAlg[F] {...} while running Ycheck on t/Test_2.scala
exception occurred while compiling t/Test_2.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: `New` node must be wrapped in a `Select`:
  parent = new Object with demo.MyAlg[F] {...}:demo.MyAlg[F]
  child = new Object with demo.MyAlg[F] {...} while compiling t/Test_2.scala
java.lang.AssertionError: assertion failed: `New` node must be wrapped in a `Select`:
  parent = new Object with demo.MyAlg[F] {...}:demo.MyAlg[F]
  child = new Object with demo.MyAlg[F] {...}
```

**Comment by nicolasstucki** [comment] 2023-01-23 08:21
This is not something we could we could do in the `New.apply`. It is also something that might be out of scope for `-Xcheck-macros`.

**Closed** 2023-02-16 14:53 UTC
Labels: itype:bug, itype:crash, area:metaprogramming:reflection
