### ISSUE TITLE
Member conflict rules should be loosened for Java fields and methods

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#5502] opened 2018-11-23 10:10 UTC
The following code compiles fine in Scalac, but reports an error in Dotty:

```Scala
public class HasFieldAndMethod {
  public int cow = 2;
  public int cow() { return 1; } // Should access this one, prefer the method to the field
}
```

Error message:

```Scala
-- [E119] Duplicate Symbol Error: examples/HasFieldAndMethod.java:20:13 --------
20 |  public int cow() { return 1; } // Should access this one, prefer the method to the field
   |             ^
   |method cow in class HasFieldAndMethod is already defined as var cow: Int at line 19.
one error found
```

**Comment by allanrenucci** [comment] 2018-11-23 10:37
Duplicate of #4739?

**Closed** 2018-11-23 10:41 UTC
Labels: area:typer, itype:bug, prio:medium
