### ISSUE TITLE
Scala.JS regression: class arg defaulting to `js.native`

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11888] opened 2021-03-25 04:48 UTC
## Compiler version

3.0.0-RC2-bin-20210322-4035f51-NIGHTLY with Scala.JS 1.5.0

## Minimized code

```scala
import scala.scalajs.js
import scala.scalajs.js.annotation._

@JSGlobal
@js.native
class X(x: js.Object = js.native) extends js.Object
```

## Output

```
[error] 6 |class X(x: js.Object = js.native) extends js.Object
[error]   |                       ^^^^^^^^^
[error]   |         js.native may only be used as stub implementation in facade types
```

## Expectation

It should compile.

**Comment by sjrd** [comment] 2021-03-25 05:56
Duplicate of  #11592

**Closed by sjrd** 2021-03-25 05:56 UTC
Labels: itype:bug
