### ISSUE TITLE
Cannot use experimental language features in @experimental code

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#13392] opened 2021-08-26 12:45 UTC
## Compiler version

3.1.0

## Minimized example

```Scala
import language.experimental.erasedDefinitions
import annotation.experimental

@experimental
erased class CanThrow[-E <: Exception]
```

## Output

```scala
Error:  2 |import language.experimental.erasedDefinitions
Error:    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error:    |Experimental features may only be used with a nightly or snapshot version of the compiler
```

## Expectation

Should compile. 

Otherwise, we cannot use experimental language features in @experimental code.

I think what happens is that we check the compiler version when we analyze the import statement. We should wait with it until we need to check whether the language import is enabled. If all these tests are from experimental scopes, this should be permitted.

**Comment by nicolasstucki** [comment] 2021-08-30 07:01
We need (1) to allow experimental language features to be used in stable compiler. Extra use case can be added later.

```scala
@experimental
class Test(xs: List[Int]: 
  import language.experimental.fewerBraces
  xs.map x =>
    x + 1
```
This works for any of the experimental language features we have except for erasedDefinitions. 

In it's current state (2) looks like a special case for us to be able to compile some code while it make it hard for users to use the feature. The current version has a rule that is already complex and also leaves some underspecified cases (or has many bugs). For the sake of the users we should not have this one and find a good way to achieve the same.

Rule happens to work for the experimental language features we have now. There is the possibility that at some point we will want to add a new experimental feature that is incompatible with this rule. This would be a blocker for that feature.

On the other hand (3) was designed to be easily usable by anyone that wants to try the erasedDefinitions feature. It is not an exception for us but it also allows us to compile the use case we care about. It also us keeps the experimental scopes rules simple.

**Comment by odersky** [comment] 2021-08-30 07:57
> In it's current state (2) looks like a special case for us to be able to compile some code while it make it hard for users to use the feature. The current version has a rule that is already complex and also leaves some underspecified cases (or has many bugs). For the sake of the users we should not have this one and find a good way to achieve the same.

I disagree and I think you have to be more specific to make that allegation. Also, any underspecification _simply does not matter_! We are not talking a type soundness theorem here but a pragmatic feature that should prevent the common misuses and allow the comon use cases. That is all. 

The solution to put `fewerBraces` inside each experimental class is workable but weird since it violates the common assumption that language imports go at the top. Someone who would try it out the first would always write it at the top
and then be surprised why it does not work, and most likely be disgusted by the proposed fix. 

I don't think we will make progress discussing this further. Let's get both fixes in and call it a day.

**Comment by nicolasstucki** [comment] 2021-08-30 08:01
### Rule (4): an alternative to rule (3) that would work for users as well

The idea is to strip the strange corner cases out of (3) and solve specifically the problem it tries to solve. Also, remove inference of experimental to avoid bad UX.

 - (4) Contents of experimental source file is in experimental scope.

This implies that all top classes must be marked as experimental as in normal experimental rules. We might also require top-level methods and values to be experimental.

It is intended to be used with rule (1) to allow all the use cases in the tests of  #13396

The question then is how to state that a source file is experimental. Here are some options:
- Special import: `import scala.language.experimental.source`
- Special file name: `Foo.experimental.scala`
- Annotate the package clause in some way `package @experimental foo { }` (not sure if possible)

**Comment by odersky** [comment] 2021-08-30 08:09
I believe any of these conventions is too complicated and not necessary. it's still in the spirit that we should do our utmost to prevent usability rather than allow common use cases without hassles.

**Comment by nicolasstucki** [comment] 2021-08-30 10:00
Now that I discovered that #13396 does not provide any tests for rule (2), it is clearly not something we want to include 1 commit before the release.

**Comment by odersky** [comment] 2021-08-30 11:23
I agree it would be good to have tests but I personally have spent way too much time on this already. So somebody else should add tests. And I insist that #13396 will go into 3.1, or experimental checking as a whole goes out.

**Comment by nicolasstucki** [comment] 2021-08-30 11:58
If we get #13396 we will have a flood of issues from users. I already have 5+ issues that I could immediately report. This would not be good from the user's perspective.

To disable experimental checks we would need to make `@experimental` experimental again. It would take a couple of days in the best of cases to implement as it is non-trivial at this point. This seems to also not allow us to re-bootstrap on a release compiler, this would block us again.

On the other hand, we have #13394 which does not touch non-experimental features, has proper tests, is useful for users, and is ready.

**Comment by nicolasstucki** [comment] 2021-08-30 13:46
We agreed that more precise version of (2) that only allows top-level definitions is the solution.

- (5) experimental language imports are allowed if all non-synthetic top-level statements are @experimental definitions

**Closed** 2021-08-30 13:47 UTC

**Comment by pshirshov** [comment] 2022-08-01 14:44
I don't know why this had been done. Seems like the enforcement rules make it's practically impossible to write libraries relying on "experimental" features, because all the client code needs to be annotated with this.

**Comment by SethTisue** [comment] 2022-08-03 00:37
> Seems like the enforcement rules make it's practically impossible to write libraries relying on "experimental" features
 
 sounds intentional to me... otherwise the concept of experimental has no teeth

**Comment by mdedetrich** [comment] 2023-08-23 17:44
I guess I am a bit late to the "experimental" train, but am I correct in my understanding is that its not possible to avoid to the usage of the `@experimental` annotation even with compiler flags?

If so its somewhat annoying, I am actually currently developing a macro annotation that is designed portable across Scala 2.12, Scala 2.13 and Scala 3 (i.e. the whole point of the macro annotation is that you have a single source that is cross compiled against those Scala versions) and since macro annotations are considered experimental in Scala 3 this basically means that users of that macro annotation would have to mark `@experimental` everywhere just because of Scala 3

**Comment by pshirshov** [comment] 2023-08-23 17:52
In most cases it is possible to work around with various tricks, in worst case by relying on java reflection.

**Comment by mdedetrich** [comment] 2023-08-23 17:54
> In most cases it is possible to work around with various tricks, in worst case by relying on java reflection.

Is there a reference/code to these tricks?

**Comment by mdedetrich** [comment] 2023-08-24 09:21
> The whole point of @experimental is that it is transitive. You cannot have a definition that's @experimental and have the users not be @experimental. I also find that mechanism a bit heavy-handed since we don't want to sprinkle @experimental on all user code.

I would question the transitivity feature specifically for macro annotations here because unless I am missing something, unlike other experimental features (i.e. direct style) whether the macro annotation is experimental or not is not relevant for users (i.e. callers) of the macro. Macros just transform code so even if the implementation of how macro annotations is designed is marked as experimental thats a problem for the macro author, i.e. if the design of macro annotations changes then the author has to deal with it but the user doesn't have to do anything, i.e. for a user they will always just do `@myMacroAnnotation`. This is contrast to direct style, where if it would hypothetically change then the user is indeed severely impact so I can see the merit of transitive checking of `@experimental` of other features.

I mean I guess there are ways around this, i.e. putting `@experimental` at the top level (such as an object) does appear to work but that also leaves other annoyances, i.e. it gives the impression that the entire top level object is experimental when in fact its just methods with the macro annotation

> But there is an alternative: we can also access experimental definition in a snapshot compiler release. This would mean you can cross compile using @experimental Scala 3 features, but the Scala 3 compiler would have to be a snapshot compiler.

At least for the project I am talking about (Pekko), using a snapshot compiler would very likely not cut it although I can see how this is a good general improvement for other cases.

Note that there is a scala contributors thread with more context on the problem I am dealing with https://contributors.scala-lang.org/t/make-scala-2-inline-annotation-work-as-inline-keyword-for-scala-3-with-source-3-0-migration/6286/7

**Comment by mdedetrich** [comment] 2023-08-24 09:26
> I mean I guess there are ways around this, i.e. putting @experimental at the top level (such as a top level object) does appear to work but that also leaves other annoyances, i.e. it gives the impression that the entire top level object is experimental when in fact its just methods with the macro annotation but its better than nothing.

I quickly tried this suggestion and while it does work for Scala 3, it doesn't work for Scala 2 because the `scala.annotation.experimental` doesn't exist although that can be worked around with a stub annotation.

**Comment by mdedetrich** [comment] 2023-08-24 09:28
@odersky Should I make a discussion thread on Scala contributors on the more general point of whether `@experimental` makes sense for macro annotations specifically?

**Comment by nicolasstucki** [comment] 2023-08-24 09:35
> What is currently the best way to specify snapshot release?

Using a nightly release is probably the simplest.

**Comment by odersky** [comment] 2023-08-24 09:39
> Using a nightly release is probably the simplest.

It would be good to see concrete incantations to achieve that, with consideration how it would work in the compiler, REPL, and the IDE.

**Comment by odersky** [comment] 2023-08-24 09:40
> @odersky Should I make a discussion thread on Scala contributors on the more general point of whether @experimental makes sense for macro annotations specifically?

I think for macro annotations @experimental is currently unavoidable until they are fully stabilized. The question how to deal with @experimental in general could be interesting in a contributors thread. Or just point to this issue here?

**Comment by mdedetrich** [comment] 2023-08-24 09:43
> I think for macro annotations @experimental is currently unavoidable until they are fully stabilized. 

True, but to clarify I am not suggesting making macro annotations fully stable. I am making a distinction between users of the macro and the implementation/design of the macro and my argument is that the former is stable (unless you are thinking of hypothetically removing macro annotations completely in the future at some point) where as the latter is unstable.

Put differently, it really doesn't matter how macro annotations are designed/implemented, for a user the code will always be `@myMacroAnnotation`, which is in stark contrast to other experimental features.

> The question how to deal with @experimental in general could be interesting in a contributors thread.

Okay ill make a thread, better to talk about it there rather than derailing this issue thread.

**Comment by nicolasstucki** [comment] 2023-08-24 09:45
>  For this reason I would argue that rather than forcing @experimental on the MacroAnnotation annotation itself I would rather put it on the transform method.

At this point the `MacroAnnotation` trait is not part of the "stable" Scala library, as such it must be marked with `@experimental`. Note that this trait could disappear at any point, for example if we decide to change its name or move it to another package.

**Comment by odersky** [comment] 2023-08-24 09:45
> True, but to clarify I am not suggesting making macro annotations fully stable. I am making a distinction between users of the macro and the implementation/design of the macro and my argument is that the former is stable (unless you are thinking of hypothetically removing macro annotations completely in the future at some point) where as the latter is unstable.

Until they are stabilized there's a theoretical chance that they might be removed or changed in a way that some functionality is no longer expressible. I don't expect it, but there's no formal guarantee it won't happen. So yes, we need users to be aware of that.

**Comment by nicolasstucki** [comment] 2023-08-24 09:47
> Put differently, it really doesn't matter how macro annotations are designed/implemented, for a user the code will always be @myMacroAnnotation, which is in stark contrast to other experimental features.

The fact that there is a reference to `@myMacroAnnotation` in the code implies that there is a dependency/call into an API that is experimental. There the user of that annotation cannot rely on it working in a later version.

**Comment by mdedetrich** [comment] 2023-08-24 09:51
> At this point the `MacroAnnotation` trait is not part of the "stable" Scala library, as such it must be marked with `@experimental`. Note that this trait could disappear at any point, for example if we decide to change its name or move it to another package.

This to me is more of a technical implementation detail because `MacroAnnotation` is relevant for authors of Macro, not users.

> Until they are stabilized there's a theoretical chance that they might be removed or changed in a way that some functionality is no longer expressible. I don't expect it, but there's no formal guarantee it won't happen. So yes, we need users to be aware of that.

Understood

> The fact that there is a reference to @myMacroAnnotation in the code implies that there is a dependency/call into an API that is experimental. There the user of that annotation cannot rely on it working in a later version.

Aside from the hypothetical macro annotations can be removed at some future point, would this case happen if users of the macro stick with a specific Scala 3 version? If not, then aside from the severe changes @odersky alluded to I don't see how it would effect users, i.e. if they upgrade their Scala version to 3.4 then that would bring in a new artifact which has a new implementation against a stable macro annotation API (not sure if this is the case, genuine question).

**Comment by nicolasstucki** [comment] 2023-08-24 12:36
> Aside from the hypothetical macro annotations can be removed at some future point, would this case happen if users of the macro stick with a specific Scala 3 version?

If they use the same patch version (3.x.y) it will be OK, but not necessarily if they use the same minor release (3.x). `@expeimental` definitions can be added/removed/modified in any patch version.

**Comment by xerial** [comment] 2023-09-05 21:27
> mechanism a bit heavy-handed since we don't want to sprinkle @experimental on all user code. 
https://github.com/lampepfl/dotty/issues/13392#issuecomment-1691303668

In Scala 3.3.1, this issue becomes more prominent. Any usage of the `@experimental` macro requires users to add the `@experimental` annotation to their code. Currently, there is no way to split the responsibility between library creators and users. Ideally, if the library creators use `@experimental` methods, they should be notified and take responsibility for fixing the code for upcoming Scala 3.x releases. In the current design, however, both library creators and users are required to annotate all experimental code usages, including transitive ones.

Especially, @pshirshov (izumi-reflect) and I (airframe-surface) have created libraries based on Scala 3 macros. I believe we share the same concerns and troubles in dealing with this experimental mechanism. It is unfortunate that, even though some features are experimental, they are good enough to be used in production. Changing or dropping the API design in the future is acceptable, but the only currently available workaround is to depend on the snapshot compiler version, which will create an additional burden for library maintainers.

**Comment by SethTisue** [comment] 2023-09-05 21:36
If there are specific experimental features or APIs that the community considers  high priority to be stabilized (not be experimental before), I think we should have specific tickets about those features. I doubt that any general expression of dissatisfaction about experimental stuff _in general_ is going to have any effect.

> Ideally, if the library creators use @experimental methods, they should be notified and take responsibility for fixing the code for upcoming Scala 3.x releases

I'm curious: could or should the open community build have caught this...?

**Comment by mdedetrich** [comment] 2023-09-05 21:46
> In Scala 3.3.1, this issue becomes more prominent. Any usage of the @experimental macro requires users to add the `@experimental` annotation to their code. 

Is this new to Scala 3.3.1? I was experiencing this already in 3.3.0, at least with the prototype macro I am writing in https://github.com/mdedetrich/get-inline the users calling that macro annotation also had to add `@experimental` (as can be seen at https://github.com/mdedetrich/get-inline/blob/main/src/test/scala-3/org/mdedetrich/Test.scala#L6)

**Comment by xerial** [comment] 2023-09-05 21:55
@mdedetrich Yes. Since 3.3.1-RC1. Another user reported the behavior change 
>  I noticed in scala 3.3.1-RC1 that if I used an experimental feature I had to add the @experimental annotation to both the macro method (that returns an Expr) and the inline def that returns the true type I care about. in scala 3.3.0 it was only necessary on the macro method. 
https://discord.com/channels/632150470000902164/875868146949554207/1121597037213925396

**Comment by xerial** [comment] 2023-09-05 22:06
@SethTisue Yes. ClassDef.apply, Symbol.newClass are essential to produce some type of code, which was impossible to generate in Scala 3.1 https://github.com/lampepfl/dotty/pull/14124. Those are marked as experimental for some reason, probably testing the usability or feasibility:
https://github.com/lampepfl/dotty/blob/6dc3737e5f83416801e61131b0444bff27af581a/tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala#L78-L80

Libraries (izumi, zio, airframe) are already using these reflect methods, so the community build will be able to track the usage.  

Yeah. I should have opened another community thread instead of messing up this ticket.

**Comment by mdedetrich** [comment] 2023-09-05 22:19
As requested, created a thread at https://contributors.scala-lang.org/t/behaviour-of-experimental-in-scala-3/6309
